(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.bt8in = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(2,0,0,4).p("AADLWIMaAAIAAmGIABAAIAAwlI47AAIAAQlIMgAAg");
	this.shape.setTransform(55.5288,50.5098,0.6956,0.6956);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E3DDE2").s().p("AADLWIAAmGIsgAAIAAwlIY7AAIAAQlIgBAAIAAGGg");
	this.shape_1.setTransform(55.5288,50.5098,0.6956,0.6956);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.bt8in, new cjs.Rectangle(-1,-1,113.1,103), null);


(lib.bt7in = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(2,0,0,4).p("A0TsXIAAQoIMeAAIAAGDIMcAAIAACDIPqAAIADpAIv3AAIAAvug");
	this.shape.setTransform(90.3885,55.0657,0.6956,0.6956);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E3DDE2").s().p("AEnMYIAAiEIscAAIAAmDIseAAIAAwoIYwAAIAAPvIP3AAIgDJAg");
	this.shape_1.setTransform(90.387,55.0657,0.6956,0.6956);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.bt7in, new cjs.Rectangle(-1,-1,212,115.1), null);


(lib.bt6in = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(2,0,0,4).p("AxRHfILvAAIAAD3INCAAIAAmGIJyAAIAAwlMgiiAAAg");
	this.shape.setTransform(76.903,50.5098,0.6956,0.6956);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E3DDE2").s().p("AliLWIAAj3IrvAAIABy0MAiiAAAIAAQlIpyAAIAAGGg");
	this.shape_1.setTransform(76.9032,50.5098,0.6956,0.6956);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.bt6in, new cjs.Rectangle(-1,-1,155.8,103), null);


(lib.bt5in = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(2,0,0,4).p("AMnnwIAAmFIsfAAIAAGFIsxAAIAAQdIBdAAIAAFJIX2AAIAAwdIgEAAIAAlJg");
	this.shape.setTransform(56.3416,61.623,0.6956,0.6956);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E3DDE2").s().p("ArMN2IAAlJIhdAAIAAwdIMxAAIAAmFIMfAAIAAGFIgBAAIAAFJIAEAAIAAQdg");
	this.shape_1.setTransform(56.3416,61.623,0.6956,0.6956);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.bt5in, new cjs.Rectangle(-1,-1,114.7,125.3), null);


(lib.bt4in = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(2,0,0,4).p("AMelLIseAAIAAmFIsdAAIAAWhIY7AAg");
	this.shape.setTransform(55.4483,50.1811,0.6956,0.6956);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E3DDE2").s().p("AscLRIAA2hIMcAAIAAGFIMeAAIAAQcg");
	this.shape_1.setTransform(55.4483,50.1811,0.6956,0.6956);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.bt4in, new cjs.Rectangle(-1,-1,112.9,102.4), null);


(lib.bt3in = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(2,0,0,4).p("AMelLIseAAIAAmFIsdAAIAAWhIY7AAg");
	this.shape.setTransform(55.457,50.1811,0.6956,0.6956);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E3DDE2").s().p("AscLRIAA2hIMcAAIAAGFIMeAAIAAQcg");
	this.shape_1.setTransform(55.457,50.1811,0.6956,0.6956);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.bt3in, new cjs.Rectangle(-1,-1,113,102.4), null);


(lib.bt2in = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(2,0,0,4).p("ARclLIsiAAIAAmFI2VAAIAAWhMAi3AAAg");
	this.shape.setTransform(77.6731,50.1811,0.6956,0.6956);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E3DDE2").s().p("AxbLRIAA2hIWVAAIAAGFIMjAAIAAQcg");
	this.shape_1.setTransform(77.6731,50.1811,0.6956,0.6956);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.bt2in, new cjs.Rectangle(-1,-1,157.4,102.4), null);


(lib.bt1in = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(2,0,0,4).p("AiPorIk0AAIAAaHIJcAAIABzOIEqAAIgCvpIpRAAg");
	this.shape.setTransform(45.226,111.55);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E3DDE2").s().p("AnDRcIAA6HIE0AAIAAowIJRAAIACPpIkqAAIgBTOg");
	this.shape_1.setTransform(45.225,111.55);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.bt1in, new cjs.Rectangle(-1,-1,92.5,225.1), null);


(lib.Group_Слой_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("AgbAdQgLgLAAgSQAAgRALgLQALgMAQAAQARAAALAMQALALAAARQAAASgLALQgLAMgRAAQgPAAgMgMgAgTgXQgIAKAAANQAAAOAIAJQAIAKALAAQANAAAIgKQAHgIAAgPQAAgNgHgKQgIgJgNAAQgLAAgIAJg");
	this.shape.setTransform(70.575,7.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("AgaAeQgLgLAAgSQAAgRALgMQALgMAQAAQARAAAKALQAKALAAARIAAAEIg/AAQABANAHAJQAIAIAKAAQAWAAAFgVIAKAAQgDANgJAIQgKAIgOAAQgRAAgLgLgAgQgYQgHAIgBAMIAzAAQAAgMgGgHQgHgJgMAAQgKAAgIAIg");
	this.shape_1.setTransform(61.7,7.475);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#333333").s().p("AgcAuQgJgLAAgSQAAgRAJgLQAKgMARAAQAKAAAHAGQAIAFADAIIAAg1IALAAIAABwIgLAAIAAgRQgDAJgHAFQgJAGgJAAQgRAAgKgMgAgZAQQABAPAGAIQAHAJALAAQAMAAAIgIQAJgIgBgOIAAgFQAAgNgHgIQgIgIgNAAQgZAAAAAgg");
	this.shape_2.setTransform(52.45,5.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#333333").s().p("AgEA4IAAhMIAKAAIAABMgAgFgoIAAgPIALAAIAAAPg");
	this.shape_3.setTransform(46.475,5.725);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#333333").s().p("AgDAnIghhNIAMAAIAZA+IAZg+IALAAIgiBNg");
	this.shape_4.setTransform(41.025,7.475);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#333333").s().p("AAUAnIgSg9IgBAAIgTA9IgKAAIgZhNIALAAIAUA+IACAAIARg+IAJAAIASA+IAUg+IAKAAIgYBNg");
	this.shape_5.setTransform(28.225,7.475);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#333333").s().p("AgaAeQgLgLAAgSQAAgRALgMQALgMAQAAQARAAALALQAJALAAARIAAAEIg/AAQABANAIAJQAIAIAKAAQAVAAAFgVIAKAAQgDANgJAIQgKAIgOAAQgQAAgMgLgAgQgYQgHAIgBAMIAzAAQAAgMgGgHQgHgJgMAAQgKAAgIAIg");
	this.shape_6.setTransform(18.275,7.475);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#333333").s().p("AgFA4IAAhMIAKAAIAABMgAgFgoIAAgPIALAAIAAAPg");
	this.shape_7.setTransform(12.35,5.725);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#333333").s().p("AgGA4IguhvIAMAAIAoBkIABAAIAohkIAMAAIgvBvg");
	this.shape_8.setTransform(5.275,5.725);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Group_Слой_1, null, null);


(lib.Монтажный_кадр_1_walls = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// walls
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E9E5E8").s().p("ArILJIAAxSILSAAIAAk/IK/AAIAAJAIplAAIAAJAIk8AAIAAERg");
	this.shape.setTransform(152.016,131.5428,0.9725,0.9725);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E9E5E8").s().p("ADhGrIAAkXIwBAAIAAo+IZBAAIAANVg");
	this.shape_1.setTransform(299.282,103.8256,0.9725,0.9725);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#E9E5E8").s().p("AAAGrIAAkXIo7AAIAAo+IR3AAIAANVg");
	this.shape_2.setTransform(432.8352,103.8256,0.9725,0.9725);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#E9E5E8").s().p("AABGrIAAkXIo8AAIAAo+IR3AAIAANVg");
	this.shape_3.setTransform(544.2147,103.8256,0.9725,0.9725);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#E9E5E8").s().p("AqHGrIAAtVISKAAIAAAAICFAAIAAJAIiFAAIgDgCIo7AAIAAEXg");
	this.shape_4.setTransform(662.8152,103.7283,0.9725,0.9725);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#E9E5E8").s().p("AtcGPIACq3IIbAAIAACxIJWAAIAAkXIHBAAIAAEmICFAAIAAH3g");
	this.shape_5.setTransform(642.1003,354.6421,0.9725,0.9725);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#E9E5E8").s().p("AujGqIAAtTII9AAIAAEWII6AAIAABeILPAAIAAGoIq7AAIAAA3g");
	this.shape_6.setTransform(467.8951,357.3895,0.9725,0.9725);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#E9E5E8").s().p("Ao8GrIAAtVII+AAIAAEYII7AAIAAgJIAAJGg");
	this.shape_7.setTransform(321.4801,357.3166,0.9725,0.9725);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Монтажный_кадр_1_walls, null, null);


(lib.Монтажный_кадр_1_texts = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// texts
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#9F979E").s().p("AgQAlQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAhDQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAGAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAIIAAABIABAAQADgGAEgCQAEgDAGgBQAFAAADACQAAAAABABQAAAAAAAAQAAAAAAABQAAAAAAABIgCAGQAAAAAAABQAAAAAAAAQgBAAAAAAQgBAAAAAAIgHgBQgHABgEAEQgFAGAAAIIAAAoQAAABAAAAQAAABgBAAQAAAAAAAAQgBABAAAAg");
	this.shape.setTransform(401.2063,231.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#9F979E").s().p("AgRAgQgHgFgDgJQgCgHAAgLQAAgKACgGQADgKAHgFQAHgFAKAAQAKAAAIAFQAHAFADAJQACAHAAAKQAAALgCAHQgDAJgHAFQgIAFgKAAQgJAAgIgFgAgLgYQgEAEgDAHIAAANIAAAPQACAGAFAEQAFAEAGAAQAHAAAFgEQAEgEACgGIABgPIgBgNQgBgHgFgEQgFgDgHAAQgGAAgFADg");
	this.shape_1.setTransform(394.25,231.325);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#9F979E").s().p("AgQAtQgHgFgDgIQgCgHAAgLQAAgMACgFQADgKAHgFQAGgFAKAAQAFAAAFADQAFACADADIAAABIABgBIAAggQAAgBAAAAQAAgBAAAAQAAAAABAAQAAgBAAAAIAHAAQAAAAABABQAAAAAAAAQAAAAABABQAAAAAAABIAABeQAAABAAAAQgBABAAAAQAAAAAAAAQgBABAAAAIgHAAQAAAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAgFIgBAAIAAAAQgDAEgFACQgFADgFAAQgJgBgHgFgAgIgLQgEACgCAGIgDAFIAAAMIAAAKIACAGQACAGAEADQAFADAFAAQAFAAAEgDQAEgDACgFIACgHIAAgKIAAgMIgCgFQgCgFgEgDQgEgDgFAAQgFAAgEADg");
	this.shape_2.setTransform(386.325,230);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#9F979E").s().p("AgCAyQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAhEQAAAAAAAAQAAgBAAAAQAAAAABAAQAAgBABAAIAFAAQABAAAAABQAAAAAAAAQABAAAAABQAAAAAAAAIAABEQAAAAAAABQAAAAgBAAQAAABAAAAQAAAAgBAAgAgFglQgCgCAAgCQAAgEACgCQACgCADAAQADAAACACQADACAAAEQAAACgDACQgCACgDABQgDgBgCgCg");
	this.shape_3.setTransform(380.875,229.95);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#9F979E").s().p("AgQAlQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAhDQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAGAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAIIAAABIABAAQADgGAEgCQAEgDAGgBQAFAAADACQAAAAABABQAAAAAAAAQAAAAAAABQAAAAAAABIgCAGQAAAAAAABQAAAAAAAAQgBAAAAAAQgBAAAAAAIgHgBQgHABgEAEQgFAGAAAIIAAAoQAAABAAAAQAAABgBAAQAAAAAAAAQgBABAAAAg");
	this.shape_4.setTransform(376.9563,231.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#9F979E").s().p("AgQAlQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAhDQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAGAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAIIAAABIABAAQADgGAEgCQAEgDAGgBQAFAAADACQAAAAABABQAAAAAAAAQAAAAAAABQAAAAAAABIgCAGQAAAAAAABQAAAAAAAAQgBAAAAAAQgBAAAAAAIgHgBQgHABgEAEQgFAGAAAIIAAAoQAAABAAAAQAAABgBAAQAAAAAAAAQgBABAAAAg");
	this.shape_5.setTransform(371.7063,231.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#9F979E").s().p("AgRAgQgHgFgDgJQgCgHAAgLQAAgKACgGQADgKAHgFQAHgFAKAAQALAAAHAFQAHAFADAJQACAHAAAKQAAALgCAHQgDAJgIAFQgGAFgLAAQgJAAgIgFgAgLgYQgFAEgCAHIgBANIABAPQACAGAFAEQAFAEAGAAQAHAAAFgEQAEgEACgGIABgPIgBgNQgBgHgFgEQgFgDgHAAQgGAAgFADg");
	this.shape_6.setTransform(364.75,231.325);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#9F979E").s().p("AgRAvQgHgEgEgHQgEgHgBgKIAAgmQABgJAEgHQAEgIAHgDQAIgEAJAAQAKAAAHADQAIAEAEAHQAEAHABAJQAAABgBAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgHAAIgBAAIAAgBQgBgKgGgGQgHgHgKAAQgKAAgGAHQgHAGABAKIAAAnQgBAKAHAGQAGAGAKAAQAKAAAHgGQAGgGABgKQAAgBAAAAQAAAAAAAAQAAgBAAAAQABAAAAAAIAHAAQAAAAAAAAQABAAAAABQAAAAAAAAQABAAAAAAIAAABQgBAJgEAHQgEAHgIAEQgHAEgKAAQgJAAgIgEg");
	this.shape_7.setTransform(356.55,229.975);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#9F979E").s().p("AgLAkIgJgCQgLgDgHgJQgHgJAAgNQAAgOAIgJQAIgIAOgDIARgBQABAAAAAAQAAABAAAAQABAAAAAAQAAABAAAAIAAA4IABABQAJAAAEgCQAIgBAFgHQAEgGAAgIQAAgIgDgGQgEgGgGgDIgBgBIAAgCIADgFQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAAAABQAJAEAGAJQAFAIAAALQAAAMgGAIQgFAJgLADQgJAEgPAAIgLAAgAgRgVQgHACgFAFQgFAGAAAIQAAAJAFAGQAEAFAHACIAMACIACgBIAAgtIgCAAIgLABg");
	this.shape_8.setTransform(40.2,170.225);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#9F979E").s().p("AgVAiQgLgEgGgJQgHgJAAgMQAAgNAHgJQAGgJAKgDIAEgBIABAAQABAAAAAAQAAAAABAAQAAABAAAAQAAABAAAAIABAIIAAAAQAAAAAAABQAAAAAAABQgBAAAAAAQAAAAgBAAIgCAAQgHACgEAGQgFAHAAAIQAAAIAFAGQAEAGAIABQAHACAKAAQAMAAAGgCQAHgBAGgGQAEgGAAgIQAAgIgEgHQgFgGgHgBIgBgBIAAAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIABgIQABAAAAgBQAAAAAAAAQABgBAAAAQABAAAAAAIADABQAKADAHAJQAGAJAAANQAAAMgGAJQgIAJgKAEQgIACgOAAQgMAAgJgCg");
	this.shape_9.setTransform(40.2,179.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#9F979E").s().p("AAAAZQgHgJAAgRIAAgTIgBgBIgHAAQgIAAgGAEQgFAGAAAKQAAAHADAGQADAFAGABQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABIgBAJQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBAAQgJgCgGgJQgGgKAAgMQAAgQAIgJQAIgIANAAIA6AAQABAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAIQAAABAAAAQAAABAAAAQAAAAgBAAQAAABgBAAIgGAAIgBAAIAAABQAFAEADAHQADAIAAAHQAAAMgGAIQgHAJgNAAQgNAAgHgKgAABgUIAAASQABAKAFAHQAEAIAIAAQAIgBAEgFQAEgGAAgIQAAgJgFgIQgFgHgJAAIgOAAIgBABg");
	this.shape_10.setTransform(40.2,188.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#9F979E").s().p("Ag6AGQgBAAAAAAQgBAAAAAAQAAgBAAAAQgBgBAAAAIAAgHQAAgBABAAQAAgBAAAAQAAAAABAAQAAAAABAAIB1AAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIAAAHQAAAAAAABQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_11.setTransform(38.5,195.125);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#9F979E").s().p("Ag6ApQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBIAAgtQAAgQAKgJQAKgJAPAAQAPAAAKAJQAIAKAAAPIAAAiIABAAIAzAAQABABAAAAQABAAAAAAQAAAAABABQAAAAAAABIAAAIQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAgAgrgWQgHAHAAAKIAAAhIABAAIAuAAIAAAAIAAghQAAgKgGgHQgGgGgLAAQgLAAgGAGg");
	this.shape_12.setTransform(38.475,201.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#9F979E").s().p("AgLAkIgJgCQgLgDgHgJQgHgJAAgNQAAgOAIgJQAIgIAOgDIARgBQABAAAAAAQAAAAAAABQABAAAAAAQAAABAAAAIAAA4IABABQAJAAAEgCQAIgBAFgHQAEgGAAgIQAAgIgDgGQgEgGgGgDIgBgBIAAgCIADgFQAAgBAAAAQABAAAAAAQAAgBABAAQAAABAAAAQAJAEAGAJQAFAIAAALQAAAMgGAIQgFAJgLADQgJAEgPAAIgLAAgAgRgVQgHACgFAFQgFAGAAAIQAAAJAFAGQAEAFAHACIAMACIACgBIAAgtIgCAAIgLABg");
	this.shape_13.setTransform(40.2,215.725);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#9F979E").s().p("AgoAiQgBAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAgIQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAABAAIAGAAIABAAIAAgBQgLgHAAgPQAAgOAIgIQAJgJANAAIA4AAQABAAABAAQAAABAAAAQABAAAAAAQAAABAAAAIAAAIQAAABAAAAQAAABgBAAQAAAAAAABQgBAAgBAAIg2AAQgJAAgGAFQgGAGAAAJQgBAJAGAFQAFAGAIABIA5AAQABAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAAAIQAAABAAAAQAAABgBAAQAAAAAAABQgBAAgBAAg");
	this.shape_14.setTransform(40.15,225.125);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#9F979E").s().p("Ag6AHQgDgDAAgEQAAgDADgDQACgDAEABQAEgBADADQACADAAADQAAAEgCADQgDADgEAAQgEAAgCgDgAgYAGQgBAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAgBIAAgGQAAgBABAAQAAgBAAAAQAAAAABAAQAAgBABAAIBTAAQABAAAAABQABAAAAAAQAAAAAAABQAAAAAAABIAAAGQAAABAAABQAAAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_15.setTransform(38.5,232.05);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#9F979E").s().p("Ag6AGQgBAAAAAAQgBAAAAAAQAAgBAAAAQgBgBAAAAIAAgHQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAABAAIB1AAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAHQAAAAAAABQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_16.setTransform(38.5,236.225);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#9F979E").s().p("AgLAkIgJgCQgLgDgHgJQgHgJAAgNQAAgOAIgJQAIgIAOgDIARgBQABAAAAAAQAAAAAAABQABAAAAAAQAAABAAAAIAAA4IABABQAJAAAEgCQAIgBAFgHQAEgGAAgIQAAgIgDgGQgEgGgGgDIgBgBIAAgCIADgFQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAAAABQAJAEAGAJQAFAIAAALQAAAMgGAIQgFAJgLADQgJAEgPAAIgLAAgAgRgVQgHACgFAFQgFAGAAAIQAAAJAFAGQAEAFAHACIAMACIACgBIAAgtIgCAAIgLABg");
	this.shape_17.setTransform(40.2,242.925);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#9F979E").s().p("AgoAYQgBAAgBgBQAAAAAAAAQgBAAAAgBQAAAAAAgBIAAgIQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAABAAIAJAAIABAAIgBgBQgGgDgDgGQgEgFAAgHQAAgGACgEQAAAAABgBQAAAAAAAAQABgBAAAAQABAAAAABIAIACQABAAAAAAQAAAAAAABQAAAAAAAAQAAABAAABQgBADAAAFQABAJAGAFQAHAGAKAAIAxAAQABAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAAAIQAAABAAAAQAAABgBAAQAAAAAAAAQgBABgBAAg");
	this.shape_18.setTransform(40.15,250.295);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#9F979E").s().p("AgdAYQgBAAgBAAQAAgBAAAAQgBAAAAAAQAAgBAAAAIAAgKIgBgBIgUAAQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAgHQAAgBAAAAQAAAAABAAQAAAAAAAAQABAAAAAAIAUAAIABgBIAAgTQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAABAAIAFAAQABAAAAAAQABABAAAAQAAAAAAABQABAAAAABIAAATIAAABIAzAAQAIAAAEgEQADgEAAgIIAAgEQAAAAAAgBQAAAAABgBQAAAAAAAAQAAAAABAAIAGAAQABAAAAAAQABAAAAAAQAAABABAAQAAABAAAAIAAAGQAAANgFAFQgFAHgNAAIg2AAIAAABIAAAKQAAAAgBABQAAAAAAAAQAAAAgBABQAAAAgBAAg");
	this.shape_19.setTransform(39.05,257.375);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#9F979E").s().p("AgoAiQgBAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAgIQAAAAAAgBQAAAAABAAQAAAAAAgBQABAAABAAIAGAAIABAAIAAgBQgLgHAAgPQAAgOAIgIQAJgJANAAIA4AAQABAAABAAQAAABAAAAQABAAAAAAQAAABAAAAIAAAIQAAABAAAAQAAABgBAAQAAAAAAABQgBAAgBAAIg2AAQgJAAgGAFQgGAGAAAJQgBAJAGAFQAFAGAIABIA5AAQABAAABAAQAAABAAAAQABAAAAAAQAAABAAAAIAAAIQAAABAAAAQAAABgBAAQAAAAAAABQgBAAgBAAg");
	this.shape_20.setTransform(40.15,265.075);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#9F979E").s().p("AgLAkIgJgCQgLgDgHgJQgHgJAAgNQAAgOAIgJQAIgIAOgDIARgBQABAAAAAAQAAABAAAAQABAAAAAAQAAABAAAAIAAA4IABABQAJAAAEgCQAIgBAFgHQAEgGAAgIQAAgIgDgGQgEgGgGgDIgBgBIAAgCIADgFQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAAAABQAJAEAGAJQAFAIAAALQAAAMgGAIQgFAJgLADQgJAEgPAAIgLAAgAgRgVQgHACgFAFQgFAGAAAIQAAAJAFAGQAEAFAHACIAMACIACgBIAAgtIgCAAIgLABg");
	this.shape_21.setTransform(40.2,274.525);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#9F979E").s().p("AgXApQgMABgJgGQgIgFgFgKQgFgJAAgMQAAgLAFgKQAEgJAJgFQAIgFAMAAQAAAAABAAQAAAAAAAAQAAAAABABQAAAAAAABIABAIIgBABIAAABIgBAAQgNAAgIAIQgHAIAAAMQAAANAHAIQAIAIANAAIAwAAQAMAAAHgIQAIgIAAgNQAAgMgIgIQgHgIgMAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAgIQAAgBAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIABAAQALAAAJAFQAIAFAGAJQAEAKAAALQAAAMgFAJQgEAKgKAFQgIAGgMgBg");
	this.shape_22.setTransform(38.5,284.5);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#9F979E").s().p("AgKA/IgCAAIAAgCQAHgLADgQQADgQAAgRQAAgRgDgQQgDgRgHgLIAAgBQAAgBAAAAQAAAAAAAAQABAAAAAAQAAAAABAAIAGAAIACABQAGALAFARQAEAQAAASQAAASgEAQQgEAQgGALIgDABg");
	this.shape_23.setTransform(663.6375,443.375);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#9F979E").s().p("AgRAlQAAAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAgBIAAhFQAAAAABgBQAAAAAAAAQAAAAABgBQAAAAAAAAIAHAAQAAAAABAAQAAABAAAAQABAAAAAAQAAABAAAAIAAAIIAAABIABAAQADgGAEgDQAEgCAGAAQAFAAADABQABAAAAABQAAAAAAAAQABAAAAABQAAAAgBABIgBAGQAAABAAAAQgBAAAAAAQAAAAgBAAQAAAAgBAAQgCgBgFABQgHAAgEAFQgFAGAAAIIAAApQAAABAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAg");
	this.shape_24.setTransform(658.8563,444.475);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#9F979E").s().p("AgRAhQgIgFgDgKQgBgHAAgLQAAgKABgHQADgKAHgEQAJgGAJAAQAKAAAIAGQAHAEADAKQACAHABAKQgBALgCAHQgDAKgHAFQgIAFgKAAQgKAAgHgFgAgLgYQgFADgCAIIgBANIABAPQABAGAGAEQAFAEAGAAQAHAAAFgEQAFgEABgGQACgFAAgKQAAgKgCgDQgBgIgFgDQgFgEgHAAQgGAAgFAEg");
	this.shape_25.setTransform(651.75,444.5);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#9F979E").s().p("AgRAhQgIgFgDgKQgBgHAAgLQAAgKABgHQADgKAHgEQAJgGAJAAQALAAAHAGQAHAEADAKQADAHAAAKQAAALgDAHQgDAKgHAFQgHAFgLAAQgKAAgHgFgAgLgYQgFADgCAIIgBANIABAPQACAGAFAEQAFAEAGAAQAHAAAFgEQAFgEABgGQACgFAAgKQAAgKgCgDQgBgIgFgDQgFgEgHAAQgGAAgFAEg");
	this.shape_26.setTransform(643.75,444.5);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#9F979E").s().p("AgCAzQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAhhQAAgBAAAAQAAgBAAAAQABAAAAAAQAAAAABAAIAFAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAABIAABhQAAABAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAg");
	this.shape_27.setTransform(638.075,443.075);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#9F979E").s().p("AgGAzQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAg8IgBgBIgJAAQgBAAAAAAQgBgBAAAAQAAAAAAAAQAAgBAAAAIAAgGQAAAAAAgBQAAAAAAAAQAAAAABgBQAAAAABAAIAJAAIABAAIAAgEQAAgJACgFQACgFAEgDQAFgCAJAAIAEAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIAAAFQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgDAAQgIAAgDAEQgDADAAAJIAAADIABAAIAPAAQABAAAAAAQABABAAAAQAAAAAAAAQAAABAAAAIAAAGQAAAAAAABQAAAAAAAAQAAAAgBABQAAAAgBAAIgPAAIgBABIAAA8QAAABAAAAQgBABAAAAQAAAAAAAAQgBAAAAAAg");
	this.shape_28.setTransform(633.725,443.075);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#9F979E").s().p("AgRAvQgHgGgCgJQgCgGAAgMQAAgMABgFQADgKAHgFQAHgFAKAAQAFAAAFACQAFACADAEIABABIAAgjQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAABAAIAGAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAABiQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAgBAAIgGAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAgGIgBAAQgDAEgFADQgFACgFAAQgKAAgHgFgAgIgLQgFADgCAEIgCAHIgBALIABAKIACAHQABAGAFADQAEADAGAAQAFAAAEgDQAEgDACgFIACgHIABgLIgBgLIgCgGQgCgFgEgDQgEgDgFAAQgFAAgEADg");
	this.shape_29.setTransform(624.175,443.125);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#9F979E").s().p("AAUAlQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgtQAAgIgFgGQgFgEgIAAQgGgBgFAFQgFAEgBAHIAAAwQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgGAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAhFQAAgBAAAAQAAgBAAAAQAAAAABAAQAAAAABAAIAGAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIAAAFIABABIAAAAQAHgJAMAAQALAAAHAGQAHAIAAALIAAAvQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAg");
	this.shape_30.setTransform(616.475,444.45);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#9F979E").s().p("AgOAjQgGgDgEgFQgDgGAAgIIAAgwQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAABAAIAGAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAAAtQAAAJAFAFQAFAEAHAAQAIAAAFgEQAFgFAAgJIAAgtQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAABAAIAGAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAABGQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgGAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgGIgBgBIAAAAQgHAKgLgBQgHAAgGgCg");
	this.shape_31.setTransform(608.525,444.55);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#9F979E").s().p("AgRAhQgIgFgDgKQgCgHAAgLQAAgKACgHQADgKAHgEQAJgGAJAAQAKAAAIAGQAHAEAEAKQACAHAAAKQAAALgCAHQgEAKgHAFQgIAFgKAAQgKAAgHgFgAgLgYQgFADgCAIIgBANIABAPQACAGAEAEQAGAEAGAAQAHAAAFgEQAFgEABgGQACgFAAgKQAAgKgCgDQgBgIgFgDQgFgEgHAAQgGAAgFAEg");
	this.shape_32.setTransform(600.65,444.5);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#9F979E").s().p("AgRAlQAAAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAgBIAAhFQAAAAABgBQAAAAAAAAQAAAAABgBQAAAAAAAAIAHAAQAAAAABAAQAAABAAAAQABAAAAAAQAAABAAAAIAAAIIAAABIABAAQADgGAEgDQAEgCAGAAQAFAAADABQABAAAAABQAAAAAAAAQABAAAAABQAAAAgBABIgBAGQAAABAAAAQgBAAAAAAQAAAAgBAAQAAAAgBAAQgCgBgFABQgHAAgEAFQgFAGAAAIIAAApQAAABAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAg");
	this.shape_33.setTransform(594.4563,444.475);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#9F979E").s().p("AgRAwQgIgEgEgHQgEgHAAgKIAAgnQAAgKAEgHQAEgHAIgEQAIgEAJAAQAKAAAIAEQAIAEAEAHQAEAHAAAJIAAABQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAIgGAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgCQAAgKgHgGQgGgGgLAAQgKAAgGAGQgHAGAAALIAAAoQAAAKAHAGQAHAGAKAAQAKAAAHgGQAGgFAAgKIAAgNIgBgBIgVAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAgFQAAgBAAAAQAAAAABAAQAAAAAAAAQABAAAAAAIAeAAQABAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAABIAAASQAAAQgJAJQgJAIgQAAQgJAAgIgEg");
	this.shape_34.setTransform(586.975,443.075);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#9F979E").s().p("AAFA/IgDgBQgFgLgFgQQgEgQAAgSQAAgSAEgQQAFgRAGgLIACgBIAGAAIABAAIAAACQgGALgEARQgCAQAAARQAAARACAQQAEAQAGALIABABQAAABAAAAQAAAAAAAAQgBAAAAAAQAAAAgBAAg");
	this.shape_35.setTransform(579.9,443.375);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#9F979E").s().p("AgQAhQgHgEgDgJQgDgHAAgNIAAgKIACgGQACgJAIgHQAHgFAKAAQAMAAAIAGQAHAHACAMIABAOQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIguAAIgBABIABALQACAGAFAEQAFAEAHAAQAHAAAFgDQAEgCADgFIABgBIABAAIAFACQAAAAAAAAQABABAAAAQAAAAAAAAQAAABAAAAQgEAIgHAEQgHAEgKAAQgJAAgHgFgAgLgYQgFADgBAHIgCAJIABABIAlAAIAAgBIAAgIQgCgHgFgEQgFgEgHAAQgHAAgEAEg");
	this.shape_36.setTransform(674.175,428.95);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#9F979E").s().p("AgRAgQgHgFgDgJQgCgHAAgLQAAgKACgHQADgJAHgGQAIgFAJAAQALAAAIAFQAIAFACAJIABAEIAAAAQAAAAAAABQAAAAgBAAQAAABAAAAQAAAAgBAAIgHAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQgBgBAAAAIAAgBQgBgGgFgEQgFgEgIAAQgGAAgFAEQgFAEgBAGQgCAFAAAJQAAAJACAGQABAGAFAEQAFAEAGAAQAHAAAGgEQAFgEABgFIAAgBQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAABAAIAGABQAAABABAAQAAAAAAAAQAAAAABABQAAAAAAAAIgBADQgCAIgIAGQgIAFgLAAQgJAAgIgGg");
	this.shape_37.setTransform(666.575,428.95);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#9F979E").s().p("AAUAlQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAgsQAAgIgFgGQgFgEgIAAQgGAAgFAEQgFAEgBAHIAAAvQAAABAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgGAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAhFQAAAAAAAAQAAgBAAAAQAAAAABAAQAAgBABABIAGAAQABgBAAABQABAAAAAAQAAAAAAABQAAAAAAAAIAAAGIABABIAAAAQAHgKAMABQALgBAHAIQAHAGAAAMIAAAuQAAABAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAg");
	this.shape_38.setTransform(658.775,428.9);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#9F979E").s().p("AgVAhQgHgGAAgKQAAgLAIgGQAIgGANAAIARAAIABAAIAAgGQAAgIgEgDQgFgFgIAAQgGAAgFADQgEACgBAFQAAAAgBABQAAAAAAAAQAAAAgBAAQAAABAAAAIgHgBQgBgBAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAQABgIAIgFQAHgFALAAQANAAAHAGQAHAIAAAKIAAAwQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAIgGAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgFIgBgBIAAABQgEAEgGACQgGACgGAAQgKAAgHgFgAgMAFQgGAEAAAHQAAAGAFAEQAEADAHAAQAIAAAGgEQAHgEAAgIIAAgLIgBAAIgPAAQgJAAgGADg");
	this.shape_39.setTransform(650.875,428.95);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#9F979E").s().p("AgRAlQAAAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBIAAhFQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAAAAAIAHAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAAAIIAAABIABAAQADgGAEgDQAEgCAGAAQAFAAADABQABAAAAABQAAAAAAAAQABAAAAABQAAAAgBABIgBAGQAAABAAAAQgBAAAAAAQAAAAgBAAQAAAAgBAAQgCgBgFABQgHAAgEAFQgFAGAAAIIAAApQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAg");
	this.shape_40.setTransform(645.1063,428.925);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#9F979E").s().p("AAMAuQgKAAgFgDQgFgFAAgKIAAgtIgBgBIgIAAQgBAAAAAAQAAAAAAAAQgBgBAAAAQAAAAAAAAIAAgGQAAAAAAAAQAAgBABAAQAAAAAAAAQAAgBABAAIAIAAIABAAIAAgRQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAABAAIAGAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAAARIABAAIAQAAQAAAAABABQAAAAAAAAQAAAAABABQAAAAAAAAIAAAGQAAAAAAAAQgBAAAAABQAAAAAAAAQgBAAAAAAIgQAAIgBABIAAAqQAAAGADAEQADACAHAAIADAAQABAAAAABQABAAAAAAQAAAAAAAAQAAABAAAAIAAAFQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_41.setTransform(639.225,428);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#9F979E").s().p("AAUAlQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAgsQAAgIgFgGQgFgEgIAAQgGAAgFAEQgFAEgBAHIAAAvQAAABAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgGAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAhFQAAAAAAAAQAAgBAAAAQAAAAABAAQAAgBABABIAGAAQABgBAAABQABAAAAAAQAAAAAAABQAAAAAAAAIAAAGIABABIAAAAQAHgKAMABQALgBAHAIQAHAGAAAMIAAAuQAAABAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAg");
	this.shape_42.setTransform(632.825,428.9);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#9F979E").s().p("AgQAhQgHgEgDgJQgDgHAAgNIAAgKIACgGQACgJAIgHQAHgFAKAAQAMAAAIAGQAHAHACAMIABAOQAAAAAAAAQgBABAAAAQAAAAAAAAQgBAAAAAAIguAAIgBABIABALQACAGAFAEQAFAEAHAAQAHAAAFgDQAEgCADgFIABgBIABAAIAFACQAAAAAAAAQABABAAAAQAAAAAAAAQAAABAAAAQgEAIgHAEQgHAEgKAAQgJAAgHgFgAgLgYQgFADgBAHIgCAJIABABIAlAAIAAgBIAAgIQgCgHgFgEQgFgEgHAAQgHAAgEAEg");
	this.shape_43.setTransform(624.975,428.95);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#9F979E").s().p("AAUAzQAAAAgBAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIgSgqIAAgBIgBAAIgPARIgBABIAAAYQAAABAAAAQAAAAgBABQAAAAAAAAQAAAAgBAAIgGAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBIAAhhQAAgBABAAQAAgBAAAAQAAAAABAAQAAAAABAAIAGAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAABIAAA6IABABIAdggIADgBIAHAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIgBACIgSATIAAABIAXAwIAAABQAAAAgBAAQAAABAAAAQAAAAAAAAQgBAAAAAAg");
	this.shape_44.setTransform(614.8,427.525);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#9F979E").s().p("AgRAlQAAAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBIAAhFQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAAAAAIAHAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAAAIIAAABIABAAQADgGAEgDQAEgCAGAAQAFAAADABQABAAAAABQAAAAAAAAQABAAAAABQAAAAgBABIgBAGQAAABAAAAQgBAAAAAAQAAAAgBAAQAAAAgBAAQgCgBgFABQgHAAgEAFQgFAGAAAIIAAApQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAg");
	this.shape_45.setTransform(608.6063,428.925);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#9F979E").s().p("AgVAhQgHgGAAgKQAAgLAIgGQAIgGANAAIARAAIABAAIAAgGQAAgIgEgDQgFgFgIAAQgGAAgFADQgEACgBAFQAAAAgBABQAAAAAAAAQAAAAgBAAQAAABAAAAIgHgBQgBgBAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAQABgIAIgFQAHgFALAAQANAAAHAGQAHAIAAAKIAAAwQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAIgGAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgFIgBgBIAAABQgEAEgGACQgGACgGAAQgKAAgHgFgAgMAFQgGAEAAAHQAAAGAFAEQAEADAHAAQAIAAAGgEQAHgEAAgIIAAgLIgBAAIgPAAQgJAAgGADg");
	this.shape_46.setTransform(601.625,428.95);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#9F979E").s().p("AgaA0QgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAhiQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAABAAIAGAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAAAGIABAAIAAAAQADgEAFgDQAFgCAFAAQAKAAAHAFQAHAGACAJQACAGAAAMQAAAMgBAFQgDAKgHAFQgHAFgKAAQgFAAgFgCQgFgCgDgEIAAgBIgBABIAAAiQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAgBAAgAgJgnQgEADgCAFIgCAHIAAALIAAALIACAGQACAFAEADQAEADAFAAQAFAAAFgDQAEgDACgEIACgHIABgLIgBgKIgCgHQgBgGgFgDQgEgDgGAAQgFAAgEADg");
	this.shape_47.setTransform(594.225,430.325);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#9F979E").s().p("AgRAlQAAAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBIAAhFQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAAAAAIAHAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAAAIIAAABIABAAQADgGAEgDQAEgCAGAAQAFAAADABQABAAAAABQAAAAAAAAQABAAAAABQAAAAgBABIgBAGQAAABAAAAQgBAAAAAAQAAAAgBAAQAAAAgBAAQgCgBgFABQgHAAgEAFQgFAGAAAIIAAApQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAg");
	this.shape_48.setTransform(584.9063,428.925);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#9F979E").s().p("AgVAhQgHgGAAgKQAAgLAIgGQAIgGANAAIARAAIABAAIAAgGQAAgIgEgDQgFgFgIAAQgGAAgFADQgEACgBAFQAAAAgBABQAAAAAAAAQAAAAgBAAQAAABAAAAIgHgBQgBgBAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAQABgIAIgFQAHgFALAAQANAAAHAGQAHAIAAAKIAAAwQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAIgGAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgFIgBgBIAAABQgEAEgGACQgGACgGAAQgKAAgHgFgAgMAFQgGAEAAAHQAAAGAFAEQAEADAHAAQAIAAAGgEQAHgEAAgIIAAgLIgBAAIgPAAQgJAAgGADg");
	this.shape_49.setTransform(577.875,428.95);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#9F979E").s().p("AgRAwQgIgEgEgHQgEgIAAgJIAAgnQAAgKAEgHQAEgHAIgEQAIgFAJAAQAKAAAIAFQAIADAEAIQAEAHAAAJQAAAAAAABQAAAAAAAAQAAAAgBAAQAAABAAAAIgHAAIgBAAIgBAAIAAgBQAAgLgHgGQgGgGgLgBQgKABgGAGQgHAGAAALIAAAnQAAAKAHAHQAGAGAKAAQALAAAGgGQAHgHAAgKQAAAAAAAAQAAgBABAAQAAAAAAAAQAAgBABAAIAHABIABAAIAAABQAAAKgEAHQgEAHgIAEQgIAFgKAAQgJAAgIgFg");
	this.shape_50.setTransform(569.925,427.55);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Монтажный_кадр_1_texts, null, null);


(lib.Монтажный_кадр_1_stair = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// stair
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D0CBCF").s().p("EghUAMqIAA5TMBCpAAAIAADqInrAAIAALRIrZAAIAArRMgjpAAAIAAVpg");
	this.shape.setTransform(398.8451,297.7489,0.9725,0.9725);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Монтажный_кадр_1_stair, null, null);


(lib.Монтажный_кадр_1_N = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// N
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgTAuIgBgBIgOhOIAAgCIABAAIADgBIACABIA2A7IABABIAAgBIgNhDIABgBIAAAAIAEgBIABAAIABABIAOBPIAAABIgBAAIgDABIgCgBIg2g7IgBgBIAAABIANBDIAAABIgBABIgEAAIgBAAg");
	this.shape.setTransform(703.749,408.9871,1.1679,1.1679);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#333333").ss(1,0,0,4).p("AAMBFIgXiJ");
	this.shape_1.setTransform(707.55,428.3254,1.084,1.084);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#333333").ss(1,0,0,4).p("AgYiJQA5gKAvAhQAwAiAKA5QAKA4ghAvQghAwg5AKQg5AKgvghQgwghgKg6QgKg4AhgvQAhgwA5gKg");
	this.shape_2.setTransform(708.5788,435.6271,1.0837,1.0837);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Монтажный_кадр_1_N, null, null);


(lib.Монтажный_кадр_1_bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// bg
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E3DDE2").s().p("Eg+fAlaMAAAhKzMB8/AAAMAAABKzg");
	this.shape.setTransform(400,239.425);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Монтажный_кадр_1_bg, null, null);


(lib.Group = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1_obj_
	this.Слой_1 = new lib.Group_Слой_1();
	this.Слой_1.name = "Слой_1";
	this.Слой_1.parent = this;
	this.Слой_1.setTransform(37.3,5.8,1,1,0,0,0,37.3,5.8);
	this.Слой_1.depth = 0;
	this.Слой_1.isAttachedToCamera = 0
	this.Слой_1.isAttachedToMask = 0
	this.Слой_1.layerDepth = 0
	this.Слой_1.layerIndex = 0
	this.Слой_1.maskLayerName = 0

	this.timeline.addTween(cjs.Tween.get(this.Слой_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.Group, new cjs.Rectangle(0,0,74.5,11.6), null);


(lib.viewvideo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFEFB").s().p("AgEBkIAAhfIhfAAIAAgJIBfAAIAAhfIAJAAIAABfIBfAAIAAAJIhfAAIAABfg");
	this.shape.setTransform(37.6,16.5);

	this.instance = new lib.Group();
	this.instance.parent = this;
	this.instance.setTransform(37.3,46.45,1,1,0,0,0,37.3,5.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("Ah0B1QgwgwAAhFQAAhEAwgvQAwgxBEAAQBFAAAvAxQAxAwAABDQAABFgxAwQgvAwhFAAQhEAAgwgwg");
	this.shape_1.setTransform(37.6,16.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.instance},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,74.5,52.3);


(lib.video = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.viewvideo("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(24.95,17.65,0.6711,0.6708,0,0,0,37.2,26.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,50,35.1);


(lib.btn8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgTBDQgIgEgFgJQgFgJAAgOQAAgLAEgJQAFgKAKgEQAAAAAAgBQAAAAAAAAQAAAAAAAAQAAgBAAAAQgHgDgGgHQgGgJAAgLQAAgLAFgIQAFgIAJgEQAIgFAKAAQAMAAAJAFQAIAFAFAIQAEAIAAAKQAAALgGAJQgFAHgHAEQAAAAgBAAQAAAAAAAAQAAAAAAABQABAAAAAAQAKAEAFALQADAIAAALQAAAPgFAKQgFAHgIAFQgJAEgLAAQgKAAgJgFgAgYAPQgCAGAAAKQAAAMAEAIQAHAMAPAAQAQAAAHgMQAFgIAAgMQAAgJgDgGQgCgIgHgEQgGgEgKAAQgRAAgHAPgAgNg6QgHAEgDAGQgEAGAAAIQAAAIAFAHQAEAFAGADQAFADAHAAIAAAAQAIAAAGgDQAGgDAEgFQAEgHAAgIQAAgIgDgGQgEgGgGgEQgGgDgJAAQgHAAgGADg");
	this.shape.setTransform(66.425,37.325);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgdA9QgLgKAAgSIAAhBQAAgRALgLQALgLASAAQASAAAMALQALALAAARIAABBQAAASgLAKQgMALgSAAQgSAAgLgLgAgVg2QgIAJAAANIAABBQAAANAIAJQAIAHANAAQAOAAAIgHQAIgJAAgNIAAhBQAAgNgIgJQgIgHgOAAQgNAAgIAHg");
	this.shape_1.setTransform(55.725,37.35);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgWBBQgKgIgEgLQgBgIAAgLIAAg+QAAgQAKgKQAKgKARABQAPAAALAJQAKAJgBAPIAAACIgBACIgBAAIgGAAIgBAAIgBgBIAAgCQAAgLgIgIQgHgGgKAAQgLAAgIAHQgHAHgBANIAAAgIABAAQAFgIAHgDQAHgCAIAAQAaAAAIAVQADAIAAAOQAAAMgCAHQgEALgJAHQgJAHgOgBQgMAAgKgGgAgQgBQgHAFgCAIQgBAGgBAKQABAKABAEQACAJAHAGQAGAFAKAAQAJAAAHgFQAHgFADgKQACgFgBgJQAAgLgBgFQgDgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_2.setTransform(45.15,37.35);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgTBDQgIgEgFgJQgFgJAAgOQAAgLAEgJQAFgKAKgEQAAAAAAgBQAAAAAAAAQAAAAAAAAQAAgBAAAAQgHgDgGgHQgGgJAAgLQAAgLAFgIQAFgIAJgEQAIgFAKAAQAMAAAJAFQAIAFAFAIQAEAIAAAKQAAALgGAJQgFAHgHAEQAAAAgBAAQAAAAAAAAQAAAAAAABQABAAAAAAQAKAEAFALQADAIAAALQAAAPgFAKQgFAHgIAFQgJAEgLAAQgKAAgJgFgAgYAPQgCAGAAAKQAAAMAEAIQAHAMAPAAQAQAAAHgMQAFgIAAgMQAAgJgDgGQgCgIgHgEQgGgEgKAAQgRAAgHAPgAgNg6QgHAEgDAGQgEAGAAAIQAAAIAFAHQAEAFAGADQAFADAHAAIAAAAQAIAAAGgDQAGgDAEgFQAEgHAAgIQAAgIgDgGQgEgGgGgEQgGgDgJAAQgHAAgGADg");
	this.shape_3.setTransform(66.425,37.325);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgdA9QgLgKAAgSIAAhBQAAgRALgLQALgLASAAQASAAAMALQALALAAARIAABBQAAASgLAKQgMALgSAAQgSAAgLgLgAgVg2QgIAJAAANIAABBQAAANAIAJQAIAHANAAQAOAAAIgHQAIgJAAgNIAAhBQAAgNgIgJQgIgHgOAAQgNAAgIAHg");
	this.shape_4.setTransform(55.725,37.35);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgWBBQgKgIgEgLQgBgIAAgLIAAg+QAAgQAKgKQAKgKARABQAPAAALAJQAKAJgBAPIAAACIgBACIgBAAIgGAAIgBAAIgBgBIAAgCQAAgLgIgIQgHgGgKAAQgLAAgIAHQgHAHgBANIAAAgIABAAQAFgIAHgDQAHgCAIAAQAaAAAIAVQADAIAAAOQAAAMgCAHQgEALgJAHQgJAHgOgBQgMAAgKgGgAgQgBQgHAFgCAIQgBAGgBAKQABAKABAEQACAJAHAGQAGAFAKAAQAJAAAHgFQAHgFADgKQACgFgBgJQAAgLgBgFQgDgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_5.setTransform(45.15,37.35);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3}]},1).wait(1));

	// Слой_3
	this.btnvideo608 = new lib.video();
	this.btnvideo608.name = "btnvideo608";
	this.btnvideo608.parent = this;
	this.btnvideo608.setTransform(83.15,96.35,1,1,0,0,0,25,17.5);
	this.btnvideo608._off = true;
	new cjs.ButtonHelper(this.btnvideo608, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.btnvideo608).wait(1).to({_off:false},0).wait(1));

	// Слой_2
	this.bt8 = new lib.bt8in();
	this.bt8.name = "bt8";
	this.bt8.parent = this;
	this.bt8.setTransform(55.5,50.5,1,1,0,0,0,55.5,50.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#FFFFFF").ss(2,0,0,4).p("AADLWIMaAAIAAmGIABAAIAAwlI47AAIAAQlIMgAAg");
	this.shape_6.setTransform(55.5288,50.5098,0.6956,0.6956);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AADLWIAAmGIsgAAIAAwlIY7AAIAAQlIgBAAIAAGGg");
	this.shape_7.setTransform(55.5288,50.5098,0.6956,0.6956);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.bt8}]}).to({state:[{t:this.shape_7},{t:this.shape_6}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,113.1,114.9);


(lib.btn7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgPBGQAAAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAuh9IAAgBIg6AAIgBAAIAAAJIgBABIgBABIgFAAIgBgBIgBgBIAAgQIABgCIABgBIBLAAIACABIAAACIAAAFIAAADIguB+QAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAg");
	this.shape.setTransform(66.175,37.35);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgdA9QgLgKAAgSIAAhBQAAgRALgLQALgLASAAQASAAAMALQALALAAARIAABBQAAASgLAKQgMALgSAAQgSAAgLgLgAgVg2QgIAJAAANIAABBQAAANAIAJQAIAHANAAQAOAAAIgHQAIgJAAgNIAAhBQAAgNgIgJQgIgHgOAAQgNAAgIAHg");
	this.shape_1.setTransform(55.725,37.35);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgWBBQgKgIgEgLQgBgIAAgLIAAg+QAAgQAKgKQAKgKARABQAPAAALAJQAKAJgBAPIAAACIgBACIgBAAIgGAAIgBAAIgBgBIAAgCQAAgLgIgIQgHgGgKAAQgLAAgIAHQgHAHgBANIAAAgIABAAQAFgIAHgDQAHgCAIAAQAaAAAIAVQADAIAAAOQAAAMgCAHQgEALgJAHQgJAHgOgBQgMAAgKgGgAgQgBQgHAFgCAIQgBAGgBAKQABAKABAEQACAJAHAGQAGAFAKAAQAJAAAHgFQAHgFADgKQACgFgBgJQAAgLgBgFQgDgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_2.setTransform(45.15,37.35);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgPBGQAAAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAuh9IAAgBIg6AAIgBAAIAAAJIgBABIgBABIgFAAIgBgBIgBgBIAAgQIABgCIABgBIBLAAIACABIAAACIAAAFIAAADIguB+QAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAg");
	this.shape_3.setTransform(66.175,37.35);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgdA9QgLgKAAgSIAAhBQAAgRALgLQALgLASAAQASAAAMALQALALAAARIAABBQAAASgLAKQgMALgSAAQgSAAgLgLgAgVg2QgIAJAAANIAABBQAAANAIAJQAIAHANAAQAOAAAIgHQAIgJAAgNIAAhBQAAgNgIgJQgIgHgOAAQgNAAgIAHg");
	this.shape_4.setTransform(55.725,37.35);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgWBBQgKgIgEgLQgBgIAAgLIAAg+QAAgQAKgKQAKgKARABQAPAAALAJQAKAJgBAPIAAACIgBACIgBAAIgGAAIgBAAIgBgBIAAgCQAAgLgIgIQgHgGgKAAQgLAAgIAHQgHAHgBANIAAAgIABAAQAFgIAHgDQAHgCAIAAQAaAAAIAVQADAIAAAOQAAAMgCAHQgEALgJAHQgJAHgOgBQgMAAgKgGgAgQgBQgHAFgCAIQgBAGgBAKQABAKABAEQACAJAHAGQAGAFAKAAQAJAAAHgFQAHgFADgKQACgFgBgJQAAgLgBgFQgDgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_5.setTransform(45.15,37.35);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3}]},1).wait(1));

	// Слой_3
	this.btnvideo607 = new lib.video();
	this.btnvideo607.name = "btnvideo607";
	this.btnvideo607.parent = this;
	this.btnvideo607.setTransform(79.2,96.45,1,1,0,0,0,25,17.5);
	this.btnvideo607._off = true;
	new cjs.ButtonHelper(this.btnvideo607, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.btnvideo607).wait(1).to({_off:false},0).wait(1));

	// Слой_2
	this.bt7 = new lib.bt7in();
	this.bt7.name = "bt7";
	this.bt7.parent = this;
	this.bt7.setTransform(105,56.5,1,1,0,0,0,105,56.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#FFFFFF").ss(2,0,0,4).p("A0TsXIAAQoIMeAAIAAGDIMcAAIAACDIPqAAIADpAIv3AAIAAvug");
	this.shape_6.setTransform(90.3885,55.0657,0.6956,0.6956);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AEnMYIAAiEIscAAIAAmDIseAAIAAwoIYwAAIAAPvIP3AAIgDJAg");
	this.shape_7.setTransform(90.387,55.0657,0.6956,0.6956);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.bt7}]}).to({state:[{t:this.shape_7},{t:this.shape_6}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,212,115.1);


(lib.btn6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgWBBQgKgIgDgLQgCgIgBgLIAAg+QAAgQALgKQALgKAQABQAPAAALAJQAJAJABAPIAAACIgBACIgCAAIgGAAIgBAAIgCgBIAAgCQAAgLgGgIQgIgGgKAAQgLAAgIAHQgIAHABANIAAAgIABAAQAEgIAHgDQAHgCAIAAQAaAAAJAVQACAIAAAOQAAAMgCAHQgEALgJAHQgJAHgNgBQgOAAgJgGgAgQgBQgGAFgDAIQgBAGAAAKQAAAKABAEQACAJAHAGQAGAFAKAAQAJAAAIgFQAGgFADgKQABgFABgJQAAgLgCgFQgDgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape.setTransform(90.65,37.35);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgdA9QgLgKAAgSIAAhBQAAgRALgLQALgLASAAQASAAAMALQALALAAARIAABBQAAASgLAKQgMALgSAAQgSAAgLgLgAgVg2QgIAJAAANIAABBQAAANAIAJQAIAHANAAQAOAAAIgHQAIgJAAgNIAAhBQAAgNgIgJQgIgHgOAAQgNAAgIAHg");
	this.shape_1.setTransform(79.775,37.35);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgWBBQgKgIgEgLQgCgIAAgLIAAg+QAAgQALgKQALgKAQABQAPAAAKAJQAKAJAAAPIAAACIgBACIgBAAIgGAAIgCAAIgBgBIAAgCQABgLgIgIQgGgGgLAAQgMAAgHAHQgIAHAAANIAAAgIABAAQAFgIAHgDQAHgCAIAAQAaAAAIAVQAEAIAAAOQAAAMgDAHQgEALgJAHQgJAHgOgBQgNAAgJgGgAgQgBQgGAFgDAIQgCAGAAAKQAAAKACAEQACAJAHAGQAGAFAKAAQAKAAAGgFQAIgFACgKQABgFAAgJQAAgLgCgFQgCgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_2.setTransform(69.2,37.35);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgWBBQgKgIgDgLQgCgIgBgLIAAg+QAAgQALgKQALgKAQABQAPAAALAJQAJAJABAPIAAACIgBACIgCAAIgGAAIgBAAIgCgBIAAgCQAAgLgGgIQgIgGgKAAQgLAAgIAHQgIAHABANIAAAgIABAAQAEgIAHgDQAHgCAIAAQAaAAAJAVQACAIAAAOQAAAMgCAHQgEALgJAHQgJAHgNgBQgOAAgJgGgAgQgBQgGAFgDAIQgBAGAAAKQAAAKABAEQACAJAHAGQAGAFAKAAQAJAAAIgFQAGgFADgKQABgFABgJQAAgLgCgFQgDgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_3.setTransform(90.65,37.35);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgdA9QgLgKAAgSIAAhBQAAgRALgLQALgLASAAQASAAAMALQALALAAARIAABBQAAASgLAKQgMALgSAAQgSAAgLgLgAgVg2QgIAJAAANIAABBQAAANAIAJQAIAHANAAQAOAAAIgHQAIgJAAgNIAAhBQAAgNgIgJQgIgHgOAAQgNAAgIAHg");
	this.shape_4.setTransform(79.775,37.35);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgWBBQgKgIgEgLQgCgIAAgLIAAg+QAAgQALgKQALgKAQABQAPAAAKAJQAKAJAAAPIAAACIgBACIgBAAIgGAAIgCAAIgBgBIAAgCQABgLgIgIQgGgGgLAAQgMAAgHAHQgIAHAAANIAAAgIABAAQAFgIAHgDQAHgCAIAAQAaAAAIAVQAEAIAAAOQAAAMgDAHQgEALgJAHQgJAHgOgBQgNAAgJgGgAgQgBQgGAFgDAIQgCAGAAAKQAAAKACAEQACAJAHAGQAGAFAKAAQAKAAAGgFQAIgFACgKQABgFAAgJQAAgLgCgFQgCgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_5.setTransform(69.2,37.35);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3}]},1).wait(1));

	// Слой_3
	this.btnvideo606 = new lib.video();
	this.btnvideo606.name = "btnvideo606";
	this.btnvideo606.parent = this;
	this.btnvideo606.setTransform(81.45,97.25,1,1,0,0,0,25,17.5);
	this.btnvideo606._off = true;
	new cjs.ButtonHelper(this.btnvideo606, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.btnvideo606).wait(1).to({_off:false},0).wait(1));

	// Слой_2
	this.bt6 = new lib.bt6in();
	this.bt6.name = "bt6";
	this.bt6.parent = this;
	this.bt6.setTransform(76.9,50.5,1,1,0,0,0,76.9,50.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#FFFFFF").ss(2,0,0,4).p("AxRHfILvAAIAAD3INCAAIAAmGIJyAAIAAwlMgiiAAAg");
	this.shape_6.setTransform(76.903,50.5098,0.6956,0.6956);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AliLWIAAj3IrvAAIABy0MAiiAAAIAAQlIpyAAIAAGGg");
	this.shape_7.setTransform(76.9032,50.5098,0.6956,0.6956);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.bt6}]}).to({state:[{t:this.shape_7},{t:this.shape_6}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,155.8,115.8);


(lib.btn5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgWBAQgKgIgDgMIgCgHIAAgBQAAAAAAgBQABAAAAAAQAAAAAAgBQABAAAAAAIAGAAQABAAAAAAQABABAAAAQAAAAABAAQAAABAAAAIAAABIABADQACAKAHAGQAHAFAJAAQALAAAHgGQAHgGACgKIABgMIgBgOQgCgKgHgFQgHgFgLAAQgJAAgHAEQgHADgCAHQAAABgBAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgHAAIgBAAIgBgCIAAhKIABgCIABgBIBBAAIACABIABACIAAAEIgBACIgCABIg4AAIAAAAIgBA2IABABIAAgBQAFgFAHgDQAIgDAHAAQAOAAAKAHQAKAHACAMQABAIAAAJQAAAKgBAHQgDANgKAHQgKAIgOAAQgNAAgJgHg");
	this.shape.setTransform(66.575,60.175);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgdA9QgLgKAAgSIAAhBQAAgRALgLQALgLASAAQASAAAMALQALALAAARIAABBQAAASgLAKQgMALgSAAQgSAAgLgLgAgVg2QgIAJAAANIAABCQAAANAIAHQAIAJANgBQAOABAIgJQAIgHAAgNIAAhCQAAgNgIgJQgIgHgOgBQgNABgIAHg");
	this.shape_1.setTransform(55.725,60.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgWBAQgKgGgEgNQgBgGAAgMIAAg+QAAgQAKgKQAKgKARAAQAPABALAIQAKAKgBAPIAAACIgBABIgBABIgGAAIgBgBIgBgBIAAgBQAAgLgIgIQgHgGgKAAQgLAAgIAHQgHAHgBAMIAAAhIABAAQAFgHAHgDQAHgDAIgBQAaAAAIAWQADAIAAANQAAANgCAGQgEAMgJAHQgJAGgOAAQgMABgKgIgAgQgBQgHAEgCAJQgBAGgBAKQABAKABAEQACAJAHAGQAGAFAKAAQAJAAAHgFQAHgFADgKQACgEgBgLQAAgKgBgFQgDgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_2.setTransform(45.15,60.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgWBAQgKgIgDgMIgCgHIAAgBQAAAAAAgBQABAAAAAAQAAAAAAgBQABAAAAAAIAGAAQABAAAAAAQABABAAAAQAAAAABAAQAAABAAAAIAAABIABADQACAKAHAGQAHAFAJAAQALAAAHgGQAHgGACgKIABgMIgBgOQgCgKgHgFQgHgFgLAAQgJAAgHAEQgHADgCAHQAAABgBAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgHAAIgBAAIgBgCIAAhKIABgCIABgBIBBAAIACABIABACIAAAEIgBACIgCABIg4AAIAAAAIgBA2IABABIAAgBQAFgFAHgDQAIgDAHAAQAOAAAKAHQAKAHACAMQABAIAAAJQAAAKgBAHQgDANgKAHQgKAIgOAAQgNAAgJgHg");
	this.shape_3.setTransform(66.575,60.175);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgdA9QgLgKAAgSIAAhBQAAgRALgLQALgLASAAQASAAAMALQALALAAARIAABBQAAASgLAKQgMALgSAAQgSAAgLgLgAgVg2QgIAJAAANIAABCQAAANAIAHQAIAJANgBQAOABAIgJQAIgHAAgNIAAhCQAAgNgIgJQgIgHgOgBQgNABgIAHg");
	this.shape_4.setTransform(55.725,60.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgWBAQgKgGgEgNQgBgGAAgMIAAg+QAAgQAKgKQAKgKARAAQAPABALAIQAKAKgBAPIAAACIgBABIgBABIgGAAIgBgBIgBgBIAAgBQAAgLgIgIQgHgGgKAAQgLAAgIAHQgHAHgBAMIAAAhIABAAQAFgHAHgDQAHgDAIgBQAaAAAIAWQADAIAAANQAAANgCAGQgEAMgJAHQgJAGgOAAQgMABgKgIgAgQgBQgHAEgCAJQgBAGgBAKQABAKABAEQACAJAHAGQAGAFAKAAQAJAAAHgFQAHgFADgKQACgEgBgLQAAgKgBgFQgDgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_5.setTransform(45.15,60.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3}]},1).wait(1));

	// Слой_3
	this.btnvideo605 = new lib.video();
	this.btnvideo605.name = "btnvideo605";
	this.btnvideo605.parent = this;
	this.btnvideo605.setTransform(82.6,117.3,1,1,0,0,0,25,17.5);
	this.btnvideo605._off = true;
	new cjs.ButtonHelper(this.btnvideo605, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.btnvideo605).wait(1).to({_off:false},0).wait(1));

	// Слой_2
	this.bt5 = new lib.bt5in();
	this.bt5.name = "bt5";
	this.bt5.parent = this;
	this.bt5.setTransform(56.3,61.6,1,1,0,0,0,56.3,61.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#FFFFFF").ss(2,0,0,4).p("AMnnwIAAmFIsfAAIAAGFIsxAAIAAQdIBdAAIAAFJIX2AAIAAwdIgEAAIAAlJg");
	this.shape_6.setTransform(56.3416,61.623,0.6956,0.6956);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("ArMN2IAAlJIhdAAIAAwdIMxAAIAAmFIMfAAIAAGFIgBAAIAAFJIAEAAIAAQdg");
	this.shape_7.setTransform(56.3416,61.623,0.6956,0.6956);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.bt5}]}).to({state:[{t:this.shape_7},{t:this.shape_6}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,114.7,135.9);


(lib.btn4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAWBGIgBgBIAAgBIAAgkIgBgBIg7AAIgBgBIgBgCIAAgEIABgDIAphYQAAgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAIAGAAIABABIAAACIgoBWIAAABIAxAAIABAAIAAghIAAgCIABAAIAHAAIABAAIABACIAAAhIABAAIAIAAIABABIABACIAAAEIgBACIgBABIgIAAIgBABIAAAkIgBABIgBABg");
	this.shape.setTransform(66.6,60.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgdA9QgLgKAAgSIAAhBQAAgRALgLQALgLASAAQASAAAMALQALALAAARIAABBQAAASgLAKQgMALgSAAQgSAAgLgLgAgVg2QgIAJAAANIAABCQAAANAIAHQAIAJANgBQAOABAIgJQAIgHAAgNIAAhCQAAgNgIgJQgIgHgOgBQgNABgIAHg");
	this.shape_1.setTransform(55.725,60.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgWBAQgKgGgEgNQgBgGAAgMIAAg+QAAgQAKgKQAKgKARAAQAPABALAIQAKAKgBAPIAAACIgBABIgBABIgGAAIgBgBIgBgBIAAgBQAAgLgIgIQgHgGgKAAQgLAAgIAHQgHAHgBAMIAAAhIABAAQAFgHAHgDQAHgDAIgBQAaAAAIAWQADAIAAANQAAANgCAGQgEAMgJAHQgJAGgOAAQgMABgKgIgAgQgBQgHAEgCAJQgBAGgBAKQABAKABAEQACAJAHAGQAGAFAKAAQAJAAAHgFQAHgFADgKQACgEgBgLQAAgKgBgFQgDgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_2.setTransform(45.15,60.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AAWBGIgBgBIAAgBIAAgkIgBgBIg7AAIgBgBIgBgCIAAgEIABgDIAphYQAAgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAIAGAAIABABIAAACIgoBWIAAABIAxAAIABAAIAAghIAAgCIABAAIAHAAIABAAIABACIAAAhIABAAIAIAAIABABIABACIAAAEIgBACIgBABIgIAAIgBABIAAAkIgBABIgBABg");
	this.shape_3.setTransform(66.6,60.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgdA9QgLgKAAgSIAAhBQAAgRALgLQALgLASAAQASAAAMALQALALAAARIAABBQAAASgLAKQgMALgSAAQgSAAgLgLgAgVg2QgIAJAAANIAABCQAAANAIAHQAIAJANgBQAOABAIgJQAIgHAAgNIAAhCQAAgNgIgJQgIgHgOgBQgNABgIAHg");
	this.shape_4.setTransform(55.725,60.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgWBAQgKgGgEgNQgBgGAAgMIAAg+QAAgQAKgKQAKgKARAAQAPABALAIQAKAKgBAPIAAACIgBABIgBABIgGAAIgBgBIgBgBIAAgBQAAgLgIgIQgHgGgKAAQgLAAgIAHQgHAHgBAMIAAAhIABAAQAFgHAHgDQAHgDAIgBQAaAAAIAWQADAIAAANQAAANgCAGQgEAMgJAHQgJAGgOAAQgMABgKgIgAgQgBQgHAEgCAJQgBAGgBAKQABAKABAEQACAJAHAGQAGAFAKAAQAJAAAHgFQAHgFADgKQACgEgBgLQAAgKgBgFQgDgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_5.setTransform(45.15,60.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3}]},1).wait(1));

	// Слой_3
	this.btnvideo604 = new lib.video();
	this.btnvideo604.name = "btnvideo604";
	this.btnvideo604.parent = this;
	this.btnvideo604.setTransform(99.3,95.1,1,1,0,0,0,25,17.5);
	this.btnvideo604._off = true;
	new cjs.ButtonHelper(this.btnvideo604, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.btnvideo604).wait(1).to({_off:false},0).wait(1));

	// Слой_2
	this.bt4 = new lib.bt4in();
	this.bt4.name = "bt4";
	this.bt4.parent = this;
	this.bt4.setTransform(55.5,50.1,1,1,0,0,0,55.5,50.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#FFFFFF").ss(2,0,0,4).p("AMelLIseAAIAAmFIsdAAIAAWhIY7AAg");
	this.shape_6.setTransform(55.4483,50.1811,0.6956,0.6956);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AscLRIAA2hIMcAAIAAGFIMeAAIAAQcg");
	this.shape_7.setTransform(55.4483,50.1811,0.6956,0.6956);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.bt4}]}).to({state:[{t:this.shape_7},{t:this.shape_6}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,125.3,113.7);


(lib.btn3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgWBAQgKgIgDgMQgCgFAAgJQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAIAGAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIABAKQADAKAHAGQAHAFAJAAQAKAAAGgEQAGgEADgJQADgIAAgJQAAgNgEgIQgGgPgSAAIgFABIgBABQAAAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAgBIgDgDIAAgCIAAgBIAjgsIAAgBIg6AAIgCgBIgBgCIAAgEIABgCIACgBIBFAAIACABIABACIAAAFIgBADIgiAqIAAABIABAAQALABAIAFQAIAFADAIQAEAKAAAOQAAALgCAIQgEAMgJAHQgJAGgOAAQgNAAgJgHg");
	this.shape.setTransform(66.275,60.175);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgdA9QgLgKAAgSIAAhBQAAgRALgLQALgLASAAQASAAAMALQALALAAARIAABBQAAASgLAKQgMALgSAAQgSAAgLgLgAgVg2QgIAJAAANIAABCQAAANAIAHQAIAJANgBQAOABAIgJQAIgHAAgNIAAhCQAAgNgIgJQgIgHgOgBQgNABgIAHg");
	this.shape_1.setTransform(55.725,60.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgWBAQgKgGgEgNQgBgGAAgMIAAg+QAAgQAKgKQAKgKARAAQAPABALAIQAKAKgBAPIAAACIgBABIgBABIgGAAIgBgBIgBgBIAAgBQAAgLgIgIQgHgGgKAAQgLAAgIAHQgHAHgBAMIAAAhIABAAQAFgHAHgDQAHgDAIgBQAaAAAIAWQADAIAAANQAAANgCAGQgEAMgJAHQgJAGgOAAQgMABgKgIgAgQgBQgHAEgCAJQgBAGgBAKQABAKABAEQACAJAHAGQAGAFAKAAQAJAAAHgFQAHgFADgKQACgEgBgLQAAgKgBgFQgDgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_2.setTransform(45.15,60.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgWBAQgKgIgDgMQgCgFAAgJQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAIAGAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIABAKQADAKAHAGQAHAFAJAAQAKAAAGgEQAGgEADgJQADgIAAgJQAAgNgEgIQgGgPgSAAIgFABIgBABQAAAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAgBIgDgDIAAgCIAAgBIAjgsIAAgBIg6AAIgCgBIgBgCIAAgEIABgCIACgBIBFAAIACABIABACIAAAFIgBADIgiAqIAAABIABAAQALABAIAFQAIAFADAIQAEAKAAAOQAAALgCAIQgEAMgJAHQgJAGgOAAQgNAAgJgHg");
	this.shape_3.setTransform(66.275,60.175);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgdA9QgLgKAAgSIAAhBQAAgRALgLQALgLASAAQASAAAMALQALALAAARIAABBQAAASgLAKQgMALgSAAQgSAAgLgLgAgVg2QgIAJAAANIAABCQAAANAIAHQAIAJANgBQAOABAIgJQAIgHAAgNIAAhCQAAgNgIgJQgIgHgOgBQgNABgIAHg");
	this.shape_4.setTransform(55.725,60.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgWBAQgKgGgEgNQgBgGAAgMIAAg+QAAgQAKgKQAKgKARAAQAPABALAIQAKAKgBAPIAAACIgBABIgBABIgGAAIgBgBIgBgBIAAgBQAAgLgIgIQgHgGgKAAQgLAAgIAHQgHAHgBAMIAAAhIABAAQAFgHAHgDQAHgDAIgBQAaAAAIAWQADAIAAANQAAANgCAGQgEAMgJAHQgJAGgOAAQgMABgKgIgAgQgBQgHAEgCAJQgBAGgBAKQABAKABAEQACAJAHAGQAGAFAKAAQAJAAAHgFQAHgFADgKQACgEgBgLQAAgKgBgFQgDgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_5.setTransform(45.15,60.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3}]},1).wait(1));

	// Слой_3
	this.btnvideo603 = new lib.video();
	this.btnvideo603.name = "btnvideo603";
	this.btnvideo603.parent = this;
	this.btnvideo603.setTransform(98.75,95.7,1,1,0,0,0,25,17.5);
	this.btnvideo603._off = true;
	new cjs.ButtonHelper(this.btnvideo603, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.btnvideo603).wait(1).to({_off:false},0).wait(1));

	// Слой_2
	this.bt3 = new lib.bt3in();
	this.bt3.name = "bt3";
	this.bt3.parent = this;
	this.bt3.setTransform(55.5,50.1,1,1,0,0,0,55.5,50.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#FFFFFF").ss(2,0,0,4).p("AMelLIseAAIAAmFIsdAAIAAWhIY7AAg");
	this.shape_6.setTransform(55.457,50.1811,0.6956,0.6956);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AscLRIAA2hIMcAAIAAGFIMeAAIAAQcg");
	this.shape_7.setTransform(55.457,50.1811,0.6956,0.6956);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.bt3}]}).to({state:[{t:this.shape_7},{t:this.shape_6}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,124.8,114.3);


(lib.btn2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AglBHIgBgBIgBgCIAAgFIABgDIAsg5QATgYAAgOQAAgLgIgHQgIgHgLAAQgMAAgHAHQgIAHAAALIAAAGIgBACIgBAAIgGAAIgCAAIAAgCIAAgHQAAgPAKgKQAKgJARAAQALAAAIAFQAJAEAFAIQAFAIAAAKQAAARgUAYIgpA2QAAABAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAIA/AAIACABIABACIAAAEIgBACIgCABg");
	this.shape.setTransform(88.1,60.025);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgdA9QgLgKAAgSIAAhBQAAgRALgLQALgLASAAQASAAAMALQALALAAARIAABBQAAASgLAKQgMALgSAAQgSAAgLgLgAgVg2QgIAJAAANIAABCQAAANAIAHQAIAJANgBQAOABAIgJQAIgHAAgNIAAhCQAAgNgIgJQgIgHgOgBQgNABgIAHg");
	this.shape_1.setTransform(77.175,60.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgWBAQgKgGgEgNQgCgGAAgMIAAg+QAAgQALgKQALgKAQAAQAQABAJAIQAKAKAAAPIAAACIgBABIgBABIgGAAIgCgBIgBgBIAAgBQABgLgIgIQgGgGgLAAQgMAAgHAHQgIAHAAAMIAAAhIACAAQAEgHAHgDQAHgDAIgBQAaAAAIAWQAEAIAAANQgBANgCAGQgEAMgJAHQgJAGgNAAQgNABgKgIgAgQgBQgGAEgDAJQgCAGAAAKQAAAKACAEQACAJAHAGQAHAFAJAAQAKAAAGgFQAIgFACgKQACgEAAgLQgBgKgCgFQgCgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_2.setTransform(66.6,60.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AglBHIgBgBIgBgCIAAgFIABgDIAsg5QATgYAAgOQAAgLgIgHQgIgHgLAAQgMAAgHAHQgIAHAAALIAAAGIgBACIgBAAIgGAAIgCAAIAAgCIAAgHQAAgPAKgKQAKgJARAAQALAAAIAFQAJAEAFAIQAFAIAAAKQAAARgUAYIgpA2QAAABAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAIA/AAIACABIABACIAAAEIgBACIgCABg");
	this.shape_3.setTransform(88.1,60.025);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgdA9QgLgKAAgSIAAhBQAAgRALgLQALgLASAAQASAAAMALQALALAAARIAABBQAAASgLAKQgMALgSAAQgSAAgLgLgAgVg2QgIAJAAANIAABCQAAANAIAHQAIAJANgBQAOABAIgJQAIgHAAgNIAAhCQAAgNgIgJQgIgHgOgBQgNABgIAHg");
	this.shape_4.setTransform(77.175,60.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgWBAQgKgGgEgNQgCgGAAgMIAAg+QAAgQALgKQALgKAQAAQAQABAJAIQAKAKAAAPIAAACIgBABIgBABIgGAAIgCgBIgBgBIAAgBQABgLgIgIQgGgGgLAAQgMAAgHAHQgIAHAAAMIAAAhIACAAQAEgHAHgDQAHgDAIgBQAaAAAIAWQAEAIAAANQgBANgCAGQgEAMgJAHQgJAGgNAAQgNABgKgIgAgQgBQgGAEgDAJQgCAGAAAKQAAAKACAEQACAJAHAGQAHAFAJAAQAKAAAGgFQAIgFACgKQACgEAAgLQgBgKgCgFQgCgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_5.setTransform(66.6,60.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3}]},1).wait(1));

	// Слой_6
	this.btnvideo602 = new lib.video();
	this.btnvideo602.name = "btnvideo602";
	this.btnvideo602.parent = this;
	this.btnvideo602.setTransform(78.05,94.55,1,1,0,0,0,25,17.5);
	this.btnvideo602._off = true;
	new cjs.ButtonHelper(this.btnvideo602, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.btnvideo602).wait(1).to({_off:false},0).wait(1));

	// Слой_2
	this.bt2 = new lib.bt2in();
	this.bt2.name = "bt2";
	this.bt2.parent = this;
	this.bt2.setTransform(77.7,50.1,1,1,0,0,0,77.7,50.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#FFFFFF").ss(2,0,0,4).p("ARclLIsiAAIAAmFI2VAAIAAWhMAi3AAAg");
	this.shape_6.setTransform(77.6731,50.1811,0.6956,0.6956);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AxbLRIAA2hIWVAAIAAGFIMjAAIAAQcg");
	this.shape_7.setTransform(77.6731,50.1811,0.6956,0.6956);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.bt2}]}).to({state:[{t:this.shape_7},{t:this.shape_6}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,157.4,113.1);


(lib.btn1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAKBGIgCgBIAAgCIAAh8IgBAAIAAAAIgVAKIgCAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAgDQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBIAWgMIADgBIAHAAIACABIAAABIAACGIAAACIgCABg");
	this.shape.setTransform(39.575,120.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgdA9QgLgKAAgSIAAhBQAAgSALgKQALgLASAAQASAAAMALQALAKAAASIAABBQAAASgLAKQgMALgSAAQgSAAgLgLgAgVg1QgIAHAAAOIAABBQAAANAIAJQAIAHANABQAOgBAIgHQAIgJAAgNIAAhBQAAgOgIgHQgIgIgOAAQgNAAgIAIg");
	this.shape_1.setTransform(30.925,120.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgWBBQgKgIgDgLQgDgIAAgLIAAg+QAAgQALgKQALgJAQAAQAQAAAJAJQALAJAAAPIAAACIgCACIgBAAIgGAAIgCAAIgBgBIAAgCQAAgLgGgIQgIgGgKAAQgMAAgHAHQgIAIABAMIAAAgIABAAQAEgIAHgDQAHgCAIAAQAaAAAJAVQADAIAAAOQgBAMgCAHQgEALgJAHQgJAHgNAAQgOgBgJgGgAgQgBQgHAEgCAJQgBAGAAAKQAAAKABAEQACAJAHAGQAHAFAJAAQAKAAAGgFQAIgFACgKQACgFAAgJQAAgLgDgFQgCgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_2.setTransform(20.35,120.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AAKBGIgCgBIAAgCIAAh8IgBAAIAAAAIgVAKIgCAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAgDQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBIAWgMIADgBIAHAAIACABIAAABIAACGIAAACIgCABg");
	this.shape_3.setTransform(39.575,120.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgdA9QgLgKAAgSIAAhBQAAgSALgKQALgLASAAQASAAAMALQALAKAAASIAABBQAAASgLAKQgMALgSAAQgSAAgLgLgAgVg1QgIAHAAAOIAABBQAAANAIAJQAIAHANABQAOgBAIgHQAIgJAAgNIAAhBQAAgOgIgHQgIgIgOAAQgNAAgIAIg");
	this.shape_4.setTransform(30.925,120.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgWBBQgKgIgDgLQgDgIAAgLIAAg+QAAgQALgKQALgJAQAAQAQAAAJAJQALAJAAAPIAAACIgCACIgBAAIgGAAIgCAAIgBgBIAAgCQAAgLgGgIQgIgGgKAAQgMAAgHAHQgIAIABAMIAAAgIABAAQAEgIAHgDQAHgCAIAAQAaAAAJAVQADAIAAAOQgBAMgCAHQgEALgJAHQgJAHgNAAQgOgBgJgGgAgQgBQgHAEgCAJQgBAGAAAKQAAAKABAEQACAJAHAGQAHAFAJAAQAKAAAGgFQAIgFACgKQACgFAAgJQAAgLgDgFQgCgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_5.setTransform(20.35,120.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3}]},1).wait(1));

	// Слой_3
	this.btnvideo601 = new lib.video();
	this.btnvideo601.name = "btnvideo601";
	this.btnvideo601.parent = this;
	this.btnvideo601.setTransform(29.7,217.8,1,1,0,0,0,25,17.5);
	this.btnvideo601._off = true;
	new cjs.ButtonHelper(this.btnvideo601, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.btnvideo601).wait(1).to({_off:false},0).wait(1));

	// Слой_2
	this.bt1 = new lib.bt1in();
	this.bt1.name = "bt1";
	this.bt1.parent = this;
	this.bt1.setTransform(45.2,111.5,1,1,0,0,0,45.2,111.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#FFFFFF").ss(2,0,0,4).p("AjOseIm7AAMAAAAliINlAAIAC7oIGsAAIgD2fItVAAg");
	this.shape_6.setTransform(45.2276,111.5553,0.6956,0.6956);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AqJZEMAAAgliIG8AAIAAslINVAAIACWfImsAAIgCbog");
	this.shape_7.setTransform(45.227,111.5553,0.6956,0.6956);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.bt1}]}).to({state:[{t:this.shape_7},{t:this.shape_6}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-4,171.4,239.4);


(lib.Монтажный_кадр_1_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// btn
	this.instance = new lib.btn8();
	this.instance.parent = this;
	this.instance.setTransform(321.6,292.35,1.0032,1.0032,0,0,0,55.6,50.6);
	new cjs.ButtonHelper(this.instance, 0, 1, 1);

	this.instance_1 = new lib.btn7();
	this.instance_1.parent = this;
	this.instance_1.setTransform(467.95,296.85,1.0032,1.0032,0,0,0,90.5,55.1);
	new cjs.ButtonHelper(this.instance_1, 0, 1, 1);

	this.instance_2 = new lib.btn4();
	this.instance_2.parent = this;
	this.instance_2.setTransform(544.35,168.5,1.0032,1.0032,0,0,0,55.6,50.3);
	new cjs.ButtonHelper(this.instance_2, 0, 1, 1);

	this.instance_3 = new lib.btn5();
	this.instance_3.parent = this;
	this.instance_3.setTransform(599.8,118.15,1.0032,1.0032,0,0,0,0,0.1);
	new cjs.ButtonHelper(this.instance_3, 0, 1, 1);

	this.instance_4 = new lib.btn6();
	this.instance_4.parent = this;
	this.instance_4.setTransform(558.5,241.6,1.0032,1.0032);
	new cjs.ButtonHelper(this.instance_4, 0, 1, 1);

	this.instance_5 = new lib.btn3();
	this.instance_5.parent = this;
	this.instance_5.setTransform(433,168.5,1.0032,1.0032,0,0,0,55.6,50.3);
	new cjs.ButtonHelper(this.instance_5, 0, 1, 1);

	this.instance_6 = new lib.btn2();
	this.instance_6.parent = this;
	this.instance_6.setTransform(299.25,168.5,1.0032,1.0032,0,0,0,77.7,50.3);
	new cjs.ButtonHelper(this.instance_6, 0, 1, 1);

	this.instance_7 = new lib.btn1();
	this.instance_7.parent = this;
	this.instance_7.setTransform(176.15,230.25,1.0032,1.0032,0,0,0,45.3,111.6);
	new cjs.ButtonHelper(this.instance_7, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_7},{t:this.instance_6},{t:this.instance_5},{t:this.instance_4},{t:this.instance_3},{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Монтажный_кадр_1_btn, null, null);


// stage content:
(lib.FLOOR6_v441 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	this.___GetDepth___ = function(obj) {
		var depth = obj.depth;
		var cameraObj = this.___camera___instance;
		if(cameraObj && cameraObj.depth && obj.isAttachedToCamera)
		{
			depth += depth + cameraObj.depth;
		}
		return depth;
		}
	this.___needSorting___ = function() {
		for (var i = 0; i < this.getNumChildren() - 1; i++)
		{
			var prevDepth = this.___GetDepth___(this.getChildAt(i));
			var nextDepth = this.___GetDepth___(this.getChildAt(i + 1));
			if (prevDepth < nextDepth)
				return true;
		}
		return false;
	}
	this.___sortFunction___ = function(obj1, obj2) {
		return (this.exportRoot.___GetDepth___(obj2) - this.exportRoot.___GetDepth___(obj1));
	}
	this.on('tick', function (event){
		var curTimeline = event.currentTarget;
		if (curTimeline.___needSorting___()){
			this.sortChildren(curTimeline.___sortFunction___);
		}
	});

	// btn_obj_
	this.btn = new lib.Монтажный_кадр_1_btn();
	this.btn.name = "btn";
	this.btn.parent = this;
	this.btn.setTransform(421.8,235.5,1,1,0,0,0,421.8,235.5);
	this.btn.depth = 0;
	this.btn.isAttachedToCamera = 0
	this.btn.isAttachedToMask = 0
	this.btn.layerDepth = 0
	this.btn.layerIndex = 0
	this.btn.maskLayerName = 0

	this.timeline.addTween(cjs.Tween.get(this.btn).wait(1));

	// texts_obj_
	this.texts = new lib.Монтажный_кадр_1_texts();
	this.texts.name = "texts";
	this.texts.parent = this;
	this.texts.setTransform(354.7,308.2,1,1,0,0,0,354.7,308.2);
	this.texts.depth = 0;
	this.texts.isAttachedToCamera = 0
	this.texts.isAttachedToMask = 0
	this.texts.layerDepth = 0
	this.texts.layerIndex = 1
	this.texts.maskLayerName = 0

	this.timeline.addTween(cjs.Tween.get(this.texts).wait(1));

	// walls_obj_
	this.walls = new lib.Монтажный_кадр_1_walls();
	this.walls.name = "walls";
	this.walls.parent = this;
	this.walls.setTransform(404.2,230.5,1,1,0,0,0,404.2,230.5);
	this.walls.depth = 0;
	this.walls.isAttachedToCamera = 0
	this.walls.isAttachedToMask = 0
	this.walls.layerDepth = 0
	this.walls.layerIndex = 2
	this.walls.maskLayerName = 0

	this.timeline.addTween(cjs.Tween.get(this.walls).wait(1));

	// stair_obj_
	this.stair = new lib.Монтажный_кадр_1_stair();
	this.stair.name = "stair";
	this.stair.parent = this;
	this.stair.setTransform(398.9,297.8,1,1,0,0,0,398.9,297.8);
	this.stair.depth = 0;
	this.stair.isAttachedToCamera = 0
	this.stair.isAttachedToMask = 0
	this.stair.layerDepth = 0
	this.stair.layerIndex = 3
	this.stair.maskLayerName = 0

	this.timeline.addTween(cjs.Tween.get(this.stair).wait(1));

	// N_obj_
	this.N = new lib.Монтажный_кадр_1_N();
	this.N.name = "N";
	this.N.parent = this;
	this.N.setTransform(708.6,427.4,1,1,0,0,0,708.6,427.4);
	this.N.depth = 0;
	this.N.isAttachedToCamera = 0
	this.N.isAttachedToMask = 0
	this.N.layerDepth = 0
	this.N.layerIndex = 4
	this.N.maskLayerName = 0

	this.timeline.addTween(cjs.Tween.get(this.N).wait(1));

	// bg_obj_
	this.bg = new lib.Монтажный_кадр_1_bg();
	this.bg.name = "bg";
	this.bg.parent = this;
	this.bg.setTransform(400,239.4,1,1,0,0,0,400,239.4);
	this.bg.depth = 0;
	this.bg.isAttachedToCamera = 0
	this.bg.isAttachedToMask = 0
	this.bg.layerDepth = 0
	this.bg.layerIndex = 5
	this.bg.maskLayerName = 0

	this.timeline.addTween(cjs.Tween.get(this.bg).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(400,240,400,238.89999999999998);
// library properties:
lib.properties = {
	id: '224194AF442E2F4E81860E254E11FC15',
	width: 800,
	height: 480,
	fps: 24,
	color: "#E3DDE2",
	opacity: 1.00,
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['224194AF442E2F4E81860E254E11FC15'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


// Layer depth API : 

AdobeAn.Layer = new function() {
	this.getLayerZDepth = function(timeline, layerName)
	{
		if(layerName === "Camera")
		layerName = "___camera___instance";
		var script = "if(timeline." + layerName + ") timeline." + layerName + ".depth; else 0;";
		return eval(script);
	}
	this.setLayerZDepth = function(timeline, layerName, zDepth)
	{
		const MAX_zDepth = 10000;
		const MIN_zDepth = -5000;
		if(zDepth > MAX_zDepth)
			zDepth = MAX_zDepth;
		else if(zDepth < MIN_zDepth)
			zDepth = MIN_zDepth;
		if(layerName === "Camera")
		layerName = "___camera___instance";
		var script = "if(timeline." + layerName + ") timeline." + layerName + ".depth = " + zDepth + ";";
		eval(script);
	}
	this.removeLayer = function(timeline, layerName)
	{
		if(layerName === "Camera")
		layerName = "___camera___instance";
		var script = "if(timeline." + layerName + ") timeline.removeChild(timeline." + layerName + ");";
		eval(script);
	}
	this.addNewLayer = function(timeline, layerName, zDepth)
	{
		if(layerName === "Camera")
		layerName = "___camera___instance";
		zDepth = typeof zDepth !== 'undefined' ? zDepth : 0;
		var layer = new createjs.MovieClip();
		layer.name = layerName;
		layer.depth = zDepth;
		layer.layerIndex = 0;
		timeline.addChild(layer);
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;