(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Group_Слой_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("AgbAdQgLgLAAgSQAAgRALgLQALgMAQAAQARAAALAMQALALAAARQAAASgLALQgLAMgRAAQgPAAgMgMgAgTgXQgIAKAAANQAAAOAIAJQAIAKALAAQANAAAIgKQAHgIAAgPQAAgNgHgKQgIgJgNAAQgLAAgIAJg");
	this.shape.setTransform(70.575,7.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("AgaAeQgLgLAAgSQAAgRALgMQALgMAQAAQARAAAKALQAKALAAARIAAAEIg/AAQABANAHAJQAIAIAKAAQAWAAAFgVIAKAAQgDANgJAIQgKAIgOAAQgRAAgLgLgAgQgYQgHAIgBAMIAzAAQAAgMgGgHQgHgJgMAAQgKAAgIAIg");
	this.shape_1.setTransform(61.7,7.475);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#333333").s().p("AgcAuQgJgLAAgSQAAgRAJgLQAKgMARAAQAKAAAHAGQAIAFADAIIAAg1IALAAIAABwIgLAAIAAgRQgDAJgHAFQgJAGgJAAQgRAAgKgMgAgZAQQABAPAGAIQAHAJALAAQAMAAAIgIQAJgIgBgOIAAgFQAAgNgHgIQgIgIgNAAQgZAAAAAgg");
	this.shape_2.setTransform(52.45,5.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#333333").s().p("AgEA4IAAhMIAKAAIAABMgAgFgoIAAgPIALAAIAAAPg");
	this.shape_3.setTransform(46.475,5.725);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#333333").s().p("AgDAnIghhNIAMAAIAZA+IAZg+IALAAIgiBNg");
	this.shape_4.setTransform(41.025,7.475);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#333333").s().p("AAUAnIgSg9IgBAAIgTA9IgKAAIgZhNIALAAIAUA+IACAAIARg+IAJAAIASA+IAUg+IAKAAIgYBNg");
	this.shape_5.setTransform(28.225,7.475);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#333333").s().p("AgaAeQgLgLAAgSQAAgRALgMQALgMAQAAQARAAALALQAJALAAARIAAAEIg/AAQABANAIAJQAIAIAKAAQAVAAAFgVIAKAAQgDANgJAIQgKAIgOAAQgQAAgMgLgAgQgYQgHAIgBAMIAzAAQAAgMgGgHQgHgJgMAAQgKAAgIAIg");
	this.shape_6.setTransform(18.275,7.475);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#333333").s().p("AgFA4IAAhMIAKAAIAABMgAgFgoIAAgPIALAAIAAAPg");
	this.shape_7.setTransform(12.35,5.725);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#333333").s().p("AgGA4IguhvIAMAAIAoBkIABAAIAohkIAMAAIgvBvg");
	this.shape_8.setTransform(5.275,5.725);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Group_Слой_1, null, null);


(lib.Монтажный_кадр_1_walls = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// walls
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E9E5E8").s().p("ArILJIAAxSILSAAIAAk/IK/AAIAAJAIplAAIAAJAIk8AAIAAERg");
	this.shape.setTransform(151.9146,131.4914,0.9725,0.9725);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E9E5E8").s().p("ADhGrIAAkXIwBAAIAAo+IZBAAIAANVg");
	this.shape_1.setTransform(299.1783,103.7746,0.9725,0.9725);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#E9E5E8").s().p("AAAGrIAAkXIo7AAIAAo+IR3AAIAANVg");
	this.shape_2.setTransform(432.7295,103.7746,0.9725,0.9725);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#E9E5E8").s().p("AABGrIAAkXIo8AAIAAo+IR3AAIAANVg");
	this.shape_3.setTransform(544.1072,103.7746,0.9725,0.9725);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#E9E5E8").s().p("AqHGrIAAtVISKAAIAAAAICFAAIAAJAIiFAAIgDgCIo7AAIAAEXg");
	this.shape_4.setTransform(662.7059,103.6774,0.9725,0.9725);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#E9E5E8").s().p("AtcGPIACq3IIbAAIAACxIJWAAIAAkXIHBAAIAAEmICFAAIAAH3g");
	this.shape_5.setTransform(641.9912,354.5872,0.9725,0.9725);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#E9E5E8").s().p("AujGqIAAtTII9AAIAAEWII6AAIAABeILPAAIAAGoIq7AAIAAA3g");
	this.shape_6.setTransform(467.7888,357.3346,0.9725,0.9725);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#E9E5E8").s().p("Ao8GrIAAtVII+AAIAAEYII7AAIAAgJIAAJGg");
	this.shape_7.setTransform(321.3761,357.2617,0.9725,0.9725);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Монтажный_кадр_1_walls, null, null);


(lib.Монтажный_кадр_1_texts = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// texts
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#9F979E").s().p("AgQAlQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAhDQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAGAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAIIAAABIABAAQADgGAEgCQAEgDAGgBQAFAAADACQAAAAABABQAAAAAAAAQAAAAAAABQAAAAAAABIgCAGQAAAAAAABQAAAAAAAAQgBAAAAAAQgBAAAAAAIgHgBQgHABgEAEQgFAGAAAIIAAAoQAAABAAAAQAAABgBAAQAAAAAAAAQgBABAAAAg");
	this.shape.setTransform(401.2063,231.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#9F979E").s().p("AgRAgQgHgFgDgJQgCgHAAgLQAAgKACgGQADgKAHgFQAHgFAKAAQAKAAAIAFQAHAFADAJQACAHAAAKQAAALgCAHQgDAJgHAFQgIAFgKAAQgJAAgIgFgAgLgYQgEAEgDAHIAAANIAAAPQACAGAFAEQAFAEAGAAQAHAAAFgEQAEgEACgGIABgPIgBgNQgBgHgFgEQgFgDgHAAQgGAAgFADg");
	this.shape_1.setTransform(394.25,231.325);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#9F979E").s().p("AgQAtQgHgFgDgIQgCgHAAgLQAAgMACgFQADgKAHgFQAGgFAKAAQAFAAAFADQAFACADADIAAABIABgBIAAggQAAgBAAAAQAAgBAAAAQAAAAABAAQAAgBAAAAIAHAAQAAAAABABQAAAAAAAAQAAAAABABQAAAAAAABIAABeQAAABAAAAQgBABAAAAQAAAAAAAAQgBABAAAAIgHAAQAAAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAgFIgBAAIAAAAQgDAEgFACQgFADgFAAQgJgBgHgFgAgIgLQgEACgCAGIgDAFIAAAMIAAAKIACAGQACAGAEADQAFADAFAAQAFAAAEgDQAEgDACgFIACgHIAAgKIAAgMIgCgFQgCgFgEgDQgEgDgFAAQgFAAgEADg");
	this.shape_2.setTransform(386.325,230);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#9F979E").s().p("AgCAyQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAhEQAAAAAAAAQAAgBAAAAQAAAAABAAQAAgBABAAIAFAAQABAAAAABQAAAAAAAAQABAAAAABQAAAAAAAAIAABEQAAAAAAABQAAAAgBAAQAAABAAAAQAAAAgBAAgAgFglQgCgCAAgCQAAgEACgCQACgCADAAQADAAACACQADACAAAEQAAACgDACQgCACgDABQgDgBgCgCg");
	this.shape_3.setTransform(380.875,229.95);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#9F979E").s().p("AgQAlQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAhDQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAGAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAIIAAABIABAAQADgGAEgCQAEgDAGgBQAFAAADACQAAAAABABQAAAAAAAAQAAAAAAABQAAAAAAABIgCAGQAAAAAAABQAAAAAAAAQgBAAAAAAQgBAAAAAAIgHgBQgHABgEAEQgFAGAAAIIAAAoQAAABAAAAQAAABgBAAQAAAAAAAAQgBABAAAAg");
	this.shape_4.setTransform(376.9563,231.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#9F979E").s().p("AgQAlQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAhDQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAGAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAIIAAABIABAAQADgGAEgCQAEgDAGgBQAFAAADACQAAAAABABQAAAAAAAAQAAAAAAABQAAAAAAABIgCAGQAAAAAAABQAAAAAAAAQgBAAAAAAQgBAAAAAAIgHgBQgHABgEAEQgFAGAAAIIAAAoQAAABAAAAQAAABgBAAQAAAAAAAAQgBABAAAAg");
	this.shape_5.setTransform(371.7063,231.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#9F979E").s().p("AgRAgQgHgFgDgJQgCgHAAgLQAAgKACgGQADgKAHgFQAHgFAKAAQALAAAHAFQAHAFADAJQACAHAAAKQAAALgCAHQgDAJgIAFQgGAFgLAAQgJAAgIgFgAgLgYQgFAEgCAHIgBANIABAPQACAGAFAEQAFAEAGAAQAHAAAFgEQAEgEACgGIABgPIgBgNQgBgHgFgEQgFgDgHAAQgGAAgFADg");
	this.shape_6.setTransform(364.75,231.325);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#9F979E").s().p("AgRAvQgHgEgEgHQgEgHgBgKIAAgmQABgJAEgHQAEgIAHgDQAIgEAJAAQAKAAAHADQAIAEAEAHQAEAHABAJQAAABgBAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgHAAIgBAAIAAgBQgBgKgGgGQgHgHgKAAQgKAAgGAHQgHAGABAKIAAAnQgBAKAHAGQAGAGAKAAQAKAAAHgGQAGgGABgKQAAgBAAAAQAAAAAAAAQAAgBAAAAQABAAAAAAIAHAAQAAAAAAAAQABAAAAABQAAAAAAAAQABAAAAAAIAAABQgBAJgEAHQgEAHgIAEQgHAEgKAAQgJAAgIgEg");
	this.shape_7.setTransform(356.55,229.975);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#9F979E").s().p("AgLAkIgJgCQgLgDgHgJQgHgJAAgNQAAgOAIgJQAIgIAOgDIARgBQABAAAAAAQAAABAAAAQABAAAAAAQAAABAAAAIAAA4IABABQAJAAAEgCQAIgBAFgHQAEgGAAgIQAAgIgDgGQgEgGgGgDIgBgBIAAgCIADgFQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAAAABQAJAEAGAJQAFAIAAALQAAAMgGAIQgFAJgLADQgJAEgPAAIgLAAgAgRgVQgHACgFAFQgFAGAAAIQAAAJAFAGQAEAFAHACIAMACIACgBIAAgtIgCAAIgLABg");
	this.shape_8.setTransform(40.2,170.225);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#9F979E").s().p("AgVAiQgLgEgGgJQgHgJAAgMQAAgNAHgJQAGgJAKgDIAEgBIABAAQABAAAAAAQAAAAABAAQAAABAAAAQAAABAAAAIABAIIAAAAQAAAAAAABQAAAAAAABQgBAAAAAAQAAAAgBAAIgCAAQgHACgEAGQgFAHAAAIQAAAIAFAGQAEAGAIABQAHACAKAAQAMAAAGgCQAHgBAGgGQAEgGAAgIQAAgIgEgHQgFgGgHgBIgBgBIAAAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIABgIQABAAAAgBQAAAAAAAAQABgBAAAAQABAAAAAAIADABQAKADAHAJQAGAJAAANQAAAMgGAJQgIAJgKAEQgIACgOAAQgMAAgJgCg");
	this.shape_9.setTransform(40.2,179.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#9F979E").s().p("AAAAZQgHgJAAgRIAAgTIgBgBIgHAAQgIAAgGAEQgFAGAAAKQAAAHADAGQADAFAGABQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABIgBAJQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBAAQgJgCgGgJQgGgKAAgMQAAgQAIgJQAIgIANAAIA6AAQABAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAIQAAABAAAAQAAABAAAAQAAAAgBAAQAAABgBAAIgGAAIgBAAIAAABQAFAEADAHQADAIAAAHQAAAMgGAIQgHAJgNAAQgNAAgHgKgAABgUIAAASQABAKAFAHQAEAIAIAAQAIgBAEgFQAEgGAAgIQAAgJgFgIQgFgHgJAAIgOAAIgBABg");
	this.shape_10.setTransform(40.2,188.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#9F979E").s().p("Ag6AGQgBAAAAAAQgBAAAAAAQAAgBAAAAQgBgBAAAAIAAgHQAAgBABAAQAAgBAAAAQAAAAABAAQAAAAABAAIB1AAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIAAAHQAAAAAAABQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_11.setTransform(38.5,195.125);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#9F979E").s().p("Ag6ApQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBIAAgtQAAgQAKgJQAKgJAPAAQAPAAAKAJQAIAKAAAPIAAAiIABAAIAzAAQABABAAAAQABAAAAAAQAAAAABABQAAAAAAABIAAAIQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAgAgrgWQgHAHAAAKIAAAhIABAAIAuAAIAAAAIAAghQAAgKgGgHQgGgGgLAAQgLAAgGAGg");
	this.shape_12.setTransform(38.475,201.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#9F979E").s().p("AgLAkIgJgCQgLgDgHgJQgHgJAAgNQAAgOAIgJQAIgIAOgDIARgBQABAAAAAAQAAAAAAABQABAAAAAAQAAABAAAAIAAA4IABABQAJAAAEgCQAIgBAFgHQAEgGAAgIQAAgIgDgGQgEgGgGgDIgBgBIAAgCIADgFQAAgBAAAAQABAAAAAAQAAgBABAAQAAABAAAAQAJAEAGAJQAFAIAAALQAAAMgGAIQgFAJgLADQgJAEgPAAIgLAAgAgRgVQgHACgFAFQgFAGAAAIQAAAJAFAGQAEAFAHACIAMACIACgBIAAgtIgCAAIgLABg");
	this.shape_13.setTransform(40.2,215.725);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#9F979E").s().p("AgoAiQgBAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAgIQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAABAAIAGAAIABAAIAAgBQgLgHAAgPQAAgOAIgIQAJgJANAAIA4AAQABAAABAAQAAABAAAAQABAAAAAAQAAABAAAAIAAAIQAAABAAAAQAAABgBAAQAAAAAAABQgBAAgBAAIg2AAQgJAAgGAFQgGAGAAAJQgBAJAGAFQAFAGAIABIA5AAQABAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAAAIQAAABAAAAQAAABgBAAQAAAAAAABQgBAAgBAAg");
	this.shape_14.setTransform(40.15,225.125);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#9F979E").s().p("Ag6AHQgDgDAAgEQAAgDADgDQACgDAEABQAEgBADADQACADAAADQAAAEgCADQgDADgEAAQgEAAgCgDgAgYAGQgBAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAgBIAAgGQAAgBABAAQAAgBAAAAQAAAAABAAQAAgBABAAIBTAAQABAAAAABQABAAAAAAQAAAAAAABQAAAAAAABIAAAGQAAABAAABQAAAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_15.setTransform(38.5,232.05);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#9F979E").s().p("Ag6AGQgBAAAAAAQgBAAAAAAQAAgBAAAAQgBgBAAAAIAAgHQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAABAAIB1AAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAHQAAAAAAABQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_16.setTransform(38.5,236.225);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#9F979E").s().p("AgLAkIgJgCQgLgDgHgJQgHgJAAgNQAAgOAIgJQAIgIAOgDIARgBQABAAAAAAQAAAAAAABQABAAAAAAQAAABAAAAIAAA4IABABQAJAAAEgCQAIgBAFgHQAEgGAAgIQAAgIgDgGQgEgGgGgDIgBgBIAAgCIADgFQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAAAABQAJAEAGAJQAFAIAAALQAAAMgGAIQgFAJgLADQgJAEgPAAIgLAAgAgRgVQgHACgFAFQgFAGAAAIQAAAJAFAGQAEAFAHACIAMACIACgBIAAgtIgCAAIgLABg");
	this.shape_17.setTransform(40.2,242.925);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#9F979E").s().p("AgoAYQgBAAgBgBQAAAAAAAAQgBAAAAgBQAAAAAAgBIAAgIQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAABAAIAJAAIABAAIgBgBQgGgDgDgGQgEgFAAgHQAAgGACgEQAAAAABgBQAAAAAAAAQABgBAAAAQABAAAAABIAIACQABAAAAAAQAAAAAAABQAAAAAAAAQAAABAAABQgBADAAAFQABAJAGAFQAHAGAKAAIAxAAQABAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAAAIQAAABAAAAQAAABgBAAQAAAAAAAAQgBABgBAAg");
	this.shape_18.setTransform(40.15,250.295);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#9F979E").s().p("AgdAYQgBAAgBAAQAAgBAAAAQgBAAAAAAQAAgBAAAAIAAgKIgBgBIgUAAQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAgHQAAgBAAAAQAAAAABAAQAAAAAAAAQABAAAAAAIAUAAIABgBIAAgTQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAABAAIAFAAQABAAAAAAQABABAAAAQAAAAAAABQABAAAAABIAAATIAAABIAzAAQAIAAAEgEQADgEAAgIIAAgEQAAAAAAgBQAAAAABgBQAAAAAAAAQAAAAABAAIAGAAQABAAAAAAQABAAAAAAQAAABABAAQAAABAAAAIAAAGQAAANgFAFQgFAHgNAAIg2AAIAAABIAAAKQAAAAgBABQAAAAAAAAQAAAAgBABQAAAAgBAAg");
	this.shape_19.setTransform(39.05,257.375);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#9F979E").s().p("AgoAiQgBAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAgIQAAAAAAgBQAAAAABAAQAAAAAAgBQABAAABAAIAGAAIABAAIAAgBQgLgHAAgPQAAgOAIgIQAJgJANAAIA4AAQABAAABAAQAAABAAAAQABAAAAAAQAAABAAAAIAAAIQAAABAAAAQAAABgBAAQAAAAAAABQgBAAgBAAIg2AAQgJAAgGAFQgGAGAAAJQgBAJAGAFQAFAGAIABIA5AAQABAAABAAQAAABAAAAQABAAAAAAQAAABAAAAIAAAIQAAABAAAAQAAABgBAAQAAAAAAABQgBAAgBAAg");
	this.shape_20.setTransform(40.15,265.075);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#9F979E").s().p("AgLAkIgJgCQgLgDgHgJQgHgJAAgNQAAgOAIgJQAIgIAOgDIARgBQABAAAAAAQAAABAAAAQABAAAAAAQAAABAAAAIAAA4IABABQAJAAAEgCQAIgBAFgHQAEgGAAgIQAAgIgDgGQgEgGgGgDIgBgBIAAgCIADgFQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAAAABQAJAEAGAJQAFAIAAALQAAAMgGAIQgFAJgLADQgJAEgPAAIgLAAgAgRgVQgHACgFAFQgFAGAAAIQAAAJAFAGQAEAFAHACIAMACIACgBIAAgtIgCAAIgLABg");
	this.shape_21.setTransform(40.2,274.525);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#9F979E").s().p("AgXApQgMABgJgGQgIgFgFgKQgFgJAAgMQAAgLAFgKQAEgJAJgFQAIgFAMAAQAAAAABAAQAAAAAAAAQAAAAABABQAAAAAAABIABAIIgBABIAAABIgBAAQgNAAgIAIQgHAIAAAMQAAANAHAIQAIAIANAAIAwAAQAMAAAHgIQAIgIAAgNQAAgMgIgIQgHgIgMAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAgIQAAgBAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIABAAQALAAAJAFQAIAFAGAJQAEAKAAALQAAAMgFAJQgEAKgKAFQgIAGgMgBg");
	this.shape_22.setTransform(38.5,284.5);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#9F979E").s().p("AgKA/IgCAAIAAgCQAHgLADgQQADgQAAgRQAAgRgDgQQgDgRgHgLIAAgBQAAgBAAAAQAAAAAAAAQABAAAAAAQAAAAABAAIAGAAIACABQAGALAFARQAEAQAAASQAAASgEAQQgEAQgGALIgDABg");
	this.shape_23.setTransform(663.6375,443.375);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#9F979E").s().p("AgRAlQAAAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAgBIAAhFQAAAAABgBQAAAAAAAAQAAAAABgBQAAAAAAAAIAHAAQAAAAABAAQAAABAAAAQABAAAAAAQAAABAAAAIAAAIIAAABIABAAQADgGAEgDQAEgCAGAAQAFAAADABQABAAAAABQAAAAAAAAQABAAAAABQAAAAgBABIgBAGQAAABAAAAQgBAAAAAAQAAAAgBAAQAAAAgBAAQgCgBgFABQgHAAgEAFQgFAGAAAIIAAApQAAABAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAg");
	this.shape_24.setTransform(658.8563,444.475);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#9F979E").s().p("AgRAhQgIgFgDgKQgBgHAAgLQAAgKABgHQADgKAHgEQAJgGAJAAQAKAAAIAGQAHAEADAKQACAHABAKQgBALgCAHQgDAKgHAFQgIAFgKAAQgKAAgHgFgAgLgYQgFADgCAIIgBANIABAPQABAGAGAEQAFAEAGAAQAHAAAFgEQAFgEABgGQACgFAAgKQAAgKgCgDQgBgIgFgDQgFgEgHAAQgGAAgFAEg");
	this.shape_25.setTransform(651.75,444.5);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#9F979E").s().p("AgRAhQgIgFgDgKQgBgHAAgLQAAgKABgHQADgKAHgEQAJgGAJAAQALAAAHAGQAHAEADAKQADAHAAAKQAAALgDAHQgDAKgHAFQgHAFgLAAQgKAAgHgFgAgLgYQgFADgCAIIgBANIABAPQACAGAFAEQAFAEAGAAQAHAAAFgEQAFgEABgGQACgFAAgKQAAgKgCgDQgBgIgFgDQgFgEgHAAQgGAAgFAEg");
	this.shape_26.setTransform(643.75,444.5);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#9F979E").s().p("AgCAzQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAhhQAAgBAAAAQAAgBAAAAQABAAAAAAQAAAAABAAIAFAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAABIAABhQAAABAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAg");
	this.shape_27.setTransform(638.075,443.075);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#9F979E").s().p("AgGAzQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAg8IgBgBIgJAAQgBAAAAAAQgBgBAAAAQAAAAAAAAQAAgBAAAAIAAgGQAAAAAAgBQAAAAAAAAQAAAAABgBQAAAAABAAIAJAAIABAAIAAgEQAAgJACgFQACgFAEgDQAFgCAJAAIAEAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIAAAFQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgDAAQgIAAgDAEQgDADAAAJIAAADIABAAIAPAAQABAAAAAAQABABAAAAQAAAAAAAAQAAABAAAAIAAAGQAAAAAAABQAAAAAAAAQAAAAgBABQAAAAgBAAIgPAAIgBABIAAA8QAAABAAAAQgBABAAAAQAAAAAAAAQgBAAAAAAg");
	this.shape_28.setTransform(633.725,443.075);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#9F979E").s().p("AgRAvQgHgGgCgJQgCgGAAgMQAAgMABgFQADgKAHgFQAHgFAKAAQAFAAAFACQAFACADAEIABABIAAgjQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAABAAIAGAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAABiQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAgBAAIgGAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAgGIgBAAQgDAEgFADQgFACgFAAQgKAAgHgFgAgIgLQgFADgCAEIgCAHIgBALIABAKIACAHQABAGAFADQAEADAGAAQAFAAAEgDQAEgDACgFIACgHIABgLIgBgLIgCgGQgCgFgEgDQgEgDgFAAQgFAAgEADg");
	this.shape_29.setTransform(624.175,443.125);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#9F979E").s().p("AAUAlQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgtQAAgIgFgGQgFgEgIAAQgGgBgFAFQgFAEgBAHIAAAwQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgGAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAhFQAAgBAAAAQAAgBAAAAQAAAAABAAQAAAAABAAIAGAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIAAAFIABABIAAAAQAHgJAMAAQALAAAHAGQAHAIAAALIAAAvQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAg");
	this.shape_30.setTransform(616.475,444.45);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#9F979E").s().p("AgOAjQgGgDgEgFQgDgGAAgIIAAgwQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAABAAIAGAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAAAtQAAAJAFAFQAFAEAHAAQAIAAAFgEQAFgFAAgJIAAgtQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAABAAIAGAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAABGQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgGAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgGIgBgBIAAAAQgHAKgLgBQgHAAgGgCg");
	this.shape_31.setTransform(608.525,444.55);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#9F979E").s().p("AgRAhQgIgFgDgKQgCgHAAgLQAAgKACgHQADgKAHgEQAJgGAJAAQAKAAAIAGQAHAEAEAKQACAHAAAKQAAALgCAHQgEAKgHAFQgIAFgKAAQgKAAgHgFgAgLgYQgFADgCAIIgBANIABAPQACAGAEAEQAGAEAGAAQAHAAAFgEQAFgEABgGQACgFAAgKQAAgKgCgDQgBgIgFgDQgFgEgHAAQgGAAgFAEg");
	this.shape_32.setTransform(600.65,444.5);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#9F979E").s().p("AgRAlQAAAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAgBIAAhFQAAAAABgBQAAAAAAAAQAAAAABgBQAAAAAAAAIAHAAQAAAAABAAQAAABAAAAQABAAAAAAQAAABAAAAIAAAIIAAABIABAAQADgGAEgDQAEgCAGAAQAFAAADABQABAAAAABQAAAAAAAAQABAAAAABQAAAAgBABIgBAGQAAABAAAAQgBAAAAAAQAAAAgBAAQAAAAgBAAQgCgBgFABQgHAAgEAFQgFAGAAAIIAAApQAAABAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAg");
	this.shape_33.setTransform(594.4563,444.475);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#9F979E").s().p("AgRAwQgIgEgEgHQgEgHAAgKIAAgnQAAgKAEgHQAEgHAIgEQAIgEAJAAQAKAAAIAEQAIAEAEAHQAEAHAAAJIAAABQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAIgGAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgCQAAgKgHgGQgGgGgLAAQgKAAgGAGQgHAGAAALIAAAoQAAAKAHAGQAHAGAKAAQAKAAAHgGQAGgFAAgKIAAgNIgBgBIgVAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAgFQAAgBAAAAQAAAAABAAQAAAAAAAAQABAAAAAAIAeAAQABAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAABIAAASQAAAQgJAJQgJAIgQAAQgJAAgIgEg");
	this.shape_34.setTransform(586.975,443.075);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#9F979E").s().p("AAFA/IgDgBQgFgLgFgQQgEgQAAgSQAAgSAEgQQAFgRAGgLIACgBIAGAAIABAAIAAACQgGALgEARQgCAQAAARQAAARACAQQAEAQAGALIABABQAAABAAAAQAAAAAAAAQgBAAAAAAQAAAAgBAAg");
	this.shape_35.setTransform(579.9,443.375);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#9F979E").s().p("AgQAhQgHgEgDgJQgDgHAAgNIAAgKIACgGQACgJAIgHQAHgFAKAAQAMAAAIAGQAHAHACAMIABAOQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIguAAIgBABIABALQACAGAFAEQAFAEAHAAQAHAAAFgDQAEgCADgFIABgBIABAAIAFACQAAAAAAAAQABABAAAAQAAAAAAAAQAAABAAAAQgEAIgHAEQgHAEgKAAQgJAAgHgFgAgLgYQgFADgBAHIgCAJIABABIAlAAIAAgBIAAgIQgCgHgFgEQgFgEgHAAQgHAAgEAEg");
	this.shape_36.setTransform(674.175,428.95);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#9F979E").s().p("AgRAgQgHgFgDgJQgCgHAAgLQAAgKACgHQADgJAHgGQAIgFAJAAQALAAAIAFQAIAFACAJIABAEIAAAAQAAAAAAABQAAAAgBAAQAAABAAAAQAAAAgBAAIgHAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQgBgBAAAAIAAgBQgBgGgFgEQgFgEgIAAQgGAAgFAEQgFAEgBAGQgCAFAAAJQAAAJACAGQABAGAFAEQAFAEAGAAQAHAAAGgEQAFgEABgFIAAgBQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAABAAIAGABQAAABABAAQAAAAAAAAQAAAAABABQAAAAAAAAIgBADQgCAIgIAGQgIAFgLAAQgJAAgIgGg");
	this.shape_37.setTransform(666.575,428.95);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#9F979E").s().p("AAUAlQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAgsQAAgIgFgGQgFgEgIAAQgGAAgFAEQgFAEgBAHIAAAvQAAABAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgGAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAhFQAAAAAAAAQAAgBAAAAQAAAAABAAQAAgBABABIAGAAQABgBAAABQABAAAAAAQAAAAAAABQAAAAAAAAIAAAGIABABIAAAAQAHgKAMABQALgBAHAIQAHAGAAAMIAAAuQAAABAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAg");
	this.shape_38.setTransform(658.775,428.9);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#9F979E").s().p("AgVAhQgHgGAAgKQAAgLAIgGQAIgGANAAIARAAIABAAIAAgGQAAgIgEgDQgFgFgIAAQgGAAgFADQgEACgBAFQAAAAgBABQAAAAAAAAQAAAAgBAAQAAABAAAAIgHgBQgBgBAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAQABgIAIgFQAHgFALAAQANAAAHAGQAHAIAAAKIAAAwQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAIgGAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgFIgBgBIAAABQgEAEgGACQgGACgGAAQgKAAgHgFgAgMAFQgGAEAAAHQAAAGAFAEQAEADAHAAQAIAAAGgEQAHgEAAgIIAAgLIgBAAIgPAAQgJAAgGADg");
	this.shape_39.setTransform(650.875,428.95);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#9F979E").s().p("AgRAlQAAAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBIAAhFQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAAAAAIAHAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAAAIIAAABIABAAQADgGAEgDQAEgCAGAAQAFAAADABQABAAAAABQAAAAAAAAQABAAAAABQAAAAgBABIgBAGQAAABAAAAQgBAAAAAAQAAAAgBAAQAAAAgBAAQgCgBgFABQgHAAgEAFQgFAGAAAIIAAApQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAg");
	this.shape_40.setTransform(645.1063,428.925);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#9F979E").s().p("AAMAuQgKAAgFgDQgFgFAAgKIAAgtIgBgBIgIAAQgBAAAAAAQAAAAAAAAQgBgBAAAAQAAAAAAAAIAAgGQAAAAAAAAQAAgBABAAQAAAAAAAAQAAgBABAAIAIAAIABAAIAAgRQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAABAAIAGAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAAARIABAAIAQAAQAAAAABABQAAAAAAAAQAAAAABABQAAAAAAAAIAAAGQAAAAAAAAQgBAAAAABQAAAAAAAAQgBAAAAAAIgQAAIgBABIAAAqQAAAGADAEQADACAHAAIADAAQABAAAAABQABAAAAAAQAAAAAAAAQAAABAAAAIAAAFQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_41.setTransform(639.225,428);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#9F979E").s().p("AAUAlQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAgsQAAgIgFgGQgFgEgIAAQgGAAgFAEQgFAEgBAHIAAAvQAAABAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgGAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAhFQAAAAAAAAQAAgBAAAAQAAAAABAAQAAgBABABIAGAAQABgBAAABQABAAAAAAQAAAAAAABQAAAAAAAAIAAAGIABABIAAAAQAHgKAMABQALgBAHAIQAHAGAAAMIAAAuQAAABAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAg");
	this.shape_42.setTransform(632.825,428.9);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#9F979E").s().p("AgQAhQgHgEgDgJQgDgHAAgNIAAgKIACgGQACgJAIgHQAHgFAKAAQAMAAAIAGQAHAHACAMIABAOQAAAAAAAAQgBABAAAAQAAAAAAAAQgBAAAAAAIguAAIgBABIABALQACAGAFAEQAFAEAHAAQAHAAAFgDQAEgCADgFIABgBIABAAIAFACQAAAAAAAAQABABAAAAQAAAAAAAAQAAABAAAAQgEAIgHAEQgHAEgKAAQgJAAgHgFgAgLgYQgFADgBAHIgCAJIABABIAlAAIAAgBIAAgIQgCgHgFgEQgFgEgHAAQgHAAgEAEg");
	this.shape_43.setTransform(624.975,428.95);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#9F979E").s().p("AAUAzQAAAAgBAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIgSgqIAAgBIgBAAIgPARIgBABIAAAYQAAABAAAAQAAAAgBABQAAAAAAAAQAAAAgBAAIgGAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBIAAhhQAAgBABAAQAAgBAAAAQAAAAABAAQAAAAABAAIAGAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAABIAAA6IABABIAdggIADgBIAHAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIgBACIgSATIAAABIAXAwIAAABQAAAAgBAAQAAABAAAAQAAAAAAAAQgBAAAAAAg");
	this.shape_44.setTransform(614.8,427.525);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#9F979E").s().p("AgRAlQAAAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBIAAhFQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAAAAAIAHAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAAAIIAAABIABAAQADgGAEgDQAEgCAGAAQAFAAADABQABAAAAABQAAAAAAAAQABAAAAABQAAAAgBABIgBAGQAAABAAAAQgBAAAAAAQAAAAgBAAQAAAAgBAAQgCgBgFABQgHAAgEAFQgFAGAAAIIAAApQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAg");
	this.shape_45.setTransform(608.6063,428.925);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#9F979E").s().p("AgVAhQgHgGAAgKQAAgLAIgGQAIgGANAAIARAAIABAAIAAgGQAAgIgEgDQgFgFgIAAQgGAAgFADQgEACgBAFQAAAAgBABQAAAAAAAAQAAAAgBAAQAAABAAAAIgHgBQgBgBAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAQABgIAIgFQAHgFALAAQANAAAHAGQAHAIAAAKIAAAwQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAIgGAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgFIgBgBIAAABQgEAEgGACQgGACgGAAQgKAAgHgFgAgMAFQgGAEAAAHQAAAGAFAEQAEADAHAAQAIAAAGgEQAHgEAAgIIAAgLIgBAAIgPAAQgJAAgGADg");
	this.shape_46.setTransform(601.625,428.95);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#9F979E").s().p("AgaA0QgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAhiQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAABAAIAGAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAAAGIABAAIAAAAQADgEAFgDQAFgCAFAAQAKAAAHAFQAHAGACAJQACAGAAAMQAAAMgBAFQgDAKgHAFQgHAFgKAAQgFAAgFgCQgFgCgDgEIAAgBIgBABIAAAiQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAgBAAgAgJgnQgEADgCAFIgCAHIAAALIAAALIACAGQACAFAEADQAEADAFAAQAFAAAFgDQAEgDACgEIACgHIABgLIgBgKIgCgHQgBgGgFgDQgEgDgGAAQgFAAgEADg");
	this.shape_47.setTransform(594.225,430.325);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#9F979E").s().p("AgRAlQAAAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBIAAhFQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAAAAAIAHAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAAAIIAAABIABAAQADgGAEgDQAEgCAGAAQAFAAADABQABAAAAABQAAAAAAAAQABAAAAABQAAAAgBABIgBAGQAAABAAAAQgBAAAAAAQAAAAgBAAQAAAAgBAAQgCgBgFABQgHAAgEAFQgFAGAAAIIAAApQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAg");
	this.shape_48.setTransform(584.9063,428.925);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#9F979E").s().p("AgVAhQgHgGAAgKQAAgLAIgGQAIgGANAAIARAAIABAAIAAgGQAAgIgEgDQgFgFgIAAQgGAAgFADQgEACgBAFQAAAAgBABQAAAAAAAAQAAAAgBAAQAAABAAAAIgHgBQgBgBAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAQABgIAIgFQAHgFALAAQANAAAHAGQAHAIAAAKIAAAwQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAIgGAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgFIgBgBIAAABQgEAEgGACQgGACgGAAQgKAAgHgFgAgMAFQgGAEAAAHQAAAGAFAEQAEADAHAAQAIAAAGgEQAHgEAAgIIAAgLIgBAAIgPAAQgJAAgGADg");
	this.shape_49.setTransform(577.875,428.95);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#9F979E").s().p("AgRAwQgIgEgEgHQgEgIAAgJIAAgnQAAgKAEgHQAEgHAIgEQAIgFAJAAQAKAAAIAFQAIADAEAIQAEAHAAAJQAAAAAAABQAAAAAAAAQAAAAgBAAQAAABAAAAIgHAAIgBAAIgBAAIAAgBQAAgLgHgGQgGgGgLgBQgKABgGAGQgHAGAAALIAAAnQAAAKAHAHQAGAGAKAAQALAAAGgGQAHgHAAgKQAAAAAAAAQAAgBABAAQAAAAAAAAQAAgBABAAIAHABIABAAIAAABQAAAKgEAHQgEAHgIAEQgIAFgKAAQgJAAgIgFg");
	this.shape_50.setTransform(569.925,427.55);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Монтажный_кадр_1_texts, null, null);


(lib.Монтажный_кадр_1_stair = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// stair
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D0CBCF").s().p("EghUAMqIAA5TMBCpAAAIAADqInrAAIAALRIrZAAIAArRMgjpAAAIAAVpg");
	this.shape.setTransform(398.8451,297.7489,0.9725,0.9725);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Монтажный_кадр_1_stair, null, null);


(lib.Монтажный_кадр_1_N = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// N
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgTAuIgBgBIgOhOIAAgCIABAAIADgBIACABIA2A7IABABIAAgBIgNhDIABgBIAAAAIAEgBIABAAIABABIAOBPIAAABIgBAAIgDABIgCgBIg2g7IgBgBIAAABIANBDIAAABIgBABIgEAAIgBAAg");
	this.shape.setTransform(703.749,408.9871,1.1679,1.1679);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#333333").ss(1,0,0,4).p("AAMBFIgXiJ");
	this.shape_1.setTransform(707.4094,428.2433,1.0838,1.0838);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#333333").ss(1,0,0,4).p("AgYiJQA5gKAvAhQAwAiAKA5QAKA4ghAvQghAwg5AKQg5AKgvghQgwghgKg6QgKg4AhgvQAhgwA5gKg");
	this.shape_2.setTransform(708.2622,435.4406,1.0834,1.0834);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Монтажный_кадр_1_N, null, null);


(lib.Монтажный_кадр_1_bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// bg
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E3DDE2").s().p("A4/O+IAA97MAx/AAAIAAd7g");
	this.shape.setTransform(400,239.4375,2.5,2.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Монтажный_кадр_1_bg, null, null);


(lib.Group = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1_obj_
	this.Слой_1 = new lib.Group_Слой_1();
	this.Слой_1.name = "Слой_1";
	this.Слой_1.parent = this;
	this.Слой_1.setTransform(37.3,5.8,1,1,0,0,0,37.3,5.8);
	this.Слой_1.depth = 0;
	this.Слой_1.isAttachedToCamera = 0
	this.Слой_1.isAttachedToMask = 0
	this.Слой_1.layerDepth = 0
	this.Слой_1.layerIndex = 0
	this.Слой_1.maskLayerName = 0

	this.timeline.addTween(cjs.Tween.get(this.Слой_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.Group, new cjs.Rectangle(0,0,74.5,11.6), null);


(lib.viewvideo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFEFB").s().p("AgEBkIAAhfIhfAAIAAgJIBfAAIAAhfIAJAAIAABfIBfAAIAAAJIhfAAIAABfg");
	this.shape.setTransform(37.6,16.5);

	this.instance = new lib.Group();
	this.instance.parent = this;
	this.instance.setTransform(37.3,46.45,1,1,0,0,0,37.3,5.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("Ah0B1QgwgwAAhFQAAhEAwgvQAwgxBEAAQBFAAAvAxQAxAwAABDQAABFgxAwQgvAwhFAAQhEAAgwgwg");
	this.shape_1.setTransform(37.6,16.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.instance},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,74.5,52.3);


(lib.btn8video = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgTBDQgIgEgFgJQgFgJAAgOQAAgLAEgJQAFgKAKgEQAAAAAAgBQAAAAAAAAQAAAAAAAAQAAgBAAAAQgHgDgGgHQgGgJAAgLQAAgLAFgIQAFgIAJgEQAIgFAKAAQAMAAAJAFQAIAFAFAIQAEAIAAAKQAAALgGAJQgFAHgHAEQAAAAgBAAQAAAAAAAAQAAAAAAABQABAAAAAAQAKAEAFALQADAIAAALQAAAPgFAKQgFAHgIAFQgJAEgLAAQgKAAgJgFgAgYAPQgCAGAAAKQAAAMAEAIQAHAMAPAAQAQAAAHgMQAFgIAAgMQAAgJgDgGQgCgIgHgEQgGgEgKAAQgRAAgHAPgAgNg6QgHAEgDAGQgEAGAAAIQAAAIAFAHQAEAFAGADQAFADAHAAIAAAAQAIAAAGgDQAGgDAEgFQAEgHAAgIQAAgIgDgGQgEgGgGgEQgGgDgJAAQgHAAgGADg");
	this.shape.setTransform(66.425,37.325);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgdA9QgLgKAAgSIAAhBQAAgRALgLQALgLASAAQASAAAMALQALALAAARIAABBQAAASgLAKQgMALgSAAQgSAAgLgLgAgVg2QgIAJAAANIAABBQAAANAIAJQAIAHANAAQAOAAAIgHQAIgJAAgNIAAhBQAAgNgIgJQgIgHgOAAQgNAAgIAHg");
	this.shape_1.setTransform(55.725,37.35);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgWBBQgKgIgEgLQgBgIAAgLIAAg+QAAgQAKgKQAKgKARABQAPAAALAJQAKAJgBAPIAAACIgBACIgBAAIgGAAIgBAAIgBgBIAAgCQAAgLgIgIQgHgGgKAAQgLAAgIAHQgHAHgBANIAAAgIABAAQAFgIAHgDQAHgCAIAAQAaAAAIAVQADAIAAAOQAAAMgCAHQgEALgJAHQgJAHgOgBQgMAAgKgGgAgQgBQgHAFgCAIQgBAGgBAKQABAKABAEQACAJAHAGQAGAFAKAAQAJAAAHgFQAHgFADgKQACgFgBgJQAAgLgBgFQgDgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_2.setTransform(45.15,37.35);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).to({state:[]},1).wait(1));

	// Слой_2
	this.instance = new lib.viewvideo("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(83.1,96.5,0.6711,0.6708,0,0,0,37.2,26.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#FFFFFF").ss(2,0,0,4).p("AADLWIMaAAIAAmGIABAAIAAwlI47AAIAAQlIMgAAg");
	this.shape_3.setTransform(55.5288,50.5098,0.6956,0.6956);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AADLWIAAmGIsgAAIAAwlIY7AAIAAQlIgBAAIAAGGg");
	this.shape_4.setTransform(55.5288,50.5098,0.6956,0.6956);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#9F979E").s().p("AkLDOIAAmbIIXAAIAAGbg");
	this.shape_5.setTransform(83.425,97.65);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.instance,p:{y:96.5}}]},1).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.instance,p:{y:99.5}}]},1).to({state:[{t:this.shape_5}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,113.1,119.3);


(lib.btn8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgTBDQgIgEgFgJQgFgJAAgOQAAgLAEgJQAFgKAKgEQAAAAAAgBQAAAAAAAAQAAAAAAAAQAAgBAAAAQgHgDgGgHQgGgJAAgLQAAgLAFgIQAFgIAJgEQAIgFAKAAQAMAAAJAFQAIAFAFAIQAEAIAAAKQAAALgGAJQgFAHgHAEQAAAAgBAAQAAAAAAAAQAAAAAAABQABAAAAAAQAKAEAFALQADAIAAALQAAAPgFAKQgFAHgIAFQgJAEgLAAQgKAAgJgFgAgYAPQgCAGAAAKQAAAMAEAIQAHAMAPAAQAQAAAHgMQAFgIAAgMQAAgJgDgGQgCgIgHgEQgGgEgKAAQgRAAgHAPgAgNg6QgHAEgDAGQgEAGAAAIQAAAIAFAHQAEAFAGADQAFADAHAAIAAAAQAIAAAGgDQAGgDAEgFQAEgHAAgIQAAgIgDgGQgEgGgGgEQgGgDgJAAQgHAAgGADg");
	this.shape.setTransform(66.425,37.325);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgdA9QgLgKAAgSIAAhBQAAgRALgLQALgLASAAQASAAAMALQALALAAARIAABBQAAASgLAKQgMALgSAAQgSAAgLgLgAgVg2QgIAJAAANIAABBQAAANAIAJQAIAHANAAQAOAAAIgHQAIgJAAgNIAAhBQAAgNgIgJQgIgHgOAAQgNAAgIAHg");
	this.shape_1.setTransform(55.725,37.35);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgWBBQgKgIgEgLQgBgIAAgLIAAg+QAAgQAKgKQAKgKARABQAPAAALAJQAKAJgBAPIAAACIgBACIgBAAIgGAAIgBAAIgBgBIAAgCQAAgLgIgIQgHgGgKAAQgLAAgIAHQgHAHgBANIAAAgIABAAQAFgIAHgDQAHgCAIAAQAaAAAIAVQADAIAAAOQAAAMgCAHQgEALgJAHQgJAHgOgBQgMAAgKgGgAgQgBQgHAFgCAIQgBAGgBAKQABAKABAEQACAJAHAGQAGAFAKAAQAJAAAHgFQAHgFADgKQACgFgBgJQAAgLgBgFQgDgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_2.setTransform(45.15,37.35);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgTBDQgIgEgFgJQgFgJAAgOQAAgLAEgJQAFgKAKgEQAAAAAAgBQAAAAAAAAQAAAAAAAAQAAgBAAAAQgHgDgGgHQgGgJAAgLQAAgLAFgIQAFgIAJgEQAIgFAKAAQAMAAAJAFQAIAFAFAIQAEAIAAAKQAAALgGAJQgFAHgHAEQAAAAgBAAQAAAAAAAAQAAAAAAABQABAAAAAAQAKAEAFALQADAIAAALQAAAPgFAKQgFAHgIAFQgJAEgLAAQgKAAgJgFgAgYAPQgCAGAAAKQAAAMAEAIQAHAMAPAAQAQAAAHgMQAFgIAAgMQAAgJgDgGQgCgIgHgEQgGgEgKAAQgRAAgHAPgAgNg6QgHAEgDAGQgEAGAAAIQAAAIAFAHQAEAFAGADQAFADAHAAIAAAAQAIAAAGgDQAGgDAEgFQAEgHAAgIQAAgIgDgGQgEgGgGgEQgGgDgJAAQgHAAgGADg");
	this.shape_3.setTransform(66.425,37.325);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgdA9QgLgKAAgSIAAhBQAAgRALgLQALgLASAAQASAAAMALQALALAAARIAABBQAAASgLAKQgMALgSAAQgSAAgLgLgAgVg2QgIAJAAANIAABBQAAANAIAJQAIAHANAAQAOAAAIgHQAIgJAAgNIAAhBQAAgNgIgJQgIgHgOAAQgNAAgIAHg");
	this.shape_4.setTransform(55.725,37.35);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgWBBQgKgIgEgLQgBgIAAgLIAAg+QAAgQAKgKQAKgKARABQAPAAALAJQAKAJgBAPIAAACIgBACIgBAAIgGAAIgBAAIgBgBIAAgCQAAgLgIgIQgHgGgKAAQgLAAgIAHQgHAHgBANIAAAgIABAAQAFgIAHgDQAHgCAIAAQAaAAAIAVQADAIAAAOQAAAMgCAHQgEALgJAHQgJAHgOgBQgMAAgKgGgAgQgBQgHAFgCAIQgBAGgBAKQABAKABAEQACAJAHAGQAGAFAKAAQAJAAAHgFQAHgFADgKQACgFgBgJQAAgLgBgFQgDgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_5.setTransform(45.15,37.35);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3}]},1).wait(1));

	// Слой_2
	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#FFFFFF").ss(2,0,0,4).p("AADLWIMaAAIAAmGIABAAIAAwlI47AAIAAQlIMgAAg");
	this.shape_6.setTransform(55.5288,50.5098,0.6956,0.6956);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#E3DDE2").s().p("AADLWIAAmGIsgAAIAAwlIY7AAIAAQlIgBAAIAAGGg");
	this.shape_7.setTransform(55.5288,50.5098,0.6956,0.6956);

	this.instance = new lib.viewvideo("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(83.1,96.5,0.6711,0.6708,0,0,0,37.2,26.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AADLWIAAmGIsgAAIAAwlIY7AAIAAQlIgBAAIAAGGg");
	this.shape_8.setTransform(55.5288,50.5098,0.6956,0.6956);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6}]}).to({state:[{t:this.shape_8},{t:this.shape_6},{t:this.instance}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,113.1,114.9);


(lib.btn7video = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgPBGQAAAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAuh9IAAgBIg6AAIgBAAIAAAJIgBABIgBABIgFAAIgBgBIgBgBIAAgQIABgCIABgBIBLAAIACABIAAACIAAAFIAAADIguB+QAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAg");
	this.shape.setTransform(66.175,37.35);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgdA9QgLgKAAgSIAAhBQAAgRALgLQALgLASAAQASAAAMALQALALAAARIAABBQAAASgLAKQgMALgSAAQgSAAgLgLgAgVg2QgIAJAAANIAABBQAAANAIAJQAIAHANAAQAOAAAIgHQAIgJAAgNIAAhBQAAgNgIgJQgIgHgOAAQgNAAgIAHg");
	this.shape_1.setTransform(55.725,37.35);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgWBBQgKgIgEgLQgBgIAAgLIAAg+QAAgQAKgKQAKgKARABQAPAAALAJQAKAJgBAPIAAACIgBACIgBAAIgGAAIgBAAIgBgBIAAgCQAAgLgIgIQgHgGgKAAQgLAAgIAHQgHAHgBANIAAAgIABAAQAFgIAHgDQAHgCAIAAQAaAAAIAVQADAIAAAOQAAAMgCAHQgEALgJAHQgJAHgOgBQgMAAgKgGgAgQgBQgHAFgCAIQgBAGgBAKQABAKABAEQACAJAHAGQAGAFAKAAQAJAAAHgFQAHgFADgKQACgFgBgJQAAgLgBgFQgDgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_2.setTransform(45.15,37.35);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).to({state:[]},1).wait(1));

	// Слой_2
	this.instance = new lib.viewvideo("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(79.15,96.6,0.6711,0.6708,0,0,0,37.2,26.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#FFFFFF").ss(2,0,0,4).p("A0TsXIAAQoIMeAAIAAGDIMcAAIAACDIPqAAIADpAIv3AAIAAvug");
	this.shape_3.setTransform(90.3885,55.0657,0.6956,0.6956);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AEnMYIAAiEIscAAIAAmDIseAAIAAwoIYwAAIAAPvIP3AAIgDJAg");
	this.shape_4.setTransform(90.387,55.0657,0.6956,0.6956);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#9F979E").s().p("AkRDFIAAmJIIjAAIAAGJg");
	this.shape_5.setTransform(83.45,97.35);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.instance,p:{y:96.6}}]},1).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.instance,p:{y:99.6}}]},1).to({state:[{t:this.shape_5}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,212,118.1);


(lib.btn7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgPBGQAAAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAuh9IAAgBIg6AAIgBAAIAAAJIgBABIgBABIgFAAIgBgBIgBgBIAAgQIABgCIABgBIBLAAIACABIAAACIAAAFIAAADIguB+QAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAg");
	this.shape.setTransform(66.175,37.35);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgdA9QgLgKAAgSIAAhBQAAgRALgLQALgLASAAQASAAAMALQALALAAARIAABBQAAASgLAKQgMALgSAAQgSAAgLgLgAgVg2QgIAJAAANIAABBQAAANAIAJQAIAHANAAQAOAAAIgHQAIgJAAgNIAAhBQAAgNgIgJQgIgHgOAAQgNAAgIAHg");
	this.shape_1.setTransform(55.725,37.35);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgWBBQgKgIgEgLQgBgIAAgLIAAg+QAAgQAKgKQAKgKARABQAPAAALAJQAKAJgBAPIAAACIgBACIgBAAIgGAAIgBAAIgBgBIAAgCQAAgLgIgIQgHgGgKAAQgLAAgIAHQgHAHgBANIAAAgIABAAQAFgIAHgDQAHgCAIAAQAaAAAIAVQADAIAAAOQAAAMgCAHQgEALgJAHQgJAHgOgBQgMAAgKgGgAgQgBQgHAFgCAIQgBAGgBAKQABAKABAEQACAJAHAGQAGAFAKAAQAJAAAHgFQAHgFADgKQACgFgBgJQAAgLgBgFQgDgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_2.setTransform(45.15,37.35);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgPBGQAAAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAuh9IAAgBIg6AAIgBAAIAAAJIgBABIgBABIgFAAIgBgBIgBgBIAAgQIABgCIABgBIBLAAIACABIAAACIAAAFIAAADIguB+QAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAg");
	this.shape_3.setTransform(66.175,37.35);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgdA9QgLgKAAgSIAAhBQAAgRALgLQALgLASAAQASAAAMALQALALAAARIAABBQAAASgLAKQgMALgSAAQgSAAgLgLgAgVg2QgIAJAAANIAABBQAAANAIAJQAIAHANAAQAOAAAIgHQAIgJAAgNIAAhBQAAgNgIgJQgIgHgOAAQgNAAgIAHg");
	this.shape_4.setTransform(55.725,37.35);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgWBBQgKgIgEgLQgBgIAAgLIAAg+QAAgQAKgKQAKgKARABQAPAAALAJQAKAJgBAPIAAACIgBACIgBAAIgGAAIgBAAIgBgBIAAgCQAAgLgIgIQgHgGgKAAQgLAAgIAHQgHAHgBANIAAAgIABAAQAFgIAHgDQAHgCAIAAQAaAAAIAVQADAIAAAOQAAAMgCAHQgEALgJAHQgJAHgOgBQgMAAgKgGgAgQgBQgHAFgCAIQgBAGgBAKQABAKABAEQACAJAHAGQAGAFAKAAQAJAAAHgFQAHgFADgKQACgFgBgJQAAgLgBgFQgDgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_5.setTransform(45.15,37.35);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3}]},1).wait(1));

	// Слой_2
	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#FFFFFF").ss(2,0,0,4).p("A0TsXIAAQoIMeAAIAAGDIMcAAIAACDIPqAAIADpAIv3AAIAAvug");
	this.shape_6.setTransform(90.3885,55.0657,0.6956,0.6956);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#E3DDE2").s().p("AEnMYIAAiEIscAAIAAmDIseAAIAAwoIYwAAIAAPvIP3AAIgDJAg");
	this.shape_7.setTransform(90.387,55.0657,0.6956,0.6956);

	this.instance = new lib.viewvideo("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(79.15,96.6,0.6711,0.6708,0,0,0,37.2,26.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AEnMYIAAiEIscAAIAAmDIseAAIAAwoIYwAAIAAPvIP3AAIgDJAg");
	this.shape_8.setTransform(90.387,55.0657,0.6956,0.6956);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6}]}).to({state:[{t:this.shape_8},{t:this.shape_6},{t:this.instance}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,212,115.1);


(lib.btn6video = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgWBBQgKgIgDgLQgCgIgBgLIAAg+QAAgQALgKQALgKAQABQAPAAALAJQAJAJABAPIAAACIgBACIgCAAIgGAAIgBAAIgCgBIAAgCQAAgLgGgIQgIgGgKAAQgLAAgIAHQgIAHABANIAAAgIABAAQAEgIAHgDQAHgCAIAAQAaAAAJAVQACAIAAAOQAAAMgCAHQgEALgJAHQgJAHgNgBQgOAAgJgGgAgQgBQgGAFgDAIQgBAGAAAKQAAAKABAEQACAJAHAGQAGAFAKAAQAJAAAIgFQAGgFADgKQABgFABgJQAAgLgCgFQgDgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape.setTransform(90.65,37.35);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgdA9QgLgKAAgSIAAhBQAAgRALgLQALgLASAAQASAAAMALQALALAAARIAABBQAAASgLAKQgMALgSAAQgSAAgLgLgAgVg2QgIAJAAANIAABBQAAANAIAJQAIAHANAAQAOAAAIgHQAIgJAAgNIAAhBQAAgNgIgJQgIgHgOAAQgNAAgIAHg");
	this.shape_1.setTransform(79.775,37.35);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgWBBQgKgIgEgLQgCgIAAgLIAAg+QAAgQALgKQALgKAQABQAPAAAKAJQAKAJAAAPIAAACIgBACIgBAAIgGAAIgCAAIgBgBIAAgCQABgLgIgIQgGgGgLAAQgMAAgHAHQgIAHAAANIAAAgIABAAQAFgIAHgDQAHgCAIAAQAaAAAIAVQAEAIAAAOQAAAMgDAHQgEALgJAHQgJAHgOgBQgNAAgJgGgAgQgBQgGAFgDAIQgCAGAAAKQAAAKACAEQACAJAHAGQAGAFAKAAQAKAAAGgFQAIgFACgKQABgFAAgJQAAgLgCgFQgCgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_2.setTransform(69.2,37.35);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).to({state:[]},1).wait(1));

	// Слой_2
	this.instance = new lib.viewvideo("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(81.4,97.4,0.6711,0.6708,0,0,0,37.2,26.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#FFFFFF").ss(2,0,0,4).p("AxRHfILvAAIAAD3INCAAIAAmGIJyAAIAAwlMgiiAAAg");
	this.shape_3.setTransform(76.903,50.5098,0.6956,0.6956);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AliLWIAAj3IrvAAIABy0MAiiAAAIAAQlIpyAAIAAGGg");
	this.shape_4.setTransform(76.9032,50.5098,0.6956,0.6956);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#9F979E").s().p("AkODLIAAmVIIdAAIAAGVg");
	this.shape_5.setTransform(81.925,94.175);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.instance,p:{y:97.4}}]},1).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.instance,p:{y:100.4}}]},1).to({state:[{t:this.shape_5}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,155.8,118.8);


(lib.btn6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgWBBQgKgIgDgLQgCgIgBgLIAAg+QAAgQALgKQALgKAQABQAPAAALAJQAJAJABAPIAAACIgBACIgCAAIgGAAIgBAAIgCgBIAAgCQAAgLgGgIQgIgGgKAAQgLAAgIAHQgIAHABANIAAAgIABAAQAEgIAHgDQAHgCAIAAQAaAAAJAVQACAIAAAOQAAAMgCAHQgEALgJAHQgJAHgNgBQgOAAgJgGgAgQgBQgGAFgDAIQgBAGAAAKQAAAKABAEQACAJAHAGQAGAFAKAAQAJAAAIgFQAGgFADgKQABgFABgJQAAgLgCgFQgDgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape.setTransform(90.65,37.35);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgdA9QgLgKAAgSIAAhBQAAgRALgLQALgLASAAQASAAAMALQALALAAARIAABBQAAASgLAKQgMALgSAAQgSAAgLgLgAgVg2QgIAJAAANIAABBQAAANAIAJQAIAHANAAQAOAAAIgHQAIgJAAgNIAAhBQAAgNgIgJQgIgHgOAAQgNAAgIAHg");
	this.shape_1.setTransform(79.775,37.35);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgWBBQgKgIgEgLQgCgIAAgLIAAg+QAAgQALgKQALgKAQABQAPAAAKAJQAKAJAAAPIAAACIgBACIgBAAIgGAAIgCAAIgBgBIAAgCQABgLgIgIQgGgGgLAAQgMAAgHAHQgIAHAAANIAAAgIABAAQAFgIAHgDQAHgCAIAAQAaAAAIAVQAEAIAAAOQAAAMgDAHQgEALgJAHQgJAHgOgBQgNAAgJgGgAgQgBQgGAFgDAIQgCAGAAAKQAAAKACAEQACAJAHAGQAGAFAKAAQAKAAAGgFQAIgFACgKQABgFAAgJQAAgLgCgFQgCgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_2.setTransform(69.2,37.35);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgWBBQgKgIgDgLQgCgIgBgLIAAg+QAAgQALgKQALgKAQABQAPAAALAJQAJAJABAPIAAACIgBACIgCAAIgGAAIgBAAIgCgBIAAgCQAAgLgGgIQgIgGgKAAQgLAAgIAHQgIAHABANIAAAgIABAAQAEgIAHgDQAHgCAIAAQAaAAAJAVQACAIAAAOQAAAMgCAHQgEALgJAHQgJAHgNgBQgOAAgJgGgAgQgBQgGAFgDAIQgBAGAAAKQAAAKABAEQACAJAHAGQAGAFAKAAQAJAAAIgFQAGgFADgKQABgFABgJQAAgLgCgFQgDgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_3.setTransform(90.65,37.35);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgdA9QgLgKAAgSIAAhBQAAgRALgLQALgLASAAQASAAAMALQALALAAARIAABBQAAASgLAKQgMALgSAAQgSAAgLgLgAgVg2QgIAJAAANIAABBQAAANAIAJQAIAHANAAQAOAAAIgHQAIgJAAgNIAAhBQAAgNgIgJQgIgHgOAAQgNAAgIAHg");
	this.shape_4.setTransform(79.775,37.35);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgWBBQgKgIgEgLQgCgIAAgLIAAg+QAAgQALgKQALgKAQABQAPAAAKAJQAKAJAAAPIAAACIgBACIgBAAIgGAAIgCAAIgBgBIAAgCQABgLgIgIQgGgGgLAAQgMAAgHAHQgIAHAAANIAAAgIABAAQAFgIAHgDQAHgCAIAAQAaAAAIAVQAEAIAAAOQAAAMgDAHQgEALgJAHQgJAHgOgBQgNAAgJgGgAgQgBQgGAFgDAIQgCAGAAAKQAAAKACAEQACAJAHAGQAGAFAKAAQAKAAAGgFQAIgFACgKQABgFAAgJQAAgLgCgFQgCgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_5.setTransform(69.2,37.35);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3}]},1).wait(1));

	// Слой_2
	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#FFFFFF").ss(2,0,0,4).p("AxRHfILvAAIAAD3INCAAIAAmGIJyAAIAAwlMgiiAAAg");
	this.shape_6.setTransform(76.903,50.5098,0.6956,0.6956);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#E3DDE2").s().p("AliLWIAAj3IrvAAIABy0MAiiAAAIAAQlIpyAAIAAGGg");
	this.shape_7.setTransform(76.9032,50.5098,0.6956,0.6956);

	this.instance = new lib.viewvideo("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(81.4,97.4,0.6711,0.6708,0,0,0,37.2,26.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AliLWIAAj3IrvAAIABy0MAiiAAAIAAQlIpyAAIAAGGg");
	this.shape_8.setTransform(76.9032,50.5098,0.6956,0.6956);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6}]}).to({state:[{t:this.shape_8},{t:this.shape_6},{t:this.instance}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,155.8,115.8);


(lib.btn5video = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgWBAQgKgIgDgMIgCgHIAAgBQAAAAAAgBQABAAAAAAQAAAAAAgBQABAAAAAAIAGAAQABAAAAAAQABABAAAAQAAAAABAAQAAABAAAAIAAABIABADQACAKAHAGQAHAFAJAAQALAAAHgGQAHgGACgKIABgMIgBgOQgCgKgHgFQgHgFgLAAQgJAAgHAEQgHADgCAHQAAABgBAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgHAAIgBAAIgBgCIAAhKIABgCIABgBIBBAAIACABIABACIAAAEIgBACIgCABIg4AAIAAAAIgBA2IABABIAAgBQAFgFAHgDQAIgDAHAAQAOAAAKAHQAKAHACAMQABAIAAAJQAAAKgBAHQgDANgKAHQgKAIgOAAQgNAAgJgHg");
	this.shape.setTransform(66.575,60.175);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgdA9QgLgKAAgSIAAhBQAAgRALgLQALgLASAAQASAAAMALQALALAAARIAABBQAAASgLAKQgMALgSAAQgSAAgLgLgAgVg2QgIAJAAANIAABCQAAANAIAHQAIAJANgBQAOABAIgJQAIgHAAgNIAAhCQAAgNgIgJQgIgHgOgBQgNABgIAHg");
	this.shape_1.setTransform(55.725,60.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgWBAQgKgGgEgNQgBgGAAgMIAAg+QAAgQAKgKQAKgKARAAQAPABALAIQAKAKgBAPIAAACIgBABIgBABIgGAAIgBgBIgBgBIAAgBQAAgLgIgIQgHgGgKAAQgLAAgIAHQgHAHgBAMIAAAhIABAAQAFgHAHgDQAHgDAIgBQAaAAAIAWQADAIAAANQAAANgCAGQgEAMgJAHQgJAGgOAAQgMABgKgIgAgQgBQgHAEgCAJQgBAGgBAKQABAKABAEQACAJAHAGQAGAFAKAAQAJAAAHgFQAHgFADgKQACgEgBgLQAAgKgBgFQgDgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_2.setTransform(45.15,60.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).to({state:[]},1).wait(1));

	// Слой_2
	this.instance = new lib.viewvideo("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(57.3,101.05,0.6711,0.6708,0,0,0,37.2,26.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#FFFFFF").ss(2,0,0,4).p("AMnnwIAAmFIsfAAIAAGFIsxAAIAAQdIBdAAIAAFJIX2AAIAAwdIgEAAIAAlJg");
	this.shape_3.setTransform(56.3416,61.623,0.6956,0.6956);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("ArMN2IAAlJIhdAAIAAwdIMxAAIAAmFIMfAAIAAGFIgBAAIAAFJIAEAAIAAQdg");
	this.shape_4.setTransform(56.3416,61.623,0.6956,0.6956);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#9F979E").s().p("AkRDFIAAmJIIjAAIAAGJg");
	this.shape_5.setTransform(58.2,100.975);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.instance,p:{y:101.05}}]},1).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.instance,p:{y:104.05}}]},1).to({state:[{t:this.shape_5}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,114.7,125.3);


(lib.btn5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgWBAQgKgIgDgMIgCgHIAAgBQAAAAAAgBQABAAAAAAQAAAAAAgBQABAAAAAAIAGAAQABAAAAAAQABABAAAAQAAAAABAAQAAABAAAAIAAABIABADQACAKAHAGQAHAFAJAAQALAAAHgGQAHgGACgKIABgMIgBgOQgCgKgHgFQgHgFgLAAQgJAAgHAEQgHADgCAHQAAABgBAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgHAAIgBAAIgBgCIAAhKIABgCIABgBIBBAAIACABIABACIAAAEIgBACIgCABIg4AAIAAAAIgBA2IABABIAAgBQAFgFAHgDQAIgDAHAAQAOAAAKAHQAKAHACAMQABAIAAAJQAAAKgBAHQgDANgKAHQgKAIgOAAQgNAAgJgHg");
	this.shape.setTransform(66.575,60.175);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgdA9QgLgKAAgSIAAhBQAAgRALgLQALgLASAAQASAAAMALQALALAAARIAABBQAAASgLAKQgMALgSAAQgSAAgLgLgAgVg2QgIAJAAANIAABCQAAANAIAHQAIAJANgBQAOABAIgJQAIgHAAgNIAAhCQAAgNgIgJQgIgHgOgBQgNABgIAHg");
	this.shape_1.setTransform(55.725,60.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgWBAQgKgGgEgNQgBgGAAgMIAAg+QAAgQAKgKQAKgKARAAQAPABALAIQAKAKgBAPIAAACIgBABIgBABIgGAAIgBgBIgBgBIAAgBQAAgLgIgIQgHgGgKAAQgLAAgIAHQgHAHgBAMIAAAhIABAAQAFgHAHgDQAHgDAIgBQAaAAAIAWQADAIAAANQAAANgCAGQgEAMgJAHQgJAGgOAAQgMABgKgIgAgQgBQgHAEgCAJQgBAGgBAKQABAKABAEQACAJAHAGQAGAFAKAAQAJAAAHgFQAHgFADgKQACgEgBgLQAAgKgBgFQgDgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_2.setTransform(45.15,60.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgWBAQgKgIgDgMIgCgHIAAgBQAAAAAAgBQABAAAAAAQAAAAAAgBQABAAAAAAIAGAAQABAAAAAAQABABAAAAQAAAAABAAQAAABAAAAIAAABIABADQACAKAHAGQAHAFAJAAQALAAAHgGQAHgGACgKIABgMIgBgOQgCgKgHgFQgHgFgLAAQgJAAgHAEQgHADgCAHQAAABgBAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgHAAIgBAAIgBgCIAAhKIABgCIABgBIBBAAIACABIABACIAAAEIgBACIgCABIg4AAIAAAAIgBA2IABABIAAgBQAFgFAHgDQAIgDAHAAQAOAAAKAHQAKAHACAMQABAIAAAJQAAAKgBAHQgDANgKAHQgKAIgOAAQgNAAgJgHg");
	this.shape_3.setTransform(66.575,60.175);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgdA9QgLgKAAgSIAAhBQAAgRALgLQALgLASAAQASAAAMALQALALAAARIAABBQAAASgLAKQgMALgSAAQgSAAgLgLgAgVg2QgIAJAAANIAABCQAAANAIAHQAIAJANgBQAOABAIgJQAIgHAAgNIAAhCQAAgNgIgJQgIgHgOgBQgNABgIAHg");
	this.shape_4.setTransform(55.725,60.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgWBAQgKgGgEgNQgBgGAAgMIAAg+QAAgQAKgKQAKgKARAAQAPABALAIQAKAKgBAPIAAACIgBABIgBABIgGAAIgBgBIgBgBIAAgBQAAgLgIgIQgHgGgKAAQgLAAgIAHQgHAHgBAMIAAAhIABAAQAFgHAHgDQAHgDAIgBQAaAAAIAWQADAIAAANQAAANgCAGQgEAMgJAHQgJAGgOAAQgMABgKgIgAgQgBQgHAEgCAJQgBAGgBAKQABAKABAEQACAJAHAGQAGAFAKAAQAJAAAHgFQAHgFADgKQACgEgBgLQAAgKgBgFQgDgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_5.setTransform(45.15,60.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3}]},1).wait(1));

	// Слой_2
	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#FFFFFF").ss(2,0,0,4).p("AMnnwIAAmFIsfAAIAAGFIsxAAIAAQdIBdAAIAAFJIX2AAIAAwdIgEAAIAAlJg");
	this.shape_6.setTransform(56.3416,61.623,0.6956,0.6956);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#E3DDE2").s().p("ArMN2IAAlJIhdAAIAAwdIMxAAIAAmFIMfAAIAAGFIgBAAIAAFJIAEAAIAAQdg");
	this.shape_7.setTransform(56.3416,61.623,0.6956,0.6956);

	this.instance = new lib.viewvideo("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(57.3,101.05,0.6711,0.6708,0,0,0,37.2,26.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("ArMN2IAAlJIhdAAIAAwdIMxAAIAAmFIMfAAIAAGFIgBAAIAAFJIAEAAIAAQdg");
	this.shape_8.setTransform(56.3416,61.623,0.6956,0.6956);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6}]}).to({state:[{t:this.shape_8},{t:this.shape_6},{t:this.instance}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,114.7,125.3);


(lib.btn4video = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAWBGIgBgBIAAgBIAAgkIgBgBIg7AAIgBgBIgBgCIAAgEIABgDIAphYQAAgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAIAGAAIABABIAAACIgoBWIAAABIAxAAIABAAIAAghIAAgCIABAAIAHAAIABAAIABACIAAAhIABAAIAIAAIABABIABACIAAAEIgBACIgBABIgIAAIgBABIAAAkIgBABIgBABg");
	this.shape.setTransform(66.6,60.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgdA9QgLgKAAgSIAAhBQAAgRALgLQALgLASAAQASAAAMALQALALAAARIAABBQAAASgLAKQgMALgSAAQgSAAgLgLgAgVg2QgIAJAAANIAABCQAAANAIAHQAIAJANgBQAOABAIgJQAIgHAAgNIAAhCQAAgNgIgJQgIgHgOgBQgNABgIAHg");
	this.shape_1.setTransform(55.725,60.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgWBAQgKgGgEgNQgBgGAAgMIAAg+QAAgQAKgKQAKgKARAAQAPABALAIQAKAKgBAPIAAACIgBABIgBABIgGAAIgBgBIgBgBIAAgBQAAgLgIgIQgHgGgKAAQgLAAgIAHQgHAHgBAMIAAAhIABAAQAFgHAHgDQAHgDAIgBQAaAAAIAWQADAIAAANQAAANgCAGQgEAMgJAHQgJAGgOAAQgMABgKgIgAgQgBQgHAEgCAJQgBAGgBAKQABAKABAEQACAJAHAGQAGAFAKAAQAJAAAHgFQAHgFADgKQACgEgBgLQAAgKgBgFQgDgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_2.setTransform(45.15,60.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).to({state:[]},1).wait(1));

	// Слой_2
	this.instance = new lib.viewvideo("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(85.85,95.25,0.6711,0.6708,0,0,0,37.2,26.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#FFFFFF").ss(2,0,0,4).p("AMelLIseAAIAAmFIsdAAIAAWhIY7AAg");
	this.shape_3.setTransform(55.4483,50.1811,0.6956,0.6956);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AscLRIAA2hIMcAAIAAGFIMeAAIAAQcg");
	this.shape_4.setTransform(55.4483,50.1811,0.6956,0.6956);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#9F979E").s().p("AkLDLIAAmVIIXAAIAAGVg");
	this.shape_5.setTransform(86.525,91.175);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.instance,p:{y:95.25}}]},1).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.instance,p:{y:98.25}}]},1).to({state:[{t:this.shape_5}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,114.3,116.7);


(lib.btn4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAWBGIgBgBIAAgBIAAgkIgBgBIg7AAIgBgBIgBgCIAAgEIABgDIAphYQAAgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAIAGAAIABABIAAACIgoBWIAAABIAxAAIABAAIAAghIAAgCIABAAIAHAAIABAAIABACIAAAhIABAAIAIAAIABABIABACIAAAEIgBACIgBABIgIAAIgBABIAAAkIgBABIgBABg");
	this.shape.setTransform(66.6,60.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgdA9QgLgKAAgSIAAhBQAAgRALgLQALgLASAAQASAAAMALQALALAAARIAABBQAAASgLAKQgMALgSAAQgSAAgLgLgAgVg2QgIAJAAANIAABCQAAANAIAHQAIAJANgBQAOABAIgJQAIgHAAgNIAAhCQAAgNgIgJQgIgHgOgBQgNABgIAHg");
	this.shape_1.setTransform(55.725,60.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgWBAQgKgGgEgNQgBgGAAgMIAAg+QAAgQAKgKQAKgKARAAQAPABALAIQAKAKgBAPIAAACIgBABIgBABIgGAAIgBgBIgBgBIAAgBQAAgLgIgIQgHgGgKAAQgLAAgIAHQgHAHgBAMIAAAhIABAAQAFgHAHgDQAHgDAIgBQAaAAAIAWQADAIAAANQAAANgCAGQgEAMgJAHQgJAGgOAAQgMABgKgIgAgQgBQgHAEgCAJQgBAGgBAKQABAKABAEQACAJAHAGQAGAFAKAAQAJAAAHgFQAHgFADgKQACgEgBgLQAAgKgBgFQgDgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_2.setTransform(45.15,60.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AAWBGIgBgBIAAgBIAAgkIgBgBIg7AAIgBgBIgBgCIAAgEIABgDIAphYQAAgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAIAGAAIABABIAAACIgoBWIAAABIAxAAIABAAIAAghIAAgCIABAAIAHAAIABAAIABACIAAAhIABAAIAIAAIABABIABACIAAAEIgBACIgBABIgIAAIgBABIAAAkIgBABIgBABg");
	this.shape_3.setTransform(66.6,60.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgdA9QgLgKAAgSIAAhBQAAgRALgLQALgLASAAQASAAAMALQALALAAARIAABBQAAASgLAKQgMALgSAAQgSAAgLgLgAgVg2QgIAJAAANIAABCQAAANAIAHQAIAJANgBQAOABAIgJQAIgHAAgNIAAhCQAAgNgIgJQgIgHgOgBQgNABgIAHg");
	this.shape_4.setTransform(55.725,60.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgWBAQgKgGgEgNQgBgGAAgMIAAg+QAAgQAKgKQAKgKARAAQAPABALAIQAKAKgBAPIAAACIgBABIgBABIgGAAIgBgBIgBgBIAAgBQAAgLgIgIQgHgGgKAAQgLAAgIAHQgHAHgBAMIAAAhIABAAQAFgHAHgDQAHgDAIgBQAaAAAIAWQADAIAAANQAAANgCAGQgEAMgJAHQgJAGgOAAQgMABgKgIgAgQgBQgHAEgCAJQgBAGgBAKQABAKABAEQACAJAHAGQAGAFAKAAQAJAAAHgFQAHgFADgKQACgEgBgLQAAgKgBgFQgDgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_5.setTransform(45.15,60.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3}]},1).wait(1));

	// Слой_2
	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#FFFFFF").ss(2,0,0,4).p("AMelLIseAAIAAmFIsdAAIAAWhIY7AAg");
	this.shape_6.setTransform(55.4483,50.1811,0.6956,0.6956);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#E3DDE2").s().p("AscLRIAA2hIMcAAIAAGFIMeAAIAAQcg");
	this.shape_7.setTransform(55.4483,50.1811,0.6956,0.6956);

	this.instance = new lib.viewvideo("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(85.85,95.25,0.6711,0.6708,0,0,0,37.2,26.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AscLRIAA2hIMcAAIAAGFIMeAAIAAQcg");
	this.shape_8.setTransform(55.4483,50.1811,0.6956,0.6956);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6}]}).to({state:[{t:this.shape_8},{t:this.shape_6},{t:this.instance}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,112.9,113.7);


(lib.btn3video = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgWBAQgKgIgDgMQgCgFAAgJQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAIAGAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIABAKQADAKAHAGQAHAFAJAAQAKAAAGgEQAGgEADgJQADgIAAgJQAAgNgEgIQgGgPgSAAIgFABIgBABQAAAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAgBIgDgDIAAgCIAAgBIAjgsIAAgBIg6AAIgCgBIgBgCIAAgEIABgCIACgBIBFAAIACABIABACIAAAFIgBADIgiAqIAAABIABAAQALABAIAFQAIAFADAIQAEAKAAAOQAAALgCAIQgEAMgJAHQgJAGgOAAQgNAAgJgHg");
	this.shape.setTransform(66.275,60.175);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgdA9QgLgKAAgSIAAhBQAAgRALgLQALgLASAAQASAAAMALQALALAAARIAABBQAAASgLAKQgMALgSAAQgSAAgLgLgAgVg2QgIAJAAANIAABCQAAANAIAHQAIAJANgBQAOABAIgJQAIgHAAgNIAAhCQAAgNgIgJQgIgHgOgBQgNABgIAHg");
	this.shape_1.setTransform(55.725,60.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgWBAQgKgGgEgNQgBgGAAgMIAAg+QAAgQAKgKQAKgKARAAQAPABALAIQAKAKgBAPIAAACIgBABIgBABIgGAAIgBgBIgBgBIAAgBQAAgLgIgIQgHgGgKAAQgLAAgIAHQgHAHgBAMIAAAhIABAAQAFgHAHgDQAHgDAIgBQAaAAAIAWQADAIAAANQAAANgCAGQgEAMgJAHQgJAGgOAAQgMABgKgIgAgQgBQgHAEgCAJQgBAGgBAKQABAKABAEQACAJAHAGQAGAFAKAAQAJAAAHgFQAHgFADgKQACgEgBgLQAAgKgBgFQgDgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_2.setTransform(45.15,60.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).to({state:[]},1).wait(1));

	// Слой_2
	this.instance = new lib.viewvideo("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(85.9,95.85,0.6711,0.6708,0,0,0,37.2,26.3);

	this.instance_1 = new lib.viewvideo("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(85.9,95.85,0.6711,0.6708,0,0,0,37.2,26.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#FFFFFF").ss(2,0,0,4).p("AMelLIseAAIAAmFIsdAAIAAWhIY7AAg");
	this.shape_3.setTransform(55.457,50.1811,0.6956,0.6956);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AscLRIAA2hIMcAAIAAGFIMeAAIAAQcg");
	this.shape_4.setTransform(55.457,50.1811,0.6956,0.6956);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#9F979E").s().p("AkXDbIAAm1IIvAAIAAG1g");
	this.shape_5.setTransform(84.65,92.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.instance_1},{t:this.instance,p:{y:95.85}}]},1).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.instance,p:{y:98.85}}]},1).to({state:[{t:this.shape_5}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,113.7,117.3);


(lib.btn3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgWBAQgKgIgDgMQgCgFAAgJQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAIAGAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIABAKQADAKAHAGQAHAFAJAAQAKAAAGgEQAGgEADgJQADgIAAgJQAAgNgEgIQgGgPgSAAIgFABIgBABQAAAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAgBIgDgDIAAgCIAAgBIAjgsIAAgBIg6AAIgCgBIgBgCIAAgEIABgCIACgBIBFAAIACABIABACIAAAFIgBADIgiAqIAAABIABAAQALABAIAFQAIAFADAIQAEAKAAAOQAAALgCAIQgEAMgJAHQgJAGgOAAQgNAAgJgHg");
	this.shape.setTransform(66.275,60.175);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgdA9QgLgKAAgSIAAhBQAAgRALgLQALgLASAAQASAAAMALQALALAAARIAABBQAAASgLAKQgMALgSAAQgSAAgLgLgAgVg2QgIAJAAANIAABCQAAANAIAHQAIAJANgBQAOABAIgJQAIgHAAgNIAAhCQAAgNgIgJQgIgHgOgBQgNABgIAHg");
	this.shape_1.setTransform(55.725,60.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgWBAQgKgGgEgNQgBgGAAgMIAAg+QAAgQAKgKQAKgKARAAQAPABALAIQAKAKgBAPIAAACIgBABIgBABIgGAAIgBgBIgBgBIAAgBQAAgLgIgIQgHgGgKAAQgLAAgIAHQgHAHgBAMIAAAhIABAAQAFgHAHgDQAHgDAIgBQAaAAAIAWQADAIAAANQAAANgCAGQgEAMgJAHQgJAGgOAAQgMABgKgIgAgQgBQgHAEgCAJQgBAGgBAKQABAKABAEQACAJAHAGQAGAFAKAAQAJAAAHgFQAHgFADgKQACgEgBgLQAAgKgBgFQgDgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_2.setTransform(45.15,60.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgWBAQgKgIgDgMQgCgFAAgJQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAIAGAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIABAKQADAKAHAGQAHAFAJAAQAKAAAGgEQAGgEADgJQADgIAAgJQAAgNgEgIQgGgPgSAAIgFABIgBABQAAAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAgBIgDgDIAAgCIAAgBIAjgsIAAgBIg6AAIgCgBIgBgCIAAgEIABgCIACgBIBFAAIACABIABACIAAAFIgBADIgiAqIAAABIABAAQALABAIAFQAIAFADAIQAEAKAAAOQAAALgCAIQgEAMgJAHQgJAGgOAAQgNAAgJgHg");
	this.shape_3.setTransform(66.275,60.175);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgdA9QgLgKAAgSIAAhBQAAgRALgLQALgLASAAQASAAAMALQALALAAARIAABBQAAASgLAKQgMALgSAAQgSAAgLgLgAgVg2QgIAJAAANIAABCQAAANAIAHQAIAJANgBQAOABAIgJQAIgHAAgNIAAhCQAAgNgIgJQgIgHgOgBQgNABgIAHg");
	this.shape_4.setTransform(55.725,60.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgWBAQgKgGgEgNQgBgGAAgMIAAg+QAAgQAKgKQAKgKARAAQAPABALAIQAKAKgBAPIAAACIgBABIgBABIgGAAIgBgBIgBgBIAAgBQAAgLgIgIQgHgGgKAAQgLAAgIAHQgHAHgBAMIAAAhIABAAQAFgHAHgDQAHgDAIgBQAaAAAIAWQADAIAAANQAAANgCAGQgEAMgJAHQgJAGgOAAQgMABgKgIgAgQgBQgHAEgCAJQgBAGgBAKQABAKABAEQACAJAHAGQAGAFAKAAQAJAAAHgFQAHgFADgKQACgEgBgLQAAgKgBgFQgDgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_5.setTransform(45.15,60.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3}]},1).wait(1));

	// Слой_2
	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#FFFFFF").ss(2,0,0,4).p("AMelLIseAAIAAmFIsdAAIAAWhIY7AAg");
	this.shape_6.setTransform(55.457,50.1811,0.6956,0.6956);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#E3DDE2").s().p("AscLRIAA2hIMcAAIAAGFIMeAAIAAQcg");
	this.shape_7.setTransform(55.457,50.1811,0.6956,0.6956);

	this.instance = new lib.viewvideo("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(85.9,95.85,0.6711,0.6708,0,0,0,37.2,26.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AscLRIAA2hIMcAAIAAGFIMeAAIAAQcg");
	this.shape_8.setTransform(55.457,50.1811,0.6956,0.6956);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6}]}).to({state:[{t:this.shape_8},{t:this.shape_6},{t:this.instance}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,113,114.3);


(lib.btn2video = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AglBHIgBgBIgBgCIAAgFIABgDIAsg5QATgYAAgOQAAgLgIgHQgIgHgLAAQgMAAgHAHQgIAHAAALIAAAGIgBACIgBAAIgGAAIgCAAIAAgCIAAgHQAAgPAKgKQAKgJARAAQALAAAIAFQAJAEAFAIQAFAIAAAKQAAARgUAYIgpA2QAAABAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAIA/AAIACABIABACIAAAEIgBACIgCABg");
	this.shape.setTransform(88.1,60.025);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgdA9QgLgKAAgSIAAhBQAAgRALgLQALgLASAAQASAAAMALQALALAAARIAABBQAAASgLAKQgMALgSAAQgSAAgLgLgAgVg2QgIAJAAANIAABCQAAANAIAHQAIAJANgBQAOABAIgJQAIgHAAgNIAAhCQAAgNgIgJQgIgHgOgBQgNABgIAHg");
	this.shape_1.setTransform(77.175,60.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgWBAQgKgGgEgNQgCgGAAgMIAAg+QAAgQALgKQALgKAQAAQAQABAJAIQAKAKAAAPIAAACIgBABIgBABIgGAAIgCgBIgBgBIAAgBQABgLgIgIQgGgGgLAAQgMAAgHAHQgIAHAAAMIAAAhIACAAQAEgHAHgDQAHgDAIgBQAaAAAIAWQAEAIAAANQgBANgCAGQgEAMgJAHQgJAGgNAAQgNABgKgIgAgQgBQgGAEgDAJQgCAGAAAKQAAAKACAEQACAJAHAGQAHAFAJAAQAKAAAGgFQAIgFACgKQACgEAAgLQgBgKgCgFQgCgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_2.setTransform(66.6,60.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).to({state:[]},1).wait(1));

	// Слой_2
	this.instance = new lib.viewvideo("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(76.65,94.7,0.6711,0.6708,0,0,0,37.2,26.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#FFFFFF").ss(2,0,0,4).p("ARclLIsiAAIAAmFI2VAAIAAWhMAi3AAAg");
	this.shape_3.setTransform(77.6731,50.1811,0.6956,0.6956);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AxbLRIAA2hIWVAAIAAGFIMjAAIAAQcg");
	this.shape_4.setTransform(77.6731,50.1811,0.6956,0.6956);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#E3DDE2").s().p("Ak1DeIAAm7IJrAAIAAG7g");
	this.shape_5.setTransform(78.2,90.725);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.instance,p:{y:94.7}}]},1).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.instance,p:{y:97.7}}]},1).to({state:[{t:this.shape_5}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,157.4,116.1);


(lib.btn2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AglBHIgBgBIgBgCIAAgFIABgDIAsg5QATgYAAgOQAAgLgIgHQgIgHgLAAQgMAAgHAHQgIAHAAALIAAAGIgBACIgBAAIgGAAIgCAAIAAgCIAAgHQAAgPAKgKQAKgJARAAQALAAAIAFQAJAEAFAIQAFAIAAAKQAAARgUAYIgpA2QAAABAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAIA/AAIACABIABACIAAAEIgBACIgCABg");
	this.shape.setTransform(88.1,60.025);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgdA9QgLgKAAgSIAAhBQAAgRALgLQALgLASAAQASAAAMALQALALAAARIAABBQAAASgLAKQgMALgSAAQgSAAgLgLgAgVg2QgIAJAAANIAABCQAAANAIAHQAIAJANgBQAOABAIgJQAIgHAAgNIAAhCQAAgNgIgJQgIgHgOgBQgNABgIAHg");
	this.shape_1.setTransform(77.175,60.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgWBAQgKgGgEgNQgCgGAAgMIAAg+QAAgQALgKQALgKAQAAQAQABAJAIQAKAKAAAPIAAACIgBABIgBABIgGAAIgCgBIgBgBIAAgBQABgLgIgIQgGgGgLAAQgMAAgHAHQgIAHAAAMIAAAhIACAAQAEgHAHgDQAHgDAIgBQAaAAAIAWQAEAIAAANQgBANgCAGQgEAMgJAHQgJAGgNAAQgNABgKgIgAgQgBQgGAEgDAJQgCAGAAAKQAAAKACAEQACAJAHAGQAHAFAJAAQAKAAAGgFQAIgFACgKQACgEAAgLQgBgKgCgFQgCgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_2.setTransform(66.6,60.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AglBHIgBgBIgBgCIAAgFIABgDIAsg5QATgYAAgOQAAgLgIgHQgIgHgLAAQgMAAgHAHQgIAHAAALIAAAGIgBACIgBAAIgGAAIgCAAIAAgCIAAgHQAAgPAKgKQAKgJARAAQALAAAIAFQAJAEAFAIQAFAIAAAKQAAARgUAYIgpA2QAAABAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAIA/AAIACABIABACIAAAEIgBACIgCABg");
	this.shape_3.setTransform(88.1,60.025);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgdA9QgLgKAAgSIAAhBQAAgRALgLQALgLASAAQASAAAMALQALALAAARIAABBQAAASgLAKQgMALgSAAQgSAAgLgLgAgVg2QgIAJAAANIAABCQAAANAIAHQAIAJANgBQAOABAIgJQAIgHAAgNIAAhCQAAgNgIgJQgIgHgOgBQgNABgIAHg");
	this.shape_4.setTransform(77.175,60.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgWBAQgKgGgEgNQgCgGAAgMIAAg+QAAgQALgKQALgKAQAAQAQABAJAIQAKAKAAAPIAAACIgBABIgBABIgGAAIgCgBIgBgBIAAgBQABgLgIgIQgGgGgLAAQgMAAgHAHQgIAHAAAMIAAAhIACAAQAEgHAHgDQAHgDAIgBQAaAAAIAWQAEAIAAANQgBANgCAGQgEAMgJAHQgJAGgNAAQgNABgKgIgAgQgBQgGAEgDAJQgCAGAAAKQAAAKACAEQACAJAHAGQAHAFAJAAQAKAAAGgFQAIgFACgKQACgEAAgLQgBgKgCgFQgCgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_5.setTransform(66.6,60.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3}]},1).wait(1));

	// Слой_2
	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#FFFFFF").ss(2,0,0,4).p("AMJjmIovAAIAAkPIviAAIAAPrIYRAAg");
	this.shape_6.setTransform(77.675,50.175);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#E3DDE2").s().p("AsIH2IAAvrIPiAAIAAEPIIvAAIAALcg");
	this.shape_7.setTransform(77.675,50.175);

	this.instance = new lib.viewvideo("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(76.65,94.7,0.6711,0.6708,0,0,0,37.2,26.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#FFFFFF").ss(2,0,0,4).p("ARclLIsiAAIAAmFI2VAAIAAWhMAi3AAAg");
	this.shape_8.setTransform(77.6731,50.1811,0.6956,0.6956);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AxbLRIAA2hIWVAAIAAGFIMjAAIAAQcg");
	this.shape_9.setTransform(77.6731,50.1811,0.6956,0.6956);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("#FFFFFF").ss(2,0,0,4).p("ARclLIsiAAIAAmFI2VAAIAAWhMAi3AAAg");
	this.shape_10.setTransform(77.6731,50.1811,0.6956,0.6956);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AxbLRIAA2hIWVAAIAAGFIMjAAIAAQcg");
	this.shape_11.setTransform(77.6731,50.1811,0.6956,0.6956);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6}]}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.instance}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,157.4,113.1);


(lib.btn1video = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAKBGIgCgBIAAgCIAAh8IgBAAIAAAAIgVAKIgCAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAgDQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBIAWgMIADgBIAHAAIACABIAAABIAACGIAAACIgCABg");
	this.shape.setTransform(39.575,120.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgdA9QgLgKAAgSIAAhBQAAgSALgKQALgLASAAQASAAAMALQALAKAAASIAABBQAAASgLAKQgMALgSAAQgSAAgLgLgAgVg1QgIAHAAAOIAABBQAAANAIAJQAIAHANABQAOgBAIgHQAIgJAAgNIAAhBQAAgOgIgHQgIgIgOAAQgNAAgIAIg");
	this.shape_1.setTransform(30.925,120.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgWBBQgKgIgDgLQgDgIAAgLIAAg+QAAgQALgKQALgJAQAAQAQAAAJAJQALAJAAAPIAAACIgCACIgBAAIgGAAIgCAAIgBgBIAAgCQAAgLgGgIQgIgGgKAAQgMAAgHAHQgIAIABAMIAAAgIABAAQAEgIAHgDQAHgCAIAAQAaAAAJAVQADAIAAAOQgBAMgCAHQgEALgJAHQgJAHgNAAQgOgBgJgGgAgQgBQgHAEgCAJQgBAGAAAKQAAAKABAEQACAJAHAGQAHAFAJAAQAKAAAGgFQAIgFACgKQACgFAAgJQAAgLgDgFQgCgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_2.setTransform(20.35,120.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).to({state:[]},1).wait(1));

	// Слой_2
	this.instance = new lib.viewvideo("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(29.65,217.95,0.6711,0.6708,0,0,0,37.2,26.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#FFFFFF").ss(2,0,0,4).p("AiPorIk0AAIAAaHIJcAAIABzOIEqAAIgCvpIpRAAg");
	this.shape_3.setTransform(45.226,111.55);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AnDRcIAA6HIE0AAIAAowIJRAAIACPpIkqAAIgBTOg");
	this.shape_4.setTransform(45.225,111.55);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#E3DDE2").s().p("AkjDtIAAnZIJHAAIAAHZg");
	this.shape_5.setTransform(30.6,214.375);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.instance,p:{y:217.95}}]},1).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.instance,p:{y:220.95}}]},1).to({state:[{t:this.shape_5}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,92.5,239.4);


(lib.btn1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAKBGIgCgBIAAgCIAAh8IgBAAIAAAAIgVAKIgCAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAgDQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBIAWgMIADgBIAHAAIACABIAAABIAACGIAAACIgCABg");
	this.shape.setTransform(39.575,120.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgdA9QgLgKAAgSIAAhBQAAgSALgKQALgLASAAQASAAAMALQALAKAAASIAABBQAAASgLAKQgMALgSAAQgSAAgLgLgAgVg1QgIAHAAAOIAABBQAAANAIAJQAIAHANABQAOgBAIgHQAIgJAAgNIAAhBQAAgOgIgHQgIgIgOAAQgNAAgIAIg");
	this.shape_1.setTransform(30.925,120.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgWBBQgKgIgDgLQgDgIAAgLIAAg+QAAgQALgKQALgJAQAAQAQAAAJAJQALAJAAAPIAAACIgCACIgBAAIgGAAIgCAAIgBgBIAAgCQAAgLgGgIQgIgGgKAAQgMAAgHAHQgIAIABAMIAAAgIABAAQAEgIAHgDQAHgCAIAAQAaAAAJAVQADAIAAAOQgBAMgCAHQgEALgJAHQgJAHgNAAQgOgBgJgGgAgQgBQgHAEgCAJQgBAGAAAKQAAAKABAEQACAJAHAGQAHAFAJAAQAKAAAGgFQAIgFACgKQACgFAAgJQAAgLgDgFQgCgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_2.setTransform(20.35,120.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AAKBGIgCgBIAAgCIAAh8IgBAAIAAAAIgVAKIgCAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAgDQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBIAWgMIADgBIAHAAIACABIAAABIAACGIAAACIgCABg");
	this.shape_3.setTransform(39.575,120.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgdA9QgLgKAAgSIAAhBQAAgSALgKQALgLASAAQASAAAMALQALAKAAASIAABBQAAASgLAKQgMALgSAAQgSAAgLgLgAgVg1QgIAHAAAOIAABBQAAANAIAJQAIAHANABQAOgBAIgHQAIgJAAgNIAAhBQAAgOgIgHQgIgIgOAAQgNAAgIAIg");
	this.shape_4.setTransform(30.925,120.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgWBBQgKgIgDgLQgDgIAAgLIAAg+QAAgQALgKQALgJAQAAQAQAAAJAJQALAJAAAPIAAACIgCACIgBAAIgGAAIgCAAIgBgBIAAgCQAAgLgGgIQgIgGgKAAQgMAAgHAHQgIAIABAMIAAAgIABAAQAEgIAHgDQAHgCAIAAQAaAAAJAVQADAIAAAOQgBAMgCAHQgEALgJAHQgJAHgNAAQgOgBgJgGgAgQgBQgHAEgCAJQgBAGAAAKQAAAKABAEQACAJAHAGQAHAFAJAAQAKAAAGgFQAIgFACgKQACgFAAgJQAAgLgDgFQgCgJgGgEQgHgFgKAAQgJAAgHAFg");
	this.shape_5.setTransform(20.35,120.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3}]},1).wait(1));

	// Слой_2
	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#FFFFFF").ss(2,0,0,4).p("AiPorIk0AAIAAaHIJcAAIABzOIEqAAIgCvpIpRAAg");
	this.shape_6.setTransform(45.226,111.55);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#E3DDE2").s().p("AnDRcIAA6HIE0AAIAAowIJRAAIACPpIkqAAIgBTOg");
	this.shape_7.setTransform(45.225,111.55);

	this.instance = new lib.viewvideo("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(29.65,217.95,0.6711,0.6708,0,0,0,37.2,26.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AnDRcIAA6HIE0AAIAAowIJRAAIACPpIkqAAIgBTOg");
	this.shape_8.setTransform(45.225,111.55);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6}]}).to({state:[{t:this.shape_8},{t:this.shape_6},{t:this.instance}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-4,171.4,239.4);


(lib.Монтажный_кадр_1_video_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// video_btn
	this.btnvideo608 = new lib.btn8video();
	this.btnvideo608.name = "btnvideo608";
	this.btnvideo608.parent = this;
	this.btnvideo608.setTransform(321.6,292.35,1.0031,1.0031,0,0,0,55.7,50.6);
	new cjs.ButtonHelper(this.btnvideo608, 0, 1, 2, false, new lib.btn8video(), 3);

	this.btnvideo607 = new lib.btn7video();
	this.btnvideo607.name = "btnvideo607";
	this.btnvideo607.parent = this;
	this.btnvideo607.setTransform(467.9,296.85,1.0031,1.0031,0,0,0,90.5,55.1);
	new cjs.ButtonHelper(this.btnvideo607, 0, 1, 2, false, new lib.btn7video(), 3);

	this.btnvideo604 = new lib.btn4video();
	this.btnvideo604.name = "btnvideo604";
	this.btnvideo604.parent = this;
	this.btnvideo604.setTransform(544.25,168.55,1.0031,1.0031,0,0,0,55.6,50.4);
	new cjs.ButtonHelper(this.btnvideo604, 0, 1, 2, false, new lib.btn4video(), 3);

	this.btnvideo605 = new lib.btn5video();
	this.btnvideo605.name = "btnvideo605";
	this.btnvideo605.parent = this;
	this.btnvideo605.setTransform(599.85,118.1,1.0031,1.0031,0,0,0,0.1,0.1);
	new cjs.ButtonHelper(this.btnvideo605, 0, 1, 2, false, new lib.btn5video(), 3);

	this.btnvideo606 = new lib.btn6video();
	this.btnvideo606.name = "btnvideo606";
	this.btnvideo606.parent = this;
	this.btnvideo606.setTransform(558.5,241.6,1.0031,1.0031);
	new cjs.ButtonHelper(this.btnvideo606, 0, 1, 2, false, new lib.btn6video(), 3);

	this.btnvideo603 = new lib.btn3video();
	this.btnvideo603.name = "btnvideo603";
	this.btnvideo603.parent = this;
	this.btnvideo603.setTransform(432.85,168.55,1.0031,1.0031,0,0,0,55.6,50.4);
	new cjs.ButtonHelper(this.btnvideo603, 0, 1, 2, false, new lib.btn3video(), 3);

	this.btnvideo602 = new lib.btn2video();
	this.btnvideo602.name = "btnvideo602";
	this.btnvideo602.parent = this;
	this.btnvideo602.setTransform(299.3,168.55,1.0031,1.0031,0,0,0,77.8,50.4);
	new cjs.ButtonHelper(this.btnvideo602, 0, 1, 2, false, new lib.btn2video(), 3);

	this.btnvideo601 = new lib.btn1video();
	this.btnvideo601.name = "btnvideo601";
	this.btnvideo601.parent = this;
	this.btnvideo601.setTransform(176.15,230.3,1.0031,1.0031,0,0,0,45.4,111.7);
	new cjs.ButtonHelper(this.btnvideo601, 0, 1, 2, false, new lib.btn1video(), 3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.btnvideo601},{t:this.btnvideo602},{t:this.btnvideo603},{t:this.btnvideo606},{t:this.btnvideo605},{t:this.btnvideo604},{t:this.btnvideo607},{t:this.btnvideo608}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Монтажный_кадр_1_video_btn, null, null);


(lib.Монтажный_кадр_1_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// btn
	this.nb608 = new lib.btn8();
	this.nb608.name = "nb608";
	this.nb608.parent = this;
	this.nb608.setTransform(321.6,292.35,1.0031,1.0031,0,0,0,55.7,50.6);
	new cjs.ButtonHelper(this.nb608, 0, 1, 1);

	this.nb607 = new lib.btn7();
	this.nb607.name = "nb607";
	this.nb607.parent = this;
	this.nb607.setTransform(467.9,296.85,1.0031,1.0031,0,0,0,90.5,55.1);
	new cjs.ButtonHelper(this.nb607, 0, 1, 1);

	this.nb604 = new lib.btn4();
	this.nb604.name = "nb604";
	this.nb604.parent = this;
	this.nb604.setTransform(544.25,168.55,1.0031,1.0031,0,0,0,55.6,50.4);
	new cjs.ButtonHelper(this.nb604, 0, 1, 1);

	this.nb605 = new lib.btn5();
	this.nb605.name = "nb605";
	this.nb605.parent = this;
	this.nb605.setTransform(599.85,118.1,1.0031,1.0031,0,0,0,0.1,0.1);
	new cjs.ButtonHelper(this.nb605, 0, 1, 1);

	this.nb606 = new lib.btn6();
	this.nb606.name = "nb606";
	this.nb606.parent = this;
	this.nb606.setTransform(558.5,241.6,1.0031,1.0031);
	new cjs.ButtonHelper(this.nb606, 0, 1, 1);

	this.nb603 = new lib.btn3();
	this.nb603.name = "nb603";
	this.nb603.parent = this;
	this.nb603.setTransform(432.85,168.55,1.0031,1.0031,0,0,0,55.6,50.4);
	new cjs.ButtonHelper(this.nb603, 0, 1, 1);

	this.nb602 = new lib.btn2();
	this.nb602.name = "nb602";
	this.nb602.parent = this;
	this.nb602.setTransform(299.3,168.55,1.0031,1.0031,0,0,0,77.8,50.4);
	new cjs.ButtonHelper(this.nb602, 0, 1, 1);

	this.nb601 = new lib.btn1();
	this.nb601.name = "nb601";
	this.nb601.parent = this;
	this.nb601.setTransform(176.15,230.3,1.0031,1.0031,0,0,0,45.4,111.7);
	new cjs.ButtonHelper(this.nb601, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.nb601},{t:this.nb602},{t:this.nb603},{t:this.nb606},{t:this.nb605},{t:this.nb604},{t:this.nb607},{t:this.nb608}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Монтажный_кадр_1_btn, null, null);


// stage content:
(lib.FLOOR6_v7_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	this.___GetDepth___ = function(obj) {
		var depth = obj.depth;
		var cameraObj = this.___camera___instance;
		if(cameraObj && cameraObj.depth && obj.isAttachedToCamera)
		{
			depth += depth + cameraObj.depth;
		}
		return depth;
		}
	this.___needSorting___ = function() {
		for (var i = 0; i < this.getNumChildren() - 1; i++)
		{
			var prevDepth = this.___GetDepth___(this.getChildAt(i));
			var nextDepth = this.___GetDepth___(this.getChildAt(i + 1));
			if (prevDepth < nextDepth)
				return true;
		}
		return false;
	}
	this.___sortFunction___ = function(obj1, obj2) {
		return (this.exportRoot.___GetDepth___(obj2) - this.exportRoot.___GetDepth___(obj1));
	}
	this.on('tick', function (event){
		var curTimeline = event.currentTarget;
		if (curTimeline.___needSorting___()){
			this.sortChildren(curTimeline.___sortFunction___);
		}
	});

	// timeline functions:
	this.frame_0 = function() {
		this.btnvideo601 = this.video_btn.btnvideo601;
		this.btnvideo602 = this.video_btn.btnvideo602;
		this.btnvideo603 = this.video_btn.btnvideo603;
		this.btnvideo606 = this.video_btn.btnvideo606;
		this.btnvideo605 = this.video_btn.btnvideo605;
		this.btnvideo604 = this.video_btn.btnvideo604;
		this.btnvideo607 = this.video_btn.btnvideo607;
		this.btnvideo608 = this.video_btn.btnvideo608;
		this.nb601 = this.btn.nb601;
		this.nb602 = this.btn.nb602;
		this.nb603 = this.btn.nb603;
		this.nb606 = this.btn.nb606;
		this.nb605 = this.btn.nb605;
		this.nb604 = this.btn.nb604;
		this.nb607 = this.btn.nb607;
		this.nb608 = this.btn.nb608;
		//trigers_______________________________
		
		this.nb601.addEventListener("click", GoTo);
		function GoTo() {
			window.open("#apt601", "_self");
		}	
		
		this.nb602.addEventListener("click", GoTo_nb602);
		function GoTo_nb602() {
			window.open("#apt602", "_self");
		}	
		
		this.nb603.addEventListener("click", GoTo_nb603);
		function GoTo_nb603() {
			window.open("#apt603", "_self");
		}	
		
		this.nb604.addEventListener("click", GoTo_nb604);
		function GoTo_nb604() {
			window.open("#apt604", "_self");
		}	
		
		this.nb605.addEventListener("click", GoTo_nb605);
		function GoTo_nb605() {
			window.open("#apt605", "_self");
		}	
		
		this.nb606.addEventListener("click", GoTo_nb606);
		function GoTo_nb606() {
			window.open("#apt606", "_self");
		}	
		
		this.nb607.addEventListener("click", GoTo_nb607);
		function GoTo_nb607() {
			window.open("#apt607", "_self");
		}	
		
		this.nb608.addEventListener("click", GoTo_nb608);
		function GoTo_nb608() {
			window.open("#apt608", "_self");
		}	
		
		
		
		
		
		this.btnvideo601.addEventListener("click", ToGoVideo601);
		function ToGoVideo601() {
			window.open("#viewvideo601", "_self");
		}
		
		
		this.btnvideo602.addEventListener("click", ToGoVideo602);
		function ToGoVideo602() {
			window.open("#viewvideo602", "_self");
		}
		
		
		this.btnvideo603.addEventListener("click", ToGoVideo603);
		function ToGoVideo603() {
			window.open("#viewvideo603", "_self");
		}
		
		
		this.btnvideo604.addEventListener("click", ToGoVideo604);
		function ToGoVideo604() {
			window.open("#viewvideo604", "_self");
			}
			
			
		this.btnvideo605.addEventListener("click", ToGoVideo605);
		function ToGoVideo605() {
			window.open("#viewvideo605", "_self");
		}
		
		
		this.btnvideo606.addEventListener("click", ToGoVideo606);
		function ToGoVideo606() {
			window.open("#viewvideo606", "_self");
		}
		
		
		this.btnvideo607.addEventListener("click", ToGoVideo607);
		function ToGoVideo607() {
			window.open("#viewvideo607", "_self");
		}
		
		
		this.btnvideo608.addEventListener("click", ToGoVideo608);
		function ToGoVideo608() {
			window.open("#viewvideo608", "_self");
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// video_btn_obj_
	this.video_btn = new lib.Монтажный_кадр_1_video_btn();
	this.video_btn.name = "video_btn";
	this.video_btn.parent = this;
	this.video_btn.setTransform(421.7,238.6,1,1,0,0,0,421.7,238.6);
	this.video_btn.depth = 0;
	this.video_btn.isAttachedToCamera = 0
	this.video_btn.isAttachedToMask = 0
	this.video_btn.layerDepth = 0
	this.video_btn.layerIndex = 0
	this.video_btn.maskLayerName = 0

	this.timeline.addTween(cjs.Tween.get(this.video_btn).wait(1));

	// btn_obj_
	this.btn = new lib.Монтажный_кадр_1_btn();
	this.btn.name = "btn";
	this.btn.parent = this;
	this.btn.setTransform(421.7,236.8,1,1,0,0,0,421.7,236.8);
	this.btn.depth = 0;
	this.btn.isAttachedToCamera = 0
	this.btn.isAttachedToMask = 0
	this.btn.layerDepth = 0
	this.btn.layerIndex = 1
	this.btn.maskLayerName = 0

	this.timeline.addTween(cjs.Tween.get(this.btn).wait(1));

	// walls_obj_
	this.walls = new lib.Монтажный_кадр_1_walls();
	this.walls.name = "walls";
	this.walls.parent = this;
	this.walls.setTransform(404.1,230.5,1,1,0,0,0,404.1,230.5);
	this.walls.depth = 0;
	this.walls.isAttachedToCamera = 0
	this.walls.isAttachedToMask = 0
	this.walls.layerDepth = 0
	this.walls.layerIndex = 2
	this.walls.maskLayerName = 0

	this.timeline.addTween(cjs.Tween.get(this.walls).wait(1));

	// N_obj_
	this.N = new lib.Монтажный_кадр_1_N();
	this.N.name = "N";
	this.N.parent = this;
	this.N.setTransform(708.3,427.4,1,1,0,0,0,708.3,427.4);
	this.N.depth = 0;
	this.N.isAttachedToCamera = 0
	this.N.isAttachedToMask = 0
	this.N.layerDepth = 0
	this.N.layerIndex = 3
	this.N.maskLayerName = 0

	this.timeline.addTween(cjs.Tween.get(this.N).wait(1));

	// texts_obj_
	this.texts = new lib.Монтажный_кадр_1_texts();
	this.texts.name = "texts";
	this.texts.parent = this;
	this.texts.setTransform(354.7,308.2,1,1,0,0,0,354.7,308.2);
	this.texts.depth = 0;
	this.texts.isAttachedToCamera = 0
	this.texts.isAttachedToMask = 0
	this.texts.layerDepth = 0
	this.texts.layerIndex = 4
	this.texts.maskLayerName = 0

	this.timeline.addTween(cjs.Tween.get(this.texts).wait(1));

	// stair_obj_
	this.stair = new lib.Монтажный_кадр_1_stair();
	this.stair.name = "stair";
	this.stair.parent = this;
	this.stair.setTransform(398.9,297.8,1,1,0,0,0,398.9,297.8);
	this.stair.depth = 0;
	this.stair.isAttachedToCamera = 0
	this.stair.isAttachedToMask = 0
	this.stair.layerDepth = 0
	this.stair.layerIndex = 5
	this.stair.maskLayerName = 0

	this.timeline.addTween(cjs.Tween.get(this.stair).wait(1));

	// bg_obj_
	this.bg = new lib.Монтажный_кадр_1_bg();
	this.bg.name = "bg";
	this.bg.parent = this;
	this.bg.setTransform(400,239.5,1,1,0,0,0,400,239.5);
	this.bg.depth = 0;
	this.bg.isAttachedToCamera = 0
	this.bg.isAttachedToMask = 0
	this.bg.layerDepth = 0
	this.bg.layerIndex = 6
	this.bg.maskLayerName = 0

	this.timeline.addTween(cjs.Tween.get(this.bg).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(400,240,400,238.89999999999998);
// library properties:
lib.properties = {
	id: '224194AF442E2F4E81860E254E11FC15',
	width: 800,
	height: 480,
	fps: 25,
	color: "#E3DDE2",
	opacity: 1.00,
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['224194AF442E2F4E81860E254E11FC15'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


// Layer depth API : 

AdobeAn.Layer = new function() {
	this.getLayerZDepth = function(timeline, layerName)
	{
		if(layerName === "Camera")
		layerName = "___camera___instance";
		var script = "if(timeline." + layerName + ") timeline." + layerName + ".depth; else 0;";
		return eval(script);
	}
	this.setLayerZDepth = function(timeline, layerName, zDepth)
	{
		const MAX_zDepth = 10000;
		const MIN_zDepth = -5000;
		if(zDepth > MAX_zDepth)
			zDepth = MAX_zDepth;
		else if(zDepth < MIN_zDepth)
			zDepth = MIN_zDepth;
		if(layerName === "Camera")
		layerName = "___camera___instance";
		var script = "if(timeline." + layerName + ") timeline." + layerName + ".depth = " + zDepth + ";";
		eval(script);
	}
	this.removeLayer = function(timeline, layerName)
	{
		if(layerName === "Camera")
		layerName = "___camera___instance";
		var script = "if(timeline." + layerName + ") timeline.removeChild(timeline." + layerName + ");";
		eval(script);
	}
	this.addNewLayer = function(timeline, layerName, zDepth)
	{
		if(layerName === "Camera")
		layerName = "___camera___instance";
		zDepth = typeof zDepth !== 'undefined' ? zDepth : 0;
		var layer = new createjs.MovieClip();
		layer.name = layerName;
		layer.depth = zDepth;
		layer.layerIndex = 0;
		timeline.addChild(layer);
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;