(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [
		{name:"SouthCitySq_AdWords_300x250_atlas_", frames: [[405,269,67,115],[0,0,476,267],[0,269,403,267]]}
];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib.logo = function() {
	this.spriteSheet = ss["SouthCitySq_AdWords_300x250_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.pc1 = function() {
	this.spriteSheet = ss["SouthCitySq_AdWords_300x250_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.pc2 = function() {
	this.spriteSheet = ss["SouthCitySq_AdWords_300x250_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.txt2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AARAqIgBAAIgBgBIgfgnIAAAlIAAACIgCABIgLAAIgCgBIgBgCIAAhNIABgCIACgBIALAAIACABIAAACIAAAgIAegiIABAAIABgBIAMAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAABQAAAAABAAQAAABAAAAQAAAAgBABQAAAAAAAAIgeAkIAgAnQAAAAABABQAAAAAAAAQAAAAAAABQgBAAAAABQAAAAAAAAQAAAAgBABQAAAAAAAAQAAAAgBAAg");
	this.shape.setTransform(58.3,24.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgYAqIgBAAIgBgCIAAhOIABgCIABgBIAwAAIACABIABACIAAAJIgBABIgCABIgiAAIAAAUIAcAAIACABIABACIAAAJIgBABIgCABIgcAAIAAAUIAiAAIACABIABACIAAAKIgBACIgCAAg");
	this.shape_1.setTransform(50.6,24.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgYAqIgBAAIgBgCIAAhOIABgCIABgBIAwAAIACABIABACIAAAJIgBABIgCABIgiAAIAAAUIAcAAIACABIABACIAAAJIgBABIgCABIgcAAIAAAUIAiAAIACABIABACIAAAKIgBACIgCAAg");
	this.shape_2.setTransform(43.6,24.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAaArIgDAAIgBAAIgBgBIgVg1IAAAAIgVA1IgBABIgBAAIgBAAIgCAAIgBgBIgXhQQAAAAAAAAQAAgBAAAAQAAAAABAAQAAgBAAAAIABgBIAMAAIABABIABABIAMAvIABAAIATgxIAAgBIACAAIABAAIABAAIABABIATAxIABAAIAMgvIABgBIABgBIALAAIACABQAAAAAAABQABAAAAAAQAAAAAAABQAAAAgBAAIgWBQIgBABIgBAAg");
	this.shape_3.setTransform(34.4,24.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAPAqIgBAAIAAgBIgPggIgOAAIAAAfIAAACIgCAAIgLAAIgCAAIAAgCIAAhOIAAgCIACgBIAhAAQAIAAAFAEQAGADAEAGQADAFAAAIQAAAIgFAHQgEAFgIADIAQAeIAAADIgCABgAgPgCIATAAQAFgBADgEQAEgDAAgFQAAgFgEgDQgDgDgFgBIgTAAg");
	this.shape_4.setTransform(22.6,24.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgYAqIgBAAIgBgCIAAhOIABgCIABgBIAwAAIACABIABACIAAAJIgBABIgCABIgiAAIAAAUIAcAAIACABIABACIAAAJIgBABIgCABIgcAAIAAAUIAiAAIACABIABACIAAAKIgBACIgCAAg");
	this.shape_5.setTransform(15.1,24.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgaAqIgBAAIgBgCIAAhOIABgCIABgBIAcAAQAHAAAGAEQAGADAEAGQADAGABAHQgBAIgDAGQgEAFgGAEQgGADgHAAIgOAAIAAAdIgBACIgCAAgAgMgCIANAAQAFAAADgEQAEgDAAgGQAAgFgEgDQgDgDgFgBIgNAAg");
	this.shape_6.setTransform(8.2,24.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Ag8CLQgagTgNgjQgNgkAAgxQAAgxANgjQANgiAagUQAZgSAjgBQAkABAZASQAaAUANAiQANAjAAAxQAAAxgNAkQgNAjgaATQgZASgkABQgjgBgZgSgAgnhMQgOAbAAAxQAAAzAOAaQAOAbAZAAQAaAAAOgbQAOgaABgzQgBgxgOgbQgOgbgaAAQgZAAgOAbg");
	this.shape_7.setTransform(51.7,-0.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("Ag4CSQgYgLgMgUQgNgTgBgZQABgPAGgMQAHgMAJgKQAJgLAJgGIAOgIIAAgBQgKgGgKgJQgLgKgIgNQgHgOgBgSQABgZANgTQANgSAWgKQAWgLAbAAQAcAAAWALQAWAKANASQANATABAZQgBARgHAOQgIAOgLAJQgKAKgKAFIAAACQALAEAMALQANAKAJAPQAJAPABATQgBAZgMATQgNAUgZALQgYAMggAAQggAAgYgMgAgiApQgMANAAAQQAAANAHAJQAHAKAKAEQALAGALAAQANAAAKgGQALgEAGgKQAHgJAAgNQAAgQgMgNQgMgNgXgGQgWAGgMANgAgchjQgMALAAAQQAAAQAKAKQAKALAUAGIAAAAQAVgFAKgMQAKgLAAgPQAAgQgMgLQgMgKgRgBQgRABgLAKg");
	this.shape_8.setTransform(24.9,-0.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgyCWQgTgIgMgJQgLgJgEgGQgCgDgBgDQABgDACgDIAXgWQADgCADAAQADAAADACIAIAIQAJAFAMAGQAMAFAOABQALAAALgGQALgFAGgKQAHgKAAgMQABgMgIgKQgGgKgOgGQgNgGgVAAIgZAAQgDgBgDgCQgDgCAAgEIAAgbQAAgFADgDQACgCAEAAIAZAAQAbAAAOgMQAOgMAAgSQAAgMgGgJQgGgJgKgGQgKgEgLAAQgRAAgLAHQgMAGgFAIQgDADgDAAQgDAAgDgDIgWgUQgDgCAAgEQABgEACgCIAGgGQAGgGALgIQAMgHAPgGQAQgHASAAQAaAAAVAKQAWAKANATQANASAAAaQAAASgHAOQgHAOgLAJQgKAKgLAFIAAABQALAEAMAKQANAJAJAPQAJAOABAVQgBAZgNAUQgMAUgYALQgXAMgeAAQgcgBgTgHg");
	this.shape_9.setTransform(0,-0.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgIDHQgEgBAAgFIAAgwQgZgBgRgIQgSgGgLgHIgPgMQgDgDgBgDQgBgDADgFIAJgQQAFgJAGgFQAFgFAHAFIAJAFIAUANQANAFAOAFIAAgsIAAgrQgVgIgVgLQgUgMgOgUQgNgSgBgeQAAgWAKgSQAKgSAUgNQAUgMAegCIAAgPQABgEACgCQADgCADgBIAFAAQADABADACQACACAAAEIAAAPQAVACAQAFQAQAGALAHIAPAKQADABABAFQABAEgDAEIgKAPQgFAJgGAGQgGAFgFgEIgJgFQgHgFgLgFQgKgGgMgDIAABQIAfAPQAQAJAOAMQAOALAJAQQAJARAAAWQAAAZgLATQgLATgVAMQgUALgfACIAAAwQAAADgCACQgDADgEAAIgIgCgAAKBhQAPgDAJgIQAKgKAAgNQAAgNgIgLQgJgLgRgKgAgmh0QgJAIAAALQAAANAJAKQAIALARAJIAAhJQgRADgIAIg");
	this.shape_10.setTransform(-23,0.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AABArIgBAAIgBAAIgBgBIgVguIgBAAIgHAsIAAACIgCAAIgLAAIgBgBQgBAAAAAAQAAAAAAAAQAAgBAAAAQAAAAAAgBIAOhPIABgBIACgBIACAAIABAAIABABIAZA4IAAAAIAbg4IAAgBIACAAIACAAIABABIABABIAOBPIAAACIgCABIgLAAIgCAAIAAgCIgHgsIgBAAIgVAuIgBABIgBAAg");
	this.shape_11.setTransform(-5.4,-28.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgVAmQgJgGgGgKQgGgJAAgNQAAgLAGgKQAGgJAJgGQAKgGALAAQAMAAAKAGQAJAGAGAJQAGAKAAALQAAANgGAJQgGAKgJAGQgKAFgMAAQgLAAgKgFgAgNgXQgGAEgEAGQgDAHAAAGQAAAIADAGQAEAGAGAEQAGAEAHAAQAHAAAHgEQAGgEAEgGQADgGABgIQgBgGgDgHQgEgGgGgEQgHgDgHAAQgHAAgGADg");
	this.shape_12.setTransform(-15.4,-28.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAPAqIgBgBIAAAAIgPggIgOAAIAAAeIAAACIgCABIgLAAIgCgBIAAgCIAAhOIAAgCIACAAIAhAAQAIAAAFADQAGAEAEAGQADAFAAAIQAAAIgFAHQgEAFgIADIAQAeIAAADIgCABgAgPgDIATAAQAFAAADgDQAEgEAAgFQAAgFgEgDQgDgEgFABIgTAAg");
	this.shape_13.setTransform(-24,-28.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgYAqIgBgBIgBgCIAAhOIABgCIABAAIAwAAIACAAIABACIAAAKIgBACIgCABIgiAAIAAAWIAcAAIACAAIABACIAAAJIgBACIgCABIgcAAIAAAdIgBACIgCABg");
	this.shape_14.setTransform(-31.2,-28.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.txt2, new cjs.Rectangle(-37,-39,105,74.7), null);


(lib.txt1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0099CC").s().p("AA9BgQgCAAgCgBIgEgFIgMgcIhQAAIgOAcIgCAFQgCABgEAAIgXAAQgBAAAAAAQgBAAgBgBQAAAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBAAgBQAAAAAAgBIBVi1IABgCIADgBIABAAIAEABIABACIBTC1QABABAAAAQAAABAAABQAAAAAAABQAAAAgBABQAAAAAAABQgBAAAAAAQgBABgBAAQAAAAgBAAgAAbAgIgbg7IAAAAIgaA7IA1AAg");
	this.shape.setTransform(114.6,28.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#0099CC").s().p("Ag7BeQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAAAIAAiyQAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAQABAAAAAAQABgBAAAAIA9AAQARAAAMAHQANAGAIAMQAHALAAAPQAAAKgFAIQgEAJgHAHQgHAFgGAEQAHABAIAGQAIAFAGAJQAFAJABANQAAAPgIAMQgIALgNAHQgOAGgQAAgAgdA/IAgAAQAKAAAHgHQAHgHAAgLQAAgHgEgFQgEgFgGgDQgGgDgHgBIgdAAgAgdgOIAdAAQAJgBAHgGQAGgHAAgLQAAgJgGgHQgHgGgJAAIgdAAg");
	this.shape_1.setTransform(97.9,28.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#0099CC").s().p("Ag7BeQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAAAIAAiyQAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAQABAAAAAAQABgBAAAAIA9AAQARAAAMAHQANAGAIAMQAHALAAAPQAAAKgFAIQgEAJgHAHQgHAFgGAEQAHABAIAGQAIAFAGAJQAFAJABANQAAAPgIAMQgIALgNAHQgOAGgQAAgAgdA/IAgAAQAKAAAHgHQAHgHAAgLQAAgHgEgFQgEgFgGgDQgGgDgHgBIgdAAgAgdgOIAdAAQAJgBAHgGQAGgHAAgLQAAgJgGgHQgHgGgJAAIgdAAg");
	this.shape_2.setTransform(81.2,28.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#0099CC").s().p("AA9BgQgCAAgCgBIgEgFIgMgcIhQAAIgOAcIgDAFQgBABgDAAIgYAAQgBAAAAAAQgBAAgBgBQAAAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBAAgBQAAAAAAgBIBVi1IABgCIADgBIACAAIADABIABACIBTC1QABABAAAAQAAABAAABQAAAAAAABQAAAAgBABQAAAAAAABQgBAAAAAAQgBABgBAAQAAAAgBAAgAAbAgIgbg7IAAAAIgaA7IA1AAg");
	this.shape_3.setTransform(63.4,28.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#0099CC").s().p("AgiBUQgWgNgNgVQgNgWAAgcQAAgaANgWQANgWAWgNQAWgNAaAAQASAAARAHQARAGAOAMIABAEIgBAEIgRARIgDACQgBAAAAAAQAAAAgBgBQAAAAgBAAQAAAAgBgBQgJgIgKgEQgKgEgLAAQgQABgOAIQgNAJgIAOQgJAOAAAQQAAARAJAOQAIAOANAJQAOAIAQAAQALAAAIgCIANgFIAAgXIgVAAQgBAAgBAAQAAAAgBAAQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgWQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABgBIAEgBIAzAAQABAAAAAAQABAAAAABQABAAAAAAQAAAAAAABQABAAAAABQAAAAABAAQAAABAAAAQAAABAAAAIAABFIgBADIgBACIgJAEQgIAEgQAFQgOAEgUAAQgaAAgWgNg");
	this.shape_4.setTransform(44.6,28.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#0099CC").s().p("ABEBiIhwh8IAAB0QAAAAAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAQgBAAAAAAIgZAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAAAIAAi1QAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAQABAAAAAAQABAAAAgBIAHAAIBwB3IAAhuQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABAAQAAgBABAAIAZAAQAAAAABABQAAAAABAAQAAAAAAAAQABABAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABIAAC0QAAABAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgBABAAAAg");
	this.shape_5.setTransform(24.8,28.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#0099CC").s().p("AgwBUQgWgMgMgXQgNgVgBgcQABgaANgWQAMgWAWgNQAWgNAagBQAbABAWANQAWANANAWQANAWAAAaQAAAcgNAVQgNAXgWAMQgWANgbABQgagBgWgNgAgeg0QgOAIgJAOQgIAOAAAQQAAASAIANQAJAPAOAIQANAIARAAQARAAAOgIQAOgIAJgPQAIgNAAgSQAAgQgIgOQgJgOgOgIQgOgJgRAAQgRAAgNAJg");
	this.shape_6.setTransform(3.6,28.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#0099CC").s().p("AgwBUQgWgMgMgXQgNgVgBgcQABgaANgWQAMgWAWgNQAWgNAagBQAbABAWANQAWANANAWQANAWAAAaQAAAcgNAVQgNAXgWAMQgWANgbABQgagBgWgNgAgeg0QgOAIgJAOQgIAOAAAQQAAASAIANQAJAPAOAIQANAIARAAQARAAAOgIQAOgIAJgPQAIgNAAgSQAAgQgIgOQgJgOgOgIQgOgJgRAAQgRAAgNAJg");
	this.shape_7.setTransform(-18,28.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#0099CC").s().p("AgwBeQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAgBAAIAAiyQABgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAQAAgBABAAIAYAAQABAAAAABQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABQAAAAAAABQABAAAAABIAACWIBEAAQAAAAAAAAQABAAAAAAQABABAAAAQABAAAAABQAAAAABAAQAAABAAAAQAAABAAAAQAAABAAAAIAAAXQAAAAAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAAAAAg");
	this.shape_8.setTransform(-34.6,28.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#0099CC").s().p("AgwBeQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQgBAAAAAAIAAiyQAAgBABAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAQAAgBABAAIAZAAQAAAAAAABQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABQAAAAAAABQAAAAAAABIAACWIBFAAQAAAAAAAAQABAAAAAAQABABAAAAQABAAAAABQAAAAABAAQAAABAAAAQAAABAAAAQAAABAAAAIAAAXQAAAAAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAAAAAg");
	this.shape_9.setTransform(-48.2,28.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#0099CC").s().p("AgwBUQgWgMgNgXQgNgVAAgcQAAgaANgWQANgWAWgNQAVgNAbgBQAbABAWANQAWANANAWQANAWAAAaQAAAcgNAVQgNAXgWAMQgWANgbABQgbgBgVgNgAgeg0QgOAIgIAOQgJAOAAAQQAAASAJANQAIAPAOAIQAOAIAQAAQARAAAOgIQAOgIAJgPQAIgNAAgSQAAgQgIgOQgJgOgOgIQgOgJgRAAQgQAAgOAJg");
	this.shape_10.setTransform(-66.9,28.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#0099CC").s().p("AgwBUQgWgMgNgXQgNgVAAgcQAAgaANgWQANgWAWgNQAVgNAbgBQAbABAWANQAWANANAWQANAWAAAaQAAAcgNAVQgNAXgWAMQgWANgbABQgbgBgVgNgAgeg0QgOAIgIAOQgJAOAAAQQAAASAJANQAIAPAOAIQAOAIAQAAQARAAAOgIQAOgIAJgPQAIgNAAgSQAAgQgIgOQgJgOgOgIQgOgJgRAAQgQAAgOAJg");
	this.shape_11.setTransform(-88.5,28.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#0099CC").s().p("AA1BiIgDgBIgBgDIgwh5IgBAAIgwB5IgBADIgDABIgFAAIgDgCIgBgDIgzi0QgBgBAAAAQAAgBAAgBQAAAAABgBQAAAAAAAAQAAgBABAAQAAgBABAAQAAAAABAAQAAgBABAAIAZAAIADABIACADIAcBrIABAAIArhvIACgCIADgBIAEAAIADABIABACIAsBvIABAAIAbhqIACgEIADgBIAZAAQAAAAABABQABAAAAAAQABAAAAABQABAAAAABQAAAAABAAQAAABAAAAQAAABAAABQAAAAAAABIgzC0IgCADIgDACg");
	this.shape_12.setTransform(-111.4,28.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#0099CC").s().p("AgLBfQgBAAAAgBQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQgBAAAAAAIAAiXIgpAAIgEgCQAAAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAIAAgXQAAAAAAAAQAAgBAAAAQABgBAAAAQAAgBAAAAQABAAAAgBQABAAAAAAQABAAAAAAQAAAAABAAIB1AAQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAIABADIAAAXIgBADIgEACIgpAAIAACXIgCADQAAAAgBABQAAAAAAAAQgBAAAAAAQgBABAAAAg");
	this.shape_13.setTransform(57.8,-0.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#0099CC").s().p("ABEBiIhwh8IAAB0QAAAAAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAABQgBAAAAAAQgBAAAAAAQgBABAAAAIgZAAQAAAAgBgBQAAAAgBAAQAAAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAAAIAAi1QAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAQABAAAAAAQABgBAAAAIAHAAIBwB3IAAhvQAAAAAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABAAQAAAAABAAIAZAAQAAAAABAAQAAAAABAAQAAAAAAAAQABABAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAAAIAAC1QAAABAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgBABAAAAg");
	this.shape_14.setTransform(40.6,-0.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#0099CC").s().p("Ag2BfQgBAAAAgBQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAAAIAAizQAAAAAAAAQAAgBAAAAQABgBAAAAQAAgBAAAAQABAAAAgBQABAAAAAAQABAAAAAAQAAAAABAAIBtAAQAAAAABAAQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAABABQAAAAAAABQAAAAAAAAIAAAXQAAAAAAABQAAAAAAABQgBAAAAABQAAAAgBAAIgDACIhPAAIAAAsIBCAAIAEACQAAAAAAABQAAAAABAAQAAABAAAAQAAABAAABIAAAUQAAABAAABQAAAAAAABQgBAAAAABQAAAAAAABQgBAAAAAAQgBAAAAABQgBAAAAAAQAAAAgBAAIhCAAIAAAvIBPAAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAAAQABABAAAAQAAABABAAQAAABAAAAQAAABAAAAIAAAXQAAAAAAAAQAAABAAAAQgBABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAQgBABAAAAg");
	this.shape_15.setTransform(22.7,-0.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#0099CC").s().p("AAjBfIgDgCIgBgBIgjhIIgfAAIAABGQAAAAAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAQAAABAAAAIgaAAQAAAAAAgBQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAAAIAAizQAAAAAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAQAAAAAAAAIBNAAQAQAAANAHQAOAIAHANQAJANgBAQQABATgMAPQgKANgSAHIAlBFQABADgBACQgCADgDAAgAgigIIArAAQALABAHgJQAIgIAAgLQAAgLgIgIQgHgHgLAAIgrAAg");
	this.shape_16.setTransform(5.8,-0.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#0099CC").s().p("AAjBfIgDgCIgBgBIgjhIIgfAAIAABGQAAAAAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAQAAABAAAAIgaAAQAAAAAAgBQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQgBAAAAAAIAAizQAAAAABAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAQAAAAAAAAIBNAAQAQAAAOAHQANAIAHANQAJANgBAQQABATgLAPQgLANgSAHIAlBFQABADgBACQgCADgDAAgAgigIIArAAQALABAHgJQAJgIgBgLQABgLgJgIQgHgHgLAAIgrAAg");
	this.shape_17.setTransform(-18.2,-0.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#0099CC").s().p("AgwBUQgWgNgNgVQgNgWAAgcQAAgaANgWQANgWAWgNQAVgNAbgBQAbABAWANQAWANANAWQANAWAAAaQAAAcgNAWQgNAVgWANQgWANgbABQgbgBgVgNgAgeg1QgOAJgIAOQgJAOAAAQQAAASAJAOQAIAOAOAIQAOAIAQAAQARAAAOgIQAOgIAJgOQAIgOAAgSQAAgQgIgOQgJgOgOgJQgOgIgRgBQgQABgOAIg");
	this.shape_18.setTransform(-38.5,-0.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#0099CC").s().p("Ag2BfQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAAAIAAizQAAAAAAAAQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQABAAAAAAQABAAAAAAIBtAAQABAAAAAAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAABABQAAAAAAABQAAAAAAAAIAAAXQAAAAAAABQAAAAAAABQgBAAAAABQAAAAAAAAIgEACIhPAAIAAAzIBCAAIADABQABAAAAABQAAAAABABQAAAAAAABQAAAAAAABIAAAVQAAAAAAABQAAAAAAABQgBAAAAABQAAAAgBAAQAAABAAAAQgBAAAAABQgBAAAAAAQgBAAAAAAIhCAAIAABFQAAAAAAAAQAAABAAAAQgBABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAQgBABAAAAg");
	this.shape_19.setTransform(-56.1,-0.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#0099CC").s().p("AgcBdQgNgEgHgFQgIgFgCgDIgDgDQgBgCACgDIAKgRQACgCACgBQADAAACACIAHAEIAQAIQAJAEAJAAQAKAAAGgGQAHgFAAgKQAAgKgIgIQgJgHgQgHQgNgFgLgIQgMgHgHgLQgHgLgBgQQAAgMAHgLQAGgMANgJQAOgHAVgBQANABALAEQALADAIAFIAKAFQACACABADQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAIgKAQIgFAEQgCABgDgBIgHgFIgPgHQgIgDgHAAQgHAAgFACQgGADgCAEQgDAFAAAEQAAAKAIAHQAHAHAQAGQANAGANAIQANAGAIAMQAJAMAAAQQAAAPgIAMQgHAMgOAHQgOAIgTAAQgQAAgMgEg");
	this.shape_20.setTransform(78.7,-29);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#0099CC").s().p("AgMBfQAAAAAAgBQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAgBIAAiWIgqAAIgDgCQgBAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAIAAgXQAAAAAAAAQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQABAAAAAAQABAAAAAAIB1AAQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAIABADIAAAXIgBADIgEACIgpAAIAACWIgCAEQAAAAgBABQAAAAAAAAQgBAAAAAAQgBABgBAAg");
	this.shape_21.setTransform(64.5,-29);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#0099CC").s().p("ABEBhIhwh7IAABzQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAQgBABAAAAIgZAAQAAAAgBgBQAAAAgBAAQAAAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAi1QAAAAAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAQABAAAAAAQABgBAAAAIAHAAIBwB3IAAhvQAAAAAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABAAQAAAAABAAIAZAAQAAAAABAAQAAAAABAAQAAAAAAAAQABABAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAAAIAAC2QAAAAAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgBAAAAAAg");
	this.shape_22.setTransform(47.3,-29);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#0099CC").s().p("Ag2BfQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAiyQAAAAAAAAQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQABAAAAAAQABAAAAAAIBtAAQABAAAAAAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAABABQAAAAAAABQAAAAAAAAIAAAXQAAAAAAABQAAAAAAABQgBAAAAABQAAAAAAAAIgEACIhPAAIAAAsIBCAAIADACQABAAAAABQAAAAABAAQAAABAAAAQAAABAAABIAAAUQAAABAAABQAAAAAAABQgBAAAAABQAAAAgBABQAAAAAAAAQgBAAAAABQgBAAAAAAQgBAAAAAAIhCAAIAAAvIBPAAQABAAAAAAQAAAAABAAQAAABABAAQAAAAABAAQAAABAAAAQAAABABAAQAAABAAAAQAAAAAAABIAAAWQAAABAAAAQAAABAAAAQgBABAAAAQAAABAAAAQgBAAAAABQgBAAAAAAQgBAAAAAAQAAABgBAAg");
	this.shape_23.setTransform(29.4,-29);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#0099CC").s().p("AgCBhIgCgBIgCgCIgwhpIAAAAIgBAAIgPBlIgCADQAAAAgBABQAAAAAAAAQgBAAAAAAQgBABAAAAIgYAAQgBAAgBgBQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAgBIAhi0IABgDQAAAAABgBQAAAAAAAAQABAAAAAAQABgBAAAAIAFAAIADACIABACIA7B+IAAAAIABAAIA7h+IACgCIACgCIAFAAQAAAAABABQAAAAABAAQAAAAABAAQAAABAAAAIACADIAgC0QAAABAAABQAAAAAAABQAAAAgBABQAAAAAAABQgBAAAAABQgBAAAAAAQgBAAAAAAQgBABAAAAIgZAAQAAAAgBgBQAAAAgBAAQAAAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAAAQgBAAAAgBQAAAAAAgBIgQhlIAAAAIgBAAIgvBpQAAAAAAABQAAAAgBAAQAAABAAAAQAAAAgBAAIgDABg");
	this.shape_24.setTransform(9.2,-29);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#0099CC").s().p("AgLBfQgBAAAAgBQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQgBAAAAgBIAAiWIgpAAIgEgCQAAAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAIAAgXQAAAAAAAAQAAgBAAAAQABgBAAAAQAAgBAAAAQABAAAAgBQABAAAAAAQABAAAAAAQABAAAAAAIB1AAQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAIABADIAAAXIgBADIgEACIgpAAIAACWIgCAEQAAAAgBABQAAAAAAAAQgBAAAAAAQgBABgBAAg");
	this.shape_25.setTransform(-9.4,-29);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#0099CC").s().p("AAjBfIgDgBIgCgCIgjhHIgdAAIAABEQAAABgBAAQAAABAAAAQAAABAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAQAAABgBAAIgZAAQAAAAAAgBQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAgBIAAiyQAAAAAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAQAAAAAAAAIBNAAQARgBAMAJQAOAHAIANQAHANAAAQQAAAUgLAOQgLANgRAHIAkBFQACADgBACQgCACgDABgAgigIIArAAQALAAAIgIQAHgHABgMQgBgLgHgIQgIgHgLAAIgrAAg");
	this.shape_26.setTransform(-24.6,-29);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#0099CC").s().p("AA9BgQgDAAgBgCIgDgDIgOgeIhQAAIgMAeIgEADQgCACgCAAIgYAAQgBAAAAAAQgBAAgBAAQAAgBgBAAQAAAAAAgBQgBgCABgDIBTi1IACgCIADgBIACAAIADABIABACIBUC1QABADgBACQgBABAAAAQgBAAAAABQgBAAgBAAQAAAAgBAAgAAbAfIgbg6IAAAAIgaA6IA1AAg");
	this.shape_27.setTransform(-43.1,-29.1);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#0099CC").s().p("Ag6BfQgBAAAAgBQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQgBAAAAgBIAAiyQAAAAABAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABAAIA+AAQARgBANAJQAOAHAJAOQAHAOAAAQQAAARgHAOQgJANgOAHQgNAJgQAAIgiAAIAAA/QAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAQAAABgBAAgAgdgGIAfAAQALAAAJgIQAHgIABgMQgBgMgHgHQgJgHgLgBIgfAAg");
	this.shape_28.setTransform(-59.1,-29);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#0099CC").s().p("AA+BgQgDAAgDgCIgCgDIgOgeIhQAAIgNAeIgCADQgCACgEAAIgXAAQgBAAAAAAQgBAAgBAAQAAgBgBAAQAAAAgBgBQAAgCAAgDIBUi1IACgCIADgBIABAAIAEABIACACIBTC1QAAADAAACQgBABAAAAQgBAAAAABQgBAAgBAAQAAAAgBAAgAAbAfIgbg6IAAAAIgaA6IA1AAg");
	this.shape_29.setTransform(-77,-29.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.txt1, new cjs.Rectangle(-125.6,-49.9,251.2,99.8), null);


(lib.pc2_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.pc1();
	this.instance.parent = this;
	this.instance.setTransform(-238,-133.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.pc2_1, new cjs.Rectangle(-238,-133.5,476,267), null);


(lib.pc1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.pc2();
	this.instance.parent = this;
	this.instance.setTransform(-165,-109.3,0.819,0.819);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.pc1_1, new cjs.Rectangle(-165,-109.3,330,218.7), null);


(lib.logo_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.logo();
	this.instance.parent = this;
	this.instance.setTransform(-33.5,-57.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.logo_1, new cjs.Rectangle(-33.5,-57.5,67,115), null);


(lib.Анимация8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgOBIQgFgGgBgJQABgJAFgGQAGgGAIAAQAIAAAHAGQAGAGAAAJQAAAJgGAGQgHAGgIAAQgIAAgGgGgAgEAQIgDgBIgBgDIgKg8IAAgZIABgDIACgBIAfAAIADABIAAADIAAAZIgKA8IgBADIgEABg");
	this.shape.setTransform(80.1,-0.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAsBQIgCgBIgCgCIgohZIAAAAIgoBZIgBACIgCABIgEAAIgCgBIgCgDIgpiTQAAAAAAgBQgBAAAAgBQABAAAAgBQAAAAAAAAQABgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAaAAIADABIABACIATBJIABAAIAihMIACgCIACgBIADAAIACABIACACIAiBMIAAAAIAThJIACgCIACgBIAaAAQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAAAQAAABAAAAQABABAAAAQgBABAAAAIgpCTIgCADIgCABg");
	this.shape_1.setTransform(66.8,-0.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgnBFQgSgLgKgRQgLgTAAgWQAAgVALgSQAKgSASgKQASgLAVgBQAWABASALQASAKAKASQALASAAAVQAAAWgLATQgKARgSALQgSAKgWABQgVgBgSgKgAgVglQgKAGgGAKQgGAKAAALQAAAMAGAKQAGAKAKAGQAKAGALAAQAMAAAKgGQAKgGAGgKQAGgKAAgMQAAgLgGgKQgGgKgKgGQgKgGgMAAQgLAAgKAGg");
	this.shape_2.setTransform(48.2,-0.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AA7BQIgCgBIgBgBIhWhXIAABSIgBADIgDABIgbAAIgDgBIgBgDIAAiTIABgDQABAAAAgBQAAAAABAAQAAAAAAAAQABgBAAAAIAGAAIBWBUIABAAIAAhNIABgDIADgBIAaAAIADABIABADIAACUIgBACIgDACg");
	this.shape_3.setTransform(31,-0.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAYBNIgDAAIgBgCIgcg6IgQAAIAAA4QAAAAAAABQAAAAAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgbAAIgDgBIgBgDIAAiRIABgDIADgBIBBAAQAOAAAKAGQALAHAHAKQAFAMABANQAAAPgKAMQgIAKgOAGIAdA4QABAAAAABQAAAAAAABQAAAAAAABQAAABgBAAQAAAAAAABQgBAAAAAAQgBABAAAAQgBAAAAAAgAgYgKIAgAAQAHAAAFgGQAEgEABgIQgBgHgEgEQgFgGgHAAIggAAg");
	this.shape_4.setTransform(10.8,-0.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgtBNIgDgBIgBgDIAAiRIABgDIADgBIBaAAIADABIACADIAAAYQAAAAAAABQAAAAgBABQAAAAAAAAQAAABgBAAIgDABIg8AAIAAAbIAyAAQAAAAAAABQABAAAAAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAAAQABABAAAAQAAAAAAABIAAAWQAAABAAAAQAAABgBAAQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAABQAAAAgBAAQAAAAAAAAIgyAAIAAAdIA8AAIADACQABAAAAABQAAAAAAAAQABABAAAAQAAAAAAABIAAAYQAAAAAAABQAAAAgBAAQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_5.setTransform(-3.1,-0.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgMBNQAAAAgBAAQAAAAgBAAQAAgBAAAAQgBAAAAAAIgBgDIAAh1IggAAIgDgBIgBgDIAAgYIABgDIADgBIBhAAIADABIABADIAAAYIgBADIgDABIgfAAIAAB1QAAAAgBABQAAAAAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_6.setTransform(-15.5,-0.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgXBMQgLgDgGgEIgIgHIgDgCIABgEIALgSQAAAAABgBQAAAAAAAAQABgBABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAAAIAFAEIAMAFQAHADAHABQAGAAAEgEQAEgEABgGQAAgGgGgGQgGgGgKgEQgKgEgKgGQgJgFgHgKQgGgJgBgOQAAgLAGgJQAGgKALgHQALgGARgBQALABAJADQAJADAHAEIAKAGIACAEIgBADIgLARIgDADQgBAAAAAAQgBABAAAAQgBAAAAgBQgBAAAAAAIgGgEIgMgGQgHgDgGAAQgGAAgEADQgDAEAAAEQgBAGAGAFQAGAFALAFIAPAHQAHAEAHAFQAHAGAEAIQAFAJAAALQAAALgGAKQgHALgLAGQgMAHgQABQgNgBgKgDg");
	this.shape_7.setTransform(-27.1,-0.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgMBNIgDgBIgBgDIAAiRIABgDIADgBIAZAAIADABIABADIAACRIgBADIgDABg");
	this.shape_8.setTransform(-36.8,-0.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgcBFQgRgLgLgSQgKgSAAgWQAAgVAKgSQALgSARgKQASgLAWAAQAOAAAOAFQAOAGALAKIACACQAAABAAAAQAAABAAAAQgBAAAAABQAAAAAAAAIgSATIgDABIgDgBQgGgGgIgCQgHgCgHgBQgMABgKAGQgJAGgGAKQgGAKAAALQAAAMAGAKQAGAKAJAGQAKAGAMAAIAKgBIAJgCIAAgOIgOAAIgDgBQAAAAAAAAQAAAAgBgBQAAAAAAgBQAAAAAAAAIAAgWQAAAAAAgBQAAAAAAgBQABAAAAAAQAAAAAAAAQABAAAAgBQAAAAABAAQAAAAABAAQAAAAAAAAIAsAAIAEABIABACIAAA7IgBACIgBACIgHAEQgHADgMAEQgNACgPABQgWAAgSgKg");
	this.shape_9.setTransform(-48.3,-0.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgtBNIgDgBIgBgDIAAiRIABgDIADgBIBaAAIADABIACADIAAAYQAAAAAAABQAAAAgBABQAAAAAAAAQAAABgBAAIgDABIg8AAIAAAbIAyAAQAAAAAAABQABAAAAAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAAAQABABAAAAQAAAAAAABIAAAWQAAABAAAAQAAABgBAAQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAABQAAAAgBAAQAAAAAAAAIgyAAIAAAdIA8AAIADACQABAAAAABQAAAAAAAAQABABAAAAQAAAAAAABIAAAYQAAAAAAABQAAAAgBAAQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_10.setTransform(-61.9,-0.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAXBNIgCAAIgBgCIgcg6IgQAAIAAA4QAAAAAAABQAAAAAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgbAAIgDgBIgBgDIAAiRIABgDIADgBIBBAAQANAAALAGQALAHAHAKQAFAMABANQAAAPgKAMQgIAKgOAGIAdA4QABAAAAABQAAAAAAABQAAAAAAABQAAABgBAAQAAAAAAABQgBAAAAAAQAAABgBAAQgBAAAAAAgAgYgKIAgAAQAHAAAFgGQAEgEABgIQgBgHgEgEQgFgGgHAAIggAAg");
	this.shape_11.setTransform(-75.7,-0.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-85.6,-17.7,171.2,35.5);


(lib.Анимация7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgOBIQgFgGgBgJQABgJAFgGQAGgGAIAAQAIAAAHAGQAGAGAAAJQAAAJgGAGQgHAGgIAAQgIAAgGgGgAgEAQIgDgBIgBgDIgKg8IAAgZIABgDIACgBIAfAAIADABIAAADIAAAZIgKA8IgBADIgEABg");
	this.shape.setTransform(80.1,-0.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAsBQIgCgBIgCgCIgohZIAAAAIgoBZIgBACIgCABIgEAAIgCgBIgCgDIgpiTQAAAAAAgBQgBAAAAgBQABAAAAgBQAAAAAAAAQABgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAaAAIADABIABACIATBJIABAAIAihMIACgCIACgBIADAAIACABIACACIAiBMIAAAAIAThJIACgCIACgBIAaAAQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAAAQAAABAAAAQABABAAAAQgBABAAAAIgpCTIgCADIgCABg");
	this.shape_1.setTransform(66.8,-0.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgnBFQgSgLgKgRQgLgTAAgWQAAgVALgSQAKgSASgKQASgLAVgBQAWABASALQASAKAKASQALASAAAVQAAAWgLATQgKARgSALQgSAKgWABQgVgBgSgKgAgVglQgKAGgGAKQgGAKAAALQAAAMAGAKQAGAKAKAGQAKAGALAAQAMAAAKgGQAKgGAGgKQAGgKAAgMQAAgLgGgKQgGgKgKgGQgKgGgMAAQgLAAgKAGg");
	this.shape_2.setTransform(48.2,-0.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AA7BQIgCgBIgBgBIhWhXIAABSIgBADIgDABIgbAAIgDgBIgBgDIAAiTIABgDQABAAAAgBQAAAAABAAQAAAAAAAAQABgBAAAAIAGAAIBWBUIABAAIAAhNIABgDIADgBIAaAAIADABIABADIAACUIgBACIgDACg");
	this.shape_3.setTransform(31,-0.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAYBNIgDAAIgBgCIgcg6IgQAAIAAA4QAAAAAAABQAAAAAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgbAAIgDgBIgBgDIAAiRIABgDIADgBIBBAAQAOAAAKAGQALAHAHAKQAFAMABANQAAAPgKAMQgIAKgOAGIAdA4QABAAAAABQAAAAAAABQAAAAAAABQAAABgBAAQAAAAAAABQgBAAAAAAQgBABAAAAQgBAAAAAAgAgYgKIAgAAQAHAAAFgGQAEgEABgIQgBgHgEgEQgFgGgHAAIggAAg");
	this.shape_4.setTransform(10.8,-0.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgtBNIgDgBIgBgDIAAiRIABgDIADgBIBaAAIADABIACADIAAAYQAAAAAAABQAAAAgBABQAAAAAAAAQAAABgBAAIgDABIg8AAIAAAbIAyAAQAAAAAAABQABAAAAAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAAAQABABAAAAQAAAAAAABIAAAWQAAABAAAAQAAABgBAAQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAABQAAAAgBAAQAAAAAAAAIgyAAIAAAdIA8AAIADACQABAAAAABQAAAAAAAAQABABAAAAQAAAAAAABIAAAYQAAAAAAABQAAAAgBAAQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_5.setTransform(-3.1,-0.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgMBNQAAAAgBAAQAAAAgBAAQAAgBAAAAQgBAAAAAAIgBgDIAAh1IggAAIgDgBIgBgDIAAgYIABgDIADgBIBhAAIADABIABADIAAAYIgBADIgDABIgfAAIAAB1QAAAAgBABQAAAAAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_6.setTransform(-15.5,-0.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgXBMQgLgDgGgEIgIgHIgDgCIABgEIALgSQAAAAABgBQAAAAAAAAQABgBABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAAAIAFAEIAMAFQAHADAHABQAGAAAEgEQAEgEABgGQAAgGgGgGQgGgGgKgEQgKgEgKgGQgJgFgHgKQgGgJgBgOQAAgLAGgJQAGgKALgHQALgGARgBQALABAJADQAJADAHAEIAKAGIACAEIgBADIgLARIgDADQgBAAAAAAQgBABAAAAQgBAAAAgBQgBAAAAAAIgGgEIgMgGQgHgDgGAAQgGAAgEADQgDAEAAAEQgBAGAGAFQAGAFALAFIAPAHQAHAEAHAFQAHAGAEAIQAFAJAAALQAAALgGAKQgHALgLAGQgMAHgQABQgNgBgKgDg");
	this.shape_7.setTransform(-27.1,-0.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgMBNIgDgBIgBgDIAAiRIABgDIADgBIAZAAIADABIABADIAACRIgBADIgDABg");
	this.shape_8.setTransform(-36.8,-0.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgcBFQgRgLgLgSQgKgSAAgWQAAgVAKgSQALgSARgKQASgLAWAAQAOAAAOAFQAOAGALAKIACACQAAABAAAAQAAABAAAAQgBAAAAABQAAAAAAAAIgSATIgDABIgDgBQgGgGgIgCQgHgCgHgBQgMABgKAGQgJAGgGAKQgGAKAAALQAAAMAGAKQAGAKAJAGQAKAGAMAAIAKgBIAJgCIAAgOIgOAAIgDgBQAAAAAAAAQAAAAgBgBQAAAAAAgBQAAAAAAAAIAAgWQAAAAAAgBQAAAAAAgBQABAAAAAAQAAAAAAAAQABAAAAgBQAAAAABAAQAAAAABAAQAAAAAAAAIAsAAIAEABIABACIAAA7IgBACIgBACIgHAEQgHADgMAEQgNACgPABQgWAAgSgKg");
	this.shape_9.setTransform(-48.3,-0.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgtBNIgDgBIgBgDIAAiRIABgDIADgBIBaAAIADABIACADIAAAYQAAAAAAABQAAAAgBABQAAAAAAAAQAAABgBAAIgDABIg8AAIAAAbIAyAAQAAAAAAABQABAAAAAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAAAQABABAAAAQAAAAAAABIAAAWQAAABAAAAQAAABgBAAQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAABQAAAAgBAAQAAAAAAAAIgyAAIAAAdIA8AAIADACQABAAAAABQAAAAAAAAQABABAAAAQAAAAAAABIAAAYQAAAAAAABQAAAAgBAAQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_10.setTransform(-61.9,-0.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAXBNIgCAAIgBgCIgcg6IgQAAIAAA4QAAAAAAABQAAAAAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgbAAIgDgBIgBgDIAAiRIABgDIADgBIBBAAQANAAALAGQALAHAHAKQAFAMABANQAAAPgKAMQgIAKgOAGIAdA4QABAAAAABQAAAAAAABQAAAAAAABQAAABgBAAQAAAAAAABQgBAAAAAAQAAABgBAAQgBAAAAAAgAgYgKIAgAAQAHAAAFgGQAEgEABgIQgBgHgEgEQgFgGgHAAIggAAg");
	this.shape_11.setTransform(-75.7,-0.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-85.6,-17.7,171.2,35.5);


// stage content:
(lib.SouthCitySq_AdWords_300x250 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgNBIQgHgGAAgJQAAgJAHgGQAFgGAIAAQAJAAAFAGQAHAGAAAJQAAAJgHAGQgFAGgJAAQgIAAgFgGgAgEAQIgCgBIgBgDIgMg8IAAgZIABgDIAEgBIAdAAIAEABIABADIAAAZIgLA8IgCADIgCABg");
	this.shape.setTransform(264.2,231.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAsBPIgCAAIgCgCIgohZIAAAAIgoBZIgBACIgCAAIgEAAIgCAAIgCgDIgpiTQAAAAAAgBQgBAAAAgBQABAAAAgBQAAAAAAAAQABgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAaAAIADABIABACIATBJIABAAIAihMIACgCIACgBIADAAIACABIACACIAiBMIAAAAIAThJIACgCIACgBIAaAAQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAAAQAAABAAAAQABABAAAAQgBABAAAAIgpCTIgCADIgCAAg");
	this.shape_1.setTransform(250.9,231);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgnBFQgSgLgKgRQgLgTAAgWQAAgVALgSQAKgSASgKQASgLAVgBQAWABASALQASAKAKASQALASAAAVQAAAWgLATQgKARgSALQgSAKgWAAQgVAAgSgKgAgVglQgKAGgGAKQgGAKAAALQAAAMAGAKQAGAKAKAGQAKAGALAAQAMAAAKgGQAKgGAGgKQAGgKAAgMQAAgLgGgKQgGgKgKgGQgKgGgMAAQgLAAgKAGg");
	this.shape_2.setTransform(232.3,231);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AA7BPIgCAAIgBgBIhWhXIAABSIgBADIgDABIgbAAIgDgBIgBgDIAAiTIABgDQAAAAABgBQAAAAABAAQAAAAAAAAQABgBAAAAIAGAAIBWBUIABAAIAAhNIABgDIADgBIAaAAIADABIABADIAACUIgBACIgDABg");
	this.shape_3.setTransform(215.1,231);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAXBNIgBAAIgCgCIgdg6IgOAAIAAA4QAAAAgBABQAAAAAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAIgaAAIgDgBIgBgDIAAiRIABgDIADgBIBBAAQANAAALAGQALAHAGAKQAHAMAAANQAAAPgJAMQgJAKgPAGIAfA4QAAAAAAABQAAAAAAABQAAAAAAABQAAABAAAAQgBAAAAABQAAAAgBAAQAAABgBAAQgBAAgBAAgAgXgKIAfAAQAHAAAFgGQAFgEAAgIQAAgHgFgEQgFgGgHAAIgfAAg");
	this.shape_4.setTransform(194.9,231);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgtBNIgDgBIgBgDIAAiRIABgDIADgBIBaAAIADABIACADIAAAYQAAAAAAABQAAAAgBABQAAAAAAAAQAAABgBAAIgDABIg8AAIAAAbIAyAAQAAAAAAABQABAAAAAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAAAQABABAAAAQAAAAAAABIAAAWQAAABAAAAQAAABgBAAQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAABQAAAAgBAAQAAAAAAAAIgyAAIAAAdIA8AAIADACQABAAAAABQAAAAAAAAQABABAAAAQAAAAAAABIAAAYQAAAAAAABQAAAAgBAAQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_5.setTransform(181,231);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgMBNQgBAAAAAAQAAAAgBAAQAAgBAAAAQgBAAAAAAIgCgDIAAh1IgfAAIgDgBIgBgDIAAgYIABgDIADgBIBhAAIADABIABADIAAAYIgBADIgDABIggAAIAAB1QAAAAAAABQAAAAAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAAAABQAAAAgBAAQAAAAAAAAg");
	this.shape_6.setTransform(168.6,231);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgXBMQgLgDgGgEIgIgHIgDgCIABgEIALgSQAAAAABgBQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAAAIAFAEIAMAFQAHADAHABQAGAAAEgEQAEgEABgGQAAgGgGgGQgGgGgKgEQgKgEgKgGQgJgFgHgKQgGgJgBgOQAAgLAGgJQAGgKALgHQALgGARgBQALABAJADQAJADAHAEIAKAGIACAEIgBADIgLARIgDADQgBAAAAAAQgBABgBAAQAAAAAAgBQgBAAAAAAIgGgEIgMgGQgHgDgGAAQgGAAgEADQgDAEAAAEQgBAGAGAFQAGAFALAFIAPAHQAHAEAHAFQAHAGAEAIQAFAJAAALQAAALgGAKQgHALgLAGQgMAHgQAAQgNAAgKgDg");
	this.shape_7.setTransform(157,231);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgMBNIgDgBIgBgDIAAiRIABgDIADgBIAZAAIADABIABADIAACRIgBADIgDABg");
	this.shape_8.setTransform(147.3,231);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgbBFQgTgLgKgSQgLgSAAgWQAAgVALgSQAKgSATgKQARgLAVAAQAOAAAOAFQAOAGAMAKIABACQABABAAAAQAAABgBAAQAAAAAAABQAAAAgBAAIgRATIgDABIgDgBQgGgGgIgCQgHgCgIgBQgMABgIAGQgKAGgGAKQgGAKAAALQAAAMAGAKQAGAKAKAGQAIAGAMAAIAKgBIAKgCIAAgOIgOAAIgCgBQgBAAAAAAQAAAAgBgBQAAAAAAgBQAAAAAAAAIAAgWQAAAAAAgBQAAAAAAgBQABAAAAAAQAAAAABAAQAAAAAAgBQAAAAABAAQAAAAABAAQAAAAAAAAIAtAAIACABIABACIAAA7IAAACIgBACIgHAEQgHADgMAEQgNACgQABQgVAAgRgKg");
	this.shape_9.setTransform(135.8,231);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgtBNIgDgBIgBgDIAAiRIABgDIADgBIBaAAIADABIACADIAAAYQAAAAAAABQAAAAgBABQAAAAAAAAQAAABgBAAIgDABIg8AAIAAAbIAyAAQAAAAAAABQABAAAAAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAAAQABABAAAAQAAAAAAABIAAAWQAAABAAAAQAAABgBAAQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAABQAAAAgBAAQAAAAAAAAIgyAAIAAAdIA8AAIADACQABAAAAABQAAAAAAAAQABABAAAAQAAAAAAABIAAAYQAAAAAAABQAAAAgBAAQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_10.setTransform(122.2,231);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAXBNIgBAAIgCgCIgdg6IgOAAIAAA4QAAAAgBABQAAAAAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAIgaAAIgDgBIgBgDIAAiRIABgDIADgBIBBAAQANAAALAGQALAHAGAKQAHAMAAANQAAAPgJAMQgJAKgPAGIAfA4QAAAAAAABQAAAAAAABQAAAAAAABQAAABAAAAQgBAAAAABQAAAAgBAAQgBABAAAAQgBAAgBAAgAgXgKIAfAAQAHAAAFgGQAEgEABgIQgBgHgEgEQgFgGgHAAIgfAAg");
	this.shape_11.setTransform(108.4,231);

	this.instance = new lib.Анимация7("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(184.1,231.3);
	this.instance._off = true;

	this.instance_1 = new lib.Анимация8("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(195.1,231.3);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.instance}]},201).to({state:[{t:this.instance_1}]},16).to({state:[{t:this.instance_1}]},69).to({state:[{t:this.instance}]},9).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.instance).wait(201).to({_off:false},0).to({_off:true,x:195.1},16).wait(69).to({_off:false,x:184.1},9).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(201).to({_off:false},16).wait(69).to({startPosition:0},0).to({_off:true,x:184.1},9).wait(1));

	// logo
	this.instance_2 = new lib.logo_1();
	this.instance_2.parent = this;
	this.instance_2.setTransform(51.4,211.5,0.67,0.67);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(201).to({scaleX:1,scaleY:1,x:55.5,y:192.5},16).wait(69).to({scaleX:0.67,scaleY:0.67,x:51.4,y:211.5},9).wait(1));

	// Слой 1
	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#0099CC").s().p("A3bDIIAAmPMAu3AAAIAAGPg");
	this.shape_12.setTransform(150,124.5,1,6.275);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#0099CC").s().p("A3bTaMAAAgmzMAu3AAAMAAAAmzg");
	this.shape_13.setTransform(150,125.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#0099CC").s().p("A3bSzMAAAgllMAu3AAAMAAAAllg");
	this.shape_14.setTransform(150,129.8);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#0099CC").s().p("A3bRyMAAAgjjMAu3AAAMAAAAjjg");
	this.shape_15.setTransform(150,136.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#0099CC").s().p("A3bQXMAAAggtMAu3AAAMAAAAgtg");
	this.shape_16.setTransform(150,145.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#0099CC").s().p("A3bOhIAA9BMAu3AAAIAAdBg");
	this.shape_17.setTransform(150,157.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#0099CC").s().p("A3bMSIAA4jMAu3AAAIAAYjg");
	this.shape_18.setTransform(150,171.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#0099CC").s().p("A3bJpIAAzRMAu3AAAIAATRg");
	this.shape_19.setTransform(150,188.3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#0099CC").s().p("A3bGmIAAtLMAu3AAAIAANLg");
	this.shape_20.setTransform(150,207.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_12,p:{scaleY:6.275,y:124.5}}]}).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_12,p:{scaleY:1,y:230}}]},1).to({state:[{t:this.shape_12,p:{scaleY:1,y:230}}]},277).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_12,p:{scaleY:6.275,y:124.5}}]},1).wait(1));

	// Слой 9
	this.instance_3 = new lib.txt2();
	this.instance_3.parent = this;
	this.instance_3.setTransform(203.6,161.8);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(201).to({_off:false},0).to({x:142.6,alpha:1},16).wait(79));

	// Слой 13
	this.instance_4 = new lib.txt1();
	this.instance_4.parent = this;
	this.instance_4.setTransform(152.2,349.5);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(183).to({_off:false},0).to({y:66.5},18).wait(95));

	// Слой 12
	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("rgba(0,0,0,0.247)").s().p("A3sVNMAAAgg8IXupdIXoI0MAADAhlg");
	this.shape_21.setTransform(150.8,355.7);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("rgba(0,0,0,0.278)").s().p("A3sVNMAAAgg8IXupdIXoI0MAADAhlg");
	this.shape_22.setTransform(150.8,340.2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("rgba(0,0,0,0.31)").s().p("A3sVNMAAAgg8IXupdIXoIzMAADAhmg");
	this.shape_23.setTransform(150.8,324.6);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("rgba(0,0,0,0.341)").s().p("A3sVNMAAAgg8IXupdIXoIzMAADAhmg");
	this.shape_24.setTransform(150.8,309.1);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("rgba(0,0,0,0.369)").s().p("A3sVNMAAAgg8IXupdIXoIzMAADAhmg");
	this.shape_25.setTransform(150.8,293.5);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("rgba(0,0,0,0.4)").s().p("A3sVNMAAAgg8IXupdIXoIzMAADAhmg");
	this.shape_26.setTransform(150.8,277.9);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("rgba(0,0,0,0.431)").s().p("A3sVNMAAAgg8IXupdIXoIzMAADAhmg");
	this.shape_27.setTransform(150.8,262.4);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("rgba(0,0,0,0.463)").s().p("A3sVNMAAAgg8IXupdIXoI0MAADAhlg");
	this.shape_28.setTransform(150.8,246.8);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("rgba(0,0,0,0.494)").s().p("A3sVNMAAAgg8IXupdIXoI0MAADAhlg");
	this.shape_29.setTransform(150.8,231.3);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("rgba(0,0,0,0.525)").s().p("A3sVNMAAAgg8IXupdIXoIzMAADAhmg");
	this.shape_30.setTransform(150.8,215.7);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("rgba(0,0,0,0.553)").s().p("A3sVNMAAAgg8IXupdIXoIzMAADAhmg");
	this.shape_31.setTransform(150.8,200.2);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("rgba(0,0,0,0.584)").s().p("A3sVNMAAAgg8IXupdIXoIzMAADAhmg");
	this.shape_32.setTransform(150.8,184.6);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("rgba(0,0,0,0.616)").s().p("A3sVNMAAAgg8IXupdIXoI0MAADAhlg");
	this.shape_33.setTransform(150.8,169.1);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("rgba(0,0,0,0.647)").s().p("A3sVNMAAAgg8IXupdIXoI0MAADAhlg");
	this.shape_34.setTransform(150.8,153.5);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("rgba(0,0,0,0.678)").s().p("A3sVNMAAAgg8IXupdIXoI0MAADAhlg");
	this.shape_35.setTransform(150.8,137.9);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("rgba(0,0,0,0.706)").s().p("A3sVNMAAAgg8IXupdIXoI0MAADAhlg");
	this.shape_36.setTransform(150.8,122.4);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("rgba(0,0,0,0.737)").s().p("A3sVNMAAAgg8IXupdIXoIzMAADAhmg");
	this.shape_37.setTransform(150.8,106.8);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("rgba(0,0,0,0.769)").s().p("A3sVNMAAAgg8IXupdIXoIzMAADAhmg");
	this.shape_38.setTransform(150.8,91.3);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("rgba(0,0,0,0.8)").s().p("A3sVNMAAAgg8IXupdIXoIzMAADAhmg");
	this.shape_39.setTransform(150.8,75.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_21}]},183).to({state:[{t:this.shape_22}]},1).to({state:[{t:this.shape_23}]},1).to({state:[{t:this.shape_24}]},1).to({state:[{t:this.shape_25}]},1).to({state:[{t:this.shape_26}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_28}]},1).to({state:[{t:this.shape_29}]},1).to({state:[{t:this.shape_30}]},1).to({state:[{t:this.shape_31}]},1).to({state:[{t:this.shape_32}]},1).to({state:[{t:this.shape_33}]},1).to({state:[{t:this.shape_34}]},1).to({state:[{t:this.shape_35}]},1).to({state:[{t:this.shape_36}]},1).to({state:[{t:this.shape_37}]},1).to({state:[{t:this.shape_38}]},1).to({state:[{t:this.shape_39}]},1).wait(95));

	// Layer 1
	this.instance_5 = new lib.txt1();
	this.instance_5.parent = this;
	this.instance_5.setTransform(152.2,129.5);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(48).to({_off:false},0).to({y:99.5,alpha:1},16).wait(65).to({y:-110.5},17).to({_off:true},1).wait(149));

	// Слой 11 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_129 = new cjs.Graphics().p("A3sVNMAAAgg8IXupdIXoI0MAADAhlg");
	var mask_graphics_130 = new cjs.Graphics().p("A3sVNMAAAgg8IXupdIXoI0MAADAhlg");
	var mask_graphics_131 = new cjs.Graphics().p("A3sVNMAAAgg8IXupdIXoIzMAADAhmg");
	var mask_graphics_132 = new cjs.Graphics().p("A3sVNMAAAgg8IXupdIXoI0MAADAhlg");
	var mask_graphics_133 = new cjs.Graphics().p("A3sVNMAAAgg8IXupdIXoIzMAADAhmg");
	var mask_graphics_134 = new cjs.Graphics().p("A3sVNMAAAgg8IXupdIXoI0MAADAhlg");
	var mask_graphics_135 = new cjs.Graphics().p("A3sVNMAAAgg8IXupdIXoI0MAADAhlg");
	var mask_graphics_136 = new cjs.Graphics().p("A3sVNMAAAgg8IXupdIXoIzMAADAhmg");
	var mask_graphics_137 = new cjs.Graphics().p("A3sVNMAAAgg8IXupdIXoI0MAADAhlg");
	var mask_graphics_138 = new cjs.Graphics().p("A3sVNMAAAgg8IXupdIXoIzMAADAhmg");
	var mask_graphics_139 = new cjs.Graphics().p("A3sVNMAAAgg8IXupdIXoI0MAADAhlg");
	var mask_graphics_140 = new cjs.Graphics().p("A3sVNMAAAgg8IXupdIXoIzMAADAhmg");
	var mask_graphics_141 = new cjs.Graphics().p("A3sVNMAAAgg8IXupdIXoIzMAADAhmg");
	var mask_graphics_142 = new cjs.Graphics().p("A3sVNMAAAgg8IXupdIXoI0MAADAhlg");
	var mask_graphics_143 = new cjs.Graphics().p("A3sVNMAAAgg8IXupdIXoIzMAADAhmg");
	var mask_graphics_144 = new cjs.Graphics().p("A3sVNMAAAgg8IXupdIXoI0MAADAhlg");
	var mask_graphics_145 = new cjs.Graphics().p("A3sVNMAAAgg8IXupdIXoIzMAADAhmg");
	var mask_graphics_146 = new cjs.Graphics().p("A3sVNMAAAgg8IXupdIXoIzMAADAhmg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(129).to({graphics:mask_graphics_129,x:150.8,y:355.7}).wait(1).to({graphics:mask_graphics_130,x:150.8,y:339.3}).wait(1).to({graphics:mask_graphics_131,x:150.8,y:322.8}).wait(1).to({graphics:mask_graphics_132,x:150.8,y:306.3}).wait(1).to({graphics:mask_graphics_133,x:150.8,y:289.8}).wait(1).to({graphics:mask_graphics_134,x:150.8,y:273.4}).wait(1).to({graphics:mask_graphics_135,x:150.8,y:256.9}).wait(1).to({graphics:mask_graphics_136,x:150.8,y:240.4}).wait(1).to({graphics:mask_graphics_137,x:150.8,y:224}).wait(1).to({graphics:mask_graphics_138,x:150.8,y:207.5}).wait(1).to({graphics:mask_graphics_139,x:150.8,y:191}).wait(1).to({graphics:mask_graphics_140,x:150.8,y:174.5}).wait(1).to({graphics:mask_graphics_141,x:150.8,y:158.1}).wait(1).to({graphics:mask_graphics_142,x:150.8,y:141.6}).wait(1).to({graphics:mask_graphics_143,x:150.8,y:125.1}).wait(1).to({graphics:mask_graphics_144,x:150.8,y:108.7}).wait(1).to({graphics:mask_graphics_145,x:150.8,y:92.2}).wait(1).to({graphics:mask_graphics_146,x:150.8,y:75.7}).wait(150));

	// Слой 10
	this.instance_6 = new lib.pc2_1();
	this.instance_6.parent = this;
	this.instance_6.setTransform(93,85.5);
	this.instance_6._off = true;

	var maskedShapeInstanceList = [this.instance_6];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(129).to({_off:false},0).to({scaleX:0.8,scaleY:0.8,x:183,y:106.5},166).wait(1));

	// Слой 7
	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("rgba(0,0,0,0.247)").s().p("A3sVNMAAAgg8IXupdIXoI0MAADAhlg");
	this.shape_40.setTransform(150.8,355.7);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("rgba(0,0,0,0.275)").s().p("A3sVNMAAAgg8IXupdIXoI0MAADAhlg");
	this.shape_41.setTransform(150.8,341.7);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("rgba(0,0,0,0.302)").s().p("A3sVNMAAAgg8IXupdIXoIzMAADAhmg");
	this.shape_42.setTransform(150.8,327.7);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("rgba(0,0,0,0.329)").s().p("A3sVNMAAAgg8IXupdIXoI0MAADAhlg");
	this.shape_43.setTransform(150.8,313.7);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("rgba(0,0,0,0.357)").s().p("A3sVNMAAAgg8IXupdIXoIzMAADAhmg");
	this.shape_44.setTransform(150.8,299.7);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("rgba(0,0,0,0.384)").s().p("A3sVNMAAAgg8IXupdIXoI0MAADAhlg");
	this.shape_45.setTransform(150.8,285.7);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("rgba(0,0,0,0.412)").s().p("A3sVNMAAAgg8IXupdIXoIzMAADAhmg");
	this.shape_46.setTransform(150.8,271.7);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("rgba(0,0,0,0.439)").s().p("A3sVNMAAAgg8IXupdIXoI0MAADAhlg");
	this.shape_47.setTransform(150.8,257.7);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("rgba(0,0,0,0.467)").s().p("A3sVNMAAAgg8IXupdIXoIzMAADAhmg");
	this.shape_48.setTransform(150.8,243.7);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("rgba(0,0,0,0.494)").s().p("A3sVNMAAAgg8IXupdIXoI0MAADAhlg");
	this.shape_49.setTransform(150.8,229.7);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("rgba(0,0,0,0.525)").s().p("A3sVNMAAAgg8IXupdIXoIzMAADAhmg");
	this.shape_50.setTransform(150.8,215.7);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("rgba(0,0,0,0.553)").s().p("A3sVNMAAAgg8IXupdIXoIzMAADAhmg");
	this.shape_51.setTransform(150.8,201.7);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("rgba(0,0,0,0.58)").s().p("A3sVNMAAAgg8IXupdIXoI0MAADAhlg");
	this.shape_52.setTransform(150.8,187.7);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("rgba(0,0,0,0.608)").s().p("A3sVNMAAAgg8IXupdIXoIzMAADAhmg");
	this.shape_53.setTransform(150.8,173.7);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("rgba(0,0,0,0.635)").s().p("A3sVNMAAAgg8IXupdIXoI0MAADAhlg");
	this.shape_54.setTransform(150.8,159.7);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("rgba(0,0,0,0.663)").s().p("A3sVNMAAAgg8IXupdIXoIzMAADAhmg");
	this.shape_55.setTransform(150.8,145.7);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("rgba(0,0,0,0.69)").s().p("A3sVNMAAAgg8IXupdIXoI0MAADAhlg");
	this.shape_56.setTransform(150.8,131.7);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("rgba(0,0,0,0.718)").s().p("A3sVNMAAAgg8IXupdIXoIzMAADAhmg");
	this.shape_57.setTransform(150.8,117.7);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("rgba(0,0,0,0.745)").s().p("A3sVNMAAAgg8IXupdIXoI0MAADAhlg");
	this.shape_58.setTransform(150.8,103.7);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("rgba(0,0,0,0.773)").s().p("A3sVNMAAAgg8IXupdIXoIzMAADAhmg");
	this.shape_59.setTransform(150.8,89.7);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("rgba(0,0,0,0.8)").s().p("A3sVNMAAAgg8IXupdIXoIzMAADAhmg");
	this.shape_60.setTransform(150.8,75.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_40}]},39).to({state:[{t:this.shape_41}]},1).to({state:[{t:this.shape_42}]},1).to({state:[{t:this.shape_43}]},1).to({state:[{t:this.shape_44}]},1).to({state:[{t:this.shape_45}]},1).to({state:[{t:this.shape_46}]},1).to({state:[{t:this.shape_47}]},1).to({state:[{t:this.shape_48}]},1).to({state:[{t:this.shape_49}]},1).to({state:[{t:this.shape_50}]},1).to({state:[{t:this.shape_51}]},1).to({state:[{t:this.shape_52}]},1).to({state:[{t:this.shape_53}]},1).to({state:[{t:this.shape_54}]},1).to({state:[{t:this.shape_55}]},1).to({state:[{t:this.shape_56}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_58}]},1).to({state:[{t:this.shape_59}]},1).to({state:[{t:this.shape_60}]},1).to({state:[]},87).wait(150));

	// pc-2.png
	this.instance_7 = new lib.pc1_1();
	this.instance_7.parent = this;
	this.instance_7.setTransform(153,108.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).to({scaleX:1.31,scaleY:1.31,y:88.2},129).to({_off:true},17).wait(150));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(138,124,330,251.1);
// library properties:
lib.properties = {
	width: 300,
	height: 250,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/SouthCitySq_AdWords_300x250_atlas_.png", id:"SouthCitySq_AdWords_300x250_atlas_"}
	],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;