(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"300x600TFHTML532_atlas_", frames: [[0,0,401,56]]}
];


// symbols:



(lib._160x600 = function() {
	this.initialize(img._160x600);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,600,1200);


(lib.logo = function() {
	this.initialize(ss["300x600TFHTML532_atlas_"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.t21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("AAdCGIgDgBQgBAAAAAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIgWiNIgCgBQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAABAAAAIgUCNIgCADIgDABIgpAAIgEgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAIg0kCQAAgBAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBIAEgBIAuAAIAEABIACAEIAWCJQAAAAAAABQAAAAAAAAQAAAAAAAAQAAAAABAAIABgBIAUiJIACgEIADgBIAmAAIAEABIABAEIAXCJIABABIABgBIAUiJIACgEIADgBIAtAAIAEABQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAABIgwECQAAABgBAAQAAABAAAAQAAABgBAAQAAAAAAAAIgDABg");
	this.shape.setTransform(295.775,76.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("Ag3B1QgVgUgBgjIAAh6QABgjAVgVQAUgUAjgBQAYABARAJQARAJAKARQAKARAAAYIAAB6QAAAXgKARQgKARgRAJQgRAKgYAAQgjAAgUgVgAgQhSQgGAHAAAMIAAB/QAAAMAGAIQAGAHAKAAQALAAAGgHQAHgIAAgMIAAh/QAAgMgHgHQgGgIgLAAQgKAAgGAIg");
	this.shape_1.setTransform(273.425,76.175);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#333333").s().p("AAcCGIgDgBIgCgCIgxiPIgBgBIgBABIAACOIAAADQgBAAAAABQgBAAAAAAQgBAAAAAAQgBAAAAAAIgsAAQgBAAAAAAQAAAAgBAAQAAAAgBAAQAAgBgBAAIgBgDIAAkDIABgEIAEgBIAwAAIADABIACAEIAxCOIABABIABgBIAAiOQAAgBAAAAQAAAAAAgBQABAAAAgBQAAAAABgBIADgBIAsAAIADABIABAEIAAEDIgBADQAAAAAAABQgBAAAAAAQgBAAAAAAQgBAAAAAAg");
	this.shape_2.setTransform(254.5,76.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#333333").s().p("AgmCBQgRgJgJgQQgJgPAAgVIAAgNQAAAAAAgBQAAAAAAAAQAAgBABAAQAAgBAAAAQAAAAABAAQAAgBAAAAQABAAAAAAQABAAAAAAIAsAAQABAAAAAAQABAAAAAAQABAAAAABQAAAAABAAQAAAAAAABQABAAAAABQAAAAAAAAQAAABAAAAIAAAKQAAAMAGAHQAGAHAIAAQAKAAAGgHQAGgGAAgMQAAgIgEgGQgEgHgIgHIgUgQQgPgKgOgMQgNgLgJgQQgJgQAAgWQAAgWAJgQQAJgQARgJQAQgIAWgBQAiABAUAUQAUAUABAhIAAAJQAAABAAAAQAAABgBAAQAAABAAAAQAAAAgBABQAAAAAAAAQgBABAAAAQAAAAgBAAQAAAAgBAAIgsAAQgBAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAgKQAAgMgGgHQgGgHgJAAQgJAAgFAHQgGAGAAAMQAAAIADAHQAEAGAHAHQAHAIAOAJQAUAPANALQAOAMAHAOQAHANAAATQAAAXgJAQQgKARgRAJQgQAJgXAAQgVAAgRgJg");
	this.shape_3.setTransform(228.425,76.175);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#333333").s().p("AhGCGQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAgBgBAAIgBgDIAAkDIABgEIAEgBIBFAAQAjABAVAUQAUAUABAiIAAB3QgBAigUAUQgVAUgjAAgAgUhXIgBACIAACrIABACIABAAIASAAQAJgBAHgIQAGgJAAgOIAAhvQAAgPgGgJQgGgIgLAAIgRAAIgBAAg");
	this.shape_4.setTransform(210.675,76.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#333333").s().p("AAcCHIgEgBIgCgDIgchqIgBgBIgBgBIgNAAIgCABIAAABIAABpIgBADQAAABgBAAQAAAAgBAAQAAABgBAAQAAAAgBAAIgtAAQAAAAgBAAQAAAAAAgBQgBAAAAAAQgBAAAAgBIgBgDIAAkDIABgDQAAgBABAAQAAAAABAAQAAgBAAAAQABAAAAAAIBNAAQAWAAAQALQAQAKAJASQAJASAAAYQAAAXgIASQgJAQgPAKIgCABIAAABIAkBxQAAABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAgBAAgAgXhWIAAABIAABCIAAABIACAAIARAAQALAAAIgJQAHgJAAgQQAAgRgHgJQgIgJgLAAIgRAAIgCABg");
	this.shape_5.setTransform(192.7583,76.175);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#333333").s().p("Ag3B1QgVgUgBgjIAAh6QABgjAVgVQAUgUAjgBQAYABARAJQARAJAKARQAKARAAAYIAAB6QAAAXgKARQgKARgRAJQgRAKgYAAQgjAAgUgVgAgQhSQgGAHAAAMIAAB/QAAAMAGAIQAGAHAKAAQALAAAGgHQAHgIAAgMIAAh/QAAgMgHgHQgGgIgLAAQgKAAgGAIg");
	this.shape_6.setTransform(174.125,76.175);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#333333").s().p("AgnCBQgRgKgKgRQgJgRgBgXIAAh7QABgYAJgQQAKgRARgJQARgJAWgBQAXABARAJQASAJAJARQAJAQABAYIAAAEQAAAAAAABQAAAAgBABQAAAAAAAAQAAABgBAAIgDABIgtACIgDgBQgBAAAAAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAgKQAAgLgGgHQgGgHgKAAQgJAAgGAHQgGAHAAALIAACEQAAALAGAHQAGAGAJAAQAKAAAGgGQAGgHAAgLIAAgLQAAAAAAgBQAAAAABAAQAAgBAAAAQAAAAABgBQAAAAABAAQAAgBAAAAQABAAAAAAQABAAAAAAIAtACIADABQABAAAAAAQAAABAAAAQABABAAAAQAAABAAAAIAAAEQgBAXgJARQgJARgSAKQgRAJgXAAQgWAAgRgJg");
	this.shape_7.setTransform(156.175,76.175);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#333333").s().p("AhBCGQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAgBAAAAIgBgDIAAkDIABgEIADgBICDAAIADABQAAABABAAQAAABAAAAQAAABAAAAQAAAAAAABIAAAmQAAAAAAAAQAAABAAAAQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAIhQAAIgBAAIAAACIAAA8IAAACIABABIAtAAQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAIABADIAAAkIgBAEQAAAAgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAIgtAAIgBABIAAABIAAA9IAAACIABAAIBQAAQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABQAAAAAAAAIAAAmQAAAAAAABQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgBAAAAAAg");
	this.shape_8.setTransform(139.15,76.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#333333").s().p("AAcCHIgEgBIgCgDIgchqIgBgBIgBgBIgNAAIgCABIAAABIAABpIgBADQAAABgBAAQAAAAgBAAQAAABgBAAQAAAAgBAAIgtAAQAAAAgBAAQAAAAAAgBQgBAAAAAAQgBAAAAgBIgBgDIAAkDIABgDQAAgBABAAQAAAAABAAQAAgBAAAAQABAAAAAAIBNAAQAWAAAQALQAQAKAJASQAJASAAAYQAAAXgIASQgJAQgPAKIgCABIAAABIAkBxQAAABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAgBAAgAgXhWIAAABIAABCIAAABIACAAIARAAQALAAAIgJQAHgJAAgQQAAgRgHgJQgIgJgLAAIgRAAIgCABg");
	this.shape_9.setTransform(121.7583,76.175);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#333333").s().p("AhBCGQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAgBgBAAIAAgDIAAkDIAAgEIAEgBICDAAIADABQAAABABAAQAAABAAAAQAAABAAAAQABAAAAABIAAAmQAAAAgBAAQAAABAAAAQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQAAAAgBAAIhQAAIgBAAIAAACIAAA8IAAACIABABIAtAAQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAIABADIAAAkIgBAEQAAAAgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAIgtAAIgBABIAAABIAAA9IAAACIABAAIBQAAQABAAAAAAQAAAAABAAQAAABAAAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABQABAAAAAAIAAAmQAAAAgBABQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAQAAAAgBAAg");
	this.shape_10.setTransform(96.5,76.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#333333").s().p("AAcCGIgDgBIgCgCIgxiPIAAgBIgBABIAACOIgBADQgBAAAAABQgBAAAAAAQgBAAAAAAQAAAAgBAAIgsAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAgBgBAAIgBgDIAAkDIABgEIAEgBIAxAAIACABIACAEIAxCOIABABIABgBIAAiOQAAgBAAAAQAAAAAAgBQABAAAAgBQAAAAAAgBIAEgBIAsAAIADABIABAEIAAEDIgBADQAAAAAAABQgBAAAAAAQgBAAAAAAQgBAAAAAAg");
	this.shape_11.setTransform(77.9,76.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#333333").s().p("AgVCGQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAIgBgDIAAkDIABgEIAEgBIAsAAIADABIABAEIAAEDIgBADQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAAAAAg");
	this.shape_12.setTransform(63.5,76.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#333333").s().p("AhBCGQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAgBgBAAIgBgDIAAkDIABgEIAEgBIAtAAIADABIABAEIAADXIABACIABAAIBQAAQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAAAQABABAAAAQAAAAAAABQABAAAAABQAAAAAAAAIAAAmQAAAAAAABQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgBAAAAAAg");
	this.shape_13.setTransform(51.525,76.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#333333").s().p("AAcCGIgDgBIgCgCIgwiPIgCgBIgBABIAACOIgBADQAAAAAAABQgBAAAAAAQgBAAAAAAQgBAAAAAAIgsAAQgBAAAAAAQAAAAgBAAQAAAAgBAAQAAgBAAAAIgCgDIAAkDIACgEIADgBIAwAAIAEABIABAEIAxCOIACABIAAgBIAAiOQAAgBAAAAQAAAAAAgBQABAAAAgBQAAAAABgBIACgBIAtAAIADABIACAEIAAEDIgCADQAAAAAAABQgBAAAAAAQgBAAAAAAQAAAAgBAAg");
	this.shape_14.setTransform(32.85,76.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#333333").s().p("Ag3B1QgVgUgBgjIAAh6QABgjAVgVQAUgUAjgBQAYABARAJQARAJAKARQAKARAAAYIAAB6QAAAXgKARQgKARgRAJQgRAKgYAAQgjAAgUgVgAgQhSQgGAHAAAMIAAB/QAAAMAGAIQAGAHAKAAQALAAAGgHQAHgIAAgMIAAh/QAAgMgHgHQgGgIgLAAQgKAAgGAIg");
	this.shape_15.setTransform(13.825,76.175);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#333333").s().p("AAcCHIgEgBIgCgDIgchqIgBgBIgBgBIgNAAIgCABIAAABIAABpIgBADQAAABgBAAQAAAAgBAAQAAABgBAAQAAAAgBAAIgtAAQAAAAgBAAQAAAAAAgBQgBAAAAAAQgBAAAAgBIgBgDIAAkDIABgDQAAgBABAAQAAAAABAAQAAgBAAAAQABAAAAAAIBNAAQAWAAAQALQAQAKAJASQAJASAAAYQAAAXgIASQgJAQgPAKIgCABIAAABIAkBxQAAABAAAAQAAABAAABQAAAAAAAAQAAABgBAAQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAgBAAgAgXhWIAAABIAABCIAAABIACAAIARAAQALAAAIgJQAHgJAAgQQAAgRgHgJQgIgJgLAAIgRAAIgCABg");
	this.shape_16.setTransform(246.1083,39.025);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#333333").s().p("AgWCGQAAAAAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAIgBgDIAAkDIABgDIADgCIAsAAIAEACIABADIAAEDIgBADQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAgBAAg");
	this.shape_17.setTransform(232.15,39.05);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#333333").s().p("AhBCGQgBAAAAAAQAAAAgBAAQAAAAgBAAQAAgBgBAAIgBgDIAAkDIABgDIAEgCICDAAIADACQAAAAABAAQAAABAAAAQAAABAAAAQABAAAAABIAAAlQAAABgBAAQAAABAAAAQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQAAAAgBAAIhQAAIgBABIgBABIAAA9IABABIABABIAuAAQAAAAAAAAQABAAAAAAQABAAAAAAQABABAAAAIABADIAAAkIgBAEQAAAAgBAAQAAAAgBABQAAAAgBAAQAAAAAAAAIguAAIgBAAIgBACIAAA9IABABIABABIBQAAQABAAAAAAQAAAAABAAQAAABAAAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABQABAAAAABIAAAlQAAAAgBABQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAQAAAAgBAAg");
	this.shape_18.setTransform(219.65,39.05);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#333333").s().p("AAaCGQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAgBgBAAIgBgDIAAhpIAAgCIgCAAIglAAIgCAAIAAACIAABpIgBADQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBAAIgtAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBgBAAAAIgBgDIAAkDIABgDIADgCIAtAAIAEACIABADIAABpIAAABIACABIAlAAIACgBIAAgBIAAhpIABgDIAEgCIAtAAIADACQAAAAAAAAQABABAAAAQAAABAAAAQAAAAAAABIAAEDQAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAg");
	this.shape_19.setTransform(201.625,39.05);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#333333").s().p("AgWCGQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAIgBgDIAAjXIgBgBIgBgBIguAAQgBAAAAAAQAAAAgBAAQAAgBgBAAQAAAAgBgBIgBgDIAAglIABgDIAEgCICXAAIADACIABADIAAAlIgBADQAAABAAAAQgBAAAAABQgBAAAAAAQgBAAAAAAIgwAAIgCABIAAABIAADXIgBADQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAAAAAg");
	this.shape_20.setTransform(183.4,39.05);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#333333").s().p("AAaCGQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAgBgBAAIgBgDIAAhpIAAgCIgCAAIglAAIgCAAIAAACIAABpIgBADQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBAAIgtAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBgBAAAAIgBgDIAAkDIABgDIADgCIAtAAIAEACIABADIAABpIAAABIACABIAlAAIACgBIAAgBIAAhpIABgDIAEgCIAtAAIADACQAAAAAAAAQABABAAAAQAAABAAAAQAAAAAAABIAAEDQAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAQAAAAgBABQAAAAgBAAQAAAAAAAAQgBAAAAAAg");
	this.shape_21.setTransform(157.475,39.05);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#333333").s().p("AgnCBQgRgKgKgRQgJgRgBgXIAAh7QABgYAJgQQAKgRARgJQARgJAWgBQAXABARAJQASAJAJARQAJAQABAYIAAAEQAAAAAAABQAAAAgBABQAAAAAAAAQAAABgBAAIgDABIgtACIgDgBQgBAAAAAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAgKQAAgLgGgHQgGgHgKAAQgJAAgGAHQgGAHAAALIAACEQAAALAGAHQAGAGAJAAQAKAAAGgGQAGgHAAgLIAAgLQAAAAAAgBQAAAAABAAQAAgBAAAAQAAAAABgBQAAAAABAAQAAgBAAAAQABAAAAAAQABAAAAAAIAtACIADABQABAAAAAAQAAABAAAAQABABAAAAQAAABAAAAIAAAEQgBAXgJARQgJARgSAKQgRAJgXAAQgWAAgRgJg");
	this.shape_22.setTransform(139.375,39.025);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#333333").s().p("AAcCHIgEgBIgCgDIgchqIgBgBIgBgBIgNAAIgCABIAAABIAABpIgBADQAAABgBAAQAAAAgBAAQAAABgBAAQAAAAgBAAIgtAAQAAAAgBAAQAAAAAAgBQgBAAAAAAQgBAAAAgBIgBgDIAAkDIABgDQAAgBABAAQAAAAABAAQAAgBAAAAQABAAAAAAIBNAAQAWAAAQALQAQAKAJASQAJASAAAYQAAAXgIASQgJAQgPAKIgCABIAAABIAkBxQAAABAAAAQAAABAAABQAAAAAAAAQAAABgBAAQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAgBAAgAgXhWIAAABIAABCIAAABIACAAIARAAQALAAAIgJQAHgJAAgQQAAgRgHgJQgIgJgLAAIgRAAIgCABg");
	this.shape_23.setTransform(121.7583,39.025);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#333333").s().p("AAlCGIgDgBQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIgGgkIAAgCIgCAAIgvAAIgCAAIgBABIgHAlQAAABAAAAQAAABAAAAQAAABAAAAQgBAAAAAAIgDABIgtAAIgEgBIAAgDIA5kDQAAgBAAAAQAAgBAAAAQAAgBAAAAQABAAAAAAIADgCIAzAAIADACQABAAAAAAQAAAAABABQAAAAAAABQAAAAAAABIA4EDIAAADIgEABgAAAgyIgRBiIAAACIACAAIAgAAIABgBIAAgBIgQhiIgBgBIgBABg");
	this.shape_24.setTransform(102.65,39.05);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#333333").s().p("AhBCGQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAgBAAAAIgBgDIAAkDIABgDIADgCICDAAIADACQAAAAABAAQAAABAAAAQAAABAAAAQAAAAAAABIAAAlQAAABAAAAQAAABAAAAQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAIhPAAIgCABIAAABIAAA9IAAABIACABIAtAAQAAAAAAAAQABAAAAAAQABAAAAAAQABABAAAAIABADIAAAkIgBAEQAAAAgBAAQAAAAgBABQAAAAgBAAQAAAAAAAAIgtAAIgCAAIAAACIAAA9IAAABIACABIBPAAQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABQAAAAAAABIAAAlQAAAAAAABQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgBAAAAAAg");
	this.shape_25.setTransform(84.95,39.05);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#333333").s().p("AgmCBQgRgJgJgQQgJgPAAgVIAAgNQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAAAAAQABAAAAAAIAsAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQAAABAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAAAKQAAAMAGAHQAGAHAIAAQAKAAAGgHQAGgGAAgMQAAgIgEgGQgEgHgIgHIgUgQQgPgKgOgMQgNgLgJgQQgJgQAAgWQAAgWAJgQQAJgQARgJQAQgIAWgBQAiABAUAUQAUAUABAhIAAAJQAAABAAAAQAAABgBAAQAAABAAAAQAAAAgBABQAAAAAAAAQgBABAAAAQAAAAgBAAQAAAAgBAAIgsAAQgBAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAgKQAAgMgGgHQgGgHgJAAQgJAAgFAHQgGAGAAAMQAAAIADAHQAEAGAHAHQAHAIAOAJQAUAPANALQAOAMAHAOQAHANAAATQAAAXgJAQQgKARgRAJQgQAJgXAAQgVAAgRgJg");
	this.shape_26.setTransform(67.725,39.025);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.t21, new cjs.Rectangle(-8.4,11.2,330.7,92.6), null);


(lib.t11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("AgUBvQgHgIAAgLQAAgLAHgIQAIgHALgBQAKABAHAHQAIAIAAALQAAALgIAIQgHAIgKAAQgLAAgIgIgAgXAsIgDgBIgBgDIAAgLQABgRAHgKQAHgKAJgHQAIgIAHgIQAHgIABgMQAAgLgFgGQgFgHgJAAQgJAAgFAHQgGAHAAALIAAAGIgBADIgDAAIgngBIgDgBQAAgBAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAgEQAAgUAJgPQAIgQAQgIQAPgJAUAAQAeABASARQARASAAAdQAAAVgHAMQgIAMgJAIIgQAOQgIAHAAALIAAAIQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAAAABQgBAAAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAg");
	this.shape.setTransform(140.525,95.275);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("AgwBmQgRgRgBgdIAAhwQABgdARgRQASgQAegBQAUAAAPAIQAPAIAIAOQAJAOAAAUIAAAMIgBADIgEABIgnAAIgCgBIgBgDIAAgNQAAgKgGgGQgFgGgJAAQgIAAgFAGQgFAGgBAKIAABxQABAKAFAGQAFAGAIAAQAJAAAFgGQAGgGAAgKIAAgbIgBgBIgBgBIgPAAIgCgBIgBgDIAAgcIABgDIACgBIA7AAIAEABIABADIAAA8QAAAUgJAOQgIAOgPAIQgPAHgUABQgegBgSgRg");
	this.shape_1.setTransform(125.55,95.425);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#333333").s().p("AAZB1IgDgBIgCgDIgqh8IgBgBIgBABIAAB8IAAADIgDABIgnAAIgDgBIgBgDIAAjgIABgDIADgCIAqAAIADABIACADIApB8IABABIACgCIAAh6IABgDIACgCIAnAAIADACIABADIAADgIgBADIgDABg");
	this.shape_2.setTransform(109.2,95.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#333333").s().p("AgTB1IgCgBIgCgDIAAjgQAAgBAAAAQAAgBABAAQAAgBAAAAQAAAAABAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAAAAAIAmAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQABAAAAAAQAAAAAAABQABAAAAABQAAAAAAABIAADgIgCADIgDABg");
	this.shape_3.setTransform(96.775,95.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#333333").s().p("AgVB1IgDgBIgBgDIgwjgQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAIADgBIArAAIADABIABADIAWCSIABABIABgBIAXiSQAAgBAAAAQAAAAAAgBQAAAAABAAQAAgBAAAAIADgBIAqAAIADABIAAAEIgwDgIgBADIgDABg");
	this.shape_4.setTransform(84.7792,95.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#333333").s().p("AAgB1IgCgBQgBAAAAAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIgFgfIgBgCIgBgBIgpAAIgBABIgBABIgGAgIgBADIgDABIgnAAIgDgBQgBAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAIAxjhIACgDIADgBIAsAAIADABIABADIAxDhIAAADIgDABgAAAgrIgPBUIABACIABAAIAcAAIABAAIAAgCIgOhUIgBgCIgBACg");
	this.shape_5.setTransform(68.2792,95.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#333333").s().p("AAWB1IgCgBIgBgDIAAhbIgBgBIgBgBIggAAIgBABIgBABIAABbIgBADIgEABIgmAAIgDgBIgCgDIAAjgQAAgBABAAQAAgBAAAAQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAABAAIAmAAQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAAAQAAAAABABQAAAAAAABQAAAAAAABIAABaIABABIABAAIAgAAIABAAIABgBIAAhaIABgDQAAgBAAAAQAAAAABgBQAAAAABAAQAAAAAAAAIAoAAQAAAAAAAAQABAAAAAAQABABAAAAQAAAAABABIAAADIAADgIAAADIgDABg");
	this.shape_6.setTransform(51.95,95.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#333333").s().p("Ag4B1IgDgBIgCgDIAAjgQAAgBABAAQAAgBAAAAQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAABAAIBxAAQABAAAAAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAABAAQAAAAAAABQAAAAAAABQABAAAAABIAAAgQAAAAgBAAQAAABAAAAQAAABAAAAQgBAAAAABIgDAAIhEAAIgBABIgBABIAAA1IABABIABAAIAmAAQABAAAAABQABAAAAAAQABAAAAAAQAAABAAAAIACADIAAAfIgCADIgDABIgmAAIgBABIgBABIAAA1IABABIABAAIBEAAIADABIACADIAAAhIgCADIgDABg");
	this.shape_7.setTransform(36.95,95.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#333333").s().p("Ag+B1IgDgBIgBgDIAAjgQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQAAAAABAAIA4AAQAUAAAQAHQAQAHAJAPQAJAOAAAVQAAARgGAMQgGAMgLAHIgBABIABABQAMAHAHAOQAHANAAATQAAAWgIAOQgJAPgPAIQgQAHgTAAgAgSAOIgBABIAAA8IABABIABAAIAOAAQALAAAGgIQAGgHAAgPQAAgQgGgIQgGgIgKgBIgPAAIgBABgAgShLIgBABIAAA1IABABIABAAIAMAAQAKAAAHgHQAGgHAAgNQAAgOgGgHQgHgHgKgBIgMAAIgBABg");
	this.shape_8.setTransform(21.825,95.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#333333").s().p("AAYB1IgDgBIgCgDIgYhbIgBgBIgBgBIgLAAIgBABIgBABIAABbIgBADIgDABIgnAAIgDgBIgBgDIAAjhQAAgBAAAAQAAAAAAgBQAAAAABAAQAAgBAAAAIADgBIBCAAQATAAAOAJQAOAJAIAPQAIAQAAAVQAAAVgHAOQgIAOgNAJIgBABIAAABIAfBjQAAAAAAAAQAAABAAAAQAAABAAAAQAAAAgBAAQAAABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAgAgThLIgBABIAAA5IABACIABAAIAPAAQAJAAAHgIQAGgIAAgOQAAgPgGgHQgHgJgJAAIgPAAIgBABg");
	this.shape_9.setTransform(117.2583,63);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#333333").s().p("Ag5B1IgCgBIgCgDIAAjhQABAAAAAAQAAgBAAAAQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAAAAAIByAAQABAAAAAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAABAAQAAAAAAABQAAAAAAABQABAAAAAAIAAAhQAAAAgBAAQAAABAAAAQAAABAAAAQgBAAAAABIgDAAIhFAAIgBABIAAABIAAA1IAAABIABAAIAoAAQAAAAAAABQABAAAAAAQABAAAAAAQAAABAAAAIABADIAAAfIgBADIgCABIgoAAIgBABIAAABIAAA1IAAABIABABIBFAAIADAAIACADIAAAhIgCADIgDABg");
	this.shape_10.setTransform(102,63);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#333333").s().p("AAYB1IgCgBIgCgDIgqh8IgBgBIgBABIABB8IgBADIgEABIgmAAIgDgBIgBgDIAAjhIABgCIADgCIAqAAIADABIABADIArB8IAAABIABgCIAAh7IABgCIAEgCIAmAAIADACIABACIAADhIgBADIgDABg");
	this.shape_11.setTransform(85.85,63);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#333333").s().p("AgTB1IgDgBIgBgDIAAi7IgBgBIgBgBIgoAAIgDAAIgBgDIAAghIABgCIADgCICDAAQABAAAAAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAAAQABAAAAABQAAAAAAABQAAAAAAAAIAAAhQAAAAAAAAQAAABAAAAQAAABgBAAQAAAAAAABIgDAAIgqAAIgBABIAAABIAAC7IgBADIgDABg");
	this.shape_12.setTransform(69.425,63);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#333333").s().p("AAYB1IgDgBIgCgDIgYhbIgBgBIgBgBIgLAAIgBABIgBABIAABbIgBADIgDABIgnAAIgDgBIgBgDIAAjhQAAgBAAAAQAAAAAAgBQAAAAABAAQAAgBAAAAIADgBIBCAAQATAAAOAJQAOAJAIAPQAIAQAAAVQAAAVgHAOQgIAOgNAJIgBABIAAABIAfBjQAAAAAAAAQAAABAAAAQAAABAAAAQAAAAgBAAQAAABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAgAgThLIgBABIAAA5IABACIABAAIAPAAQAJAAAHgIQAGgIAAgOQAAgPgGgHQgHgJgJAAIgPAAIgBABg");
	this.shape_13.setTransform(54.1083,63);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#333333").s().p("AAgB1IgCgBQgBAAAAAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIgFgfIgBgCIgBgBIgpAAIgBABIgBABIgGAgIgBADIgDABIgnAAIgDgBQgBAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAIAxjhIACgDIADgBIAsAAIADABIABADIAxDhIAAADIgDABgAAAgrIgPBUIABACIABAAIAcAAIABAAIAAgCIgOhUIgBgCIgBACg");
	this.shape_14.setTransform(37.5292,63);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#333333").s().p("Ag+B1IgDgBIgBgDIAAjhIABgDIADgBIBCAAQATAAAOAJQAOAJAIAQQAIAQAAAVQAAAggRARQgQASgcABIgXAAIgBAAIgBABIAABZIgBADIgDABgAgShLIgBABIAAA7IABACIABAAIAOAAQAKAAAGgIQAHgIAAgPQAAgPgHgIQgGgIgKgBIgOAAIgBABg");
	this.shape_15.setTransform(21.8,63);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#333333").s().p("AAYB1IgDgBIgCgDIgYhbIgBgBIgBgBIgLAAIgBABIgBABIAABbIgBADIgDABIgnAAIgDgBIgBgDIAAjhQAAgBAAAAQAAAAAAgBQAAAAABAAQAAgBAAAAIADgBIBCAAQATAAAOAJQAOAJAIAPQAIAQAAAVQAAAVgHAOQgIAOgNAJIgBABIAAABIAfBiQAAABAAAAQAAABAAAAQAAABAAAAQAAAAgBAAQAAABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAgAgThLIgBABIAAA5IABACIABAAIAPAAQAJAAAHgIQAGgIAAgOQAAgPgGgHQgHgJgJAAIgPAAIgBABg");
	this.shape_16.setTransform(98.8583,30.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#333333").s().p("AgvBjQgSgSAAggIAAiiQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAQABAAAAgBIAnAAQAAABABAAQAAAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQABAAAAAAQAAABAAAAQAAABAAAAIAACnQAAALAFAGQAFAGAIABQAJgBAFgGQAFgGAAgLIAAinQAAAAAAgBQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQAAAAABAAQAAAAAAgBIAnAAQABABAAAAQABAAAAAAQAAAAABAAQAAABAAAAIABADIAACiQAAAVgIAQQgIAPgPAIQgPAJgUAAQgdAAgSgTg");
	this.shape_17.setTransform(82.525,30.75);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#333333").s().p("AgwBlQgSgRAAgfIAAhqQAAgeASgSQASgRAegBQAVAAAOAJQAPAIAJAOQAJAPAAAUIAABqQAAAVgJAOQgJAPgPAIQgOAIgVABQgegBgSgSgAgOhIQgGAHABAKIAABuQgBALAGAHQAFAGAJAAQAKAAAFgGQAGgHgBgLIAAhuQABgKgGgHQgFgGgKAAQgJAAgFAGg");
	this.shape_18.setTransform(66.65,30.625);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#333333").s().p("AgTB1IgDgBIgBgDIAAhXIAAgBIAAgBIgviHQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAQAAgBAAAAQABAAAAAAIAqAAIADABIABADIAVBQIAAABIABgBIAVhQIABgDIADgBIApAAQABAAAAAAQABAAAAABQABAAAAAAQAAAAAAABQABAAAAAAQAAABAAAAQAAABAAAAQAAABAAAAIgvCHIgBABIAAABIAABXIgBADIgDABg");
	this.shape_19.setTransform(50.8583,30.575);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#333333").s().p("AghBwQgOgIgIgOQgIgNgBgTIAAgKQAAgBAAAAQAAgBABAAQAAAAAAgBQAAAAABAAIADgBIAmAAIADABIABADIAAAIQAAALAFAGQAFAGAHAAQAJAAAFgGQAFgGAAgKQAAgHgDgFQgEgGgHgGIgRgOQgNgJgMgKQgMgJgHgOQgIgOAAgTQAAgTAIgOQAIgOAOgIQAPgIATAAQAdABARARQASARAAAdIAAAIQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAIgDABIgmAAIgDgBIgBgDIAAgJQAAgKgGgGQgFgGgHAAQgIAAgFAFQgFAGAAALQAAAGADAGQADAGAHAGIARAPQARAMAMAKQAMAKAGAMQAGAMAAAQQAAAUgIAPQgIAOgPAIQgOAHgUABQgSgBgPgHg");
	this.shape_20.setTransform(28.875,30.625);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#333333").s().p("AgTB1IgCgBIgCgDIAAjgQAAgBAAAAQAAgBABAAQAAgBAAAAQAAAAABAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAAAAAIAmAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQABAAAAAAQAAAAAAABQABAAAAABQAAAAAAABIAADgIgCADIgDABg");
	this.shape_21.setTransform(17.475,30.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.t11, new cjs.Rectangle(11.6,7.5,142.20000000000002,110.7), null);


(lib.logo_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.logo();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.logo_1, new cjs.Rectangle(0,0,401,56), null);


(lib.btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgNBJIAAh1IgoAAIAAgcIBrAAIAAAcIgoAAIAAB1g");
	this.shape.setTransform(103.525,15.825);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgzBJIAAiRIA2AAQAUAAAPAOQAOAOAAAVQAAAVgOANQgPAOgUAAIgZAAIAAAwgAgWgBIAZAAQAIAAAGgGQAHgHgBgJQABgKgHgGQgGgGgIAAIgZAAg");
	this.shape_1.setTransform(92.15,15.825);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgsBJIAAiRIBYAAIAAAcIg7AAIAAAfIA2AAIAAAaIg2AAIAAAgIA8AAIAAAcg");
	this.shape_2.setTransform(80.55,15.825);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgvA2QgVgWAAggQAAgfAVgWQAWgWAfAAQAVAAAQAKQAQAJAKAQIgYAOQgGgKgKgFQgKgGgNAAQgTAAgNANQgNAOgBAUQABAVANANQANAOATAAQANAAAKgGQAKgFAGgKIAYAOQgKAQgQAJQgQAKgVAAQgfAAgWgWg");
	this.shape_3.setTransform(67.25,15.825);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AguA2QgWgWAAggQAAgfAWgWQAUgWAhAAQATAAARAKQAQAJAKAQIgYAOQgGgKgKgFQgKgGgMAAQgVAAgMANQgOAOAAAUQAAAVAOANQAMAOAVAAQAMAAAKgGQAKgFAGgKIAYAOQgKAQgQAJQgRAKgTAAQghAAgUgWg");
	this.shape_4.setTransform(52.15,15.825);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAlBJIgIgaIg5AAIgJAaIgfAAIAziRIAjAAIAzCRgAgTAUIAnAAIgUg7g");
	this.shape_5.setTransform(37.65,15.825);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgNBJIAAiRIAbAAIAACRg");
	this.shape_6.setTransform(22.725,15.825);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#00A575").s().p("ApSCWQgyAAAAgyIAAjHQAAgyAyAAISlAAQAyAAAAAyIAADHQAAAygyAAg");
	this.shape_7.setTransform(64.5,15);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.btn, new cjs.Rectangle(0,0,129,32.1), null);


(lib.bg2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib._160x600();
	this.instance.parent = this;
	this.instance.setTransform(-134,-39);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bg2, new cjs.Rectangle(-134,-39,600,1200), null);


// stage content:
(lib._300x600TFHTML532 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_779 = function() {
		this.stop()
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(779).call(this.frame_779).wait(22));

	// Слой_7
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,255,255,0)").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape.setTransform(150,300);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(255,255,255,0.055)").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape_1.setTransform(150,300);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(255,255,255,0.11)").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape_2.setTransform(150,300);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(255,255,255,0.169)").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape_3.setTransform(150,300);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("rgba(255,255,255,0.224)").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape_4.setTransform(150,300);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("rgba(255,255,255,0.278)").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape_5.setTransform(150,300);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("rgba(255,255,255,0.333)").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape_6.setTransform(150,300);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("rgba(255,255,255,0.388)").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape_7.setTransform(150,300);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("rgba(255,255,255,0.443)").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape_8.setTransform(150,300);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("rgba(255,255,255,0.502)").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape_9.setTransform(150,300);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("rgba(255,255,255,0.557)").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape_10.setTransform(150,300);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("rgba(255,255,255,0.612)").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape_11.setTransform(150,300);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("rgba(255,255,255,0.667)").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape_12.setTransform(150,300);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("rgba(255,255,255,0.722)").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape_13.setTransform(150,300);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("rgba(255,255,255,0.776)").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape_14.setTransform(150,300);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("rgba(255,255,255,0.831)").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape_15.setTransform(150,300);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("rgba(255,255,255,0.89)").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape_16.setTransform(150,300);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("rgba(255,255,255,0.945)").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape_17.setTransform(150,300);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape_18.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},248).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[]},1).to({state:[{t:this.shape}]},248).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[]},1).to({state:[{t:this.shape}]},248).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).wait(1));

	// Слой_5
	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f().s("#FFFFFF").ss(9,1,1).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape_19.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape_19).wait(801));

	// logo
	this.instance = new lib.logo_1();
	this.instance.parent = this;
	this.instance.setTransform(149.7,198.45,0.3005,0.3005,0,0,0,199.8,27.8);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(119).to({_off:false},0).to({_off:true},148).wait(119).to({_off:false},0).to({_off:true},148).wait(119).to({_off:false},0).wait(148));

	// t1.2
	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#333333").s().p("AgIA4IgBgBIAAgBIAAgHIAAgBIABAAQAIAAAEgDQAFgDACgFQACgFAAgIIAAgFIAAAAIgBAAQgCAEgFACQgEACgDAAQgKAAgFgHQgGgGAAgLIAAggQAAgLAGgGQAFgGAKgBQADAAAEACQAFACACAEIABABIAAgBIAAgFIAAgBIABAAIAIAAIABAAIABABIAABLQAAAKgDAIQgDAHgHAEQgHAEgJAAIgDAAgAgIgpQgEAEAAAHIAAAeQAAAHAEAEQADAEAFAAQAGAAAEgEQADgEAAgHIAAgeQAAgHgDgEQgEgEgGAAQgFAAgDAEg");
	this.shape_20.setTransform(267.5,174.4778);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#333333").s().p("AAOAoIgBgBIAAgBIAAgzQAAgIgDgEQgEgEgFAAQgGAAgDAEQgEAFAAAIIAAAyIgBABIgBABIgIAAIgBgBIAAgBIAAhKIAAgBIABgBIAIAAIABABIABABIAAAFIAAAAQAEgEAEgCQAEgCAEAAQAJAAAGAHQAFAGAAAMIAAA0IgBABIgBABg");
	this.shape_21.setTransform(261.1,172.925);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#333333").s().p("AgDA2IgBAAIgBgBIAAhLIABgBIABAAIAHAAIABAAIAAABIAABLIAAABIgBAAgAgFgoQgCgCAAgDQAAgEACgCQADgCACAAQADAAACACQACACABAEQgBADgCACQgCADgDAAQgCAAgDgDg");
	this.shape_22.setTransform(256.175,171.475);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#333333").s().p("AgDA2IgBAAIAAgBIAAhpIAAgBIABAAIAHAAIABAAIABABIAABpIgBABIgBAAg");
	this.shape_23.setTransform(253.25,171.475);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#333333").s().p("AALAxQgGAAgEgBQgDgCgDgEQgCgEAAgIIAAgyIAAAAIgBAAIgGAAIgBgBIAAgBIAAgFIAAgBIABgBIAGAAIABAAIAAAAIAAgSIAAgBIACAAIAGAAIABAAIABABIAAASIAAAAIAMAAIABABIAAABIAAAFIAAABIgBABIgMAAIAAAAIAAAvQgBAHADADQADACAFAAIABAAIABAAIABACIAAAHIgBAAIgBABg");
	this.shape_24.setTransform(249.75,172);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#333333").s().p("AgPAoIgBgBIAAgBIAAhKIAAgBIABgBIAIAAIABABIABABIAAAJIABABIAAgBQABgFADgDQAEgDAFgBIAFABIACABIABABIAAABIgCAIIAAABIgCAAIgDgBIgDAAQgGABgCAFQgEAGAAAIIAAAtIgBABIgBABg");
	this.shape_25.setTransform(245.85,172.925);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#333333").s().p("AgMAnQgFgCgDgFQgEgEAAgKQAAgJAEgGQADgEAHgDQAGgCAGAAIAMAAIAAAAIAAgBIAAgGQAAgIgEgEQgDgFgGAAQgEAAgDADQgDADgBAFIAAABIgBABIgJAAIgBgBIAAgBQAAgJAHgGQAGgFAJgBQAMABAFAHQAHAHAAALIAAA0IAAABIgBAAIgIAAIgBAAIgBgBIAAgFIAAAAIgBAAQgDAEgEACQgEACgFAAQgFAAgEgCgAgIAGQgFADABAIQAAAHADAEQADADAGAAQACAAAEgCQADgBACgEQADgDAAgGIAAgNIAAAAIAAAAIgMAAQgFAAgFAEg");
	this.shape_26.setTransform(239.9,172.975);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#333333").s().p("AAKAxQgFAAgFgBQgDgCgCgEQgCgEAAgIIAAgyIgBAAIAAAAIgGAAIgBgBIgBgBIAAgFIABgBIABgBIAGAAIAAAAIABAAIAAgSIAAgBIACAAIAGAAIABAAIABABIAAASIAAAAIAMAAIABABIAAABIAAAFIAAABIgBABIgMAAIAAAAIAAAvQAAAHACADQADACAFAAIACAAIABAAIAAACIAAAHIAAAAIgBABg");
	this.shape_27.setTransform(234.7,172);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#333333").s().p("AgSAwQgHgHAAgNIAAgEIABgBIABAAIAIAAIABAAIAAABIAAAEQAAAIAEAFQAEAFAGAAQAGAAAFgFQAEgEAAgJQAAgFgCgEQgCgEgFgDIgIgIIgMgIQgFgFgDgGQgDgFAAgIQAAgJADgGQAEgFAFgDQAGgEAHAAQALAAAHAIQAHAIAAAMIAAAEIAAABIgBABIgIAAIgBgBIgBgBIAAgEQAAgIgEgFQgEgFgGAAQgGAAgEAEQgEAFAAAIQAAAFACADQACAEADAEIAKAIIANAJQAFAFACAFQADAFAAAHQAAAJgDAGQgEAHgGADQgFADgIABQgLgBgHgHg");
	this.shape_28.setTransform(229.425,171.475);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#333333").s().p("AgRAiQgGgGAAgLIAAghQAAgKAGgHQAHgGAKgBQALABAHAGQAGAHAAAKIAAATIAAABIgBAAIgjAAIAAAAIAAABIAAALQAAAHADAEQAEAEAFAAQAFAAADgDQAEgDABgFIAAgBIABAAIAIAAIABAAIABACQgCAJgGAFQgGAFgKABQgKgBgHgGgAgJgaQgDAEAAAHIAAAKIAAABIAAAAIAZAAIAAAAIAAgBIAAgKQAAgHgEgEQgDgEgGAAQgFAAgEAEg");
	this.shape_29.setTransform(219.825,172.975);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#333333").s().p("AgYA2IgBAAIAAgBIAAhpIAAgBIABAAIAWAAQANAAAIAHQAHAHAAAOQAAAJgDAGQgEAGgGADIAAAAQAGADAEAHQAEAGAAAKQAAAOgIAIQgHAHgMAAgAgOADIAAApIAAAAIAAAAIANAAQAIAAAEgFQAFgFgBgKQABgLgFgFQgEgGgIAAIgNAAIAAAAgAgOgrIAAAlIAAABIAAAAIAMAAQAIAAAFgFQAEgFAAgJQAAgJgEgGQgFgFgIAAIgMAAIAAAAg");
	this.shape_30.setTransform(213.4,171.475);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#333333").s().p("AgRAiQgGgGAAgLIAAghQAAgKAGgHQAHgGAKgBQALABAHAGQAGAHAAAKIAAAhQAAALgGAGQgHAGgLABQgKgBgHgGgAgJgaQgDAEAAAHIAAAfQAAAHADAEQAEAEAFAAQAGAAAEgEQADgEAAgHIAAgfQAAgHgDgEQgEgEgGAAQgFAAgEAEg");
	this.shape_31.setTransform(203.375,172.975);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#333333").s().p("AgEA2IgBAAIAAgBIAAhgIAAgBIgBAAIgTAAIgBAAIgBgBIAAgHIABgBIABAAIAzAAIABAAIABABIAAAHIgBABIgBAAIgUAAIgBAAIAAABIAABgIgBABIgBAAg");
	this.shape_32.setTransform(196.825,171.475);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#333333").s().p("AgRAiQgFgFgBgJIAAgBIABgBIABgBIAHAAIABABIABAAIAAACQAAAEAEAEQADADAFAAQAGAAADgDQAEgDgBgGQAAgEgCgDIgGgEIgGgEIgJgEQgFgBgDgFQgDgEAAgIQAAgKAGgFQAGgGAKAAQAKAAAHAGQAFAGAAAKIAAAAIAAABIgBABIgHAAIgBgBIgBgBIAAgBQABgFgEgDQgDgEgGAAQgFAAgDAEQgDADAAAFQAAAEACACIAFAFIAGADQAFACAFACQAFACADAFQAEAEAAAIQAAAKgHAFQgGAFgLABQgKgBgHgFg");
	this.shape_33.setTransform(187.6,173);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#333333").s().p("AAKAxQgFAAgEgBQgDgCgDgEQgCgEAAgIIAAgyIAAAAIgBAAIgGAAIgBgBIgBgBIAAgFIABgBIABgBIAGAAIABAAIAAAAIAAgSIAAgBIABAAIAHAAIABAAIAAABIAAASIABAAIAMAAIABABIABABIAAAFIgBABIgBABIgMAAIgBAAIAAAvQABAHACADQADACAEAAIACAAIACAAIAAACIAAAHIAAAAIgCABg");
	this.shape_34.setTransform(182.55,172);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#333333").s().p("AgDA2IgBAAIAAgBIAAhpIAAgBIABAAIAHAAIABAAIAAABIAABpIAAABIgBAAg");
	this.shape_35.setTransform(179.1,171.475);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#333333").s().p("AgRAiQgFgFgBgMIAAg2IAAgBIABgBIAIAAIABABIABABIAAA0QAAAHAEAEQACAEAGAAQAGAAAEgEQADgFAAgHIAAgzIAAgBIABgBIAIAAIABABIABABIAABKIgBABIgBABIgIAAIgBgBIAAgBIAAgFIgBgBIAAABQgDAEgEACQgDACgFAAQgIAAgGgGg");
	this.shape_36.setTransform(174.35,173.025);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#333333").s().p("AgQAiQgHgFABgJIAAgBIAAgBIABgBIAIAAIAAABIABAAIAAACQAAAEADAEQAEADAFAAQAGAAADgDQADgDABgGQgBgEgCgDIgGgEIgHgEIgJgEQgEgBgDgFQgDgEAAgIQAAgKAGgFQAGgGAKAAQALAAAFAGQAHAGAAAKIAAAAIgBABIgBABIgHAAIgBgBIAAgBIAAgBQgBgFgDgDQgEgEgFAAQgFAAgDAEQgDADgBAFQAAAEACACIAGAFIAHADQAEACAFACQAFACADAFQADAEAAAIQAAAKgGAFQgGAFgLABQgKgBgGgFg");
	this.shape_37.setTransform(168.3,173);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#333333").s().p("AgRAiQgGgGAAgLIAAghQAAgKAGgHQAHgGAKgBQALABAHAGQAGAHAAAKIAAATIAAABIgBAAIgjAAIAAAAIAAABIAAALQAAAHADAEQAEAEAFAAQAFAAADgDQAEgDABgFIAAgBIABAAIAIAAIABAAIABACQgCAJgGAFQgGAFgKABQgKgBgHgGgAgJgaQgDAEAAAHIAAAKIAAABIAAAAIAZAAIAAAAIAAgBIAAgKQAAgHgEgEQgDgEgGAAQgFAAgEAEg");
	this.shape_38.setTransform(162.175,172.975);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#333333").s().p("AARA3IgBgBIgBgBIgPgwIAAgBIgBAAIgMAAIgBAAIgBABIAAAwIAAABIgBABIgIAAIgBgBIgBgBIAAhoIABgCIABgBIAZAAQALABAHAIQAHAIAAAOQAAAKgEAHQgFAHgHACIgBABIAAAAIARAxIAAABIgBABgAgPgrIAAAnIABABIABAAIANAAQAGAAAEgGQAFgFAAgJQAAgKgFgFQgEgGgGABIgNAAIgBAAIgBAAg");
	this.shape_39.setTransform(155.85,171.45);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#333333").s().p("AgNA0QgFgDgCgFQgCgGgBgHIAAgIIAAgJIAAgIIAAgIQABgKAFgGQAGgHAJAAQAEAAADACQAFACACADIABABIAAgBIAAgiIAAgBIABgBIAIAAIABABIABABIAABoIgBABIgBABIgIAAIgBgBIAAgBIAAgEIAAgBIgBAAQgCAEgFACQgDACgEAAQgGAAgFgDgAgIgLQgEAEAAAHIAAAHIAAAIIAAAPQAAAHAEAEQADAEAGAAQAFAAAEgEQADgEAAgHIAAgeQAAgHgDgEQgEgEgFAAQgGAAgDAEg");
	this.shape_40.setTransform(142.5,171.525);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#333333").s().p("AAPAoIgCgBIAAgBIAAgzQAAgIgEgEQgCgEgHAAQgFAAgEAEQgDAFAAAIIAAAyIAAABIgBABIgIAAIgBgBIgBgBIAAhKIABgBIABgBIAIAAIABABIAAABIAAAFIABAAQADgEAEgCQAEgCAEAAQAKAAAEAHQAGAGAAAMIAAA0IAAABIgCABg");
	this.shape_41.setTransform(136.05,172.925);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#333333").s().p("AgDA2IgBAAIgBgBIAAhLIABgBIABAAIAHAAIABAAIAAABIAABLIAAABIgBAAgAgFgoQgCgCAAgDQAAgEACgCQADgCACAAQADAAACACQACACABAEQgBADgCACQgCADgDAAQgCAAgDgDg");
	this.shape_42.setTransform(131.175,171.475);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#333333").s().p("AgWA2IgBAAIAAgBIAAhpIAAgBIABAAIAtAAIABAAIAAABIAAAHIAAABIgBAAIgjAAIAAAAIAAABIAAAmIAAABIAAAAIAWAAIABAAIABACIAAAFIgBABIgBABIgWAAIAAAAIAAAAIAAAwIgBABIgBAAg");
	this.shape_43.setTransform(126.9,171.475);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#333333").s().p("AgUA3IgCgBIAAgBIAAgGIAAgBIABgBIABAAQAEAAADgBQADgCACgFIADgNIAAAAIAAgBIgUhLIABgBIABgBIAIAAIABABIABABIANA8IAAAAIAAAAIAOg8IABgBIABgBIAIAAIACABIAAABIgWBTQgCAJgCAGQgDAFgFACQgEACgIAAg");
	this.shape_44.setTransform(117.4,174.525);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#333333").s().p("AgMAnQgFgCgEgFQgDgEAAgKQAAgJAEgGQAEgEAFgDQAHgCAHAAIAKAAIABAAIAAgBIAAgGQAAgIgDgEQgEgFgGAAQgEAAgDADQgDADgBAFIgBABIgBABIgIAAIgCgBIAAgBQACgJAGgGQAHgFAJgBQAKABAHAHQAGAHAAALIAAA0IgBABIgBAAIgIAAIgBAAIAAgBIAAgFIAAAAIgBAAQgDAEgEACQgFACgEAAQgFAAgEgCgAgIAGQgEADgBAIQABAHADAEQADADAFAAQAEAAADgCQAEgBACgEQACgDAAgGIAAgNIAAAAIgBAAIgKAAQgHAAgEAEg");
	this.shape_45.setTransform(111.25,172.975);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#333333").s().p("AAUA2IgBAAIgBgBIAAhPIAAAAIgBAAIgPAjIgBABIgBAAIAAAAIAAgBIgQgjIgBAAIAAAAIAABPIgBABIgBAAIgIAAIgBAAIAAgBIAAhpIAAgBIABAAIAIAAIABAAIABABIARAqIAAAAIAAAAIASgqIABgBIABAAIAIAAIABAAIAAABIAABpIAAABIgBAAg");
	this.shape_46.setTransform(104.175,171.475);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#333333").s().p("AgRAiQgGgGAAgLIAAghQAAgKAGgHQAHgGAKgBQALABAHAGQAGAHAAAKIAAATIAAABIgBAAIgjAAIAAAAIAAABIAAALQAAAHADAEQAEAEAFAAQAFAAADgDQAEgDABgFIAAgBIABAAIAIAAIABAAIABACQgCAJgGAFQgGAFgKABQgKgBgHgGgAgJgaQgDAEAAAHIAAAKIAAABIAAAAIAZAAIAAAAIAAgBIAAgKQAAgHgEgEQgDgEgGAAQgFAAgEAEg");
	this.shape_47.setTransform(93.925,172.975);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#333333").s().p("AgDA2IgBAAIgBgBIAAhpIABgBIABAAIAHAAIABAAIAAABIAABpIAAABIgBAAg");
	this.shape_48.setTransform(89.3,171.475);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#333333").s().p("AgWA3IgBgBIAAgBIAAhoIAAgBIABgBIAJAAIAAABIABABIAAAEIAAABIAAAAQADgEAFgCQADgCAEAAQAKABAFAGQAGAHAAAKIAAAJIAAAIIAAAJIAAAHQAAALgGAGQgFAGgKAAQgEAAgDgCQgFgCgDgDIAAgBIAAABIAAAiIgBABIAAABgAgIgoQgEAFAAAGIAAAeQAAAHAEAFQADADAFAAQAGAAAEgDQADgFAAgHIAAgHIAAgHIAAgQQAAgGgDgFQgEgEgGAAQgFAAgDAEg");
	this.shape_49.setTransform(84.7,174.4);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#333333").s().p("AgRAiQgGgGAAgLIAAghQAAgKAGgHQAHgGAKgBQALABAHAGQAGAHAAAKIAAAhQAAALgGAGQgHAGgLABQgKgBgHgGgAgJgaQgDAEAAAHIAAAfQAAAHADAEQAEAEAFAAQAGAAAEgEQADgEAAgHIAAgfQAAgHgDgEQgEgEgGAAQgFAAgEAEg");
	this.shape_50.setTransform(78.075,172.975);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#333333").s().p("AgRAiQgGgGAAgLIAAghQAAgKAGgHQAHgGAKgBQALABAHAGQAGAHAAAKIAAATIAAABIgBAAIgjAAIAAAAIAAABIAAALQAAAHADAEQAEAEAFAAQAFAAADgDQAEgDABgFIAAgBIABAAIAIAAIABAAIABACQgCAJgGAFQgGAFgKABQgKgBgHgGgAgJgaQgDAEAAAHIAAAKIAAABIAAAAIAZAAIAAAAIAAgBIAAgKQAAgHgEgEQgDgEgGAAQgFAAgEAEg");
	this.shape_51.setTransform(71.725,172.975);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#333333").s().p("AgYA3IgBgBIAAgBIAAhoIAAgCIABgBIAZAAQAIABAFAEQAGADADAHQADAHAAAJQAAAOgHAHQgGAIgMgBIgPAAIAAAAIAAABIAAAvIgBABIgBABgAgOgrIAAAoIAAAAIAAAAIAOAAQAHAAAEgFQAEgFAAgKQAAgJgEgGQgEgGgHABIgOAAIAAAAg");
	this.shape_52.setTransform(65.375,171.45);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#333333").s().p("AgRAiQgGgGAAgLIAAghQAAgKAGgHQAHgGAKgBQALABAHAGQAGAHAAAKIAAATIAAABIgBAAIgjAAIAAAAIAAABIAAALQAAAHADAEQAEAEAFAAQAFAAADgDQAEgDABgFIAAgBIABAAIAIAAIABAAIABACQgCAJgGAFQgGAFgKABQgKgBgHgGgAgJgaQgDAEAAAHIAAAKIAAABIAAAAIAZAAIAAAAIAAgBIAAgKQAAgHgEgEQgDgEgGAAQgFAAgEAEg");
	this.shape_53.setTransform(55.475,172.975);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#333333").s().p("AAgAoIgBgBIgBgBIAAgyQAAgIgDgFQgDgEgGAAQgGAAgDAEQgEAFAAAIIAAAyIAAABIgBABIgHAAIgBgBIgBgBIAAgyQAAgIgDgFQgDgEgGAAQgGAAgDAEQgDAFAAAIIAAAyIgBABIgBABIgIAAIgBgBIAAgBIAAhKIAAgBIABgBIAIAAIABABIABABIAAAFIAAAAIAAAAQADgEAFgCIAIgCQAGAAAEADQADADADAFIAAABIABgBQADgGAFgCQAEgDAGAAQAJAAAFAHQAFAHAAAMIAAAzIAAABIgBABg");
	this.shape_54.setTransform(47.275,172.925);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#333333").s().p("AgRAiQgGgGAAgLIAAghQAAgKAGgHQAHgGAKgBQALABAHAGQAGAHAAAKIAAAhQAAALgGAGQgHAGgLABQgKgBgHgGgAgJgaQgDAEAAAHIAAAfQAAAHADAEQAEAEAFAAQAGAAAEgEQADgEAAgHIAAgfQAAgHgDgEQgEgEgGAAQgFAAgEAEg");
	this.shape_55.setTransform(39.025,172.975);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#333333").s().p("AgSAwQgHgHAAgNIAAgEIABgBIABAAIAIAAIABAAIAAABIAAAEQAAAIAEAFQAEAFAGAAQAGAAAFgFQAEgEAAgJQAAgFgCgEQgCgEgFgDIgIgIIgMgIQgFgFgDgGQgDgFAAgIQAAgJADgGQAEgFAFgDQAGgEAHAAQALAAAHAIQAHAIAAAMIAAAEIAAABIgBABIgIAAIgBgBIgBgBIAAgEQAAgIgEgFQgEgFgGAAQgGAAgEAEQgEAFAAAIQAAAFACADQACAEADAEIAKAIIANAJQAFAFACAFQADAFAAAHQAAAJgDAGQgEAHgGADQgFADgIABQgLgBgHgHg");
	this.shape_56.setTransform(32.575,171.475);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#CC0000").s().p("AANA2IgBAAIgBgBIgMgtIgBAAIAAgBIgIAAIgBABIAAAAIAAAsIAAACIgCAAIgOAAIgBAAIgBgCIAAhnIABgCIABgBIAcAAQAIABAHAEQAGAEADAHQAEAHAAAKQAAAJgEAHQgDAGgHAEIgBAAIAQAvIgBACIgBAAgAgLglIAAAfIAAABIABAAIAJAAQAFAAADgFQAEgEAAgHQAAgIgEgEQgDgFgFAAIgJAAIgBAAg");
	this.shape_57.setTransform(178.875,153.35);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#CC0000").s().p("AgYA2IgBAAIgBgCIAAhnIABgCIABAAIAxAAIABAAIABACIAAALIgBACIgBAAIggAAIgBAAIAAABIAAAdIAAABIABAAIATAAIABABIABABIAAALIgBABIgBABIgTAAIgBAAIAAABIAAAdIAAAAIABABIAgAAIABAAIABACIAAALIgBACIgBAAg");
	this.shape_58.setTransform(171.9,153.375);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#CC0000").s().p("AARA2IgBAAIgBgCIAAhCIAAgBIgBABIgMAaIgCABIAAAAIAAAAIAAgBIgNgbIgBAAIAAABIAABCIgBACIgCAAIgNAAIgCAAIAAgCIAAhnIAAgCIACAAIANAAIACAAIABABIAOAiIAAAAIAPgiIABgBIABAAIAPAAIABAAIAAACIAABnIAAACIgBAAg");
	this.shape_59.setTransform(164.15,153.375);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#CC0000").s().p("AgHA2IAAAAIgBgCIAAhnIABgCIAAAAIAOAAIACAAIAAACIAABnIAAACIgCAAg");
	this.shape_60.setTransform(158.25,153.375);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#CC0000").s().p("AARA2IgCAAIAAgBIgDgRIAAAAIgBgBIgWAAIAAABIgBAAIgDARIAAABIgBAAIgPAAIgBAAIAAgCIAXhoIABgBIABAAIAPAAIACAAIAAABIAXBoIAAACIgCAAgAAAgZIgIAuIAAAAIABAAIAQAAIAAAAIABAAIgJguIAAgBIgBABg");
	this.shape_61.setTransform(152.75,153.375);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#CC0000").s().p("AgYA2IgBAAIgBgCIAAhnIABgCIABAAIAOAAIACAAIAAACIAABZIAAAAIABABIAgAAIACAAIAAACIAAALIAAACIgCAAg");
	this.shape_62.setTransform(146.1,153.375);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#CC0000").s().p("AgUAwQgIgIAAgOIAAg0QAAgNAIgIQAIgIAMAAQANAAAIAIQAIAIAAANIAAACIAAACIgCAAIgOABIgBgBIgBgBIAAgEQAAgFgDgEQgDgDgFAAQgEAAgDADQgDAEAAAFIAAA3QAAAFADAEQADADAEAAQAFAAADgDQADgEAAgFIAAgEIABgBIABgBIAOABIACAAIAAABIAAACQAAAOgIAIQgIAHgNABQgMgBgIgHg");
	this.shape_63.setTransform(138.975,153.375);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#CC0000").s().p("AgOA0QgGgEgEgGQgDgGgBgJIAAgEIABgBIABgBIAOAAIACABIAAABIAAAEQAAAGADADQADAEAEAAQAFAAADgDQADgEAAgGQAAgEgCgDIgFgGIgIgHIgMgIQgFgFgDgGQgEgGAAgJQAAgIAEgGQADgHAHgDQAGgEAIAAQAMAAAIAIQAIAIAAAOIAAADIAAACIgCAAIgOAAIgBAAIgBgCIAAgEQAAgGgDgDQgDgEgEAAQgEAAgDADQgDADAAAGQAAAEABADQACADADADIAIAIIAOAJQAFAFADAFQADAGAAAHQAAAJgEAHQgEAGgGAEQgGADgJABQgIgBgGgDg");
	this.shape_64.setTransform(132.025,153.375);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#CC0000").s().p("AgHA2IAAAAIgBgCIAAhnIABgCIAAAAIAOAAIACAAIAAACIAABnIAAACIgCAAg");
	this.shape_65.setTransform(126.85,153.375);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#CC0000").s().p("AgaA2IgBAAIgBgCIAAhnIABgCIABAAIAaAAQANAAAIAIQAIAIAAANIAAAxQAAANgIAIQgIAIgNAAgAgKglIAABLIAAAAIABABIAJAAQAEgBAEgEQADgEAAgHIAAguQAAgHgDgEQgDgEgFAAIgJAAIgBAAg");
	this.shape_66.setTransform(121.525,153.375);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20}]},119).to({state:[]},148).to({state:[{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20}]},119).to({state:[]},148).to({state:[{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20}]},119).wait(148));

	// Слой_2
	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.388)","rgba(255,255,255,0)"],[0,0.51,1],-205.4,-82,-75,-31.3).s().p("AqBCMQggAAAAggIAAjWQAAghAgAAIUCAAQAhAAAAAhIAADWQAAAgghAAg");
	this.shape_67.setTransform(150,114.975);
	this.shape_67._off = true;

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.388)","rgba(255,255,255,0)"],[0,0.51,1],-190.6,-77.5,-60.2,-26.8).s().p("AqBCMQggAAAAggIAAjWQAAghAgAAIUCAAQAhAAAAAhIAADWQAAAgghAAg");
	this.shape_68.setTransform(150,114.975);
	this.shape_68._off = true;

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.388)","rgba(255,255,255,0)"],[0,0.51,1],-175.7,-72.9,-45.3,-22.2).s().p("AqBCMQggAAAAggIAAjWQAAghAgAAIUCAAQAhAAAAAhIAADWQAAAgghAAg");
	this.shape_69.setTransform(150,114.975);
	this.shape_69._off = true;

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.388)","rgba(255,255,255,0)"],[0,0.51,1],-160.9,-68.4,-30.5,-17.7).s().p("AqBCMQggAAAAggIAAjWQAAghAgAAIUCAAQAhAAAAAhIAADWQAAAgghAAg");
	this.shape_70.setTransform(150,114.975);
	this.shape_70._off = true;

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.388)","rgba(255,255,255,0)"],[0,0.51,1],-146.1,-63.8,-15.7,-13.1).s().p("AqBCMQggAAAAggIAAjWQAAghAgAAIUCAAQAhAAAAAhIAADWQAAAgghAAg");
	this.shape_71.setTransform(150,114.975);
	this.shape_71._off = true;

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.388)","rgba(255,255,255,0)"],[0,0.51,1],-131.2,-59.2,-0.8,-8.5).s().p("AqBCMQggAAAAggIAAjWQAAghAgAAIUCAAQAhAAAAAhIAADWQAAAgghAAg");
	this.shape_72.setTransform(150,114.975);
	this.shape_72._off = true;

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.388)","rgba(255,255,255,0)"],[0,0.51,1],-116.4,-54.7,14,-4).s().p("AqBCMQggAAAAggIAAjWQAAghAgAAIUCAAQAhAAAAAhIAADWQAAAgghAAg");
	this.shape_73.setTransform(150,114.975);
	this.shape_73._off = true;

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.388)","rgba(255,255,255,0)"],[0,0.51,1],-101.5,-50.1,28.9,0.6).s().p("AqBCMQggAAAAggIAAjWQAAghAgAAIUCAAQAhAAAAAhIAADWQAAAgghAAg");
	this.shape_74.setTransform(150,114.975);
	this.shape_74._off = true;

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.388)","rgba(255,255,255,0)"],[0,0.51,1],-86.7,-45.6,43.7,5.1).s().p("AqBCMQggAAAAggIAAjWQAAghAgAAIUCAAQAhAAAAAhIAADWQAAAgghAAg");
	this.shape_75.setTransform(150,114.975);
	this.shape_75._off = true;

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.388)","rgba(255,255,255,0)"],[0,0.51,1],-71.8,-41,58.6,9.7).s().p("AqBCMQggAAAAggIAAjWQAAghAgAAIUCAAQAhAAAAAhIAADWQAAAgghAAg");
	this.shape_76.setTransform(150,114.975);
	this.shape_76._off = true;

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.388)","rgba(255,255,255,0)"],[0,0.51,1],-57,-36.4,73.4,14.3).s().p("AqBCMQggAAAAggIAAjWQAAghAgAAIUCAAQAhAAAAAhIAADWQAAAgghAAg");
	this.shape_77.setTransform(150,114.975);
	this.shape_77._off = true;

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.388)","rgba(255,255,255,0)"],[0,0.51,1],-42.2,-31.9,88.2,18.8).s().p("AqBCMQggAAAAggIAAjWQAAghAgAAIUCAAQAhAAAAAhIAADWQAAAgghAAg");
	this.shape_78.setTransform(150,114.975);
	this.shape_78._off = true;

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.388)","rgba(255,255,255,0)"],[0,0.51,1],-27.3,-27.3,103.1,23.4).s().p("AqBCMQggAAAAggIAAjWQAAghAgAAIUCAAQAhAAAAAhIAADWQAAAgghAAg");
	this.shape_79.setTransform(150,114.975);
	this.shape_79._off = true;

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.388)","rgba(255,255,255,0)"],[0,0.51,1],-12.5,-22.8,117.9,27.9).s().p("AqBCMQggAAAAggIAAjWQAAghAgAAIUCAAQAhAAAAAhIAADWQAAAgghAAg");
	this.shape_80.setTransform(150,114.975);
	this.shape_80._off = true;

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.388)","rgba(255,255,255,0)"],[0,0.51,1],2.4,-18.3,132.8,32.4).s().p("AqBCMQggAAAAggIAAjWQAAghAgAAIUCAAQAhAAAAAhIAADWQAAAgghAAg");
	this.shape_81.setTransform(150,114.975);
	this.shape_81._off = true;

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.388)","rgba(255,255,255,0)"],[0,0.51,1],17.2,-13.7,147.6,37).s().p("AqBCMQggAAAAggIAAjWQAAghAgAAIUCAAQAhAAAAAhIAADWQAAAgghAAg");
	this.shape_82.setTransform(150,114.975);
	this.shape_82._off = true;

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.388)","rgba(255,255,255,0)"],[0,0.51,1],32,-9.1,162.4,41.6).s().p("AqBCMQggAAAAggIAAjWQAAghAgAAIUCAAQAhAAAAAhIAADWQAAAgghAAg");
	this.shape_83.setTransform(150,114.975);
	this.shape_83._off = true;

	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.388)","rgba(255,255,255,0)"],[0,0.51,1],46.9,-4.6,177.3,46.1).s().p("AqBCMQggAAAAggIAAjWQAAghAgAAIUCAAQAhAAAAAhIAADWQAAAgghAAg");
	this.shape_84.setTransform(150,114.975);
	this.shape_84._off = true;

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.388)","rgba(255,255,255,0)"],[0,0.51,1],61.7,0,192.1,50.7).s().p("AqBCMQggAAAAggIAAjWQAAghAgAAIUCAAQAhAAAAAhIAADWQAAAgghAAg");
	this.shape_85.setTransform(150,114.975);
	this.shape_85._off = true;

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.388)","rgba(255,255,255,0)"],[0,0.51,1],76.6,4.5,207,55.2).s().p("AqBCMQggAAAAggIAAjWQAAghAgAAIUCAAQAhAAAAAhIAADWQAAAgghAAg");
	this.shape_86.setTransform(150,114.975);
	this.shape_86._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape_67).wait(119).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(169).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(169).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(50));
	this.timeline.addTween(cjs.Tween.get(this.shape_68).wait(120).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(169).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(169).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(49));
	this.timeline.addTween(cjs.Tween.get(this.shape_69).wait(121).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(169).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(169).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(48));
	this.timeline.addTween(cjs.Tween.get(this.shape_70).wait(122).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(169).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(169).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(47));
	this.timeline.addTween(cjs.Tween.get(this.shape_71).wait(123).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(169).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(169).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(46));
	this.timeline.addTween(cjs.Tween.get(this.shape_72).wait(124).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(169).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(169).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(45));
	this.timeline.addTween(cjs.Tween.get(this.shape_73).wait(125).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(169).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(169).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(44));
	this.timeline.addTween(cjs.Tween.get(this.shape_74).wait(126).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(169).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(169).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(43));
	this.timeline.addTween(cjs.Tween.get(this.shape_75).wait(127).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(169).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(169).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(42));
	this.timeline.addTween(cjs.Tween.get(this.shape_76).wait(128).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(169).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(169).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(41));
	this.timeline.addTween(cjs.Tween.get(this.shape_77).wait(129).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(169).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(169).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(40));
	this.timeline.addTween(cjs.Tween.get(this.shape_78).wait(130).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(169).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(169).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(39));
	this.timeline.addTween(cjs.Tween.get(this.shape_79).wait(131).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(169).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(169).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(38));
	this.timeline.addTween(cjs.Tween.get(this.shape_80).wait(132).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(169).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(169).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(37));
	this.timeline.addTween(cjs.Tween.get(this.shape_81).wait(133).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(169).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(169).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(36));
	this.timeline.addTween(cjs.Tween.get(this.shape_82).wait(134).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(169).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(169).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(35));
	this.timeline.addTween(cjs.Tween.get(this.shape_83).wait(135).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(169).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(169).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(34));
	this.timeline.addTween(cjs.Tween.get(this.shape_84).wait(136).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(169).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(169).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(33));
	this.timeline.addTween(cjs.Tween.get(this.shape_85).wait(137).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(169).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(169).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(32));
	this.timeline.addTween(cjs.Tween.get(this.shape_86).wait(138).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(169).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(169).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(49).to({_off:false},0).to({_off:true},1).wait(31));

	// Слой_3
	this.instance_1 = new lib.btn();
	this.instance_1.parent = this;
	this.instance_1.setTransform(150.1,115.05,1.0783,1.0783,0,0,0,64.6,15.1);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(119).to({_off:false},0).to({_off:true},148).wait(119).to({_off:false},0).to({_off:true},148).wait(119).to({_off:false},0).wait(148));

	// t1.1
	this.instance_2 = new lib.t21();
	this.instance_2.parent = this;
	this.instance_2.setTransform(89.9,44.95,0.8356,0.8356,0,0,0,85,51.8);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(119).to({_off:false},0).to({_off:true},148).wait(119).to({_off:false},0).to({_off:true},148).wait(119).to({_off:false},0).wait(148));

	// t1.1
	this.instance_3 = new lib.t11();
	this.instance_3.parent = this;
	this.instance_3.setTransform(13,26.1,1.6838,1.6838);
	this.instance_3.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({y:6.1,alpha:1},29).wait(69).to({alpha:0},21,cjs.Ease.get(-1)).to({_off:true},1).wait(147).to({_off:false,y:26.1},0).to({y:6.1,alpha:1},29).wait(69).to({alpha:0},21,cjs.Ease.get(-1)).to({_off:true},1).wait(147).to({_off:false,y:26.1},0).to({y:6.1,alpha:1},29).wait(69).to({alpha:0},21,cjs.Ease.get(-1)).to({_off:true},1).wait(147));

	// bg-2
	this.instance_4 = new lib.bg2();
	this.instance_4.parent = this;
	this.instance_4.setTransform(217,203,0.5,0.5,0,0,0,300,250);
	this.instance_4.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({alpha:1},15,cjs.Ease.get(1)).wait(252).to({alpha:0},0).to({alpha:1},15,cjs.Ease.get(1)).wait(252).to({alpha:0},0).to({alpha:1},15,cjs.Ease.get(1)).wait(252));

	// Слой_15
	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.f("#FFFFFF").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape_87.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape_87).wait(801));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(145.5,295.5,159,363);
// library properties:
lib.properties = {
	id: '307B5D341DDBB5459CF568EEF0A1BE55',
	width: 300,
	height: 600,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/_160x600.jpg", id:"_160x600"},
		{src:"images/300x600TFHTML532_atlas_.png", id:"300x600TFHTML532_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['307B5D341DDBB5459CF568EEF0A1BE55'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;