(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib.book = function() {
	this.initialize(img.book);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,396,315);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.t22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAZBaQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIgVhmIgBgBIAAABIgTBmQAAABAAAAQAAABgBAAQAAABgBAAQgBAAAAAAIgcAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBgBAAgBIgoisIAAgBQAAgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAIAgAAQAAAAABAAQABAAAAABQAAAAABABQAAAAAAABIATBiIABABIABgBIAThiQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAIAcAAQAAAAABAAQAAAAABABQAAAAAAABQABAAAAABIAUBiIABABIABgBIAShiQAAgBABAAQAAgBAAAAQABgBAAAAQABAAABAAIAeAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIgmCsQAAABAAAAQAAABgBAAQAAABgBAAQgBAAAAAAg");
	this.shape.setTransform(340.8,80.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgeBVQgOgHgHgNQgIgOAAgRIAAhDQAAgRAIgOQAHgNAOgHQANgHARAAQASAAANAHQAOAHAHANQAIAOAAARIAABDQAAARgIAOQgHANgOAHQgNAHgSAAQgRAAgNgHgAgQg1QgGAHAAAMIAABGQAAALAGAHQAGAHAKAAQALAAAGgHQAHgHAAgLIAAhGQAAgMgHgHQgGgHgLAAQgKAAgGAHg");
	this.shape_1.setTransform(323.8,80.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAcBaQAAAAgBAAQAAAAgBgBQAAAAgBAAQAAgBAAgBIgxhlIgBgBIAAABIAABlIgBACIgCABIgeAAIgCgBIgBgCIAAisIABgDIACgBIAfAAQAAAAABAAQAAAAABABQAAAAABAAQAAABAAABIAxBlIABAAIAAAAIAAhkIABgDIACgBIAeAAIACABIABADIAACsIgBACIgCABg");
	this.shape_2.setTransform(309.2,80.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAbBaQAAAAgBAAQAAAAgBgBQAAAAgBAAQAAgBAAgBIgkhGIAAgBIgBABIgMARIgBABIAAA0IgBACIgCABIgeAAIgCgBIgBgCIAAisIABgDIACgBIAeAAIACABIABADIAABDIABABIABAAIAthGQAAAAABgBQAAAAAAAAQABgBAAAAQABAAAAAAIAiAAIACABIAAADIgwBKIAAABIAyBhIABABQAAABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAg");
	this.shape_3.setTransform(295,80.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgeBVQgOgHgHgNQgIgOAAgRIAAhDQAAgRAIgOQAHgNAOgHQANgHARAAQASAAANAHQAOAHAHANQAIAOAAARIAABDQAAARgIAOQgHANgOAHQgNAHgSAAQgRAAgNgHgAgQg1QgGAHAAAMIAABGQAAALAGAHQAGAHAKAAQALAAAGgHQAHgHAAgLIAAhGQAAgMgHgHQgGgHgLAAQgKAAgGAHg");
	this.shape_4.setTransform(275.2,80.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgPBaIgCgBIAAgCIAAiPQAAAAgBgBQAAAAAAAAQAAAAAAAAQgBAAAAAAIglAAIgDgBIgBgDIAAgYIABgDIADgBIByAAIACABIABADIAAAYIgBADIgCABIgnAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQAAABAAAAIAACPIgBACIgCABg");
	this.shape_5.setTransform(261.4,80.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgeBUQgNgHgIgOQgHgNAAgQIAAh4IABgDIACgBIAeAAIACABIABADIAAB5QAAALAGAHQAHAHAJAAQAKAAAGgHQAHgHAAgLIAAh5IAAgDIADgBIAeAAIACABIABADIAAB4QAAAQgIANQgHAOgNAHQgOAHgRAAQgRAAgNgHg");
	this.shape_6.setTransform(242.4,80.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgeBVQgOgHgHgNQgIgOAAgRIAAhDQAAgRAIgOQAHgNAOgHQANgHARAAQASAAANAHQAOAHAHANQAIAOAAARIAABDQAAARgIAOQgHANgOAHQgNAHgSAAQgRAAgNgHgAgQg1QgGAHAAAMIAABGQAAALAGAHQAGAHAKAAQALAAAGgHQAHgHAAgLIAAhGQAAgMgHgHQgGgHgLAAQgKAAgGAHg");
	this.shape_7.setTransform(228.3,80.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgOBaIgCgBIgBgCIAAhCIgBgBIgshpIAAgCQAAAAAAgBQAAAAABAAQAAAAAAgBQABAAAAAAIAhAAQAAAAABAAQABABAAAAQAAAAABABQAAAAAAABIAYBBIAAABIABgBIAYhBQAAgBAAAAQABgBAAAAQAAAAABgBQABAAAAAAIAgAAIADABIAAADIgtBpIAAABIAABCIgBACIgCABg");
	this.shape_8.setTransform(214.3,80.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgPBaIgCgBIAAgCIAAiPQgBAAAAgBQAAAAAAAAQAAAAAAAAQgBAAAAAAIglAAIgDgBIgBgDIAAgYIABgDIADgBIByAAIACABIABADIAAAYIgBADIgCABIgnAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQgBABAAAAIAACPIAAACIgCABg");
	this.shape_9.setTransform(195.4,80.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAcBaQAAAAgBAAQAAAAgBgBQAAAAgBAAQAAgBAAgBIgxhlIgBgBIAAABIAABlIgBACIgCABIgeAAIgCgBIgBgCIAAisIABgDIACgBIAfAAQAAAAABAAQAAAAABABQAAAAABAAQAAABAAABIAxBlIABAAIAAAAIAAhkIABgDIACgBIAeAAIACABIABADIAACsIgBACIgCABg");
	this.shape_10.setTransform(181.1,80.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAjBaQgBAAgBAAQAAAAgBgBQAAAAAAAAQgBgBAAgBIgGgZIgBgBIgvAAIgBABIgGAZQAAABgBABQAAAAgBAAQAAABgBAAQAAAAgBAAIgfAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAAAIAvitQAAgBAAgBQAAAAABAAQAAgBABAAQABAAAAAAIAlAAQAAAAABAAQAAAAABABQAAAAABAAQAAABAAABIAvCtIAAAAQAAABAAABQgBAAAAAAQAAABgBAAQAAAAgBAAgAAAgpIAAABIgRBIIAAABIABAAIAhAAIABAAQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAAAIgRhIIAAgBIgBAAg");
	this.shape_11.setTransform(166,80.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAZBaQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIgVhmIgBgBIAAABIgTBmQAAABAAAAQAAABgBAAQAAABgBAAQgBAAAAAAIgcAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBgBAAgBIgoisIAAgBQAAgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAIAgAAQAAAAABAAQABAAAAABQAAAAABABQAAAAAAABIATBiIABABIABgBIAThiQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAIAcAAQAAAAABAAQAAAAABABQAAAAAAABQABAAAAABIAUBiIABABIABgBIAShiQAAgBABAAQAAgBAAAAQABgBAAAAQABAAABAAIAeAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIgmCsQAAABAAAAQAAABgBAAQAAABgBAAQgBAAAAAAg");
	this.shape_12.setTransform(148.6,80.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgOBaIgDgBIgBgCIAAiPQAAAAAAgBQAAAAAAAAQAAAAAAAAQgBAAAAAAIglAAIgDgBIgBgDIAAgYIABgDIADgBIByAAIACABIABADIAAAYIgBADIgCABIgnAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQgBABAAAAIAACPIgBACIgBABg");
	this.shape_13.setTransform(126.7,80.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgLAdIgCgBIgBgCIgDgzQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAAAIAeAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIgEAzIgBACIgCABg");
	this.shape_14.setTransform(117.8,74.8);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAcBaQAAAAgBAAQAAAAgBgBQAAAAgBAAQAAgBAAgBIgxhlIgBgBIAAABIAABlIgBACIgCABIgeAAIgCgBIgBgCIAAisIABgDIACgBIAfAAQAAAAABAAQAAAAABABQAAAAABAAQAAABAAABIAxBlIABAAIAAAAIAAhkIABgDIACgBIAeAAIACABIABADIAACsIgBACIgCABg");
	this.shape_15.setTransform(108.1,80.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgeBVQgOgHgHgNQgIgOAAgRIAAhDQAAgRAIgOQAHgNAOgHQANgHARAAQASAAANAHQAOAHAHANQAIAOAAARIAABDQAAARgIAOQgHANgOAHQgNAHgSAAQgRAAgNgHgAgQg1QgGAHAAAMIAABGQAAALAGAHQAGAHAKAAQALAAAGgHQAHgHAAgLIAAhGQAAgMgHgHQgGgHgLAAQgKAAgGAHg");
	this.shape_16.setTransform(93.5,80.8);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("Ag2BaIgCgBIgBgCIAAisIABgDIACgBIA2AAQARAAAOAGQANAHAHAMQAHALAAAQIAABLQAAAQgHAMQgHALgNAHQgOAGgRAAgAgVg4IAAByQAAAAAAAAQAAAAABABQAAAAAAAAQAAAAAAAAIAUAAQAKgBAGgGQAGgHAAgLIAAhCQAAgMgGgHQgGgHgKAAIgUAAQAAAAAAAAQAAAAAAAAQgBABAAAAQAAAAAAABg");
	this.shape_17.setTransform(79.6,80.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgeBVQgNgGgHgLQgHgMAAgPIAAgGIAAgDIADAAIAdAAIACAAIABADIAAAFQAAAJAHAGQAHAGAJAAQALAAAFgFQAFgFAAgJQAAgFgDgFQgEgDgFgFIgSgKIgagOQgJgFgHgLQgHgLAAgOQAAgXAPgNQAQgOAZAAQAQAAANAGQAOAHAHAMQAIAMAAAPIAAAGIgBACIgCABIgeAAIgCgBIgBgCIAAgFQAAgJgHgHQgGgGgJAAQgKAAgFAFQgGAFAAAIQAAAGAEAFQADAEAHAEIASALIAFACIAXAOQAJAGAGAJQAFAJAAANQAAAXgQAOQgQAOgaAAQgRAAgNgHg");
	this.shape_18.setTransform(236.6,48.6);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgPBaIgCgBIAAgCIAAiPQAAAAgBgBQAAAAAAAAQAAAAAAAAQgBAAAAgBIgmAAIgCAAIgBgCIAAgZIABgDIACgBIBzAAIACABIABADIAAAZIgBACIgCAAIgnAAQAAABgBAAQAAAAAAAAQAAAAAAAAQAAABAAAAIAACPIgBACIgDABg");
	this.shape_19.setTransform(223.1,48.6);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAcBaQAAAAgBAAQAAAAgBgBQAAAAgBAAQAAgBAAgBIgxhlIgBgBIAAABIAABlIgBACIgCABIgeAAIgCgBIgBgCIAAisIABgDIACgBIAfAAQAAAAABAAQAAAAABABQAAAAABAAQAAABAAABIAxBlIABAAIAAgBIAAhjIABgDIACgBIAeAAIACABIABADIAACsIgBACIgCABg");
	this.shape_20.setTransform(208.8,48.6);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgzBaIgCgBIgBgCIAAisIABgDIACgBIBnAAIACABIABADIAAAYIgBADIgCAAIhEAAQAAAAgBAAQAAAAAAAAQAAABAAAAQAAAAAAAAIAAApQAAAAAAAAQAAAAAAABQAAAAAAAAQABAAAAAAIAqAAIACABIABACIAAAYIgBACIgCABIgqAAIgBABIAAAqQAAAAAAAAQAAAAAAABQAAAAAAAAQABAAAAAAIBEAAIACABIABACIAAAZIgBACIgCABg");
	this.shape_21.setTransform(194.9,48.6);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgeBVQgNgHgHgMQgIgOAAgQIAAhHQAAgRAIgNQAHgMANgHQAOgHAQAAQARAAAOAHQANAHAIAMQAHAMAAAPIAAAGIgBACIgCABIgeAAIgCgBIgBgCIAAgFQAAgKgGgHQgHgGgKAAQgJAAgGAHQgHAHAAAKIAABJQAAALAHAGQAGAHAKAAQAKAAAGgGQAGgGAAgKIAAgQQAAAAAAgBQAAAAgBAAQAAAAAAAAQAAAAAAAAIgUAAIgCgBIAAgCIAAgXIAAgCIACgBIA2AAIACABIABACIAAAoQAAAagQAPQgQAPgbAAQgQAAgOgHg");
	this.shape_22.setTransform(181.3,48.6);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AAjBaQgBAAgBAAQAAAAgBgBQAAAAAAAAQgBgBAAgBIgGgZIgBgBIgvAAIgBABIgGAZQAAABgBABQAAAAgBAAQAAABgBAAQAAAAgBAAIgfAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAgBIAvisQAAgBAAgBQAAAAABAAQAAgBABAAQABAAAAAAIAlAAQAAAAABAAQAAAAABABQAAAAABAAQAAABAAABIAvCsIAAABQAAABAAABQgBAAAAAAQAAABgBAAQAAAAgBAAgAAAgpIAAABIgRBHIAAACIABAAIAhAAIABAAQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIgRhHIAAgBIgBAAg");
	this.shape_23.setTransform(166.8,48.6);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgzBaIgCgBIgBgCIAAisIABgDIACgBIBnAAIACABIABADIAAAYIgBADIgCAAIhEAAQgBAAAAAAQAAAAAAAAQAAABAAAAQAAAAAAAAIAAApQAAAAAAAAQAAAAAAABQAAAAAAAAQAAAAABAAIAqAAIACABIABACIAAAYIgBACIgCABIgqAAIgBABIAAAqQAAAAAAAAQAAAAAAABQAAAAAAAAQAAAAABAAIBEAAIACABIABACIAAAZIgBACIgCABg");
	this.shape_24.setTransform(147.8,48.6);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgPBaIgCgBIgBgCIAAiPQAAAAAAgBQAAAAAAAAQAAAAAAAAQgBAAAAgBIglAAIgDAAIgBgCIAAgZIABgDIADgBIByAAIACABIABADIAAAZIgBACIgCAAIgnAAQAAABgBAAQAAAAAAAAQAAAAAAAAQgBABAAAAIAACPIgBACIgBABg");
	this.shape_25.setTransform(134.3,48.6);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AAjBaQgBAAgBAAQAAAAgBgBQAAAAAAAAQgBgBAAgBIgGgZIgBgBIgvAAIgBABIgGAZQAAABgBABQAAAAgBAAQAAABgBAAQAAAAgBAAIgfAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAgBIAvisQAAgBAAgBQAAAAABAAQAAgBABAAQABAAAAAAIAlAAQAAAAABAAQAAAAABABQAAAAABAAQAAABAAABIAvCsIAAABQAAABAAABQgBAAAAAAQAAABgBAAQAAAAgBAAgAAAgpIAAABIgRBHIAAACIABAAIAhAAIABAAQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIgRhHIAAgBIgBAAg");
	this.shape_26.setTransform(120,48.6);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgPBaIgCgBIAAgCIAAiPQAAAAgBgBQAAAAAAAAQAAAAAAAAQgBAAAAgBIglAAIgDAAIgBgCIAAgZIABgDIADgBIByAAIACABIABADIAAAZIgBACIgCAAIgnAAQAAABgBAAQAAAAAAAAQAAAAAAAAQAAABAAAAIAACPIgBACIgCABg");
	this.shape_27.setTransform(105.7,48.6);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgeBVQgNgGgHgLQgHgMAAgPIAAgGIAAgDIADAAIAeAAIACAAIAAADIAAAFQABAJAGAGQAHAGAKAAQAKAAAFgFQAFgFAAgJQAAgFgDgFQgEgDgFgFIgSgKIgZgOQgKgFgHgLQgHgLAAgOQAAgXAQgNQAPgOAZAAQAQAAAOAGQANAHAHAMQAIAMAAAPIAAAGIgBACIgCABIgeAAIgCgBIgBgCIAAgFQAAgJgHgHQgFgGgLAAQgJAAgFAFQgFAFgBAIQABAGADAFQADAEAHAEIASALIAFACIAYAOQAIAGAFAJQAGAJAAANQAAAXgQAOQgPAOgbAAQgQAAgOgHg");
	this.shape_28.setTransform(92.4,48.6);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgzBaIgCgBIgBgCIAAisIABgDIACgBIBnAAIACABIABADIAAAYIgBADIgCAAIhEAAQAAAAgBAAQAAAAAAAAQAAABAAAAQAAAAAAAAIAAApQAAAAAAAAQAAAAAAABQAAAAAAAAQABAAAAAAIAqAAIACABIABACIAAAYIgBACIgCABIgqAAIgBABIAAAqQAAAAAAAAQAAAAAAABQAAAAAAAAQABAAAAAAIBEAAIACABIABACIAAAZIgBACIgCABg");
	this.shape_29.setTransform(79.3,48.6);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgzBaIgCgBIgBgCIAAitIABgCIACgBIAfAAIACABIABACIAACPQAAABAAAAQAAAAAAABQAAAAAAAAQABAAAAAAIBEAAIACABIABACIAAAZIgBACIgCABg");
	this.shape_30.setTransform(189.3,25.9);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AAjBaQgBAAgBAAQAAAAgBgBQAAAAAAAAQgBgBAAgBIgGgYIgBgBIgvAAIgBABIgGAYQAAABgBABQAAAAgBAAQAAABgBAAQAAAAgBAAIgfAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAgBIAvisQAAgBAAgBQAAAAABAAQAAgBABAAQABAAAAAAIAlAAQAAAAABAAQAAAAABABQAAAAABAAQAAABAAABIAvCsIAAABQAAABAAABQgBAAAAAAQAAABgBAAQAAAAgBAAgAAAgpIAAAAIgRBIIAAACIABAAIAhAAIABAAQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIgRhIIAAAAIgBAAg");
	this.shape_31.setTransform(174.9,25.9);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgzBaIgCgBIgBgCIAAitIABgCIACgBIBnAAIACABIABACIAAAZIgBACIgCABIhEAAQAAAAgBAAQAAAAAAAAQAAABAAAAQAAAAAAAAIAAApQAAAAAAAAQAAAAAAABQAAAAAAAAQABAAAAAAIAqAAIACABIABACIAAAYIgBACIgCABIgqAAIgBABIAAApQAAABAAAAQAAAAAAABQAAAAAAAAQABAAAAAAIBEAAIACABIABACIAAAZIgBACIgCABg");
	this.shape_32.setTransform(161.1,25.9);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AAZBaQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAgBIgahGIAAgCIgRAAIgBACIAABGIgBACIgCABIgfAAIgCgBIAAgCIAAitIAAgCIACgBIA+AAQAPAAAMAHQAMAGAGANQAHAMAAAQQAAARgIAMQgGALgOAGQAAAAAAAAQgBAAAAABQAAAAAAAAQAAAAABAAIAdBKIAAABQAAABAAABQAAAAAAAAQgBABAAAAQgBAAAAAAgAgWg5IAAAsIABABIAWAAQAJABAGgHQAGgGAAgKQAAgLgGgGQgGgHgJAAIgWAAQAAAAAAAAQgBAAAAAAQAAABAAAAQAAAAAAAAg");
	this.shape_33.setTransform(147.6,25.9);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgPBaIgCgBIgBgCIAAiPQAAAAAAgBQAAAAAAAAQAAAAAAAAQgBgBAAAAIglAAIgDgBIgBgBIAAgaIABgCIADgBIByAAIACABIABACIAAAaIgBABIgCABIgnAAQAAAAgBABQAAAAAAAAQAAAAAAAAQgBABAAAAIAACPIAAACIgCABg");
	this.shape_34.setTransform(128.4,25.9);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AAjBaQgBAAgBAAQAAAAgBgBQAAAAAAAAQgBgBAAgBIgGgYIgBgBIgvAAIgBABIgGAYQAAABgBABQAAAAgBAAQAAABgBAAQAAAAgBAAIgfAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAgBIAvisQAAgBAAgBQAAAAABAAQAAgBABAAQABAAAAAAIAlAAQAAAAABAAQAAAAABABQAAAAABAAQAAABAAABIAvCsIAAABQAAABAAABQgBAAAAAAQAAABgBAAQAAAAgBAAgAAAgpIAAAAIgRBIIAAACIABAAIAhAAIABAAQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIgRhIIAAAAIgBAAg");
	this.shape_35.setTransform(114.1,25.9);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AAZBaIgCgBIgBgCIAAhGQAAgBAAAAQAAAAAAgBQgBAAAAAAQAAAAAAAAIgpAAQAAAAAAAAQAAAAAAAAQAAABAAAAQgBAAAAABIAABGIgBACIgBABIgfAAIgCgBIgBgCIAAitIABgCIACgBIAfAAIABABIABACIAABGQAAAAABAAQAAAAAAABQAAAAAAAAQAAAAAAAAIApAAQAAAAAAAAQAAAAABAAQAAgBAAAAQAAAAAAAAIAAhGIABgCIACgBIAeAAIACABIABACIAACtIgBACIgCABg");
	this.shape_36.setTransform(99.6,25.9);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AAZBaQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIgVhmIgBgBIAAABIgTBmQAAABAAAAQAAABgBAAQAAABgBAAQgBAAAAAAIgcAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBgBAAgBIgoitIAAAAQAAgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAIAgAAQAAAAABAAQABAAAAABQAAAAABABQAAAAAAABIATBhIABABIABgBIAThhQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAIAcAAQAAAAABAAQAAAAABABQAAAAAAABQABAAAAABIAUBhIABABIABgBIAShhQAAgBABAAQAAgBAAAAQABgBAAAAQABAAABAAIAeAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAAAIgmCtQAAABAAAAQAAABgBAAQAAABgBAAQgBAAAAAAg");
	this.shape_37.setTransform(82.4,25.9);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AAcBaQAAAAgBAAQAAAAgBgBQAAAAgBAAQAAgBAAAAIgxhnIgBAAIAAABIAABlIgBACIgCABIgeAAIgCgBIgBgCIAAitIABgCIACgBIAfAAQAAAAABAAQAAAAABABQAAAAABAAQAAABAAAAIAxBmIABABIAAgBIAAhlIABgCIACgBIAeAAIACABIABACIAACtIgBACIgCABg");
	this.shape_38.setTransform(134.9,-6.3);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AAZBaQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAAAIgZhHIgBgBIgRAAIgBABIAABGIgBACIgCABIgeAAIgCgBIgBgCIAAitIABgCIACgBIA+AAQAOAAANAHQALAHAHAMQAGAMAAAQQAAARgHAMQgIALgNAGQAAAAAAAAQgBAAAAABQAAAAAAAAQAAAAAAAAIAeBLIABABQAAAAgBABQAAAAAAAAQgBABAAAAQgBAAgBAAgAgWg4IAAArIABACIAVAAQAKAAAGgHQAGgGAAgLQAAgKgGgHQgGgGgKAAIgVAAQAAAAAAAAQgBAAAAAAQAAABAAAAQAAAAAAABg");
	this.shape_39.setTransform(120.8,-6.3);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AAjBaQgBAAgBAAQAAAAgBgBQAAAAAAAAQgBgBAAAAIgGgZIgBgBIgvAAIgBABIgGAZQAAAAgBABQAAAAgBAAQAAABgBAAQAAAAgBAAIgfAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAAAIAviuQAAAAAAgBQAAAAABAAQAAgBABAAQABAAAAAAIAlAAQAAAAABAAQAAAAABABQAAAAABAAQAAABAAAAIAvCuIAAABQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAgBAAgAAAgpIAAAAIgRBIIAAACIABAAIAhAAIABAAQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIgRhIIAAAAIgBAAg");
	this.shape_40.setTransform(105.9,-6.3);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AgzBaIgCgBIgBgCIAAitIABgCIACgBIBnAAIACABIABACIAAAZIgBACIgCABIhEAAQAAAAgBAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAAnQAAABAAAAQAAAAAAABQAAAAAAAAQABAAAAAAIAqAAIACABIABACIAAAYIgBACIgCABIgqAAIgBABIAAApQAAABAAAAQAAAAAAABQAAAAAAAAQABAAAAAAIBEAAIACABIABACIAAAZIgBACIgCABg");
	this.shape_41.setTransform(92.1,-6.3);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AgzBaIgCgBIgBgCIAAitIABgCIACgBIAfAAIACABIABACIAACPQAAABAAAAQAAAAAAABQAAAAAAAAQABAAAAAAIBEAAIACABIABACIAAAZIgBACIgCABg");
	this.shape_42.setTransform(79.3,-6.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.t22, new cjs.Rectangle(71,-24,316,122.3), null);


(lib.t2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag8BpIgCgBIgBgCIAAjLIABgCIACgBIB4AAIADABIABACIAAAdIgBADIgDABIhPAAQAAAAgBAAQAAAAAAAAQAAAAAAABQgBAAAAAAIAAAvQAAABABAAQAAAAAAAAQAAABAAAAQABAAAAAAIAxAAIACABIABADIAAAcIgBACIgCABIgxAAQAAAAgBAAQAAAAAAABQAAAAAAAAQgBAAAAABIAAAwQAAABABAAQAAAAAAAAQAAABAAAAQABAAAAAAIBPAAIADABIABACIAAAeIgBACIgDABg");
	this.shape.setTransform(124.9,78.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAoBpIgDgBQAAAAgBAAQAAgBAAAAQAAAAAAgBQgBAAAAAAIAAiCIAAgBIgBABIgZArQgBADgDAAIgJAAQgDAAgCgDIgYgrIgBgBIgBABIAACCIgBACIgCABIgkAAIgCgBIgBgCIAAjLIABgCIACgBIAjAAQADAAABACIAjA/QAAAAAAAAQAAAAAAAAQAAAAABAAQAAAAAAAAIAig/QACgCADAAIAjAAIACABIABACIAADLIgBACIgCABg");
	this.shape_1.setTransform(107.5,78.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgkBkQgPgJgJgPQgJgQAAgUIAAhPQAAgUAJgQQAJgPAPgIQAQgJAUAAQAVAAAQAJQAQAIAIAPQAJAQAAAUIAABPQAAAUgJAQQgIAPgQAJQgQAIgVAAQgUAAgQgIgAgTg+QgHAIAAAOIAABSQAAANAHAIQAIAJALAAQANAAAHgJQAIgIAAgNIAAhSQAAgOgIgIQgHgIgNAAQgLAAgIAIg");
	this.shape_2.setTransform(89.8,78.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAdBpIgCgBIgBgCIAAhTQAAAAgBAAQAAgBAAAAQAAAAAAAAQgBAAAAAAIgvAAQAAAAgBAAQAAAAAAAAQAAAAAAABQgBAAAAAAIAABTIAAACIgDABIgjAAIgDgBIgBgCIAAjLIABgCIADgBIAjAAIADABIAAACIAABRQAAABABAAQAAAAAAAAQAAABAAAAQABAAAAAAIAvAAQAAAAABAAQAAAAAAgBQAAAAAAAAQABAAAAgBIAAhRIABgCIACgBIAjAAIADABIABACIAADLIgBACIgDABg");
	this.shape_3.setTransform(73.3,78.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAhBpQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAgBgBAAIg4h4IgBgBIgBABIABB3IgBACIgDABIgjAAIgDgBIgBgCIAAjLIABgCIADgBIAjAAQABAAABAAQABAAAAAAQABABAAAAQAAABABAAIA4B3IACABIABgBIgBh2IABgCIADgBIAjAAIACABQAAAAABAAQAAABAAAAQAAAAAAABQAAAAAAAAIAADLQAAAAAAAAQAAABAAAAQAAAAAAABQgBAAAAAAIgCABg");
	this.shape_4.setTransform(50.1,78.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAdBpQgDAAgBgDIgYh4IgBgBIAAABIgWB4QAAADgEAAIghAAQgDAAgBgDIgvjKIAAgCQAAAAAAgBQAAAAABgBQAAAAABAAQAAAAABAAIAlAAQABAAABAAQAAAAABAAQAAABABAAQAAABAAABIAXByIABABIABgBIAWhyQAAgBAAgBQAAAAABgBQAAAAABAAQABAAABAAIAgAAQADAAABADIAYByIABABIABgBIAVhyQAAgBABgBQAAAAAAgBQABAAABAAQAAAAABAAIAkAAQAEAAgBAEIgsDKQgBADgDAAg");
	this.shape_5.setTransform(29.6,78.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgkBkQgPgJgJgPQgJgQAAgUIAAhPQAAgUAJgQQAJgPAPgIQAQgJAUAAQAVAAAQAJQAQAIAIAPQAJAQAAAUIAABPQAAAUgJAQQgIAPgQAJQgQAIgVAAQgUAAgQgIgAgTg+QgHAIAAAOIAABSQAAANAHAIQAIAJALAAQANAAAHgJQAIgIAAgNIAAhSQAAgOgIgIQgHgIgNAAQgLAAgIAIg");
	this.shape_6.setTransform(9.7,78.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAdBpQAAAAgBAAQgBAAAAAAQgBgBAAAAQAAgBAAgBIgehSIgCgCIgSAAQgBAAAAAAQAAAAgBAAQAAABAAAAQAAAAAAABIAABSIgBACIgDABIgjAAIgDgBIgBgCIAAjLIABgDIADAAIBJAAQASgBANAJQAOAHAHAPQAIAOAAATQAAAUgJAOQgIANgPAHQgBAAAAAAQAAABAAAAQAAAAAAAAQAAABAAAAIAiBWIAAACQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAgBAAgAgahDIAAA0QAAAAAAABQAAAAAAAAQABAAAAAAQAAAAABAAIAZAAQALAAAHgHQAGgHABgNQgBgMgGgHQgHgIgLAAIgZAAQgBAAAAAAQAAAAgBAAQAAABAAAAQAAAAAAAAg");
	this.shape_7.setTransform(126.7,49.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgjBiQgQgJgIgOQgJgQAAgTIAAiOIABgCIADgBIAjAAIADABIABACIAACPQAAANAHAIQAHAIALAAQAMAAAHgIQAIgIAAgNIAAiPIABgCIACgBIAjAAIADABIABACIAACOQAAATgJAQQgIAOgQAJQgPAIgVAAQgTAAgQgIg");
	this.shape_8.setTransform(109.7,49.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgkBkQgPgJgJgPQgJgQAAgUIAAhPQAAgUAJgQQAJgPAPgIQAQgJAUAAQAVAAAQAJQAQAIAIAPQAJAQAAAUIAABPQAAAUgJAQQgIAPgQAJQgQAIgVAAQgUAAgQgIgAgTg+QgHAIAAAOIAABSQAAANAHAIQAIAJALAAQANAAAHgJQAIgIAAgNIAAhSQAAgOgIgIQgHgIgNAAQgLAAgIAIg");
	this.shape_9.setTransform(93.2,49.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgRBpIgCgBIgBgDIAAhNIgBgBIg0h7IAAgCQAAAAAAgBQAAAAABAAQAAgBABAAQAAAAABAAIAmAAQADAAABADIAcBMIAAABIABgBIAchMQABgDADAAIAmAAQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAAAIAAADIg1B7IAAABIAABNIgBADIgDABg");
	this.shape_10.setTransform(76.7,49.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("Ag7BpIgDgBIgBgCIAAjLIABgCIADgBIAjAAIACABIABACIAACoQAAABABAAQAAAAAAAAQAAABAAAAQABAAAAAAIBPAAIADABIABACIAAAeIgBACIgDABg");
	this.shape_11.setTransform(55.5,49.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("Ag8BpIgCgBIgBgCIAAjLIABgCIACgBIAkAAIACABIACACIAACoQAAABAAAAQAAAAAAAAQAAABAAAAQABAAAAAAIBQAAIACABIABACIAAAeIgBACIgCABg");
	this.shape_12.setTransform(40.5,49.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("Ag7BpIgDgBIgBgCIAAjLIABgCIADgBIB3AAIADABIABACIAAAdIgBADIgDABIhPAAQAAAAgBAAQAAAAAAAAQAAAAAAABQAAAAgBAAIAAAvQABABAAAAQAAAAAAAAQAAABAAAAQABAAAAAAIAxAAIADABIAAADIAAAcIAAACIgDABIgxAAQAAAAgBAAQAAAAAAABQAAAAAAAAQAAAAgBABIAAAwQABABAAAAQAAAAAAAAQAAABAAAAQABAAAAAAIBPAAIADABIABACIAAAeIgBACIgDABg");
	this.shape_13.setTransform(25.1,49.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgjBkQgPgHgJgNQgIgOAAgRIAAgIIABgDIACgBIAjAAIACABIABADIAAAGQABAKAHAHQAJAHALAAQAMAAAGgGQAGgGAAgJQAAgHgEgFQgDgFgIgEIgVgMQgRgJgMgIQgLgHgJgMQgIgNAAgRQAAgbASgPQATgQAcAAQAUAAAPAIQAQAHAJAOQAJAOAAASIAAAGIgBADIgDABIgiAAIgDgBIgBgDIAAgFQAAgLgIgHQgHgHgMAAQgLAAgGAFQgGAGAAAKQAAAHAEAFQADAFAHAFIAWAMIAHADQARAKAKAGQAKAHAGALQAHALAAAPQAAAbgSAQQgTARgfAAQgUAAgPgIg");
	this.shape_14.setTransform(9.4,49.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgkBkQgPgJgJgPQgJgQAAgUIAAhPQAAgUAJgQQAJgPAPgIQAQgJAUAAQAVAAAQAJQAQAIAIAPQAJAQAAAUIAABPQAAAUgJAQQgIAPgQAJQgQAIgVAAQgUAAgQgIgAgTg+QgHAIAAAOIAABSQAAANAHAIQAIAJALAAQANAAAHgJQAIgIAAgNIAAhSQAAgOgIgIQgHgIgNAAQgLAAgIAIg");
	this.shape_15.setTransform(88,20.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgRBpIgDgBIgBgCIAAioQAAgBAAAAQAAAAgBAAQAAgBAAAAQAAAAgBAAIgsAAIgCgBIgBgCIAAgeIABgCIACgBICHAAIACABIABACIAAAeIgBACIgCABIguAAQgBAAAAAAQAAAAAAABQgBAAAAAAQAAAAAAABIAACoIgBACIgCABg");
	this.shape_16.setTransform(71.9,20.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAdBpQgDAAgBgDIgYh4IgBgBIAAABIgWB4QAAADgEAAIghAAQgDAAgBgDIgvjKIAAgCQAAAAAAgBQAAAAABgBQAAAAABAAQAAAAABAAIAlAAQABAAABAAQAAAAABAAQAAABABAAQAAABAAABIAXByIABABIABgBIAWhyQAAgBAAgBQAAAAABgBQAAAAABAAQABAAABAAIAgAAQADAAABADIAYByIABABIABgBIAVhyQAAgBABgBQAAAAAAgBQABAAABAAQAAAAABAAIAkAAQAEAAgBAEIgsDKQgBADgDAAg");
	this.shape_17.setTransform(46.3,20.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgkBkQgPgJgJgPQgJgQAAgUIAAhPQAAgUAJgQQAJgPAPgIQAQgJAUAAQAVAAAQAJQAQAIAIAPQAJAQAAAUIAABPQAAAUgJAQQgIAPgQAJQgQAIgVAAQgUAAgQgIgAgTg+QgHAIAAAOIAABSQAAANAHAIQAIAJALAAQANAAAHgJQAIgIAAgNIAAhSQAAgOgIgIQgHgIgNAAQgLAAgIAIg");
	this.shape_18.setTransform(26.3,20.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AAdBpIgCgBIgBgCIAAhTQAAAAgBAAQAAgBAAAAQAAAAAAAAQgBAAAAAAIgvAAQAAAAgBAAQAAAAAAAAQAAAAAAABQgBAAAAAAIAABTIgBACIgCABIgjAAIgDgBIgBgCIAAjLIABgCIADgBIAjAAIACABIABACIAABRQAAABABAAQAAAAAAAAQAAABAAAAQABAAAAAAIAvAAQAAAAABAAQAAAAAAgBQAAAAAAAAQABAAAAgBIAAhRIABgCIACgBIAjAAIADABIABACIAADLIgBACIgDABg");
	this.shape_19.setTransform(9.9,20.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2, new cjs.Rectangle(0,0,147,98.3), null);


(lib.t1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgHAiQgDgDAAgFQAAgEADgEQAEgDADAAQAEAAADADQAEAEAAAEQAAAFgEADQgCADgFAAQgEAAgDgDgAgHgSQgDgDAAgEQAAgFADgDQAEgDADAAQAEAAADADQAEADAAAFQAAAEgEADQgCAEgFAAQgEAAgDgEg");
	this.shape.setTransform(76.2,12.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgdA3QAAAAgBAAQAAAAAAAAQAAgBAAAAQgBAAAAAAIAAhqQAAgBABAAQAAAAAAgBQAAAAAAAAQABAAAAAAIA6AAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAJQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAIgsAAIAAAAIAAAiIAAABIAdAAQAAAAABAAQAAAAAAAAQAAABAAAAQABAAAAAAIAAAJQAAABgBAAQAAAAAAABQAAAAAAAAQgBAAAAAAIgdAAIAAABIAAAjIAAAAIAsAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAKQAAAAAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_1.setTransform(70.1,10.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgeA3QgBAAAAAAQAAAAAAAAQgBgBAAAAQAAAAAAAAIAAhqQAAgBAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAfAAQAOAAAJAIQAJAJAAANIAAAxQAAAOgJAHQgJAJgOAAgAgRgpIAABTIABAAIARAAQAHAAAFgGQAEgEABgJIAAgtQAAgJgFgFQgFgFgHAAIgRAAIgBAAg");
	this.shape_2.setTransform(61.6,10.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgFA3QAAAAgBAAQAAAAAAAAQAAgBAAAAQgBAAAAAAIAAhqQAAgBABAAQAAAAAAgBQAAAAAAAAQABAAAAAAIALAAQAAAAABAAQAAAAAAAAQAAABAAAAQABAAAAABIAABqQAAAAgBAAQAAAAAAABQAAAAAAAAQgBAAAAAAg");
	this.shape_3.setTransform(55.3,10.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgRAzQgHgDgEgIQgFgIAAgKIAAhLQAAAAABgBQAAAAAAAAQAAAAAAAAQABgBAAAAIAMAAQAAAAABABQAAAAAAAAQAAAAAAAAQABABAAAAIAABMQAAAJAEAGQAGAEAHAAQAJAAAEgEQAGgGgBgJIAAhMQABAAAAgBQAAAAAAAAQAAAAAAAAQABgBAAAAIAMAAQAAAAABABQAAAAAAAAQAAAAAAAAQABABAAAAIAABLQAAAKgFAIQgEAIgHADQgIAFgKAAQgJAAgIgFg");
	this.shape_4.setTransform(49,10.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgXAwQgJgJAAgOIAAgwQAAgPAJgIQAJgJAOAAQAKAAAHAEQAIADAEAIQAEAHAAAJIAAAEQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAIgMAAQgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIAAgEQAAgIgFgFQgFgFgIAAQgHAAgFAFQgFAFAAAIIAAAxQAAAIAFAFQAFAFAHAAQAIAAAFgEQAFgFAAgIIAAgPIgBAAIgQAAQgBAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAgJQAAAAAAAAQAAgBAAAAQAAAAAAAAQAAAAABAAIAfAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAAAYQAAAPgJAJQgJAIgPAAQgOAAgJgIg");
	this.shape_5.setTransform(40.5,10.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgdA3QAAAAgBAAQAAAAAAAAQAAgBAAAAQgBAAAAAAIAAhqQAAgBABAAQAAAAAAgBQAAAAAAAAQABAAAAAAIA7AAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAJQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgtAAIAAAAIAAAiIAAABIAdAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAAAIAAAJQAAABAAAAQAAAAAAABQAAAAAAAAQgBAAAAAAIgdAAIAAABIAAAjIAAAAIAtAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAKQAAAAAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAg");
	this.shape_6.setTransform(29.4,10.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgdA3QAAAAgBAAQAAAAAAAAQAAgBAAAAQAAAAAAAAIAAhqQAAgBAAAAQAAAAAAgBQAAAAAAAAQABAAAAAAIA6AAQABAAAAAAQABAAAAAAQAAABAAAAQABAAAAABIAAAJQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAIgsAAIgBAAIAAAiIABABIAdAAQAAAAABAAQAAAAAAAAQAAABAAAAQABAAAAAAIAAAJQAAABgBAAQAAAAAAABQAAAAAAAAQgBAAAAAAIgdAAIgBABIAAAjIABAAIAsAAQABAAAAAAQABAAAAAAQAAABAAAAQABAAAAABIAAAKQAAAAgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_7.setTransform(21.2,10.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAUA3IgCgBIgSgvIgBgBIgQAAIgBABIAAAvQAAAAAAAAQAAABAAAAQAAAAAAAAQgBAAAAAAIgMAAQAAAAgBAAQAAAAAAAAQAAAAAAgBQAAAAAAAAIAAhrQAAAAAAAAQAAgBAAAAQAAAAAAAAQABAAAAAAIAiAAQAOAAAHAJQAJAIgBAOQAAALgEAHQgGAHgIADIgBABIAUAvIAAABQAAAAAAABQAAAAAAAAQAAAAAAAAQgBAAAAAAgAgSgoIAAAjIABAAIASAAQAIAAAEgEQAFgFgBgJQABgIgFgFQgEgFgIAAIgSAAIgBABg");
	this.shape_8.setTransform(13.1,10.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgdA3QAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAAAIAAhqQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAAAAAIA7AAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAJQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgtAAIAAAAIAAAiIAAABIAdAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAAAIAAAJQAAABAAAAQAAAAgBABQAAAAAAAAQAAAAgBAAIgdAAIAAABIAAAvQAAAAAAAAQAAAAgBABQAAAAAAAAQAAAAgBAAg");
	this.shape_9.setTransform(5.1,10.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1, new cjs.Rectangle(0,0,90.1,21.5), null);


(lib.tbtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAZBFQAAAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAAAIgXhrIAAAAIAAAAIgWBrQAAAAAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAIgJAAQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAgBAAIgfiFIAAgBQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAAAAAIALAAQAAAAABAAQAAAAABAAQAAABAAAAQAAAAAAABIAYBpIABABIAAgBIAWhpQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAJAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAXBpIAAABIABgBIAXhpQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAAAAAIAKAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAABIgfCFQAAAAAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAg");
	this.shape.setTransform(125.4,13.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgUBCQgJgGgGgJQgEgJAAgLIAAg8QAAgMAEgJQAGgKAJgFQAJgEALgBQAMABAJAEQAJAFAFAKQAFAJABAMIAAA8QgBALgFAJQgFAJgJAGQgJAEgMAAQgLAAgJgEgAgSgxQgIAHAAANIAAA8QAAANAIAHQAHAIALAAQAMAAAHgIQAIgHgBgNIAAg8QABgNgIgHQgHgIgMAAQgLAAgHAIg");
	this.shape_1.setTransform(112.7,13.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAdBFQAAAAgBAAQAAAAgBAAQAAgBAAAAQAAAAAAAAIg1hoIAAAAIAAABIAABmQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAIgKAAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAiFQAAgBAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAKAAQAAAAABAAQAAAAAAAAQAAABABAAQAAAAAAABIA0BmIABAAIAAAAIAAhmQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAKAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAACFQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAg");
	this.shape_2.setTransform(101.7,13.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgkBFQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAiFQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAlAAQARAAALALQAKAKAAARIAAA+QAAARgKAKQgLAKgRAAgAgYg3IAABvIABABIAZAAQAKgBAHgGQAGgIAAgLIAAg8QAAgMgGgHQgHgIgKAAIgZAAIgBABg");
	this.shape_3.setTransform(86.9,13.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAhBFQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAAAIgGgZIgCgBIguAAIAAABIgHAZQAAAAAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAIgKAAIgCAAIAAgCIAkiFQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAABAAIALAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAlCFIAAABQAAAAAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAgAAAgwIgUBOIAAABIABAAIAnAAIABAAIAAgBIgUhOIgBAAIAAAAg");
	this.shape_4.setTransform(76.1,13.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgUBCQgJgGgGgJQgEgJAAgLIAAg8QAAgMAEgJQAGgKAJgFQAJgEALgBQAMABAJAEQAJAFAFAKQAGAJAAAMIAAA8QAAALgGAJQgFAJgJAGQgJAEgMAAQgLAAgJgEgAgSgxQgIAHAAANIAAA8QAAANAIAHQAHAIALAAQAMAAAHgIQAIgHgBgNIAAg8QABgNgIgHQgHgIgMAAQgLAAgHAIg");
	this.shape_5.setTransform(65.5,13.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgiBFQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAiFQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAKAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAB6IABABIA4AAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAIQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAg");
	this.shape_6.setTransform(56.1,13.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAdBFQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAgBAAIgzhoIgBAAIgBABIABBmQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAIgKAAQAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAiFQAAgBAAAAQAAAAAAgBQABAAAAAAQABAAAAAAIAKAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIA0BmIABAAIAAAAIAAhmQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAKAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAACFQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAg");
	this.shape_7.setTransform(45,13.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAZBFQAAAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAAAIgXhrIAAAAIAAAAIgWBrQAAAAAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAIgJAAQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAgBAAIgfiFIAAgBQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAAAAAIALAAQAAAAABAAQAAAAABAAQAAABAAAAQAAAAAAABIAYBpIABABIAAgBIAWhpQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAJAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAXBpIAAABIABgBIAXhpQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAAAAAIAKAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAABIgfCFQAAAAAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAg");
	this.shape_8.setTransform(31.9,13.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgUBCQgKgGgEgJQgFgJgBgLIAAg8QABgMAFgJQAEgKAKgFQAJgEALgBQAMABAJAEQAJAFAGAKQAEAJAAAMIAAA8QAAALgEAJQgGAJgJAGQgJAEgMAAQgLAAgJgEgAgSgxQgHAHAAANIAAA8QAAANAHAHQAHAIALAAQAMAAAHgIQAIgHAAgNIAAg8QAAgNgIgHQgHgIgMAAQgLAAgHAIg");
	this.shape_9.setTransform(19.2,13.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgkBFQAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAiFQAAgBAAAAQAAAAAAgBQABAAAAAAQABAAAAAAIAlAAQARAAALALQAKAKAAARIAAA+QAAARgKAKQgLAKgRAAgAgYg3IAABvIABABIAYAAQAMgBAFgGQAHgIAAgLIAAg8QAAgMgHgHQgFgIgMAAIgYAAIgBABg");
	this.shape_10.setTransform(8.8,13.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.tbtn, new cjs.Rectangle(0,0,136,27.4), null);


(lib.book_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.book();
	this.instance.parent = this;
	this.instance.setTransform(122,21);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.book_1, new cjs.Rectangle(122,21,396,315), null);


// stage content:
(lib._300x250_Adwords_AIAB_ = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_662 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(662).call(this.frame_662).wait(94));

	// Слой 18
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,255,255,0.149)").s().p("A3bTiMAAAgnDMAu3AAAMAAAAnDgA2xS4MAtjAAAMAAAglvMgtjAAAg");
	this.shape.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(756));

	// t2
	this.instance = new lib.t22();
	this.instance.parent = this;
	this.instance.setTransform(-38.4,138.1,1,1,0,0,0,73.5,49.1);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(125).to({_off:false},0).to({x:13.6,alpha:1},7).to({x:11.6},3,cjs.Ease.get(-1)).wait(101).to({x:41.6,alpha:0},5,cjs.Ease.get(-1)).to({_off:true},11).wait(125).to({_off:false,x:-38.4},0).to({x:13.6,alpha:1},7).to({x:11.6},3,cjs.Ease.get(-1)).wait(101).to({x:41.6,alpha:0},5,cjs.Ease.get(-1)).to({_off:true},11).wait(125).to({_off:false,x:-38.4},0).to({x:13.6,alpha:1},7).to({x:11.6},3,cjs.Ease.get(-1)).wait(101).to({x:41.6,alpha:0},5,cjs.Ease.get(-1)).wait(11));

	// t1
	this.instance_1 = new lib.t1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(34.5,61,1,1,0,0,0,45,10.7);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({x:57.5,alpha:1},10,cjs.Ease.get(1)).to({x:54.5},5,cjs.Ease.get(-1)).wait(94).to({x:14.5,alpha:0},5,cjs.Ease.get(-1)).wait(138).to({x:34.5},0).to({x:57.5,alpha:1},10,cjs.Ease.get(1)).to({x:54.5},5,cjs.Ease.get(-1)).wait(94).to({x:14.5,alpha:0},5,cjs.Ease.get(-1)).wait(138).to({x:34.5},0).to({x:57.5,alpha:1},10,cjs.Ease.get(1)).to({x:54.5},5,cjs.Ease.get(-1)).wait(94).to({x:14.5,alpha:0},5,cjs.Ease.get(-1)).wait(138));

	// t2
	this.instance_2 = new lib.t2();
	this.instance_2.parent = this;
	this.instance_2.setTransform(61.6,138.1,1,1,0,0,0,73.5,49.1);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(10).to({_off:false},0).to({x:84.6,alpha:1},10,cjs.Ease.get(1)).to({x:81.6},5,cjs.Ease.get(-1)).wait(94).to({x:11.6,alpha:0},5,cjs.Ease.get(-1)).to({_off:true},128).wait(10).to({_off:false,x:61.6},0).to({x:84.6,alpha:1},10,cjs.Ease.get(1)).to({x:81.6},5,cjs.Ease.get(-1)).wait(94).to({x:11.6,alpha:0},5,cjs.Ease.get(-1)).to({_off:true},128).wait(10).to({_off:false,x:61.6},0).to({x:84.6,alpha:1},10,cjs.Ease.get(1)).to({x:81.6},5,cjs.Ease.get(-1)).wait(94).to({x:11.6,alpha:0},5,cjs.Ease.get(-1)).wait(128));

	// t-btn
	this.instance_3 = new lib.tbtn();
	this.instance_3.parent = this;
	this.instance_3.setTransform(152.3,272.6,1,1,0,0,0,68,13.7);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(20).to({_off:false},0).to({y:213.6},10,cjs.Ease.get(1)).to({y:215.6},5,cjs.Ease.get(-1)).wait(211).to({x:222.3,alpha:0},5,cjs.Ease.get(-1)).to({_off:true},1).wait(20).to({_off:false,x:152.3,y:272.6,alpha:1},0).to({y:213.6},10,cjs.Ease.get(1)).to({y:215.6},5,cjs.Ease.get(-1)).wait(211).to({x:222.3,alpha:0},5,cjs.Ease.get(-1)).to({_off:true},1).wait(20).to({_off:false,x:152.3,y:272.6,alpha:1},0).to({y:213.6},10,cjs.Ease.get(1)).to({y:215.6},5,cjs.Ease.get(-1)).wait(211).to({x:222.3,alpha:0},5,cjs.Ease.get(-1)).wait(1));

	// Слой 19
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#CC3366").s().p("AsSCvIAAldIYkAAIAAFdg");
	this.shape_1.setTransform(152.8,271.6);
	this.shape_1._off = true;

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#CC3366","#D76289","#CC3366"],[0,0.412,1],-243.4,5.4,-86.1,5.4).s().p("AsSCvIAAldIYkAAIAAFdg");
	this.shape_2.setTransform(152.8,214.6);
	this.shape_2._off = true;

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#CC3366","#D76289","#CC3366"],[0,0.412,1],-226.2,5.2,-68.9,5.2).s().p("AsSCvIAAldIYkAAIAAFdg");
	this.shape_3.setTransform(152.8,214.6);
	this.shape_3._off = true;

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["#CC3366","#D76289","#CC3366"],[0,0.412,1],-209.1,4.9,-51.8,4.9).s().p("AsSCvIAAldIYkAAIAAFdg");
	this.shape_4.setTransform(152.8,214.6);
	this.shape_4._off = true;

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.lf(["#CC3366","#D76289","#CC3366"],[0,0.412,1],-191.9,4.6,-34.6,4.6).s().p("AsSCvIAAldIYkAAIAAFdg");
	this.shape_5.setTransform(152.8,214.6);
	this.shape_5._off = true;

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.lf(["#CC3366","#D76289","#CC3366"],[0,0.412,1],-174.7,4.4,-17.4,4.4).s().p("AsSCvIAAldIYkAAIAAFdg");
	this.shape_6.setTransform(152.8,214.6);
	this.shape_6._off = true;

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.lf(["#CC3366","#D76289","#CC3366"],[0,0.412,1],-157.6,4.1,-0.3,4.1).s().p("AsSCvIAAldIYkAAIAAFdg");
	this.shape_7.setTransform(152.8,214.6);
	this.shape_7._off = true;

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.lf(["#CC3366","#D76289","#CC3366"],[0,0.412,1],-140.4,3.8,16.9,3.8).s().p("AsSCvIAAldIYkAAIAAFdg");
	this.shape_8.setTransform(152.8,214.6);
	this.shape_8._off = true;

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.lf(["#CC3366","#D76289","#CC3366"],[0,0.412,1],-123.3,3.6,34,3.6).s().p("AsSCvIAAldIYkAAIAAFdg");
	this.shape_9.setTransform(152.8,214.6);
	this.shape_9._off = true;

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.lf(["#CC3366","#D76289","#CC3366"],[0,0.412,1],-106.1,3.3,51.2,3.3).s().p("AsSCvIAAldIYkAAIAAFdg");
	this.shape_10.setTransform(152.8,214.6);
	this.shape_10._off = true;

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.lf(["#CC3366","#D76289","#CC3366"],[0,0.412,1],-89,3.1,68.3,3.1).s().p("AsSCvIAAldIYkAAIAAFdg");
	this.shape_11.setTransform(152.8,214.6);
	this.shape_11._off = true;

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.lf(["#CC3366","#D76289","#CC3366"],[0,0.412,1],-71.8,2.8,85.5,2.8).s().p("AsSCvIAAldIYkAAIAAFdg");
	this.shape_12.setTransform(152.8,214.6);
	this.shape_12._off = true;

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.lf(["#CC3366","#D76289","#CC3366"],[0,0.412,1],-54.6,2.5,102.7,2.5).s().p("AsSCvIAAldIYkAAIAAFdg");
	this.shape_13.setTransform(152.8,214.6);
	this.shape_13._off = true;

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.lf(["#CC3366","#D76289","#CC3366"],[0,0.412,1],-37.5,2.3,119.8,2.3).s().p("AsSCvIAAldIYkAAIAAFdg");
	this.shape_14.setTransform(152.8,214.6);
	this.shape_14._off = true;

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.lf(["#CC3366","#D76289","#CC3366"],[0,0.412,1],-20.3,2,137,2).s().p("AsSCvIAAldIYkAAIAAFdg");
	this.shape_15.setTransform(152.8,214.6);
	this.shape_15._off = true;

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.lf(["#CC3366","#D76289","#CC3366"],[0,0.412,1],-3.2,1.7,154.1,1.7).s().p("AsSCvIAAldIYkAAIAAFdg");
	this.shape_16.setTransform(152.8,214.6);
	this.shape_16._off = true;

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.lf(["#CC3366","#D76289","#CC3366"],[0,0.412,1],14,1.5,171.3,1.5).s().p("AsSCvIAAldIYkAAIAAFdg");
	this.shape_17.setTransform(152.8,214.6);
	this.shape_17._off = true;

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.lf(["#CC3366","#D76289","#CC3366"],[0,0.412,1],31.2,1.2,188.5,1.2).s().p("AsSCvIAAldIYkAAIAAFdg");
	this.shape_18.setTransform(152.8,214.6);
	this.shape_18._off = true;

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.lf(["#CC3366","#D76289","#CC3366"],[0,0.412,1],48.3,1,205.6,1).s().p("AsSCvIAAldIYkAAIAAFdg");
	this.shape_19.setTransform(152.8,214.6);
	this.shape_19._off = true;

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.lf(["#CC3366","#D76289","#CC3366"],[0,0.412,1],65.5,0.7,222.8,0.7).s().p("AsSCvIAAldIYkAAIAAFdg");
	this.shape_20.setTransform(152.8,214.6);
	this.shape_20._off = true;

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.lf(["#CC3366","#D76289","#CC3366"],[0,0.412,1],82.6,0.4,239.9,0.4).s().p("AsSCvIAAldIYkAAIAAFdg");
	this.shape_21.setTransform(152.8,214.6);
	this.shape_21._off = true;

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("rgba(204,51,102,0.961)").s().p("AsSCvIAAldIYlAAIAAFdg");
	this.shape_22.setTransform(155.2,214.6);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("rgba(204,51,102,0.839)").s().p("AsSCvIAAldIYlAAIAAFdg");
	this.shape_23.setTransform(162.4,214.6);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("rgba(204,51,102,0.639)").s().p("AsSCvIAAldIYkAAIAAFdg");
	this.shape_24.setTransform(174.4,214.6);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("rgba(204,51,102,0.361)").s().p("AsSCvIAAldIYlAAIAAFdg");
	this.shape_25.setTransform(191.2,214.6);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("rgba(204,51,102,0)").s().p("AsSCvIAAldIYlAAIAAFdg");
	this.shape_26.setTransform(212.8,214.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_1}]},20).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},24).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_21}]},1).to({state:[{t:this.shape_2}]},17).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_21}]},1).to({state:[{t:this.shape_2}]},11).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_21}]},1).to({state:[{t:this.shape_2}]},28).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_21}]},1).to({state:[{t:this.shape_1}]},55).to({state:[{t:this.shape_22}]},1).to({state:[{t:this.shape_23}]},1).to({state:[{t:this.shape_24}]},1).to({state:[{t:this.shape_25}]},1).to({state:[{t:this.shape_26}]},1).to({state:[]},1).to({state:[{t:this.shape_1}]},20).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},24).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_21}]},1).to({state:[{t:this.shape_2}]},17).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_21}]},1).to({state:[{t:this.shape_2}]},11).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_21}]},1).to({state:[{t:this.shape_2}]},28).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_21}]},1).to({state:[{t:this.shape_1}]},55).to({state:[{t:this.shape_22}]},1).to({state:[{t:this.shape_23}]},1).to({state:[{t:this.shape_24}]},1).to({state:[{t:this.shape_25}]},1).to({state:[{t:this.shape_26}]},1).to({state:[]},1).to({state:[{t:this.shape_1}]},20).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},24).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_21}]},1).to({state:[{t:this.shape_2}]},17).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_21}]},1).to({state:[{t:this.shape_2}]},11).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_21}]},1).to({state:[{t:this.shape_2}]},28).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_21}]},1).to({state:[{t:this.shape_1}]},55).to({state:[{t:this.shape_22}]},1).to({state:[{t:this.shape_23}]},1).to({state:[{t:this.shape_24}]},1).to({state:[{t:this.shape_25}]},1).to({state:[{t:this.shape_26}]},1).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(20).to({_off:false},0).wait(1).to({y:260.4},0).wait(1).to({y:250.4},0).wait(1).to({y:241.5},0).wait(1).to({y:233.9},0).wait(1).to({y:227.4},0).wait(1).to({y:222.1},0).wait(1).to({y:217.9},0).wait(1).to({y:215},0).wait(1).to({y:213.2},0).wait(1).to({y:212.6},0).wait(1).to({y:212.7},0).wait(1).to({y:212.9},0).wait(1).to({y:213.3},0).wait(1).to({y:213.9},0).wait(1).to({y:214.6},0).to({_off:true},24).wait(187).to({_off:false},0).to({_off:true},1).wait(25).to({_off:false,y:271.6},0).wait(1).to({y:260.4},0).wait(1).to({y:250.4},0).wait(1).to({y:241.5},0).wait(1).to({y:233.9},0).wait(1).to({y:227.4},0).wait(1).to({y:222.1},0).wait(1).to({y:217.9},0).wait(1).to({y:215},0).wait(1).to({y:213.2},0).wait(1).to({y:212.6},0).wait(1).to({y:212.7},0).wait(1).to({y:212.9},0).wait(1).to({y:213.3},0).wait(1).to({y:213.9},0).wait(1).to({y:214.6},0).to({_off:true},24).wait(187).to({_off:false},0).to({_off:true},1).wait(25).to({_off:false,y:271.6},0).wait(1).to({y:260.4},0).wait(1).to({y:250.4},0).wait(1).to({y:241.5},0).wait(1).to({y:233.9},0).wait(1).to({y:227.4},0).wait(1).to({y:222.1},0).wait(1).to({y:217.9},0).wait(1).to({y:215},0).wait(1).to({y:213.2},0).wait(1).to({y:212.6},0).wait(1).to({y:212.7},0).wait(1).to({y:212.9},0).wait(1).to({y:213.3},0).wait(1).to({y:213.9},0).wait(1).to({y:214.6},0).to({_off:true},24).wait(187).to({_off:false},0).to({_off:true},1).wait(5));
	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(59).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(138).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(138).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(79));
	this.timeline.addTween(cjs.Tween.get(this.shape_3).wait(60).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(138).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(138).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(78));
	this.timeline.addTween(cjs.Tween.get(this.shape_4).wait(61).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(138).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(138).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(77));
	this.timeline.addTween(cjs.Tween.get(this.shape_5).wait(62).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(138).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(138).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(76));
	this.timeline.addTween(cjs.Tween.get(this.shape_6).wait(63).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(138).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(138).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(75));
	this.timeline.addTween(cjs.Tween.get(this.shape_7).wait(64).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(138).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(138).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(74));
	this.timeline.addTween(cjs.Tween.get(this.shape_8).wait(65).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(138).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(138).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(73));
	this.timeline.addTween(cjs.Tween.get(this.shape_9).wait(66).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(138).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(138).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(72));
	this.timeline.addTween(cjs.Tween.get(this.shape_10).wait(67).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(138).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(138).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(71));
	this.timeline.addTween(cjs.Tween.get(this.shape_11).wait(68).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(138).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(138).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(70));
	this.timeline.addTween(cjs.Tween.get(this.shape_12).wait(69).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(138).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(138).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(69));
	this.timeline.addTween(cjs.Tween.get(this.shape_13).wait(70).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(138).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(138).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(68));
	this.timeline.addTween(cjs.Tween.get(this.shape_14).wait(71).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(138).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(138).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(67));
	this.timeline.addTween(cjs.Tween.get(this.shape_15).wait(72).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(138).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(138).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(66));
	this.timeline.addTween(cjs.Tween.get(this.shape_16).wait(73).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(138).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(138).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(65));
	this.timeline.addTween(cjs.Tween.get(this.shape_17).wait(74).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(138).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(138).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(64));
	this.timeline.addTween(cjs.Tween.get(this.shape_18).wait(75).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(138).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(138).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(63));
	this.timeline.addTween(cjs.Tween.get(this.shape_19).wait(76).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(138).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(138).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(62));
	this.timeline.addTween(cjs.Tween.get(this.shape_20).wait(77).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(138).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(138).to({_off:false},0).to({_off:true},1).wait(35).to({_off:false},0).to({_off:true},1).wait(29).to({_off:false},0).to({_off:true},1).wait(46).to({_off:false},0).to({_off:true},1).wait(61));
	this.timeline.addTween(cjs.Tween.get(this.shape_21).wait(78).to({_off:false},0).to({_off:true},17).wait(19).to({_off:false},0).to({_off:true},11).wait(19).to({_off:false},0).to({_off:true},28).wait(19).to({_off:false},0).to({_off:true},55).wait(84).to({_off:false},0).to({_off:true},17).wait(19).to({_off:false},0).to({_off:true},11).wait(19).to({_off:false},0).to({_off:true},28).wait(19).to({_off:false},0).to({_off:true},55).wait(84).to({_off:false},0).to({_off:true},17).wait(19).to({_off:false},0).to({_off:true},11).wait(19).to({_off:false},0).to({_off:true},28).wait(19).to({_off:false},0).to({_off:true},55).wait(6));

	// book
	this.instance_4 = new lib.book_1();
	this.instance_4.parent = this;
	this.instance_4.setTransform(365,95,0.5,0.5,0,0,0,241.3,183.6);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(5).to({_off:false},0).to({x:162,y:103},9,cjs.Ease.get(1)).wait(105).to({regX:241.4,regY:183.7,scaleX:0.43,scaleY:0.43,x:182.3,y:88.1},5).wait(117).to({x:352.3},5,cjs.Ease.get(-1)).to({_off:true},6).wait(5).to({_off:false,regX:241.3,regY:183.6,scaleX:0.5,scaleY:0.5,x:365,y:95},0).to({x:162,y:103},9,cjs.Ease.get(1)).wait(105).to({regX:241.4,regY:183.7,scaleX:0.43,scaleY:0.43,x:182.3,y:88.1},5).wait(117).to({x:352.3},5,cjs.Ease.get(-1)).to({_off:true},6).wait(5).to({_off:false,regX:241.3,regY:183.6,scaleX:0.5,scaleY:0.5,x:365,y:95},0).to({x:162,y:103},9,cjs.Ease.get(1)).wait(105).to({regX:241.4,regY:183.7,scaleX:0.43,scaleY:0.43,x:182.3,y:88.1},5).wait(117).to({x:352.3},5,cjs.Ease.get(-1)).wait(6));

	// Слой 23
	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#CC3366").s().p("A4SCeIAAk7MAwlAAAIAAE7g");
	this.shape_27.setTransform(-164.5,60.4);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#CC3366").s().p("A4SCeIAAk7MAwkAAAIAAE7g");
	this.shape_28.setTransform(-132.5,60.4);
	this.shape_28._off = true;

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#CC3366").s().p("A4RCeIAAk7MAwjAAAIAAE7g");
	this.shape_29.setTransform(-100.5,60.4);
	this.shape_29._off = true;

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#CC3366").s().p("A4SC2IAAlsMAwkAAAIAAFsg");
	this.shape_30.setTransform(155.5,73.6);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#CC3366").s().p("A4SDPIAAmdMAwkAAAIAAGdg");
	this.shape_31.setTransform(155.5,86.7);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#CC3366").s().p("A4SDnIAAnNMAwkAAAIAAHNg");
	this.shape_32.setTransform(155.5,99.9);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#CC3366").s().p("A4SEAIAAn/MAwkAAAIAAH/g");
	this.shape_33.setTransform(155.5,113.1);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#CC3366").s().p("A4SEZIAAoxMAwkAAAIAAIxg");
	this.shape_34.setTransform(155.5,126.2);
	this.shape_34._off = true;

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#CC3366").s().p("A4SDpIAAnRMAwlAAAIAAHRg");
	this.shape_35.setTransform(154.1,126.2);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#CC3366").s().p("A4RC5IAAlwMAwjAAAIAAFwg");
	this.shape_36.setTransform(152.7,126.3);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#CC3366").s().p("A4SCIIAAkPMAwlAAAIAAEPg");
	this.shape_37.setTransform(151.3,126.2);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#CC3366").s().p("A4RBYIAAivMAwjAAAIAACvg");
	this.shape_38.setTransform(149.9,126.3);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#CC3366").s().p("A4SAoIAAhPMAwlAAAIAABPg");
	this.shape_39.setTransform(148.5,126.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_27}]}).to({state:[{t:this.shape_28}]},1).to({state:[{t:this.shape_29}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_29}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_29}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_29}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_28}]},1).to({state:[{t:this.shape_28}]},109).to({state:[{t:this.shape_30}]},1).to({state:[{t:this.shape_31}]},1).to({state:[{t:this.shape_32}]},1).to({state:[{t:this.shape_33}]},1).to({state:[{t:this.shape_34}]},1).to({state:[{t:this.shape_34}]},122).to({state:[{t:this.shape_35}]},1).to({state:[{t:this.shape_36}]},1).to({state:[{t:this.shape_37}]},1).to({state:[{t:this.shape_38}]},1).to({state:[{t:this.shape_39}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_28}]},1).to({state:[{t:this.shape_29}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_29}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_29}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_29}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_28}]},1).to({state:[{t:this.shape_28}]},109).to({state:[{t:this.shape_30}]},1).to({state:[{t:this.shape_31}]},1).to({state:[{t:this.shape_32}]},1).to({state:[{t:this.shape_33}]},1).to({state:[{t:this.shape_34}]},1).to({state:[{t:this.shape_34}]},122).to({state:[{t:this.shape_35}]},1).to({state:[{t:this.shape_36}]},1).to({state:[{t:this.shape_37}]},1).to({state:[{t:this.shape_38}]},1).to({state:[{t:this.shape_39}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_28}]},1).to({state:[{t:this.shape_29}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_29}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_29}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_29}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_28}]},1).to({state:[{t:this.shape_28}]},109).to({state:[{t:this.shape_30}]},1).to({state:[{t:this.shape_31}]},1).to({state:[{t:this.shape_32}]},1).to({state:[{t:this.shape_33}]},1).to({state:[{t:this.shape_34}]},1).to({state:[{t:this.shape_34}]},122).to({state:[{t:this.shape_35}]},1).to({state:[{t:this.shape_36}]},1).to({state:[{t:this.shape_37}]},1).to({state:[{t:this.shape_38}]},1).to({state:[{t:this.shape_39}]},1).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.shape_27).to({_off:true},1).wait(2).to({_off:false,x:-68.5},0).to({_off:true},1).wait(1).to({_off:false,x:-4.5},0).to({_off:true},1).wait(1).to({_off:false,x:59.5},0).to({_off:true},1).wait(1).to({_off:false,x:123.5},0).to({_off:true},1).wait(242).to({_off:false,x:-164.5},0).to({_off:true},1).wait(2).to({_off:false,x:-68.5},0).to({_off:true},1).wait(1).to({_off:false,x:-4.5},0).to({_off:true},1).wait(1).to({_off:false,x:59.5},0).to({_off:true},1).wait(1).to({_off:false,x:123.5},0).to({_off:true},1).wait(242).to({_off:false,x:-164.5},0).to({_off:true},1).wait(2).to({_off:false,x:-68.5},0).to({_off:true},1).wait(1).to({_off:false,x:-4.5},0).to({_off:true},1).wait(1).to({_off:false,x:59.5},0).to({_off:true},1).wait(1).to({_off:false,x:123.5},0).to({_off:true},1).wait(242));
	this.timeline.addTween(cjs.Tween.get(this.shape_28).wait(1).to({_off:false},0).to({_off:true},1).wait(8).to({_off:false,x:155.5},0).wait(109).to({_off:true},1).wait(133).to({_off:false,x:-132.5},0).to({_off:true},1).wait(8).to({_off:false,x:155.5},0).wait(109).to({_off:true},1).wait(133).to({_off:false,x:-132.5},0).to({_off:true},1).wait(8).to({_off:false,x:155.5},0).wait(109).to({_off:true},1).wait(132));
	this.timeline.addTween(cjs.Tween.get(this.shape_29).wait(2).to({_off:false},0).to({_off:true},1).wait(1).to({_off:false,x:-36.5},0).to({_off:true},1).wait(1).to({_off:false,x:27.5},0).to({_off:true},1).wait(1).to({_off:false,x:91.5},0).to({_off:true},1).wait(245).to({_off:false,x:-100.5},0).to({_off:true},1).wait(1).to({_off:false,x:-36.5},0).to({_off:true},1).wait(1).to({_off:false,x:27.5},0).to({_off:true},1).wait(1).to({_off:false,x:91.5},0).to({_off:true},1).wait(245).to({_off:false,x:-100.5},0).to({_off:true},1).wait(1).to({_off:false,x:-36.5},0).to({_off:true},1).wait(1).to({_off:false,x:27.5},0).to({_off:true},1).wait(1).to({_off:false,x:91.5},0).to({_off:true},1).wait(243));
	this.timeline.addTween(cjs.Tween.get(this.shape_34).wait(124).to({_off:false},0).wait(122).to({_off:true},1).wait(129).to({_off:false},0).wait(122).to({_off:true},1).wait(129).to({_off:false},0).wait(122).to({_off:true},1).wait(5));

	// Слой 24
	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.lf(["#039DD3","#095697"],[0,1],-153.4,-54.8,111.3,77.6).s().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");
	this.shape_40.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.shape_40).wait(756));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-170,125,620,250);
// library properties:
lib.properties = {
	width: 300,
	height: 250,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/book.png", id:"book"}
	],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;